//* Not all Functions are applicable to the menu so this is a curated sub set
export const MENU_FUNCTION_IDS: Record<number, string> = {
  //? 22: 'Roles',
  //? 29: 'Bugs',
  48: 'Page Library',
  49: 'Page Team',
  50: 'Page News',
  51: 'Page Search',
  54: 'Page Home',
  59: 'Page Home Beta',
  64: 'Person Activity',
  67: 'Page Training',
  68: 'Page Reports',
  70: 'Page Library Beta',
  73: 'Page ToDo',
  78: 'Page Reports Users',
  79: 'Page Reports Courses',
  80: 'Page Reports Todos',
  81: 'Page Reports Roles',
  82: 'Page Reports Email',
  83: 'Page Reports Activity',
  104: 'Page Catalog Curriculum',
  107: 'Page TeamEditor',
  118: 'Page GSPPF',
  121: 'Page Manage TrainingDashboard',
  //? 155: 'ServiceBid',
  160: 'Page Survey',
  163: 'Page GSPPF Dashboard',
} as const

