export const TeamsEndpointResponses = {
  success: () => {
    return {
      team: {
        teamID: 1081395,
        teamName: 'The Avengers',
        elementType: 'ocTEAM',
        teamDesc: '',
        teamType: 'ocTEAM',
        domainID: 551,
        activeStatus: 'ocENABLED',
        address1: '',
        address2: '',
        city: '',
        state: '',
        country: '',
        postalCode: '',
        phone1: '',
        phone2: '',
        email: '',
        fax: '',
        teamLeaderID: 1503800,
        teamLeaderOutsideID: '',
        teamLeaderName: '',
        profileImageID: 1081531,
        dateFounded: '1900-01-01T00:00:00-08:00',
        outsideType: '',
        website: '',
        outsideExpirationDate: '1900-01-01T00:00:00-08:00',
        outsideID: '',
        lastRefreshWithOutside: '1900-01-01T00:00:00-08:00',
        achievementIconID: 0,
        rosterView: true,
        geographyPostalCode: '',
        createdByID: 2,
        modifiedByID: 4201,
        createdDate: '2015-07-15T11:35:41.47-07:00',
        modifiedDate: '2015-07-15T13:21:18.37-07:00',
        primaryElementID: 551,
        teamToolsConfig: {
          modifiedByID: 1503800,
          modifiedDate: '2020-10-21T10:01:57.913-07:00',
          teamName: 'Knowledge Vault',
          teamRoot: 551,
          onInitialize: {
            mayTakeDisc: false,
            mayImportDisc: false,
            mayTakeBasicTrain: false,
            mayTakeAdvTrain: false,
            hasBasicViewDisc: false,
            hasAdvViewDisc: false,
            hasPermitChange: false,
            hasGrantPermitChange: false,
          },
          onDiscComplete: {
            mayTakeDisc: false,
            mayImportDisc: false,
            mayTakeBasicTrain: false,
            mayTakeAdvTrain: false,
            hasBasicViewDisc: false,
            hasAdvViewDisc: false,
            hasPermitChange: false,
            hasGrantPermitChange: false,
          },
          onBasicTrainingComplete: {
            mayTakeDisc: false,
            mayImportDisc: false,
            mayTakeBasicTrain: false,
            mayTakeAdvTrain: false,
            hasBasicViewDisc: false,
            hasAdvViewDisc: false,
            hasPermitChange: false,
            hasGrantPermitChange: false,
          },
          onAdvTrainingComplete: {
            mayTakeDisc: false,
            mayImportDisc: false,
            mayTakeBasicTrain: false,
            mayTakeAdvTrain: false,
            hasBasicViewDisc: false,
            hasAdvViewDisc: false,
            hasPermitChange: false,
            hasGrantPermitChange: false,
          },
          basicTrainingID: 0,
          advTrainingID: 0,
        },
      },
      session: {
        adminID: 0,
        changePassword: false,
        domainID: 551,
        koPermissionSyncDate: '2023-09-29T15:25:54.27+00:00',
        onCourseURL: 'https://cherry.mocaworks.com',
        onlinePreference: 'ocHIDDEN',
        profileThumbPath:
          '/v2/domains/551/assets/1960713_tsc3eykcizn_200px.jpg',
        roleID: 1,
        teamRootID: 551,
        teamListSyncDate: '1900-01-01T00:00:00+00:00',
        termsOfServiceSignatureRequired: false,
        timeOutMnts: 129600,
        userID: 1960713,
        userName: 'Joshua Rinard',
      },
      error: {
        sts: 0,
        msg: 'initialized',
      },
      links: [],
      profileImages: [],
    }
  },
  delete: {
    success: () => {
      return {
        recordsAffected: -2,
        session: {
          userID: 2043811,
          userName: 'Johann Loch',
          changePassword: false,
          termsOfServiceSignatureRequired: false,
          adminID: 0,
          teamListSyncDate: '1900-01-01T00:00:00+00:00',
          koPermissionSyncDate: '2024-02-22T20:21:14.963+00:00',
          domainID: 551,
          timeOutMnts: 90,
          onCourseURL: 'https://cherry.mocaworks.com',
          profileThumbPath:
            '/v2/domains/551/assets/2043811_sxuwdy5uwwo_200px.jpg',
          teamRootID: 551,
          roleID: 1,
          onlinePreference: 'ocHIDDEN',
        },
        error: {
          sts: 0,
          msg: 'initialized',
        },
        links: [],
      }
    },
  },
  put: {
    success: () => {
      return {
        recordsAffected: 2,
        session: {
          userID: 2043811,
          userName: 'Johann Loch',
          changePassword: false,
          termsOfServiceSignatureRequired: false,
          adminID: 0,
          teamListSyncDate: '1900-01-01T00:00:00+00:00',
          koPermissionSyncDate: '2024-02-22T20:21:14.963+00:00',
          domainID: 551,
          timeOutMnts: 90,
          onCourseURL: 'https://cherry.mocaworks.com',
          profileThumbPath:
            '/v2/domains/551/assets/2043811_sxuwdy5uwwo_200px.jpg',
          teamRootID: 551,
          roleID: 1,
          onlinePreference: 'ocHIDDEN',
        },
        error: {
          sts: 0,
          msg: 'initialized',
        },
        links: [],
      }
    },
  },
  successCreate: () => {
    return {
      teamID: 1081395,
      session: {
        adminID: 0,
        changePassword: false,
        domainID: 551,
        koPermissionSyncDate: '2023-09-29T15:25:54.27+00:00',
        onCourseURL: 'https://cherry.mocaworks.com',
        onlinePreference: 'ocHIDDEN',
        profileThumbPath:
          '/v2/domains/551/assets/1960713_tsc3eykcizn_200px.jpg',
        roleID: 1,
        teamRootID: 551,
        teamListSyncDate: '1900-01-01T00:00:00+00:00',
        termsOfServiceSignatureRequired: false,
        timeOutMnts: 129600,
        userID: 1960713,
        userName: 'Joshua Rinard',
      },
      error: {
        sts: 0,
        msg: 'initialized',
      },
      links: [],
    }
  },
  invalidFilter: () => {
    return {
      data: [],
      links: [],
      error: {
        logID: -1,
        msg: 'validation error for filterTimeUTC',
        sts: -1000,
        technical: 'should not contain :',
      },
    }
  },
  invalidMissingRequired: (propName: string) => {
    return {
      data: [],
      links: [],
      error: {
        logID: -1,
        sts: -1000,
        msg: `validation error: ${propName} required`,
        technical: `parameters must contain ${propName}`,
      },
    }
  },
}
