/**
 * To populate this please run
 * px g @tyto/scribe:postman
 */
export const TaskStructureEndpointResponses = {
  get: {
    success: (scenario: 'default' | 'no-tasks' = 'default') => {
      return {
        task: {
          tasks:
            scenario === 'no-tasks'
              ? []
              : [
                  {
                    countcompletechildren: 0,
                    countallchildren: 0,
                    locID: 3453549,
                    name: 'Agenda items for:2024.02.01',
                    ocType: 'ocTASK',
                    taskID: 3453549,
                    taskName: 'Agenda items for:2024.02.01',
                    taskDesc: 'With Agenda',
                    taskType: 'ocCONTAINER',
                    memberID: 2448986,
                    mentorID: 0,
                    recurrenceID: 0,
                    completionNote: '',
                    taskStatus: 'ocINCOMPLETE',
                    taskStatusDate: '2024-02-01T20:01:16.77+00:00',
                    completedByID: 2209853,
                    dueDate: '1900-01-01T00:00:00+00:00',
                    createdByID: 2209853,
                    createdDate: '2024-02-01T19:50:03.343+00:00',
                    modifiedByID: 2209853,
                    modifiedDate: '2024-02-01T19:50:03.343+00:00',
                    aboutID: 2448986,
                    aboutType: 'ocEVENT',
                    daysUntilDueFromSiblingCompletion: 0,
                    devplanStepID: 0,
                    areChildrenSequential: false,
                    isCompletionOptional: true,
                    percentComplete: 0,
                    setStatus: 2,
                    attemptCountMax: 0,
                    attemptCount: 0,
                    attemptLastStatus: 'ocVACANT',
                    rootTaskID: 0,
                    startDate: '1900-01-01T00:00:00+00:00',
                    durationMinutes: -1,
                    initialStartDate: '1900-01-01T00:00:00+00:00',
                    about: {
                      name: 'With Agenda',
                      locID: 2448986,
                      ocType: 'ocEVENT',
                      elementID: 2448986,
                      elementName: 'With Agenda',
                      elementDesc: '',
                      elementType: 'ocEVENT',
                      elementSubType: 'ocITEM',
                      domainID: 1698652,
                      outsideID: '',
                      createdByID: 2209853,
                      createdDate: '2024-02-01T19:42:02.573+00:00',
                      primaryElementID: 2209853,
                      modifiedByID: 2209853,
                      modifiedDate: '2024-02-01T19:42:02.573+00:00',
                      libraryItemCount: 0,
                      assets: [],
                      activeStatus: 'ocENABLED',
                    },
                    completedAsOfDate: '1900-01-01T00:00:00+00:00',
                    taskStatusByID: 2209853,
                    isConfidential: false,
                    members: [],
                    verifierTasks: [],
                    permission: {
                      hasView: true,
                      hasConfidentialView: true,
                      hasChangeStatus: true,
                      hasChangeStructure: true,
                      hasChangeExpectation: true,
                      hasChangeDelegate: true,
                    },
                  },
                  {
                    countcompletechildren: 0,
                    countallchildren: 0,
                    locID: 3453550,
                    name: 'Laugh together',
                    ocType: 'ocTASK',
                    taskID: 3453550,
                    taskName: 'Laugh together',
                    taskDesc: 'Laugh together',
                    taskType: 'ocMEETINGAGENDA',
                    memberID: 2448986,
                    mentorID: 0,
                    recurrenceID: 0,
                    completionNote: '',
                    taskStatus: 'ocNOTSTARTED',
                    taskStatusDate: '2024-02-01T19:50:03.79+00:00',
                    completedByID: 0,
                    dueDate: '1900-01-01T11:30:00+00:00',
                    createdByID: 2209853,
                    createdDate: '2024-02-01T19:50:03.79+00:00',
                    modifiedByID: 2209853,
                    modifiedDate: '2024-02-01T19:50:03.79+00:00',
                    aboutID: 2448986,
                    aboutType: 'ocEVENT',
                    daysUntilDueFromSiblingCompletion: 0,
                    devplanStepID: 0,
                    areChildrenSequential: false,
                    isCompletionOptional: false,
                    percentComplete: 0,
                    setStatus: 2,
                    attemptCountMax: 0,
                    attemptCount: 0,
                    attemptLastStatus: 'ocVACANT',
                    rootTaskID: 0,
                    startDate: '1900-01-01T11:30:00+00:00',
                    durationMinutes: 1,
                    initialStartDate: '1900-01-01T00:00:00+00:00',
                    about: {
                      name: 'With Agenda',
                      locID: 2448986,
                      ocType: 'ocEVENT',
                      elementID: 2448986,
                      elementName: 'With Agenda',
                      elementDesc: '',
                      elementType: 'ocEVENT',
                      elementSubType: 'ocITEM',
                      domainID: 1698652,
                      outsideID: '',
                      createdByID: 2209853,
                      createdDate: '2024-02-01T19:42:02.573+00:00',
                      primaryElementID: 2209853,
                      modifiedByID: 2209853,
                      modifiedDate: '2024-02-01T19:42:02.573+00:00',
                      libraryItemCount: 0,
                      assets: [],
                      activeStatus: 'ocENABLED',
                    },
                    completedAsOfDate: '1900-01-01T00:00:00+00:00',
                    taskStatusByID: 2209853,
                    isConfidential: false,
                    members: [],
                    verifierTasks: [],
                    permission: {
                      hasView: true,
                      hasConfidentialView: true,
                      hasChangeStatus: true,
                      hasChangeStructure: true,
                      hasChangeExpectation: true,
                      hasChangeDelegate: true,
                    },
                  },
                  {
                    countcompletechildren: 0,
                    countallchildren: 0,
                    locID: 3453559,
                    name: 'Look at agenda',
                    ocType: 'ocTASK',
                    taskID: 3453559,
                    taskName: 'Look at agenda',
                    taskDesc:
                      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
                    taskType: 'ocMEETINGAGENDA',
                    memberID: 2209853,
                    mentorID: 0,
                    recurrenceID: 0,
                    completionNote: '',
                    taskStatus: 'ocNOTSTARTED',
                    taskStatusDate: '2024-02-01T20:01:16.763+00:00',
                    completedByID: 0,
                    dueDate: '1900-01-01T11:30:00+00:00',
                    createdByID: 2209853,
                    createdDate: '2024-02-01T20:01:16.763+00:00',
                    modifiedByID: 2209853,
                    modifiedDate: '2024-02-01T20:01:16.763+00:00',
                    aboutID: 2448986,
                    aboutType: 'ocEVENT',
                    daysUntilDueFromSiblingCompletion: 0,
                    devplanStepID: 0,
                    areChildrenSequential: false,
                    isCompletionOptional: false,
                    percentComplete: 0,
                    setStatus: 2,
                    attemptCountMax: 0,
                    attemptCount: 0,
                    attemptLastStatus: 'ocVACANT',
                    rootTaskID: 0,
                    startDate: '1900-01-01T11:30:00+00:00',
                    durationMinutes: -1,
                    initialStartDate: '1900-01-01T00:00:00+00:00',
                    about: {
                      name: 'With Agenda',
                      locID: 2448986,
                      ocType: 'ocEVENT',
                      elementID: 2448986,
                      elementName: 'With Agenda',
                      elementDesc: '',
                      elementType: 'ocEVENT',
                      elementSubType: 'ocITEM',
                      domainID: 1698652,
                      outsideID: '',
                      createdByID: 2209853,
                      createdDate: '2024-02-01T19:42:02.573+00:00',
                      primaryElementID: 2209853,
                      modifiedByID: 2209853,
                      modifiedDate: '2024-02-01T19:42:02.573+00:00',
                      libraryItemCount: 0,
                      assets: [],
                      activeStatus: 'ocENABLED',
                    },
                    completedAsOfDate: '1900-01-01T00:00:00+00:00',
                    taskStatusByID: 2209853,
                    isConfidential: false,
                    members: [],
                    verifierTasks: [],
                    permission: {
                      hasView: true,
                      hasConfidentialView: true,
                      hasChangeStatus: true,
                      hasChangeStructure: true,
                      hasChangeExpectation: true,
                      hasChangeDelegate: true,
                    },
                  },
                ],
          taskRelations: [
            {
              parentTaskID: 3453549,
              childTaskID: 3453550,
              seq: 1,
              rootTaskID: 0,
            },
            {
              parentTaskID: 3453549,
              childTaskID: 3453559,
              seq: 2,
              rootTaskID: 0,
            },
            {
              parentTaskID: 0,
              childTaskID: 3453549,
              seq: 9999989,
              rootTaskID: 0,
            },
          ],
          members: [
            {
              mentors: [],
              memberID: 2209853,
              memberName: 'John Bailey',
              photoAsset: {
                ocType: 'ocASSET',
                assetID: 2218073,
                assetType: 'ocPhoto',
                courseItemID: 2209853,
                assetPath: '2209853_kvemjhrbf1w_1024px.jpg',
                sizeBytes: 0,
                mimeType: 'image/jpeg',
                thumbnailPath: '2209853_kvemjhrbf1w_200px.jpg',
                thumbnailMimeType: 'image/jpeg',
                height: 500,
                width: 500,
                length: 0,
                isFixedThumbnailPath: 0,
                isFixedAssetPath: 0,
                sequence: 2,
                softwareRequirements: '',
                locID: 2218073,
                domainID: 1698652,
              },
              locID: 2209853,
              ocType: 'ocPERSON',
              domainID: 1698652,
              primaryElementID: 1763850,
              activeStatus: 'ocENABLED',
            },
            {
              mentors: [],
              memberID: 2448986,
              memberName: 'With Agenda',
              locID: 2448986,
              ocType: 'ocEVENT',
              domainID: 1698652,
              primaryElementID: 2209853,
              activeStatus: 'ocENABLED',
            },
          ],
          delegateParticipationRoles: [],
        },
        session: {
          userID: 2209853,
          userName: 'John Bailey',
          changePassword: false,
          termsOfServiceSignatureRequired: false,
          adminID: 0,
          teamListSyncDate: '1900-01-01T00:00:00+00:00',
          koPermissionSyncDate: '2024-02-01T01:37:22.477+00:00',
          domainID: 1698652,
          timeOutMnts: 129600,
          onCourseURL: 'https://cardoneventuresceo.com',
          profileThumbPath:
            '/v2/domains/1698652/assets/2209853_kvemjhrbf1w_200px.jpg',
          teamRootID: 1763850,
          roleID: 432,
          onlinePreference: 'ocAVAILABLE',
        },
        error: {
          sts: 0,
          msg: 'cmdGetTaskStructure',
        },
        links: [],
      }
    },
  },
  invalidMissingRequired: (propName: string) => {
    return {
      data: [],
      links: [],
      error: {
        logID: -1,
        sts: -1000,
        msg: `validation error: ${propName} required`,
        technical: `parameters must contain ${propName}`,
      },
    }
  },
}
