import { Endpoints } from '@tyto/client'

export const fixtureCatalogInboxPopulated =
  (): Endpoints.Tyto.CatalogInbox.Get.Response => {
    return {
      catalogs: [
        {
          childContainers: [
            {
              childContainers: [
                {
                  childContainers: [
                    {
                      childContainers: [
                        {
                          childContainers: [],
                          childItems: [],
                          images: [],
                          catalogID: 2250211,
                          description: '',
                          catalogType: 'ocINBOX',
                          parentCatalogID: 2250210,
                          primaryElementTreeSerialLeft: 0,
                          pathName: "\tNew\tCHild\tanoth\tlet's go\t",
                          pathIDs: ',2250158,2250208,2250209,2250210,',
                          thumbnailPath: '',
                          catalogItemID: 2250158,
                          catalogItemType: 'ocCATALOG',
                          catalogItemSubType: 'ocCONTAINER',
                          hasChange: true,
                          hasAdd: true,
                          hasDelete: true,
                          siblingSeq: 2250211,
                          name: 'sdfgsdfg',
                          locID: 2250211,
                          ocType: 'ocELEMENT',
                          domainID: 1698652,
                          outsideID: '',
                          createdByID: 2209853,
                          createdDate: '2023-07-26T14:32:18.317+00:00',
                          primaryElementID: 2209853,
                          modifiedByID: 2209853,
                          modifiedDate: '2023-07-26T14:32:18.317+00:00',
                          activeStatus: 'ocENABLED',
                        },
                      ],
                      childItems: [],
                      images: [],
                      catalogID: 2250210,
                      description: '',
                      catalogType: 'ocINBOX',
                      parentCatalogID: 2250209,
                      primaryElementTreeSerialLeft: 0,
                      pathName: '\tNew\tCHild\tanoth\t',
                      pathIDs: ',2250158,2250208,2250209,',
                      thumbnailPath: '',
                      catalogItemID: 2250158,
                      catalogItemType: 'ocCATALOG',
                      catalogItemSubType: 'ocCONTAINER',
                      hasChange: true,
                      hasAdd: true,
                      hasDelete: true,
                      siblingSeq: 2250210,
                      name: "let's go",
                      locID: 2250210,
                      ocType: 'ocELEMENT',
                      domainID: 1698652,
                      outsideID: '',
                      createdByID: 2209853,
                      createdDate: '2023-07-26T14:32:15.073+00:00',
                      primaryElementID: 2209853,
                      modifiedByID: 2209853,
                      modifiedDate: '2023-07-26T14:32:15.073+00:00',
                      activeStatus: 'ocENABLED',
                    },
                  ],
                  childItems: [
                    {
                      about: {
                        catalogIDs: [2255179],
                        name: 'nothing',
                        locID: 6747665,
                        ocType: 'ocNOTICE',
                        noticeID: 6747665,
                        noticeType: 'ocPrivateIN',
                        actionType: 'ocReply',
                        toElementID: 2209853,
                        fromElementID: 2209853,
                        noticeText: 'nothing',
                        noticeDate: '2023-08-03T17:19:18.093+00:00',
                        isNew: false,
                        isCritical: false,
                        isCascade: false,
                        aboutType: 'ocNOTICE',
                        aboutID: 6747664,
                        functionID: 37,
                        param1: '6747664',
                        param2: '',
                        param3: '',
                        param4: '',
                        about: {
                          locID: 6747664,
                          ocType: 'ocNOTICE',
                          name: 'test',
                          noticeID: 6747664,
                          noticeType: 'ocPrivateThread',
                          actionType: 'ocNewThread',
                          activeStatus: 'ocENABLED',
                          aboutID: 0,
                          aboutType: '',
                          noticeDate: '2023-08-03T17:19:18.09',
                          isCritical: false,
                          noticeText: 'test',
                          commentCount: 0,
                          commentCountNew: 0,
                          attachmentCount: 0,
                          members: [
                            {
                              emailPreference: 'ocINSTANT',
                              lastComment: '1900-01-01T00:00:00+00:00',
                              lastDraft: '1900-01-01T00:00:00+00:00',
                              recentUnread: '2023-08-03T17:19:18.093+00:00',
                              element: {
                                elementID: 2048276,
                                elementName: 'Ariel Zilist',
                                activeStatus: 'ocENABLED',
                                elementType: 'ocPERSON',
                                profilePhoto: {
                                  thumbnailPath:
                                    '2048276_nkjdniondpj_200px.jpg',
                                  domainID: 1698652,
                                },
                              },
                            },
                            {
                              emailPreference: 'ocINSTANT',
                              lastComment: '1900-01-01T00:00:00+00:00',
                              lastDraft: '1900-01-01T00:00:00+00:00',
                              recentUnread: '2500-01-01T00:00:00+00:00',
                              element: {
                                elementID: 2209853,
                                elementName: 'John Bailey',
                                activeStatus: 'ocENABLED',
                                elementType: 'ocPERSON',
                                profilePhoto: {
                                  thumbnailPath:
                                    '2209853_kvemjhrbf1w_200px.jpg',
                                  domainID: 1698652,
                                },
                              },
                            },
                          ],
                        },
                        activeStatus: 'ocENABLED',
                      },
                      catalogID: 2255179,
                      description: '',
                      catalogType: 'ocINBOX',
                      parentCatalogID: 2250209,
                      primaryElementTreeSerialLeft: 0,
                      pathName: '\tNew\tCHild\tanoth\t',
                      pathIDs: ',2250158,2250208,2250209,',
                      thumbnailPath: '',
                      catalogItemID: 6747665,
                      catalogItemType: 'ocNOTICE',
                      catalogItemSubType: 'ocPrivateIN',
                      hasChange: true,
                      hasAdd: true,
                      hasDelete: true,
                      siblingSeq: 2255179,
                      name: '',
                      locID: 2255179,
                      ocType: 'ocELEMENT',
                      domainID: 1698652,
                      outsideID: '',
                      createdByID: 2209853,
                      createdDate: '2023-08-06T13:36:32.68+00:00',
                      primaryElementID: 2209853,
                      modifiedByID: 2209853,
                      modifiedDate: '2023-08-06T13:36:32.68+00:00',
                      activeStatus: 'ocENABLED',
                    },
                    {
                      about: {
                        catalogIDs: [2255540],
                        name: '084671',
                        locID: 6752674,
                        ocType: 'ocNOTICE',
                        noticeID: 6752674,
                        noticeType: 'ocPrivateIN',
                        actionType: 'ocReply',
                        toElementID: 2209853,
                        fromElementID: 2209853,
                        noticeText: '084671',
                        noticeDate: '2023-08-04T23:39:36+00:00',
                        isNew: false,
                        isCritical: false,
                        isCascade: false,
                        aboutType: 'ocNOTICE',
                        aboutID: 6752673,
                        functionID: 37,
                        param1: '6752673',
                        param2: '',
                        param3: '',
                        param4: '',
                        about: {
                          locID: 6752673,
                          ocType: 'ocNOTICE',
                          name: 'Move me',
                          noticeID: 6752673,
                          noticeType: 'ocPrivateThread',
                          actionType: 'ocNewThread',
                          activeStatus: 'ocENABLED',
                          aboutID: 0,
                          aboutType: '',
                          noticeDate: '2023-08-04T23:39:35.91',
                          isCritical: false,
                          noticeText: 'Move me',
                          commentCount: 1,
                          commentCountNew: 0,
                          attachmentCount: 0,
                          members: [
                            {
                              emailPreference: 'ocINSTANT',
                              lastComment: '1900-01-01T00:00:00+00:00',
                              lastDraft: '1900-01-01T00:00:00+00:00',
                              recentUnread: '2023-08-04T23:39:35.913+00:00',
                              element: {
                                elementID: 1503800,
                                elementName: 'Austin Blain',
                                activeStatus: 'ocENABLED',
                                elementType: 'ocPERSON',
                                profilePhoto: {
                                  thumbnailPath:
                                    '1503800_xyt0irmgjfa_200px.jpg',
                                  domainID: 551,
                                },
                              },
                            },
                            {
                              emailPreference: 'ocINSTANT',
                              lastComment: '2023-08-04T23:39:35.913+00:00',
                              lastDraft: '1900-01-01T00:00:00+00:00',
                              recentUnread: '2500-01-01T00:00:00+00:00',
                              element: {
                                elementID: 2209853,
                                elementName: 'John Bailey',
                                activeStatus: 'ocENABLED',
                                elementType: 'ocPERSON',
                                profilePhoto: {
                                  thumbnailPath:
                                    '2209853_kvemjhrbf1w_200px.jpg',
                                  domainID: 1698652,
                                },
                              },
                            },
                          ],
                        },
                        activeStatus: 'ocENABLED',
                      },
                      catalogID: 2255540,
                      description: '',
                      catalogType: 'ocINBOX',
                      parentCatalogID: 2250209,
                      primaryElementTreeSerialLeft: 0,
                      pathName: '\tNew\tCHild\tanoth\t',
                      pathIDs: ',2250158,2250208,2250209,',
                      thumbnailPath: '',
                      catalogItemID: 6752674,
                      catalogItemType: 'ocNOTICE',
                      catalogItemSubType: 'ocPrivateIN',
                      hasChange: true,
                      hasAdd: true,
                      hasDelete: true,
                      siblingSeq: 2255540,
                      name: '',
                      locID: 2255540,
                      ocType: 'ocELEMENT',
                      domainID: 1698652,
                      outsideID: '',
                      createdByID: 2209853,
                      createdDate: '2023-08-07T17:07:07.66+00:00',
                      primaryElementID: 2209853,
                      modifiedByID: 2209853,
                      modifiedDate: '2023-08-07T17:07:07.66+00:00',
                      activeStatus: 'ocENABLED',
                    },
                  ],
                  images: [],
                  catalogID: 2250209,
                  description: '',
                  catalogType: 'ocINBOX',
                  parentCatalogID: 2250208,
                  primaryElementTreeSerialLeft: 0,
                  pathName: '\tNew\tCHild\t',
                  pathIDs: ',2250158,2250208,',
                  thumbnailPath: '',
                  catalogItemID: 2250158,
                  catalogItemType: 'ocCATALOG',
                  catalogItemSubType: 'ocCONTAINER',
                  hasChange: true,
                  hasAdd: true,
                  hasDelete: true,
                  siblingSeq: 2250209,
                  name: 'anoth',
                  locID: 2250209,
                  ocType: 'ocELEMENT',
                  domainID: 1698652,
                  outsideID: '',
                  createdByID: 2209853,
                  createdDate: '2023-07-26T14:32:09.253+00:00',
                  primaryElementID: 2209853,
                  modifiedByID: 2209853,
                  modifiedDate: '2023-07-26T14:32:09.253+00:00',
                  activeStatus: 'ocENABLED',
                },
                {
                  childContainers: [],
                  childItems: [],
                  images: [],
                  catalogID: 2254721,
                  description: '',
                  catalogType: 'ocINBOX',
                  parentCatalogID: 2250208,
                  primaryElementTreeSerialLeft: 0,
                  pathName: '\tNew\tCHild\t',
                  pathIDs: ',2250158,2250208,',
                  thumbnailPath: '',
                  catalogItemID: 2250158,
                  catalogItemType: 'ocCATALOG',
                  catalogItemSubType: 'ocCONTAINER',
                  hasChange: true,
                  hasAdd: true,
                  hasDelete: true,
                  siblingSeq: 2254721,
                  name: 'sfdgsdfg',
                  locID: 2254721,
                  ocType: 'ocELEMENT',
                  domainID: 1698652,
                  outsideID: '',
                  createdByID: 2209853,
                  createdDate: '2023-08-04T14:47:12.687+00:00',
                  primaryElementID: 2209853,
                  modifiedByID: 2209853,
                  modifiedDate: '2023-08-04T14:47:12.687+00:00',
                  activeStatus: 'ocENABLED',
                },
              ],
              childItems: [],
              images: [],
              catalogID: 2250208,
              description: '',
              catalogType: 'ocINBOX',
              parentCatalogID: 2250158,
              primaryElementTreeSerialLeft: 0,
              pathName: '\tNew\t',
              pathIDs: ',2250158,',
              thumbnailPath: '',
              catalogItemID: 2250158,
              catalogItemType: 'ocCATALOG',
              catalogItemSubType: 'ocCONTAINER',
              hasChange: true,
              hasAdd: true,
              hasDelete: true,
              siblingSeq: 2250208,
              name: 'CHild',
              locID: 2250208,
              ocType: 'ocELEMENT',
              domainID: 1698652,
              outsideID: '',
              createdByID: 2209853,
              createdDate: '2023-07-26T14:31:18.75+00:00',
              primaryElementID: 2209853,
              modifiedByID: 2209853,
              modifiedDate: '2023-07-26T14:31:18.75+00:00',
              activeStatus: 'ocENABLED',
            },
            {
              childContainers: [],
              childItems: [],
              images: [],
              catalogID: 2254776,
              description: '',
              catalogType: 'ocINBOX',
              parentCatalogID: 2250158,
              primaryElementTreeSerialLeft: 0,
              pathName: '\tNew\t',
              pathIDs: ',2250158,',
              thumbnailPath: '',
              catalogItemID: 2250158,
              catalogItemType: 'ocCATALOG',
              catalogItemSubType: 'ocCONTAINER',
              hasChange: true,
              hasAdd: true,
              hasDelete: true,
              siblingSeq: 2254776,
              name: 'try',
              locID: 2254776,
              ocType: 'ocELEMENT',
              domainID: 1698652,
              outsideID: '',
              createdByID: 2209853,
              createdDate: '2023-08-04T16:55:16.39+00:00',
              primaryElementID: 2209853,
              modifiedByID: 2209853,
              modifiedDate: '2023-08-04T16:55:16.39+00:00',
              activeStatus: 'ocENABLED',
            },
          ],
          childItems: [
            {
              about: {
                catalogIDs: [2254540],
                name: "I don't know what endpoint to use so I'm doing this instead",
                locID: 6747359,
                ocType: 'ocNOTICE',
                noticeID: 6747359,
                noticeType: 'ocPrivateIN',
                actionType: 'ocReply',
                toElementID: 2209853,
                fromElementID: 2209853,
                noticeText:
                  "I don't know what endpoint to use so I'm doing this instead",
                noticeDate: '2023-08-03T16:10:26.97+00:00',
                isNew: false,
                isCritical: false,
                isCascade: false,
                aboutType: 'ocNOTICE',
                aboutID: 6747358,
                functionID: 37,
                param1: '6747358',
                param2: '',
                param3: '',
                param4: '',
                about: {
                  locID: 6747358,
                  ocType: 'ocNOTICE',
                  name: 'Testing moving to other folders',
                  noticeID: 6747358,
                  noticeType: 'ocPrivateThread',
                  actionType: 'ocNewThread',
                  activeStatus: 'ocENABLED',
                  aboutID: 0,
                  aboutType: '',
                  noticeDate: '2023-08-03T16:10:26.96',
                  isCritical: false,
                  noticeText: 'Testing moving to other folders',
                  commentCount: 1,
                  commentCountNew: 0,
                  attachmentCount: 0,
                  members: [
                    {
                      emailPreference: 'ocINSTANT',
                      lastComment: '1900-01-01T00:00:00+00:00',
                      lastDraft: '1900-01-01T00:00:00+00:00',
                      recentUnread: '2023-08-03T16:10:26.97+00:00',
                      element: {
                        elementID: 1503800,
                        elementName: 'Austin Blain',
                        activeStatus: 'ocENABLED',
                        elementType: 'ocPERSON',
                        profilePhoto: {
                          thumbnailPath: '1503800_xyt0irmgjfa_200px.jpg',
                          domainID: 551,
                        },
                      },
                    },
                    {
                      emailPreference: 'ocINSTANT',
                      lastComment: '2023-08-03T16:10:26.97+00:00',
                      lastDraft: '1900-01-01T00:00:00+00:00',
                      recentUnread: '2500-01-01T00:00:00+00:00',
                      element: {
                        elementID: 2209853,
                        elementName: 'John Bailey',
                        activeStatus: 'ocENABLED',
                        elementType: 'ocPERSON',
                        profilePhoto: {
                          thumbnailPath: '2209853_kvemjhrbf1w_200px.jpg',
                          domainID: 1698652,
                        },
                      },
                    },
                  ],
                },
                activeStatus: 'ocENABLED',
              },
              catalogID: 2254540,
              description: '',
              catalogType: 'ocINBOX',
              parentCatalogID: 2250158,
              primaryElementTreeSerialLeft: 0,
              pathName: '\tNew\t',
              pathIDs: ',2250158,',
              thumbnailPath: '',
              catalogItemID: 6747359,
              catalogItemType: 'ocNOTICE',
              catalogItemSubType: 'ocPrivateIN',
              hasChange: true,
              hasAdd: true,
              hasDelete: true,
              siblingSeq: 2254540,
              name: '',
              locID: 2254540,
              ocType: 'ocELEMENT',
              domainID: 1698652,
              outsideID: '',
              createdByID: 2209853,
              createdDate: '2023-08-03T21:59:15.283+00:00',
              primaryElementID: 2209853,
              modifiedByID: 2209853,
              modifiedDate: '2023-08-03T21:59:15.283+00:00',
              activeStatus: 'ocENABLED',
            },
          ],
          images: [],
          catalogID: 2250158,
          description: '',
          catalogType: 'ocINBOX',
          parentCatalogID: 0,
          primaryElementTreeSerialLeft: 0,
          pathName: '\t',
          pathIDs: ',',
          thumbnailPath: '',
          catalogItemID: 2250158,
          catalogItemType: 'ocCATALOG',
          catalogItemSubType: 'ocCONTAINER',
          hasChange: true,
          hasAdd: true,
          hasDelete: true,
          siblingSeq: 2250158,
          name: 'New',
          locID: 2250158,
          ocType: 'ocELEMENT',
          domainID: 1698652,
          outsideID: '',
          createdByID: 2209853,
          createdDate: '2023-07-26T01:59:12.537+00:00',
          primaryElementID: 2209853,
          modifiedByID: 2209853,
          modifiedDate: '2023-07-26T14:31:08.31+00:00',
          activeStatus: 'ocENABLED',
        },
        {
          childContainers: [],
          childItems: [],
          images: [],
          catalogID: 2254744,
          description: '',
          catalogType: 'ocINBOX',
          parentCatalogID: 0,
          primaryElementTreeSerialLeft: 0,
          pathName: '\t',
          pathIDs: ',',
          thumbnailPath: '',
          catalogItemID: 2254744,
          catalogItemType: 'ocCATALOG',
          catalogItemSubType: 'ocCONTAINER',
          hasChange: true,
          hasAdd: true,
          hasDelete: true,
          siblingSeq: 2254744,
          name: 'Top one',
          locID: 2254744,
          ocType: 'ocELEMENT',
          domainID: 1698652,
          outsideID: '',
          createdByID: 2209853,
          createdDate: '2023-08-04T16:06:46.07+00:00',
          primaryElementID: 2209853,
          modifiedByID: 2209853,
          modifiedDate: '2023-08-04T16:06:46.07+00:00',
          activeStatus: 'ocENABLED',
        },
      ],
      securityTraits: [],
      domains: [
        {
          domainID: 1698652,
          audienceDescLabel: 'Audience',
          difficultyDescLabel: 'Difficulty',
          expectationDescLabel: 'Expectation',
        },
      ],
      primaryElements: [],
      session: {
        userID: 2209853,
        userName: 'John Bailey',
        changePassword: false,
        termsOfServiceSignatureRequired: false,
        adminID: 0,
        teamListSyncDate: '1900-01-01T00:00:00+00:00',
        koPermissionSyncDate: '2023-08-07T16:49:31.43+00:00',
        domainID: 1698652,
        timeOutMnts: 2160,
        onCourseURL: 'https://cardoneventuresceo.com',
        profileThumbPath:
          '/v2/domains/1698652/assets/2209853_kvemjhrbf1w_200px.jpg',
        teamRootID: 1763850,
        roleID: 432,
        onlinePreference: 'ocAVAILABLE',
      },
      error: {
        sts: 0,
        msg: 'initialized',
      },
      links: [],
    }
  }
