/**
 * To populate this please run
 * px g @tyto/scribe:postman
 */
export const MenuEndpointResponses = {
  get: {
    success: () => {
      return {
        menuItems: [
          {
            functionID: 43,
            displayName: 'Development',
            functionName: 'Beta',
            iconPath: '/v25/images/mobile/dev_128px.png',
            iconName: 'Dev',
            menuGroup: '/',
            links: [
              {
                encType: 'application/x-www-form-urlencoded',
                contentType: 'text/html',
                href: '/v25/mobile/Teamboard',
                media: 'screen',
                method: 'get',
                targetPref: '_top',
                title: 'TeamboardTest',
                parameters: [],
                rel: ['http://kvau.lt/legacy/mobile/ui'],
              },
            ],
            param4Desc: '',
            param3Desc: '',
            param2Desc: '',
            param1Desc: 'URI',
            iconPathLarge: '',
            longName: '',
          },
          {
            functionID: 89,
            displayName: 'Austin Blain',
            functionName: 'SB MyAccount',
            iconPath: '/v25/user/photo/?encoding=ocTHUMBNAIL&assetID=1942036',
            iconName: 'user',
            menuGroup: '/',
            links: [
              {
                encType: 'application/x-www-form-urlencoded',
                contentType: 'text/html',
                href: '/v25/nl/#/profile/1503800',
                media: 'screen',
                method: 'get',
                targetPref: '_top',
                title: 'Change My Profile',
                parameters: [],
                rel: ['http://kvau.lt/legacy/mobile/ui'],
              },
              {
                encType: 'application/x-www-form-urlencoded',
                contentType: 'application/json',
                href: '/api/Person/MyAccount',
                media: '',
                method: 'get',
                targetPref: '',
                title: 'My Account',
                parameters: [
                  {
                    paramName: 'sessionKey',
                    paramType: 'string',
                    value: '',
                  },
                ],
                rel: ['http://kvau.lt/api/MyAccount'],
              },
            ],
            param4Desc: '',
            param3Desc: '',
            param2Desc: '',
            param1Desc: '',
            iconPathLarge:
              '/v25/user/photo/?encoding=ocDEFAULT&assetID=1942036',
            longName: '',
          },
          {
            functionID: 102,
            displayName: 'Param1 elementName',
            functionName: 'Page Lesson',
            iconPath:
              '/viewAsset/?encoding=ocTHUMBNAIL&sessionKey=YV96HCF9R4KXKNVMRQMFMBWD0ZH2JLWFPHLKZ3452PT1Z04YLMTPJNXT67B4BV9F&eID=352514',
            iconName: '',
            menuGroup: '/',
            links: [
              {
                encType: 'application/javascript',
                contentType: 'application/x-kvault',
                href: 'kvault://viewer',
                media: 'screen',
                method: 'get',
                targetPref: '_top',
                title: 'Knowledge Object Viewer',
                parameters: [],
                rel: ['http://kvau.lt/mobileapp/native'],
              },
            ],
            param4Desc: 'lessonItemType',
            param3Desc: 'noticeID',
            param2Desc: 'assetID',
            param1Desc: 'lessonID',
            param3: ' ',
            param2: ' ',
            param1: '352514',
            param4: 'ocDOCUMENT',
            iconPathLarge:
              '/viewAsset/?encoding=ocTHUMBNAIL&sessionKey=YV96HCF9R4KXKNVMRQMFMBWD0ZH2JLWFPHLKZ3452PT1Z04YLMTPJNXT67B4BV9F&eID=352514',
            longName: '',
          },
          {
            functionID: 102,
            displayName: 'Param1 elementName',
            functionName: 'Page Lesson',
            iconPath:
              '/viewAsset/?encoding=ocTHUMBNAIL&sessionKey=YV96HCF9R4KXKNVMRQMFMBWD0ZH2JLWFPHLKZ3452PT1Z04YLMTPJNXT67B4BV9F&eID=587716',
            iconName: '',
            menuGroup: '/',
            links: [
              {
                encType: 'application/javascript',
                contentType: 'application/x-kvault',
                href: 'kvault://viewer',
                media: 'screen',
                method: 'get',
                targetPref: '_top',
                title: 'Knowledge Object Viewer',
                parameters: [],
                rel: ['http://kvau.lt/mobileapp/native'],
              },
            ],
            param4Desc: 'lessonItemType',
            param3Desc: 'noticeID',
            param2Desc: 'assetID',
            param1Desc: 'lessonID',
            param3: '',
            param2: '',
            param1: '587716',
            param4: 'ocDOCUMENT',
            iconPathLarge:
              '/viewAsset/?encoding=ocTHUMBNAIL&sessionKey=YV96HCF9R4KXKNVMRQMFMBWD0ZH2JLWFPHLKZ3452PT1Z04YLMTPJNXT67B4BV9F&eID=587716',
            longName: '',
          },
          {
            functionID: 51,
            displayName: 'Search',
            functionName: 'Page Search',
            iconPath: '',
            iconName: '',
            menuGroup: '/',
            links: [
              {
                encType: 'application/x-www-form-urlencoded',
                contentType: 'text/html',
                href: '/v25/nl/#/search',
                media: 'screen',
                method: 'get',
                targetPref: '_top',
                title: 'Search',
                parameters: [
                  {
                    paramName: 'SearchTerm',
                    paramType: 'string',
                    value: '',
                  },
                  {
                    paramName: 'page',
                    paramType: 'int',
                    value: '',
                  },
                  {
                    paramName: 'maxres',
                    paramType: 'int',
                    value: '',
                  },
                ],
                rel: ['http://kvau.lt/default', 'http://kvau.lt/legacy/v2/ui'],
              },
              {
                encType: 'application/x-www-form-urlencoded',
                contentType: 'text/html',
                href: '/v25/nl/#/chat-ambassador',
                media: 'screen',
                method: 'get',
                targetPref: '_top',
                title: 'Ambassador Chat',
                parameters: [],
                rel: [
                  'http://kvau.lt/nl',
                  'http://kvau.lt/nl/alpha?roleID=1',
                  'http://kvau.lt/nl/alpha?roleID=511',
                  'http://kvau.lt/nl/alpha?userID=1625045',
                  'http://kvau.lt/nl/alpha?userID=2077672',
                  'http://kvau.lt/nl/alpha?userID=2213955',
                  'http://kvau.lt/nl/alpha?userID=2237252',
                  'http://kvau.lt/nl/alpha?userID=2854414',
                ],
              },
            ],
            param4Desc: '',
            param3Desc: '',
            param2Desc: '',
            param1Desc: '',
            iconPathLarge: '',
            longName: '',
          },
          {
            functionID: 155,
            displayName: 'Service Request',
            functionName: 'ServiceBid',
            iconPath: '',
            iconName: '',
            menuGroup: '/',
            links: [
              {
                encType: 'application/x-www-form-urlencoded',
                contentType: 'text/html',
                href: '/v25/nl/#/servicebid/',
                media: '',
                method: 'get',
                targetPref: '_top',
                title: 'Service Request',
                parameters: [],
                rel: ['http://kvau.lt/default', 'http://kvau.lt/nl'],
              },
            ],
            subMenu: [
              {
                functionID: 159,
                displayName: 'Test Method',
                functionName: 'ServiceBidMethod=1',
                iconPath: '',
                iconName: '',
                menuGroup: '/Service Request/',
                links: [
                  {
                    encType: 'application/x-www-form-urlencoded',
                    contentType: 'text/html',
                    href: '/v25/nl/#/servicebid/1',
                    media: '',
                    method: 'get',
                    targetPref: '_top',
                    title: 'Service Method',
                    parameters: [
                      {
                        paramName: 'serviceBidMethodID',
                        paramType: 'int',
                        value: '',
                      },
                    ],
                    rel: ['http://kvau.lt/nl'],
                  },
                ],
                param4Desc: '',
                param3Desc: '',
                param2Desc: '',
                param1Desc: 'serviceBidMethodID',
                param1: '1',
                iconPathLarge: '',
                longName: '',
              },
            ],
            param4Desc: '',
            param3Desc: '',
            param2Desc: 'serviceBidMethodID',
            param1Desc: 'serviceBidID',
            iconPathLarge: '',
            longName: '',
          },
          {
            functionID: 160,
            displayName: 'Surveys',
            functionName: 'Page Survey',
            iconPath: '',
            iconName: '',
            menuGroup: '/',
            links: [
              {
                encType: 'application/x-www-form-urlencoded',
                contentType: 'text/html',
                href: '/v25/nl/#/surveys',
                media: '',
                method: 'get',
                targetPref: '_top',
                title: 'Surveys',
                parameters: [],
                rel: ['http://kvau.lt/default', 'http://kvau.lt/nl'],
              },
            ],
            param4Desc: '',
            param3Desc: '',
            param2Desc: '',
            param1Desc: 'inviteID',
            iconPathLarge: '',
            longName: '',
          },
          {
            functionID: 101,
            displayName: 'bugs',
            functionName: 'Page Bugs',
            iconPath: '/v25/images/icons/elementType/ocBUG/ocBug_50px.png',
            iconName: 'ocBug',
            menuGroup: '/',
            links: [
              {
                encType: 'application/x-www-form-urlencoded',
                contentType: 'text/html',
                href: '/x/bugs',
                media: '',
                method: 'get',
                targetPref: '_top',
                title: 'Bug Reports',
                parameters: [],
                rel: ['http://kvau.lt/default'],
              },
            ],
            param4Desc: '',
            param3Desc: '',
            param2Desc: '',
            param1Desc: 'bugID',
            iconPathLarge: '',
            keyPhrases: ['Bug report', 'This thing sucks', 'why is it broken'],
            description:
              'Browse bug reports, post suggestions for new features, ask questions about Tryyb',
            longName: '',
          },
          {
            functionID: 107,
            displayName: 'Manage Teams',
            functionName: 'Page TeamEditor',
            iconPath: '/v25/images/icons/elementType/ocTEAM/ocTeam_50px.png',
            iconName: 'ocTeam_50px.png',
            menuGroup: '/',
            links: [
              {
                encType: 'application/x-www-form-urlencoded',
                contentType: 'text/html',
                href: '/v25/team_e/team.asp',
                media: '',
                method: 'get',
                targetPref: '_top',
                title: 'Teams',
                parameters: [],
                rel: [
                  'http://kvau.lt/legacy/v2/ui',
                  'http://kvau.lt/nl/legacy?domainID=1698652',
                  'http://kvau.lt/nl/legacy?domainID=1825957',
                  'http://kvau.lt/nl/legacy?domainID=2823418',
                  'http://kvau.lt/nl/legacy?domainID=551',
                ],
              },
              {
                encType: 'application/x-www-form-urlencoded',
                contentType: 'text/html',
                href: '/v25/nl/#/team-editor',
                media: 'get',
                method: 'get',
                targetPref: '_top',
                title: 'Team Editor',
                parameters: [],
                rel: [
                  'http://kvau.lt/default',
                  'http://kvau.lt/nl',
                  'http://kvau.lt/nl/iframe?iframeOrigin=https://team-editor.azureedge.net/team-editor',
                ],
              },
            ],
            param4Desc: '',
            param3Desc: 'eID',
            param2Desc: 'userID',
            param1Desc: 'teamID',
            iconPathLarge: '',
            longName: '',
          },
          {
            functionID: 114,
            displayName: 'R3 DISC',
            functionName: 'Person TraitR3',
            iconPath: '/v2/domains/167210/images/R3_chiclet_Logo_Final_128.png',
            iconName: '',
            menuGroup: '/',
            links: [
              {
                encType: 'application/x-www-form-urlencoded',
                contentType: 'text/html',
                href: '/v25/nl/#/r3-tool',
                media: 'screen',
                method: 'get',
                targetPref: '_top',
                title: 'R3 Tool',
                parameters: [],
                rel: [
                  'http://kvau.lt/default',
                  'http://kvau.lt/nl',
                  'http://kvau.lt/nl/default?domainID=551',
                  'http://kvau.lt/nl/iframe?iframeOrigin=https://cherry-r3.azureedge.net',
                ],
              },
              {
                encType: 'application/x-www-form-urlencoded',
                contentType: 'text/html',
                href: '/v25/nl/#/r3/',
                media: 'screen',
                method: 'get',
                targetPref: '_top',
                title: 'R3 (mobile beta)',
                parameters: [],
                rel: [
                  'http://kvau.lt/_beta',
                  'http://kvau.lt/legacy/mobile/ui',
                ],
              },
              {
                encType: 'application/x-www-form-urlencoded',
                contentType: 'application/json',
                href: '/mobile/members/?command=search&teamFunctionName=Person+TraitR3&teamOperation=ocVIEW',
                media: '',
                method: 'get',
                targetPref: '',
                title: 'Search for team',
                parameters: [],
                rel: ['http://kvau.lt/legacy/api/search+members'],
              },
              {
                encType: 'application/json',
                contentType: 'application/json',
                href: '/api/People/AdvancedSearch',
                media: '',
                method: 'get',
                targetPref: '',
                title: 'Search for team',
                parameters: [
                  {
                    paramName: 'sessionKey',
                    paramType: 'string',
                    value: '',
                  },
                  {
                    paramName: 'functionName',
                    paramType: 'string',
                    value: '',
                  },
                  {
                    paramName: 'operation',
                    paramType: 'string',
                    value: '',
                  },
                  {
                    paramName: 'radius',
                    paramType: 'number',
                    value: '',
                  },
                  {
                    paramName: 'postalCode',
                    paramType: 'string',
                    value: '',
                  },
                  {
                    paramName: 'city',
                    paramType: 'string',
                    value: '',
                  },
                  {
                    paramName: 'stateProvince',
                    paramType: 'string',
                    value: '',
                  },
                  {
                    paramName: 'country',
                    paramType: 'string',
                    value: '',
                  },
                  {
                    paramName: 'longitude',
                    paramType: 'number',
                    value: '',
                  },
                  {
                    paramName: 'latitude',
                    paramType: 'number',
                    value: '',
                  },
                  {
                    paramName: 'badgeIDs',
                    paramType: 'string',
                    value: '',
                  },
                  {
                    paramName: 'teamIDs',
                    paramType: 'string',
                    value: '',
                  },
                  {
                    paramName: 'teamPath',
                    paramType: 'string',
                    value: '',
                  },
                  {
                    paramName: 'direct',
                    paramType: 'boolean',
                    value: '',
                  },
                  {
                    paramName: 'generalName',
                    paramType: 'string',
                    value: '',
                  },
                  {
                    paramName: 'outsideTypes',
                    paramType: 'string',
                    value: '',
                  },
                  {
                    paramName: 'traitIDs',
                    paramType: 'string',
                    value: '',
                  },
                  {
                    paramName: 'activeStatus',
                    paramType: 'string',
                    value: '',
                  },
                ],
                rel: ['http://kvau.lt/api/search+people'],
              },
              {
                encType: 'application/x-www-form-urlencoded',
                contentType: 'text/html',
                href: '/v25/nl/#/r3/',
                media: 'screen',
                method: 'get',
                targetPref: '_top',
                title: 'R3',
                parameters: [],
                rel: ['http://kvau.lt/legacy/v2/ui'],
              },
            ],
            param4Desc: '',
            param3Desc: '',
            param2Desc: '',
            param1Desc: 'itemTraitID',
            iconPathLarge: '',
            longName: '',
          },
          {
            functionID: 162,
            displayName: 'Team Tools',
            functionName: 'TeamTools',
            iconPath: '/v25/images/icons/team-tools-crane.png',
            iconName: 'Crane',
            menuGroup: '/',
            links: [
              {
                encType: 'application/x-www-form-urlencoded',
                contentType: 'text/html',
                href: '/tyto/api/teamTools/connect',
                media: 'screen',
                method: 'get',
                targetPref: '_blank',
                title: 'Team Tools',
                parameters: [],
                rel: ['http://kvau.lt/nl'],
              },
            ],
            param4Desc: '',
            param3Desc: '',
            param2Desc: '',
            param1Desc: '',
            iconPathLarge: '',
            longName: '',
          },
          {
            functionID: 118,
            displayName: 'PPF',
            functionName: 'Page GSPPF',
            iconPath: '/v25/images/icons/ppf_433px.png',
            iconName: 'ocPPF',
            menuGroup: '/',
            links: [
              {
                encType: 'application/x-www-form-urlencoded',
                contentType: 'text/html',
                href: '/v25/nl/#/ppf-goals',
                media: 'screen',
                method: 'get',
                targetPref: '_top',
                title: 'PPF Goals',
                parameters: [],
                rel: [
                  'http://kvau.lt/default',
                  'http://kvau.lt/nl',
                  'http://kvau.lt/nl/iframe?iframeOrigin=https://cherry-ppf.azureedge.net',
                ],
              },
              {
                encType: 'application/x-www-form-urlencoded',
                contentType: 'text/html',
                href: '/v25/nl/#/ppf',
                media: 'screen',
                method: 'get',
                targetPref: '_top',
                title: 'PPF',
                parameters: [],
                rel: ['http://kvau.lt/legacy/v2/ui'],
              },
            ],
            param4Desc: '',
            param3Desc: 'noticeID',
            param2Desc: 'goalID',
            param1Desc: 'planID',
            iconPathLarge: '',
            longName: '',
          },
          {
            functionID: 117,
            displayName: 'VCEP Editor',
            functionName: 'VCEPlan',
            iconPath: '/v2/domains/551/traitIcons/trait268_hah04mos.png',
            iconName: '',
            menuGroup: '/',
            links: [
              {
                encType: 'application/x-www-form-urlencoded',
                contentType: 'text/html',
                href: '/v25/nl/#/vcep',
                media: 'all',
                method: 'get',
                targetPref: '_top',
                title: 'VCEP',
                parameters: [],
                rel: ['http://kvau.lt/legacy/v2/ui'],
              },
              {
                encType: 'application/x-www-form-urlencoded',
                contentType: 'text/html',
                href: '/v25/nl/#/action-plan/vcep-editor',
                media: 'screen',
                method: 'get',
                targetPref: '_top',
                title: 'VCEP Editor',
                parameters: [],
                rel: [
                  'http://kvau.lt/default',
                  'http://kvau.lt/nl',
                  'http://kvau.lt/nl/iframe?iframeOrigin=https://action-plan.azureedge.net/action-plan',
                ],
              },
            ],
            param4Desc: '',
            param3Desc: '',
            param2Desc: '',
            param1Desc: 'devplanID',
            iconPathLarge: '',
            longName: '',
          },
          {
            functionID: 164,
            displayName: 'Platform Review',
            functionName: 'Team Platformreview',
            iconPath: '',
            iconName: '',
            menuGroup: '/',
            links: [
              {
                encType: 'application/x-www-form-urlencoded',
                contentType: 'text/html',
                href: '/v25/nl/#/platform-review/',
                media: 'screen',
                method: 'get',
                targetPref: '_top',
                title: 'Platform Review',
                parameters: [],
                rel: [
                  'http://kvau.lt/default',
                  'http://kvau.lt/nl',
                  'http://kvau.lt/nl/alpha?userID=1791141',
                  'http://kvau.lt/nl/beta?domainID=2803021',
                  'http://kvau.lt/nl/development?roleID=4',
                  'http://kvau.lt/nl/development?roleID=5',
                  'http://kvau.lt/nl/development?userID=1184892',
                  'http://kvau.lt/nl/development?userID=1791141',
                  'http://kvau.lt/nl/iframe?iframeOrigin=https://platform-review.azureedge.net/platform-review',
                  'http://kvau.lt/nl/legacy?roleID=156',
                ],
              },
              {
                encType: 'application/x-www-form-urlencoded',
                contentType: 'application/json',
                href: '/tyto/api/cvPlatformreview/tasks',
                media: 'screen',
                method: 'GET',
                targetPref: '',
                title: 'Platform review project data',
                parameters: [],
                rel: ['http://kvau.lt/api/cvPlatformreview/tasks'],
              },
            ],
            param4Desc: '',
            param3Desc: 'taskID',
            param2Desc: 'teamID',
            param1Desc: 'rootTaskID',
            iconPathLarge: '',
            longName: '',
          },
          {
            functionID: 54,
            displayName: 'Home',
            functionName: 'Page Home',
            iconPath: '/v25/images/icons/domain_128px.png',
            iconName: '',
            menuGroup: '/',
            links: [
              {
                encType: 'application/x-www-form-urlencoded',
                contentType: 'text/html',
                href: '/v25/nl/#/landing',
                media: 'screen',
                method: 'get',
                targetPref: '_top',
                title: 'Landing Page',
                parameters: [],
                rel: [
                  'http://kvau.lt/nl',
                  'http://kvau.lt/nl/default?domainID=2823418',
                  'http://kvau.lt/nl/iframe?iframeOrigin=https://tryyb-homepage.azureedge.net/home',
                ],
              },
              {
                encType: 'application/x-www-form-urlencoded',
                contentType: 'text/html',
                href: '/v25/top.asp',
                media: 'screen',
                method: 'get',
                targetPref: '_top',
                title: 'Top',
                parameters: [],
                rel: ['http://kvau.lt/legacy/v2/ui'],
              },
              {
                encType: 'application/x-www-form-urlencoded',
                contentType: 'text/html',
                href: '/v25/nl/#/start',
                media: 'screen',
                method: 'get',
                targetPref: '_top',
                title: 'Home',
                parameters: [],
                rel: [
                  'http://kvau.lt/default',
                  'http://kvau.lt/legacy/v2/ui',
                  'http://kvau.lt/nl',
                ],
              },
            ],
            param4Desc: '',
            param3Desc: '',
            param2Desc: '',
            param1Desc: '',
            iconPathLarge: '',
            longName: '',
          },
          {
            functionID: 37,
            displayName: 'Inbox',
            functionName: 'Notices Person',
            iconPath: '/v25/images/icons/inbox_128px.png',
            iconName: 'inbox',
            menuGroup: '/',
            links: [
              {
                encType: 'application/x-www-form-urlencoded',
                contentType: 'application/json',
                href: '/api/inbox',
                media: '',
                method: 'get',
                targetPref: '',
                title: 'Inbox',
                parameters: [
                  {
                    paramName: 'sessionKey',
                    paramType: 'string',
                    value: '',
                  },
                ],
                rel: ['http://kvau.lt/api/inbox'],
              },
              {
                encType: 'application/x-www-form-urlencoded',
                contentType: 'text/html',
                href: '/v25/nl/#/conversations',
                media: 'screen',
                method: 'get',
                targetPref: '_top',
                title: 'Inbox',
                parameters: [
                  {
                    paramName: 'nID',
                    paramType: 'int',
                    value: '',
                  },
                ],
                rel: [
                  'http://kvau.lt/default',
                  'http://kvau.lt/nl',
                  'http://kvau.lt/nl/iframe?iframeOrigin=https://conversations.azureedge.net/inbox',
                ],
              },
              {
                encType: 'application/x-www-form-urlencoded',
                contentType: 'application/json',
                href: '/mobile/inbox/?command=getUserInbox',
                media: '',
                method: 'get',
                targetPref: '',
                title: 'Inbox',
                parameters: [
                  {
                    paramName: 'sessionKey',
                    paramType: 'string',
                    value: '',
                  },
                  {
                    paramName: 'oldestDate',
                    paramType: 'date',
                    value: '',
                  },
                  {
                    paramName: 'top',
                    paramType: 'int',
                    value: '',
                  },
                ],
                rel: ['http://kvau.lt/legacy/api/getuserinbox'],
              },
              {
                encType: 'application/x-www-form-urlencoded',
                contentType: 'text/html',
                href: '/v25/nl/#/inbox',
                media: 'screen',
                method: 'get',
                targetPref: '_top',
                title: 'Inbox Legacy',
                parameters: [],
                rel: [
                  'http://kvau.lt/legacy/v2/ui',
                  'http://kvau.lt/nl/legacy?domainID=551',
                ],
              },
            ],
            param4Desc: '',
            param3Desc: '',
            param2Desc: '',
            param1Desc: 'noticeID',
            iconPathLarge: '',
            keyPhrases: [
              'individual message',
              'Inbox',
              'Email',
              'Peer to peer message',
            ],
            description: 'Send a message to an individual',
            longName: 'Inbox',
          },
          {
            functionID: 50,
            displayName: 'News',
            functionName: 'Page News',
            iconPath: '/v25/images/icons/news_128px.png',
            iconName: '',
            menuGroup: '/',
            links: [
              {
                encType: 'application/x-www-form-urlencoded',
                contentType: 'text/html',
                href: '/v25/nl/#/news/',
                media: 'screen',
                method: 'get',
                targetPref: '_top',
                title: 'News',
                parameters: [],
                rel: ['http://kvau.lt/legacy/mobile/ui'],
              },
              {
                encType: 'application/x-www-form-urlencoded',
                contentType: 'text/html',
                href: '/v25/nl/#/news/',
                media: 'screen',
                method: 'get',
                targetPref: '_top',
                title: 'News',
                parameters: [],
                rel: ['http://kvau.lt/default', 'http://kvau.lt/legacy/v2/ui'],
              },
            ],
            param4Desc: '',
            param3Desc: 'noticeCommentID',
            param2Desc: 'noticeID',
            param1Desc: 'newsID',
            iconPathLarge: '',
            longName: '',
          },
          {
            functionID: 156,
            displayName: 'Playbook',
            functionName: 'Catalog Playbook',
            iconPath: '/v25/images/icons/ocCatalog_128px.png',
            iconName: 'ocCatalog',
            menuGroup: '/',
            links: [
              {
                encType: 'application/x-www-form-urlencoded',
                contentType: 'text/html',
                href: '/v25/nl/#/playbook',
                media: '',
                method: 'get',
                targetPref: '_top',
                title: 'Playbook Catalog',
                parameters: [],
                rel: ['http://kvau.lt/default', 'http://kvau.lt/nl'],
              },
              {
                encType: 'application/x-www-form-urlencoded',
                contentType: 'application/json',
                href: '/api/CatalogPlaybook',
                media: '',
                method: 'get',
                targetPref: '',
                title: 'Playbook Catalog Api',
                parameters: [],
                rel: ['http://kvau.lt/api/CatalogPlaybook'],
              },
            ],
            param4Desc: '',
            param3Desc: 'parentCatalogID',
            param2Desc: 'memberID',
            param1Desc: 'catalogID',
            iconPathLarge: '',
            longName: '',
          },
          {
            functionID: 48,
            displayName: 'Library',
            functionName: 'Page Library',
            iconPath: '/v25/images/icons/ocLibrary_128px.png',
            iconName: '',
            menuGroup: '/',
            links: [
              {
                encType: 'application/x-www-form-urlencoded',
                contentType: 'text/html',
                href: '/v25/mobile/library/',
                media: 'screen',
                method: 'get',
                targetPref: '_top',
                title: 'Library',
                parameters: [
                  {
                    paramName: 'sessionKey',
                    paramType: 'string',
                    value: '',
                  },
                ],
                rel: ['http://kvau.lt/legacy/mobile/ui'],
              },
              {
                encType: 'application/x-www-form-urlencoded',
                contentType: 'text/html',
                href: '/v25/nl/#/library',
                media: 'screen',
                method: 'get',
                targetPref: '_top',
                title: 'Library',
                parameters: [],
                rel: ['http://kvau.lt/default', 'http://kvau.lt/legacy/v2/ui'],
              },
            ],
            param4Desc: '',
            param3Desc: '',
            param2Desc: 'categoryID',
            param1Desc: 'memberID',
            iconPathLarge: '',
            longName: '',
          },
          {
            functionID: 99,
            displayName: 'Calendar',
            functionName: 'Page Events',
            iconPath: '/v25/images/icons/elementType/ocEVENT/ocEvent_128px.png',
            iconName: '',
            menuGroup: '/',
            links: [
              {
                encType: 'application/x-www-form-urlencoded',
                contentType: 'text/html',
                href: '/v25/nl/#/calendar/',
                media: 'screen',
                method: 'get',
                targetPref: '_top',
                title: 'Calendar',
                parameters: [],
                rel: [
                  'http://kvau.lt/default',
                  'http://kvau.lt/legacy/v2/ui',
                  'http://kvau.lt/nl',
                ],
              },
              {
                encType: 'application/x-www-form-urlencoded',
                contentType: 'text/html',
                href: '/v25/nl/#/calendar/list/',
                media: 'screen',
                method: 'get',
                targetPref: '_top',
                title: 'Calendar',
                parameters: [
                  {
                    paramName: 'sessionKey',
                    paramType: 'string',
                    value: '',
                  },
                  {
                    paramName: 'eventID',
                    paramType: 'int',
                    value: '',
                  },
                  {
                    paramName: 'springboard',
                    paramType: 'string',
                    value: '',
                  },
                ],
                rel: ['http://kvau.lt/legacy/mobile/ui'],
              },
              {
                encType: 'application/x-www-form-urlencoded',
                contentType: 'text/html',
                href: '/v25/nl/#/cal',
                media: 'screen',
                method: 'get',
                targetPref: '_top',
                title: 'Calendar V2',
                parameters: [],
                rel: [
                  'http://kvau.lt/nl/beta?domainID=551',
                  'http://kvau.lt/nl/iframe?iframeOrigin=https://calendar.azureedge.net/calendar',
                ],
              },
              {
                encType: 'application/x-www-form-urlencoded',
                contentType: 'text/html',
                href: '/v25/nl/#/cal-next',
                media: 'screen',
                method: 'get',
                targetPref: '_top',
                title: 'Calendar V2 Dev',
                parameters: [],
                rel: ['http://kvau.lt/nl/development?roleID=1'],
              },
            ],
            param4Desc: '',
            param3Desc: '',
            param2Desc: '',
            param1Desc: 'eventID',
            iconPathLarge: '',
            longName: '',
          },
          {
            functionID: 49,
            displayName: 'Team',
            functionName: 'Page Team',
            iconPath: '/v25/images/icons/team_128px.png',
            iconName: '',
            menuGroup: '/',
            links: [
              {
                encType: 'application/x-www-form-urlencoded',
                contentType: 'text/html',
                href: '/v25/nl/#/teams',
                media: 'screen',
                method: 'get',
                targetPref: '_top',
                title: 'Teams',
                parameters: [],
                rel: ['http://kvau.lt/legacy/v2/ui', 'http://kvau.lt/nl'],
              },
              {
                encType: 'application/x-www-form-urlencoded',
                contentType: 'text/html',
                href: '/v25/nl/#/teams',
                media: 'screen',
                method: 'get',
                targetPref: '_top',
                title: 'Teams',
                parameters: [
                  {
                    paramName: 'sessionKey',
                    paramType: 'string',
                    value: '',
                  },
                  {
                    paramName: 'ShowAllTeams',
                    paramType: 'bool',
                    value: '',
                  },
                ],
                rel: ['http://kvau.lt/legacy/mobile/ui'],
              },
            ],
            param4Desc: '',
            param3Desc: '',
            param2Desc: 'noticeID',
            param1Desc: 'teamID',
            iconPathLarge: '',
            longName: '',
          },
          {
            functionID: 67,
            displayName: 'Training',
            functionName: 'Page Training',
            iconPath: '/v25/images/icons/course_150px.png',
            iconName: 'ocBLOCK',
            menuGroup: '/',
            links: [
              {
                encType: 'application/x-www-form-urlencoded',
                contentType: 'text/html',
                href: '/v25/mobile/training/',
                media: 'screen',
                method: 'get',
                targetPref: '_top',
                title: 'Mobile Training',
                parameters: [
                  {
                    paramName: 'sessionKey',
                    paramType: 'string',
                    value: '',
                  },
                ],
                rel: [],
              },
              {
                encType: 'application/x-www-form-urlencoded',
                contentType: 'text/html',
                href: '/v25/nl/#/mastery-next',
                media: 'screen',
                method: 'get',
                targetPref: '_top',
                title: 'Mastery Dev',
                parameters: [],
                rel: [
                  'http://kvau.lt/nl',
                  'http://kvau.lt/nl/development?roleID=1',
                  'http://kvau.lt/nl/iframe?iframeOrigin=https://mastery-development.azureedge.net',
                ],
              },
              {
                encType: 'application/x-www-form-urlencoded',
                contentType: 'text/html',
                href: '/v25/nl/#/mastery',
                media: 'screen',
                method: 'get',
                targetPref: '_top',
                title: 'Mastery',
                parameters: [],
                rel: [
                  'http://kvau.lt/default',
                  'http://kvau.lt/mobileapp/native',
                  'http://kvau.lt/nl',
                  'http://kvau.lt/nl/iframe?iframeOrigin=https://mastery-cherry-iis.mocaworks.com',
                ],
              },
              {
                encType: 'application/x-www-form-urlencoded',
                contentType: 'text/html',
                href: '/v25/nl/#/mastery',
                media: 'screen',
                method: 'get',
                targetPref: '_blank',
                title: 'Mastery Mobile',
                parameters: [],
                rel: [
                  'http://kvau.lt/nl/iframe?iframeOrigin=https://mastery-cherry-iis.mocaworks.com',
                ],
              },
            ],
            param4Desc: 'enrollmentID',
            param3Desc: 'devPlanID',
            param2Desc: 'blockID',
            param1Desc: 'taskID',
            iconPathLarge: '',
            longName: '',
          },
          {
            functionID: 121,
            displayName: 'Training Dashboard',
            functionName: 'Page Manage TrainingDashboard',
            iconPath: '/v25/images/icons/training_dash_64px.png',
            iconName: 'Training Dashboa',
            menuGroup: '/',
            links: [
              {
                encType: 'application/x-www-form-urlencoded',
                contentType: 'text/html',
                href: '/v25/nl/#/analytics-dashboard',
                media: 'screen',
                method: 'get',
                targetPref: '_top',
                title: 'Analytics Dashboard',
                parameters: [],
                rel: [
                  'http://kvau.lt/nl',
                  'http://kvau.lt/nl/beta?domainID=1825957',
                  'http://kvau.lt/nl/beta?domainID=551',
                  'http://kvau.lt/nl/iframe?iframeOrigin=https://analytics-dashboard.azureedge.net/analytics-dashboard',
                ],
              },
              {
                encType: 'application/x-www-form-urlencoded',
                contentType: 'text/html',
                href: '/v25/nl/#/training/dashboard',
                media: '',
                method: 'get',
                targetPref: '_top',
                title: 'Training Dashboard',
                parameters: [],
                rel: ['http://kvau.lt/default'],
              },
            ],
            param4Desc: '',
            param3Desc: '',
            param2Desc: '',
            param1Desc: '',
            iconPathLarge: '',
            longName: '',
          },
          {
            functionID: 73,
            displayName: "To Do's",
            functionName: 'Page ToDo',
            iconPath: '/v25/images/icons/ocTask_64px.png',
            iconName: '',
            menuGroup: '/',
            links: [
              {
                encType: 'application/x-www-form-urlencoded',
                contentType: 'text/html',
                href: '/v25/nl/#/mytodos',
                media: 'screen',
                method: 'get',
                targetPref: '_top',
                title: 'Todos',
                parameters: [],
                rel: [
                  'http://kvau.lt/default',
                  'http://kvau.lt/legacy/mobile/ui',
                  'http://kvau.lt/legacy/v2/ui',
                  'http://kvau.lt/nl',
                ],
              },
            ],
            param4Desc: '',
            param3Desc: '',
            param2Desc: 'noticeID',
            param1Desc: 'taskID',
            iconPathLarge: '',
            longName: '',
          },
          {
            functionID: 60,
            displayName: 'Additional Features',
            functionName: 'Page Portal',
            iconPath: '/v25/images/icons/gear_16px.png',
            iconName: '',
            menuGroup: '/',
            links: [
              {
                encType: 'application/x-www-form-urlencoded',
                contentType: 'text/html',
                href: '',
                media: 'screen',
                method: 'get',
                targetPref: '_top',
                title: 'Portal',
                parameters: [],
                rel: ['http://kvau.lt/legacy/v2/ui'],
              },
            ],
            subMenu: [
              {
                functionID: 60,
                displayName: '10x360 Videos Test',
                functionName: 'traitID=789',
                iconPath: '',
                iconName: '',
                menuGroup: '/Additional Features/',
                links: [
                  {
                    encType: 'application/x-www-form-urlencoded',
                    contentType: 'text/html',
                    href: '/v25/__red.asp?itemTraitID=31507',
                    media: 'all',
                    method: 'get',
                    targetPref: 'iframe',
                    title: '10x360 Videos Test',
                    parameters: [],
                    rel: ['http://kvau.lt/clientportal'],
                  },
                  {
                    encType: 'application/x-www-form-urlencoded',
                    contentType: 'text/html',
                    href: 'https://cherry.mocaworks.com/tyto/api/CustomTab/redirect?legacyServer=&itemTraitID=31507&sessionKey=YV96HCF9R4KXKNVMRQMFMBWD0ZH2JLWFPHLKZ3452PT1Z04YLMTPJNXT67B4BV9F',
                    media: 'all',
                    method: 'get',
                    targetPref: 'iframe',
                    title: '10x360 Videos Test',
                    parameters: [],
                    rel: ['http://kvau.lt/clientportal/mobile'],
                  },
                ],
                param4Desc: '',
                param3Desc: '',
                param2Desc: '',
                param1Desc: '',
                iconPathLarge: '',
                longName: '',
              },
              {
                functionID: 60,
                displayName: 'APIs',
                functionName: 'traitID=227',
                iconPath: '/v2/domains/551/traitIcons/trait227_devidy5j.png',
                iconName: '',
                menuGroup: '/Additional Features/',
                links: [
                  {
                    encType: 'application/x-www-form-urlencoded',
                    contentType: 'text/html',
                    href: '/v25/nl/#/api',
                    media: 'all',
                    method: 'get',
                    targetPref: '_blank',
                    title: 'APIs',
                    parameters: [],
                    rel: ['http://kvau.lt/clientportal'],
                  },
                  {
                    encType: 'application/x-www-form-urlencoded',
                    contentType: 'text/html',
                    href: '/v25/nl/#/api',
                    media: 'all',
                    method: 'get',
                    targetPref: '_blank',
                    title: 'APIs',
                    parameters: [],
                    rel: ['http://kvau.lt/clientportal'],
                  },
                  {
                    encType: 'application/x-www-form-urlencoded',
                    contentType: 'text/html',
                    href: '/v25/nl/#/api',
                    media: 'all',
                    method: 'get',
                    targetPref: '_blank',
                    title: 'APIs',
                    parameters: [],
                    rel: ['http://kvau.lt/clientportal/mobile'],
                  },
                  {
                    encType: 'application/x-www-form-urlencoded',
                    contentType: 'text/html',
                    href: '/v25/nl/#/api',
                    media: 'all',
                    method: 'get',
                    targetPref: '_blank',
                    title: 'APIs',
                    parameters: [],
                    rel: ['http://kvau.lt/clientportal/mobile'],
                  },
                ],
                param4Desc: '',
                param3Desc: '',
                param2Desc: '',
                param1Desc: '',
                iconPathLarge:
                  '/v2/domains/551/traitIcons/traitLrg227_1os1vbym.png',
                description: 'Tyto Api Explorer',
                longName: '',
              },
              {
                functionID: 60,
                displayName: 'Change Log (NL)',
                functionName: 'traitID=115',
                iconPath: '/v2/domains/551/traitIcons/trait115_3jorhvxz.png',
                iconName: '',
                menuGroup: '/Additional Features/',
                links: [
                  {
                    encType: 'application/x-www-form-urlencoded',
                    contentType: 'text/html',
                    href: '/v25/nl/#/changelog',
                    media: 'all',
                    method: 'get',
                    targetPref: '_self',
                    title: 'Change Log (NL)',
                    parameters: [],
                    rel: ['http://kvau.lt/clientportal'],
                  },
                  {
                    encType: 'application/x-www-form-urlencoded',
                    contentType: 'text/html',
                    href: '/v25/nl/#/changelog',
                    media: 'all',
                    method: 'get',
                    targetPref: '_self',
                    title: 'Change Log (NL)',
                    parameters: [],
                    rel: ['http://kvau.lt/clientportal/mobile'],
                  },
                ],
                param4Desc: '',
                param3Desc: '',
                param2Desc: '',
                param1Desc: '',
                iconPathLarge: '',
                longName: '',
              },
              {
                functionID: 60,
                displayName: 'Cherry Dashboard',
                functionName: 'traitID=827',
                iconPath: '',
                iconName: '',
                menuGroup: '/Additional Features/',
                links: [
                  {
                    encType: 'application/x-www-form-urlencoded',
                    contentType: 'text/html',
                    href: 'https://portal.azure.com/#@cardoneventures.onmicrosoft.com/dashboard/arm/subscriptions/ad9677be-7ad7-4000-b809-9490bb834ab2/resourcegroups/dashboards/providers/microsoft.portal/dashboards/0ac0881f-c79e-4110-97bd-97bf3f96915b',
                    media: 'all',
                    method: 'get',
                    targetPref: '_blank',
                    title: 'Cherry Dashboard',
                    parameters: [],
                    rel: ['http://kvau.lt/clientportal'],
                  },
                  {
                    encType: 'application/x-www-form-urlencoded',
                    contentType: 'text/html',
                    href: 'https://portal.azure.com/#@cardoneventures.onmicrosoft.com/dashboard/arm/subscriptions/ad9677be-7ad7-4000-b809-9490bb834ab2/resourcegroups/dashboards/providers/microsoft.portal/dashboards/0ac0881f-c79e-4110-97bd-97bf3f96915b',
                    media: 'all',
                    method: 'get',
                    targetPref: '_blank',
                    title: 'Cherry Dashboard',
                    parameters: [],
                    rel: ['http://kvau.lt/clientportal/mobile'],
                  },
                ],
                param4Desc: '',
                param3Desc: '',
                param2Desc: '',
                param1Desc: '',
                iconPathLarge:
                  '/v2/domains/551/traitIcons/traitLrg827_0k1cstd0.png',
                description:
                  'Performance Dashboard for Cherry Instance CardoneVentures',
                longName: '',
              },
              {
                functionID: 60,
                displayName: 'Command Channel Admin',
                functionName: 'traitID=581',
                iconPath: '/v2/domains/551/traitIcons/trait581_vye424fz.png',
                iconName: '',
                menuGroup: '/Additional Features/',
                links: [
                  {
                    encType: 'application/x-www-form-urlencoded',
                    contentType: 'text/html',
                    href: '/v25/nl/#/commandchanneladmin',
                    media: 'all',
                    method: 'get',
                    targetPref: '_self',
                    title: 'Command Channel Admin',
                    parameters: [],
                    rel: ['http://kvau.lt/clientportal'],
                  },
                  {
                    encType: 'application/x-www-form-urlencoded',
                    contentType: 'text/html',
                    href: '/v25/nl/#/commandchanneladmin',
                    media: 'all',
                    method: 'get',
                    targetPref: '_self',
                    title: 'Command Channel Admin',
                    parameters: [],
                    rel: ['http://kvau.lt/clientportal/mobile'],
                  },
                ],
                param4Desc: '',
                param3Desc: '',
                param2Desc: '',
                param1Desc: '',
                iconPathLarge:
                  '/v2/domains/551/traitIcons/traitLrg581_4k3s3y4k.png',
                longName: '',
              },
              {
                functionID: 60,
                displayName: 'Documents',
                functionName: 'traitID=146',
                iconPath: '/v2/domains/551/traitIcons/trait146_zshiknb0.png',
                iconName: '',
                menuGroup: '/Additional Features/',
                links: [
                  {
                    encType: 'application/x-www-form-urlencoded',
                    contentType: 'text/html',
                    href: '/v25/nl/#/documents',
                    media: 'all',
                    method: 'get',
                    targetPref: '_self',
                    title: 'Documents',
                    parameters: [],
                    rel: ['http://kvau.lt/clientportal'],
                  },
                  {
                    encType: 'application/x-www-form-urlencoded',
                    contentType: 'text/html',
                    href: '/v25/nl/#/documents',
                    media: 'all',
                    method: 'get',
                    targetPref: '_self',
                    title: 'Documents',
                    parameters: [],
                    rel: ['http://kvau.lt/clientportal/mobile'],
                  },
                ],
                param4Desc: '',
                param3Desc: '',
                param2Desc: '',
                param1Desc: '',
                iconPathLarge: '',
                longName: '',
              },
              {
                functionID: 60,
                displayName: 'Hydra Portainer',
                functionName: 'traitID=971',
                iconPath: '/v2/domains/551/traitIcons/trait971_3ju1cm2q.png',
                iconName: '',
                menuGroup: '/Additional Features/',
                links: [
                  {
                    encType: 'application/x-www-form-urlencoded',
                    contentType: 'text/html',
                    href: 'http://100.83.80.6:9000/',
                    media: 'all',
                    method: 'get',
                    targetPref: '_blank',
                    title: 'Hydra Portainer',
                    parameters: [],
                    rel: ['http://kvau.lt/clientportal'],
                  },
                  {
                    encType: 'application/x-www-form-urlencoded',
                    contentType: 'text/html',
                    href: 'http://100.83.80.6:9000/',
                    media: 'all',
                    method: 'get',
                    targetPref: '_blank',
                    title: 'Hydra Portainer',
                    parameters: [],
                    rel: ['http://kvau.lt/clientportal/mobile'],
                  },
                ],
                param4Desc: '',
                param3Desc: '',
                param2Desc: '',
                param1Desc: '',
                iconPathLarge:
                  '/v2/domains/551/traitIcons/traitLrg971_vy3kbj52.png',
                description: 'Portainer running on and for Hydra',
                longName: '',
              },
              {
                functionID: 60,
                displayName: 'Iframe Test',
                functionName: 'traitID=813',
                iconPath: '/v2/domains/551/traitIcons/trait813_mu2nryh0.png',
                iconName: '',
                menuGroup: '/Additional Features/',
                links: [
                  {
                    encType: 'application/x-www-form-urlencoded',
                    contentType: 'text/html',
                    href: '/v25/__red.asp?itemTraitID=30737',
                    media: 'all',
                    method: 'get',
                    targetPref: 'iframe',
                    title: 'Iframe Test',
                    parameters: [],
                    rel: ['http://kvau.lt/clientportal'],
                  },
                  {
                    encType: 'application/x-www-form-urlencoded',
                    contentType: 'text/html',
                    href: 'https://cherry.mocaworks.com/tyto/api/CustomTab/redirect?legacyServer=&itemTraitID=30737&sessionKey=YV96HCF9R4KXKNVMRQMFMBWD0ZH2JLWFPHLKZ3452PT1Z04YLMTPJNXT67B4BV9F',
                    media: 'all',
                    method: 'get',
                    targetPref: 'iframe',
                    title: 'Iframe Test',
                    parameters: [],
                    rel: ['http://kvau.lt/clientportal/mobile'],
                  },
                ],
                param4Desc: '',
                param3Desc: '',
                param2Desc: '',
                param1Desc: '',
                iconPathLarge:
                  '/v2/domains/551/traitIcons/traitLrg813_ufbc14q5.png',
                description: 'Testing iframe tab',
                longName: '',
              },
              {
                functionID: 60,
                displayName: 'Legacy Course Editor',
                functionName: 'traitID=943',
                iconPath: '',
                iconName: '',
                menuGroup: '/Additional Features/',
                links: [
                  {
                    encType: 'application/x-www-form-urlencoded',
                    contentType: 'text/html',
                    href: '/v25/course_e/courseBuilder.asp',
                    media: 'all',
                    method: 'get',
                    targetPref: '_self',
                    title: 'Legacy Course Editor',
                    parameters: [],
                    rel: ['http://kvau.lt/clientportal'],
                  },
                  {
                    encType: 'application/x-www-form-urlencoded',
                    contentType: 'text/html',
                    href: '/v25/course_e/courseBuilder.asp',
                    media: 'all',
                    method: 'get',
                    targetPref: '_self',
                    title: 'Legacy Course Editor',
                    parameters: [],
                    rel: ['http://kvau.lt/clientportal/mobile'],
                  },
                ],
                param4Desc: '',
                param3Desc: '',
                param2Desc: '',
                param1Desc: '',
                iconPathLarge: '',
                keyPhrases: ['Course Editor', 'Legacy'],
                longName: '',
              },
              {
                functionID: 60,
                displayName: 'Leia',
                functionName: 'traitID=625',
                iconPath: '',
                iconName: '',
                menuGroup: '/Additional Features/',
                links: [
                  {
                    encType: 'application/x-www-form-urlencoded',
                    contentType: 'text/html',
                    href: 'http://leia/tyto/api/configuration/server',
                    media: 'all',
                    method: 'get',
                    targetPref: 'iframe',
                    title: 'Leia',
                    parameters: [],
                    rel: ['http://kvau.lt/clientportal'],
                  },
                  {
                    encType: 'application/x-www-form-urlencoded',
                    contentType: 'text/html',
                    href: 'http://leia/tyto/api/configuration/server',
                    media: 'all',
                    method: 'get',
                    targetPref: 'iframe',
                    title: 'Leia',
                    parameters: [],
                    rel: ['http://kvau.lt/clientportal/mobile'],
                  },
                ],
                param4Desc: '',
                param3Desc: '',
                param2Desc: '',
                param1Desc: '',
                iconPathLarge: '',
                longName: '',
              },
              {
                functionID: 60,
                displayName: 'Loggly',
                functionName: 'traitID=422',
                iconPath: '/v2/domains/551/traitIcons/trait422_yqvg3ewa.png',
                iconName: '',
                menuGroup: '/Additional Features/',
                links: [
                  {
                    encType: 'application/x-www-form-urlencoded',
                    contentType: 'text/html',
                    href: 'https://knowledgevault.loggly.com/',
                    media: 'all',
                    method: 'get',
                    targetPref: '_blank',
                    title: 'Loggly',
                    parameters: [],
                    rel: ['http://kvau.lt/clientportal'],
                  },
                  {
                    encType: 'application/x-www-form-urlencoded',
                    contentType: 'text/html',
                    href: 'https://knowledgevault.loggly.com/',
                    media: 'all',
                    method: 'get',
                    targetPref: '_blank',
                    title: 'Loggly',
                    parameters: [],
                    rel: ['http://kvau.lt/clientportal/mobile'],
                  },
                ],
                param4Desc: '',
                param3Desc: '',
                param2Desc: '',
                param1Desc: '',
                iconPathLarge: '',
                longName: '',
              },
              {
                functionID: 60,
                displayName: 'Mastery',
                functionName: 'traitID=744',
                iconPath: '/v2/domains/551/traitIcons/trait744_art5l3be.png',
                iconName: '',
                menuGroup: '/Additional Features/',
                links: [
                  {
                    encType: 'application/x-www-form-urlencoded',
                    contentType: 'text/html',
                    href: '/v25/__red.asp?itemTraitID=30182',
                    media: 'all',
                    method: 'get',
                    targetPref: '_blank',
                    title: 'Mastery',
                    parameters: [],
                    rel: ['http://kvau.lt/clientportal'],
                  },
                  {
                    encType: 'application/x-www-form-urlencoded',
                    contentType: 'text/html',
                    href: 'https://cherry.mocaworks.com/tyto/api/CustomTab/redirect?legacyServer=&itemTraitID=30182&sessionKey=YV96HCF9R4KXKNVMRQMFMBWD0ZH2JLWFPHLKZ3452PT1Z04YLMTPJNXT67B4BV9F',
                    media: 'all',
                    method: 'get',
                    targetPref: '_blank',
                    title: 'Mastery',
                    parameters: [],
                    rel: ['http://kvau.lt/clientportal/mobile'],
                  },
                ],
                param4Desc: '',
                param3Desc: '',
                param2Desc: '',
                param1Desc: '',
                iconPathLarge:
                  '/v2/domains/551/traitIcons/traitLrg744_1syoo0dc.png',
                keyPhrases: ['Mastery'],
                description:
                  'Launches Mastery Beta site in new tab, logging user in with new session',
                longName: '',
              },
              {
                functionID: 60,
                displayName: 'Menu Links Form',
                functionName: 'traitID=949',
                iconPath: '',
                iconName: '',
                menuGroup: '/Additional Features/',
                links: [
                  {
                    encType: 'application/x-www-form-urlencoded',
                    contentType: 'text/html',
                    href: '/oc/functions.html',
                    media: 'all',
                    method: 'get',
                    targetPref: '_blank',
                    title: 'Menu Links Form',
                    parameters: [],
                    rel: ['http://kvau.lt/clientportal'],
                  },
                  {
                    encType: 'application/x-www-form-urlencoded',
                    contentType: 'text/html',
                    href: '/oc/functions.html',
                    media: 'all',
                    method: 'get',
                    targetPref: '_blank',
                    title: 'Menu Links Form',
                    parameters: [],
                    rel: ['http://kvau.lt/clientportal/mobile'],
                  },
                ],
                param4Desc: '',
                param3Desc: '',
                param2Desc: '',
                param1Desc: '',
                iconPathLarge: '',
                description: 'Form for Adding/Removing Links to a Menu Item',
                longName: '',
              },
              {
                functionID: 60,
                displayName: 'Mocaworks N8N Instance',
                functionName: 'traitID=968',
                iconPath: '/v2/domains/551/traitIcons/trait968_js11h1r0.png',
                iconName: '',
                menuGroup: '/Additional Features/',
                links: [
                  {
                    encType: 'application/x-www-form-urlencoded',
                    contentType: 'text/html',
                    href: 'https://workflows.mocaworks.com/',
                    media: 'all',
                    method: 'get',
                    targetPref: '_blank',
                    title: 'Mocaworks N8N Instance',
                    parameters: [],
                    rel: ['http://kvau.lt/clientportal'],
                  },
                  {
                    encType: 'application/x-www-form-urlencoded',
                    contentType: 'text/html',
                    href: 'https://workflows.mocaworks.com/',
                    media: 'all',
                    method: 'get',
                    targetPref: '_blank',
                    title: 'Mocaworks N8N Instance',
                    parameters: [],
                    rel: ['http://kvau.lt/clientportal/mobile'],
                  },
                ],
                param4Desc: '',
                param3Desc: '',
                param2Desc: '',
                param1Desc: '',
                iconPathLarge:
                  '/v2/domains/551/traitIcons/traitLrg968_iigome41.png',
                description: 'Self-host N8N Instance running on Hydra! ⛓️',
                longName: '',
              },
              {
                functionID: 60,
                displayName: 'My Training',
                functionName: 'traitID=582',
                iconPath: '',
                iconName: '',
                menuGroup: '/Additional Features/',
                links: [
                  {
                    encType: 'application/x-www-form-urlencoded',
                    contentType: 'text/html',
                    href: '/v25/nl/#/mytraining',
                    media: 'all',
                    method: 'get',
                    targetPref: '_self',
                    title: 'My Training',
                    parameters: [],
                    rel: ['http://kvau.lt/clientportal'],
                  },
                  {
                    encType: 'application/x-www-form-urlencoded',
                    contentType: 'text/html',
                    href: '/v25/nl/#/mytraining',
                    media: 'all',
                    method: 'get',
                    targetPref: '_self',
                    title: 'My Training',
                    parameters: [],
                    rel: ['http://kvau.lt/clientportal/mobile'],
                  },
                ],
                param4Desc: '',
                param3Desc: '',
                param2Desc: '',
                param1Desc: '',
                iconPathLarge: '',
                longName: '',
              },
              {
                functionID: 60,
                displayName: 'Native Link',
                functionName: 'traitID=648',
                iconPath: '',
                iconName: '',
                menuGroup: '/Additional Features/',
                links: [
                  {
                    encType: 'application/x-www-form-urlencoded',
                    contentType: 'text/html',
                    href: 'kvault://inbox',
                    media: 'all',
                    method: 'get',
                    targetPref: '_self',
                    title: 'Native Link',
                    parameters: [],
                    rel: ['http://kvau.lt/clientportal'],
                  },
                  {
                    encType: 'application/x-www-form-urlencoded',
                    contentType: 'text/html',
                    href: 'kvault://inbox',
                    media: 'all',
                    method: 'get',
                    targetPref: '_self',
                    title: 'Native Link',
                    parameters: [],
                    rel: ['http://kvau.lt/clientportal/mobile'],
                  },
                ],
                param4Desc: '',
                param3Desc: '',
                param2Desc: '',
                param1Desc: '',
                iconPathLarge: '',
                description: 'native link',
                longName: '',
              },
              {
                functionID: 60,
                displayName: 'ODI',
                functionName: 'traitID=583',
                iconPath: '',
                iconName: '',
                menuGroup: '/Additional Features/',
                links: [
                  {
                    encType: 'application/x-www-form-urlencoded',
                    contentType: 'text/html',
                    href: '/v25/__red.asp?itemTraitID=22818',
                    media: 'all',
                    method: 'get',
                    targetPref: 'iframe::hidemenu',
                    title: 'ODI',
                    parameters: [],
                    rel: ['http://kvau.lt/clientportal'],
                  },
                  {
                    encType: 'application/x-www-form-urlencoded',
                    contentType: 'text/html',
                    href: 'https://cherry.mocaworks.com/tyto/api/CustomTab/redirect?legacyServer=&itemTraitID=22818&sessionKey=YV96HCF9R4KXKNVMRQMFMBWD0ZH2JLWFPHLKZ3452PT1Z04YLMTPJNXT67B4BV9F',
                    media: 'all',
                    method: 'get',
                    targetPref: 'iframe::hidemenu',
                    title: 'ODI',
                    parameters: [],
                    rel: ['http://kvau.lt/clientportal/mobile'],
                  },
                ],
                param4Desc: '',
                param3Desc: '',
                param2Desc: '',
                param1Desc: '',
                iconPathLarge: '',
                description:
                  'Link for Aafco Online Database of Ingredients (ODI)',
                longName: '',
              },
              {
                functionID: 60,
                displayName: 'PPF (Beta)',
                functionName: 'traitID=801',
                iconPath: '/v2/domains/551/traitIcons/trait801_dr4rbgwu.png',
                iconName: '',
                menuGroup: '/Additional Features/',
                links: [
                  {
                    encType: 'application/x-www-form-urlencoded',
                    contentType: 'text/html',
                    href: '/v25/__red.asp?itemTraitID=30620',
                    media: 'all',
                    method: 'get',
                    targetPref: '_blank',
                    title: 'PPF (Beta)',
                    parameters: [],
                    rel: ['http://kvau.lt/clientportal'],
                  },
                  {
                    encType: 'application/x-www-form-urlencoded',
                    contentType: 'text/html',
                    href: 'https://cherry.mocaworks.com/tyto/api/CustomTab/redirect?legacyServer=&itemTraitID=30620&sessionKey=YV96HCF9R4KXKNVMRQMFMBWD0ZH2JLWFPHLKZ3452PT1Z04YLMTPJNXT67B4BV9F',
                    media: 'all',
                    method: 'get',
                    targetPref: '_blank',
                    title: 'PPF (Beta)',
                    parameters: [],
                    rel: ['http://kvau.lt/clientportal/mobile'],
                  },
                ],
                param4Desc: '',
                param3Desc: '',
                param2Desc: '',
                param1Desc: '',
                iconPathLarge:
                  '/v2/domains/551/traitIcons/traitLrg801_w3cs0bnk.png',
                keyPhrases: ['PPF'],
                description: 'Launch PPF Beta with session',
                longName: '',
              },
              {
                functionID: 60,
                displayName: 'R3 (Beta)',
                functionName: 'traitID=802',
                iconPath: '/v2/domains/551/traitIcons/trait802_pgfwnzpi.png',
                iconName: '',
                menuGroup: '/Additional Features/',
                links: [
                  {
                    encType: 'application/x-www-form-urlencoded',
                    contentType: 'text/html',
                    href: '/v25/__red.asp?itemTraitID=30619',
                    media: 'all',
                    method: 'get',
                    targetPref: '_blank',
                    title: 'R3 (Beta)',
                    parameters: [],
                    rel: ['http://kvau.lt/clientportal'],
                  },
                  {
                    encType: 'application/x-www-form-urlencoded',
                    contentType: 'text/html',
                    href: 'https://cherry.mocaworks.com/tyto/api/CustomTab/redirect?legacyServer=&itemTraitID=30619&sessionKey=YV96HCF9R4KXKNVMRQMFMBWD0ZH2JLWFPHLKZ3452PT1Z04YLMTPJNXT67B4BV9F',
                    media: 'all',
                    method: 'get',
                    targetPref: '_blank',
                    title: 'R3 (Beta)',
                    parameters: [],
                    rel: ['http://kvau.lt/clientportal/mobile'],
                  },
                ],
                param4Desc: '',
                param3Desc: '',
                param2Desc: '',
                param1Desc: '',
                iconPathLarge:
                  '/v2/domains/551/traitIcons/traitLrg802_xuze5tar.png',
                keyPhrases: ['R3'],
                longName: '',
              },
              {
                functionID: 60,
                displayName: 'Team Editor (Beta)',
                functionName: 'traitID=653',
                iconPath: '/v2/domains/551/traitIcons/trait653_qu0ob4bu.png',
                iconName: '',
                menuGroup: '/Additional Features/',
                links: [
                  {
                    encType: 'application/x-www-form-urlencoded',
                    contentType: 'text/html',
                    href: '/v25/nl/#/teameditor',
                    media: 'all',
                    method: 'get',
                    targetPref: '_self',
                    title: 'Team Editor (Beta)',
                    parameters: [],
                    rel: ['http://kvau.lt/clientportal'],
                  },
                  {
                    encType: 'application/x-www-form-urlencoded',
                    contentType: 'text/html',
                    href: '/v25/nl/#/teameditor',
                    media: 'all',
                    method: 'get',
                    targetPref: '_self',
                    title: 'Team Editor (Beta)',
                    parameters: [],
                    rel: ['http://kvau.lt/clientportal/mobile'],
                  },
                ],
                param4Desc: '',
                param3Desc: '',
                param2Desc: '',
                param1Desc: '',
                iconPathLarge:
                  '/v2/domains/551/traitIcons/traitLrg653_1vnvir4b.png',
                description: 'A link to the new Team Editor interface',
                longName: '',
              },
              {
                functionID: 60,
                displayName: 'Teams (App Test)',
                functionName: 'traitID=697',
                iconPath: '',
                iconName: '',
                menuGroup: '/Additional Features/',
                links: [
                  {
                    encType: 'application/x-www-form-urlencoded',
                    contentType: 'text/html',
                    href: '/v25/nl/#/teams',
                    media: 'all',
                    method: 'get',
                    targetPref: 'iframe',
                    title: 'Teams (App Test)',
                    parameters: [],
                    rel: ['http://kvau.lt/clientportal'],
                  },
                  {
                    encType: 'application/x-www-form-urlencoded',
                    contentType: 'text/html',
                    href: '/v25/nl/#/teams',
                    media: 'all',
                    method: 'get',
                    targetPref: 'iframe',
                    title: 'Teams (App Test)',
                    parameters: [],
                    rel: ['http://kvau.lt/clientportal/mobile'],
                  },
                ],
                param4Desc: '',
                param3Desc: '',
                param2Desc: '',
                param1Desc: '',
                iconPathLarge: '',
                longName: '',
              },
              {
                functionID: 60,
                displayName: 'Teams Beta',
                functionName: 'traitID=580',
                iconPath: '/v2/domains/551/traitIcons/trait580_yolvumde.png',
                iconName: '',
                menuGroup: '/Additional Features/',
                links: [
                  {
                    encType: 'application/x-www-form-urlencoded',
                    contentType: 'text/html',
                    href: '/v25/nl/#/teams',
                    media: 'all',
                    method: 'get',
                    targetPref: '_self',
                    title: 'Teams Beta',
                    parameters: [],
                    rel: ['http://kvau.lt/clientportal'],
                  },
                  {
                    encType: 'application/x-www-form-urlencoded',
                    contentType: 'text/html',
                    href: '/v25/nl/#/teams',
                    media: 'all',
                    method: 'get',
                    targetPref: '_self',
                    title: 'Teams Beta',
                    parameters: [],
                    rel: ['http://kvau.lt/clientportal/mobile'],
                  },
                ],
                param4Desc: '',
                param3Desc: '',
                param2Desc: '',
                param1Desc: '',
                iconPathLarge:
                  '/v2/domains/551/traitIcons/traitLrg580_jc3bghsd.png',
                longName: '',
              },
              {
                functionID: 60,
                displayName: 'TeamTools',
                functionName: 'traitID=651',
                iconPath: '/v2/domains/551/traitIcons/trait651_ah5lrn3l.png',
                iconName: '',
                menuGroup: '/Additional Features/',
                links: [
                  {
                    encType: 'application/x-www-form-urlencoded',
                    contentType: 'text/html',
                    href: '/v25/__red.asp?itemTraitID=27957',
                    media: 'all',
                    method: 'get',
                    targetPref: '_blank',
                    title: 'TeamTools',
                    parameters: [],
                    rel: ['http://kvau.lt/clientportal'],
                  },
                  {
                    encType: 'application/x-www-form-urlencoded',
                    contentType: 'text/html',
                    href: 'https://cherry.mocaworks.com/tyto/api/CustomTab/redirect?legacyServer=&itemTraitID=27957&sessionKey=YV96HCF9R4KXKNVMRQMFMBWD0ZH2JLWFPHLKZ3452PT1Z04YLMTPJNXT67B4BV9F',
                    media: 'all',
                    method: 'get',
                    targetPref: '_blank',
                    title: 'TeamTools',
                    parameters: [],
                    rel: ['http://kvau.lt/clientportal/mobile'],
                  },
                ],
                param4Desc: '',
                param3Desc: '',
                param2Desc: '',
                param1Desc: '',
                iconPathLarge:
                  '/v2/domains/551/traitIcons/traitLrg651_oys5calo.png',
                description:
                  'A link to the TeamTools WebApp that authenticates on your behalf.',
                longName: '',
              },
              {
                functionID: 60,
                displayName: 'Teespring',
                functionName: 'traitID=762',
                iconPath: '/v2/domains/551/traitIcons/trait762_ftahdvdu.png',
                iconName: '',
                menuGroup: '/Additional Features/',
                links: [
                  {
                    encType: 'application/x-www-form-urlencoded',
                    contentType: 'text/html',
                    href: 'https://my-store-bddaec.creator-spring.com/',
                    media: 'all',
                    method: 'get',
                    targetPref: '_self',
                    title: 'Teespring',
                    parameters: [],
                    rel: ['http://kvau.lt/clientportal'],
                  },
                  {
                    encType: 'application/x-www-form-urlencoded',
                    contentType: 'text/html',
                    href: 'https://my-store-bddaec.creator-spring.com/',
                    media: 'all',
                    method: 'get',
                    targetPref: '_self',
                    title: 'Teespring',
                    parameters: [],
                    rel: ['http://kvau.lt/clientportal/mobile'],
                  },
                ],
                param4Desc: '',
                param3Desc: '',
                param2Desc: '',
                param1Desc: '',
                iconPathLarge:
                  '/v2/domains/551/traitIcons/traitLrg762_ijmmxxd2.png',
                keyPhrases: ['Teespring', 'Merch'],
                description: 'Link to Mocaworks unofficial Gear',
                longName: '',
              },
              {
                functionID: 60,
                displayName: 'Test Form Data',
                functionName: 'traitID=432',
                iconPath: '',
                iconName: '',
                menuGroup: '/Additional Features/',
                links: [
                  {
                    encType: 'application/x-www-form-urlencoded',
                    contentType: 'text/html',
                    href: '/v25/__red.asp?itemTraitID=30881',
                    media: 'all',
                    method: 'get',
                    targetPref: '_self',
                    title: 'Test Form Data',
                    parameters: [],
                    rel: ['http://kvau.lt/clientportal'],
                  },
                  {
                    encType: 'application/x-www-form-urlencoded',
                    contentType: 'text/html',
                    href: 'https://cherry.mocaworks.com/tyto/api/CustomTab/redirect?legacyServer=&itemTraitID=30881&sessionKey=YV96HCF9R4KXKNVMRQMFMBWD0ZH2JLWFPHLKZ3452PT1Z04YLMTPJNXT67B4BV9F',
                    media: 'all',
                    method: 'get',
                    targetPref: '_self',
                    title: 'Test Form Data',
                    parameters: [],
                    rel: ['http://kvau.lt/clientportal/mobile'],
                  },
                ],
                param4Desc: '',
                param3Desc: '',
                param2Desc: '',
                param1Desc: '',
                iconPathLarge: '',
                longName: '',
              },
              {
                functionID: 60,
                displayName: 'TGP',
                functionName: 'traitID=343',
                iconPath: '/v2/domains/551/traitIcons/trait343_ukie4rlq.png',
                iconName: '',
                menuGroup: '/Additional Features/',
                links: [
                  {
                    encType: 'application/x-www-form-urlencoded',
                    contentType: 'text/html',
                    href: '/v25/nl/#/TGP/',
                    media: 'all',
                    method: 'get',
                    targetPref: '_self',
                    title: 'TGP',
                    parameters: [],
                    rel: ['http://kvau.lt/clientportal'],
                  },
                  {
                    encType: 'application/x-www-form-urlencoded',
                    contentType: 'text/html',
                    href: '/v25/nl/#/TGP/',
                    media: 'all',
                    method: 'get',
                    targetPref: '_self',
                    title: 'TGP',
                    parameters: [],
                    rel: ['http://kvau.lt/clientportal/mobile'],
                  },
                ],
                param4Desc: '',
                param3Desc: '',
                param2Desc: '',
                param1Desc: '',
                iconPathLarge: '',
                longName: '',
              },
            ],
            param4Desc: '',
            param3Desc: '',
            param2Desc: '',
            param1Desc: '',
            iconPathLarge: '',
            longName: '',
          },
          {
            functionID: 119,
            displayName: '10X Action Plan',
            functionName: 'TransGrowth Tasks Team',
            iconPath:
              '/v2/domains/551/traitIcons/TransGrowth_Tasks_Team_gcicvtkc.png',
            iconName: 'icon tgp',
            menuGroup: '/',
            links: [
              {
                encType: 'application/x-www-form-urlencoded',
                contentType: 'text/html',
                href: '/v25/nl/#/action-plan',
                media: 'screen',
                method: 'get',
                targetPref: '_top',
                title: 'Action Plan',
                parameters: [],
                rel: [
                  'http://kvau.lt/default',
                  'http://kvau.lt/nl',
                  'http://kvau.lt/nl/iframe?iframeOrigin=https://action-plan.azureedge.net/action-plan',
                ],
              },
              {
                encType: 'application/x-www-form-urlencoded',
                contentType: 'text/html',
                href: '/v25/nl/#/tgp',
                media: 'screen',
                method: 'get',
                targetPref: '_top',
                title: 'Transformational Growth Plan',
                parameters: [],
                rel: ['http://kvau.lt/legacy/v2/ui'],
              },
            ],
            param4Desc: '',
            param3Desc: '',
            param2Desc: 'taskID',
            param1Desc: 'teamID',
            iconPathLarge:
              '/v2/domains/551/traitIcons/TransGrowth_Tasks_Team_ijihdsoh.png',
            longName: 'Transformational Growth Plan',
          },
          {
            functionID: 150,
            displayName: 'Projects',
            functionName: 'ProjectTeam',
            iconPath:
              '/v25/images/icons/elementType/ocTEAM/ocProject_128px.png',
            iconName: 'Project Team Ico',
            menuGroup: '/',
            links: [
              {
                encType: 'application/x-www-form-urlencoded',
                contentType: 'text/html',
                href: '/v25/nl/#/projects/',
                media: '',
                method: 'get',
                targetPref: '_top',
                title: 'Projects',
                parameters: [],
                rel: ['http://kvau.lt/default', 'http://kvau.lt/nl'],
              },
            ],
            param4Desc: '',
            param3Desc: '',
            param2Desc: '',
            param1Desc: '',
            iconPathLarge: '',
            longName: '',
          },
          {
            functionID: 68,
            displayName: 'Reports',
            functionName: 'Page Reports',
            iconPath: '/v25/images/icons/statistics_50px.png',
            iconName: '',
            menuGroup: '/',
            links: [
              {
                encType: 'application/x-www-form-urlencoded',
                contentType: 'text/html',
                href: '/v25/reports/',
                media: 'screen',
                method: 'get',
                targetPref: '_top',
                title: 'Dashboard',
                parameters: [],
                rel: ['http://kvau.lt/legacy/v2/ui'],
              },
            ],
            param4Desc: '',
            param3Desc: '',
            param2Desc: '',
            param1Desc: '',
            iconPathLarge: '',
            longName: '',
          },
          {
            functionID: 55,
            displayName: 'Manage',
            functionName: 'Page Manage',
            iconPath: '/v25/images/icons/edit_128px.png',
            iconName: '',
            menuGroup: '/',
            links: [
              {
                encType: 'application/x-www-form-urlencoded',
                contentType: 'text/html',
                href: '/v25/nl/#/manage/',
                media: 'screen',
                method: 'get',
                targetPref: '_top',
                title: 'Manage',
                parameters: [],
                rel: [
                  'http://kvau.lt/default',
                  'http://kvau.lt/legacy/mobile/ui',
                  'http://kvau.lt/legacy/v2/ui',
                ],
              },
            ],
            param4Desc: '',
            param3Desc: '',
            param2Desc: '',
            param1Desc: '',
            iconPathLarge: '',
            longName: '',
          },
          {
            functionID: 24,
            displayName: 'Statistics',
            functionName: 'Reports',
            iconPath: '/v25/images/icons/chart_128px.png',
            iconName: '',
            menuGroup: '/',
            links: [
              {
                encType: 'application/x-www-form-urlencoded',
                contentType: 'text/html',
                href: '/v25/nl/#/stats/',
                media: 'screen',
                method: 'get',
                targetPref: '_top',
                title: 'Statistics',
                parameters: [
                  {
                    paramName: 'sessionKey',
                    paramType: 'string',
                    value: '',
                  },
                ],
                rel: ['http://kvau.lt/legacy/v2/ui', 'http://kvau.lt/nl'],
              },
              {
                encType: 'application/x-www-form-urlencoded',
                contentType: 'text/html',
                href: '/v25/nl/?app=t#/stats/',
                media: 'screen',
                method: 'get',
                targetPref: '_top',
                title: 'Statistics',
                parameters: [],
                rel: ['http://kvau.lt/legacy/mobile/ui'],
              },
            ],
            param4Desc: '',
            param3Desc: '',
            param2Desc: '',
            param1Desc: '',
            iconPathLarge: '',
            longName: '',
          },
          {
            functionID: 166,
            displayName: 'Course Recommendations',
            functionName: 'EnrollmentWatch',
            iconPath: '',
            iconName: '',
            menuGroup: '/',
            links: [
              {
                encType: 'application/x-www-form-urlencoded',
                contentType: 'text/html',
                href: '/v25/nl/#/mastery/assignments',
                media: 'screen',
                method: 'get',
                targetPref: '_top',
                title: 'Course Recommendations',
                parameters: [],
                rel: [
                  'http://kvau.lt/default',
                  'http://kvau.lt/nl',
                  'http://kvau.lt/nl/iframe?iframeOrigin=https://mastery-cherry-iis.mocaworks.com',
                ],
              },
            ],
            param4Desc: '',
            param3Desc: '',
            param2Desc: 'memberType',
            param1Desc: 'enrollmentWatchID',
            iconPathLarge: '',
            longName: '',
          },
          {
            functionID: 105,
            displayName: 'Services',
            functionName: 'Catalog SharedService',
            iconPath: '/v2/domains/167210/service_icons/logo_128px.png',
            iconName: 'service',
            menuGroup: '/',
            links: [
              {
                encType: '',
                contentType: 'text/html',
                href: '/v25/nl/#/services',
                media: 'screen',
                method: 'get',
                targetPref: '_top',
                title: 'Services',
                parameters: [],
                rel: ['http://kvau.lt/nl'],
              },
              {
                encType: 'application/x-www-form-urlencoded',
                contentType: 'text/html',
                href: '/v25/customactions/167210/services/',
                media: 'screen',
                method: 'get',
                targetPref: '_top',
                title: 'Services',
                parameters: [],
                rel: ['http://kvau.lt/legacy/v2/ui'],
              },
            ],
            param4Desc: '',
            param3Desc: 'parentCatalogID',
            param2Desc: 'memberID',
            param1Desc: 'catalogID',
            iconPathLarge: '',
            longName: '',
          },
        ],
        session: {
          adminID: 0,
          changePassword: false,
          domainID: 551,
          koPermissionSyncDate: '2023-09-29T15:25:54.27+00:00',
          onCourseURL: 'https://cherry.mocaworks.com',
          onlinePreference: 'ocHIDDEN',
          profileThumbPath:
            '/v2/domains/551/assets/1960713_tsc3eykcizn_200px.jpg',
          roleID: 1,
          teamRootID: 551,
          teamListSyncDate: '1900-01-01T00:00:00+00:00',
          termsOfServiceSignatureRequired: false,
          timeOutMnts: 129600,
          userID: 1960713,
          userName: 'Joshua Rinard',
        },
      }
    },
  },
  invalidMissingRequired: (propName: string) => {
    return {
      data: [],
      links: [],
      error: {
        logID: -1,
        sts: -1000,
        msg: `validation error: ${propName} required`,
        technical: `parameters must contain ${propName}`,
      },
    }
  },
}
