import { Resource as TytoResource } from './utils/Resource'
export { default as TytoClient } from './client'
export { useTytoClient } from './hooks/useTytoClient'
export {
  TytoClientContext,
  TytoClientProvider,
  TytoClientContextConsumer,
} from './context'
export type { TytoClientProviderProps } from './typings/context'
export {
  deleteCall,
  getCall,
  postCall,
  postFormCall,
  putCall,
} from './utils/utils'
export { pullErrorMsg } from './utils/error-message'
export type Resource = typeof TytoResource
export { SessionInjectionInterceptor } from './interceptors/requests/SessionInjectionInterceptor'
export { ErrorInterceptor } from './interceptors/responses/ErrorInterceptor'
export { TYTO_ENDPOINT_PATHS } from './constants'
export type {
  Endpoints,
  TytoResponseNonGet,
  TytoEndpoints,
  SearchLessonResult,
} from './typings'
export type {
  FunctionID,
  FunctionName,
  OperationName,
} from './constants/security-role'
export {
  FUNCTION_SCOPE_NAMES,
  FUNCTION_IDS_BY_FRIENDLY_NAME,
} from './constants/security-role'
export * from './exceptions'
export * from './resources/BlockEnrollment'
export * from './resources/CatalogCurriculumPublication'
export * from './resources/CatalogCurriculumPublication/CatalogCurriculumPublicationEnhancedPermissions'
export * from './resources/CatalogCurriculumPublication/CatalogCurriculumPublicationEnhancedPermissionsPerson'
export * from './resources/Courses'
export * from './resources/CustomTab'
export * from './resources/CustomTabs'
export * from './resources/Domain'
export * from './resources/TeamCustomTabs'
export * from './resources/TeamCustomTab'
export * from './resources/PersonCustomTabs'
export * from './resources/PersonCustomTab'
export * from './resources/EmailQueueStatusUser'
export * from './resources/PersonActivityLog'
export * from './resources/TeamBanners'
export * from './resources/TeamBanner'
export * from './resources/Telecom'
export * from './resources/PersonSubordinates'
export * from './resources/PersonAbsence'
export * from './resources/Roles'
export * from './resources/EnrollmentHistory'
export * from './resources/PersonPassword'
export * from './resources/LoginResetPasswordValidate'
export * from './resources/BlockEnrollment'
export * from './resources/Enrollment'
export * from './resources/LaunchEnrollment'
export * from './resources/PeopleSearch'
export * from './resources/PersonProfilePhoto'

export type TytoEndpoint<T extends (...args: unknown[]) => unknown> = Awaited<
  ReturnType<T>
>
export * from './resources/DomainInvitationEmail'
export * from './resources/EmailQueueStatusUser'
export * from './resources/EmailAddress'
export * from './resources/EventAttendee'
export * from './resources/Enrollment'
export * from './resources/EnrollmentHistory'
export * from './resources/Event'
export * from './resources/EventAgenda'
export * from './resources/EventAttendees'
export * from './resources/EventAttendeesDiscProfiles'
export * from './resources/EventRsvp'
export * from './resources/Events'
export * from './resources/LaunchEnrollment'
export * from './resources/LoginResetPasswordValidate'
export * from './resources/Menu'
export * from './resources/PeopleAdvancedSearch'
export * from './resources/Person'
export * from './resources/PersonAbsence'
export * from './resources/PersonActivityLog'
export * from './resources/PersonCustomTab'
export * from './resources/PersonCustomTabs'
export * from './resources/PersonPassword'
export * from './resources/PersonSubordinates'
export * from './resources/Roles'
export * from './resources/TaskStructure'
export * from './resources/Tasks'
export * from './resources/Team'
export * from './resources/TeamBanner'
export * from './resources/TeamBanners'
export * from './resources/TeamCustomTab'
export * from './resources/TeamCustomTabs'
export * from './resources/TeamIDsByFunction'
export * from './resources/TeamMembershipPerson'
export * from './resources/TeamsByFunction'
export * from './resources/Telecom'
export * from './resources/Training'
export * from './resources/Transcript'
export * from './resources/Role'
export * from './resources/TeamMembershipTeam'
export * from './resources/TeamTools.Config'
export * from './resources/PlatformReviewTeams'
export * from './resources/PlatformReviewTask'
export * from './resources/PlatformReviewTeamInitialize'
export * from './resources/PlatformReviewStats'
export * from './resources/BlockEnrollmentCompletionPerSubBlock'
export * from './resources/PeopleByFunction'
export * from './resources/PrerequisiteEnrollments'
export * from './resources/TeamAdmin'
export * from './resources/DiscProfilesMini'
export * from './resources/PersonAccount'
export * from './resources/ViewHistorySummary'
export * from './resources/ViewHistoryMostRecent'
export * from './resources/BlockEnrollmentCompleteStatusForce'
export * from './resources/ClientServiceNoteAttach'
export * from './resources/DomainInvitationEmailTemplate'
export * from './resources/ClientServiceNote'
export * from './resources/ClientServiceNotesByElement'
export * from './resources/Badge'
export * from './resources/SendEmailNoActivity'
export * from './resources/FunctionOps'
export * from './resources/TeamDefaultEnrollmentsTeam'
export * from './resources/TeamDefaultEnrollment'
export * from './resources/LoginTOS'
export * from './resources/Domainterms'
export * from './resources/BlockPrerequisites'
export * from './resources/EnrollmentCurriculumCompleteJob'
export * from './resources/EnrollmentCurriculumCompleteJobs'
export * from './resources/PersonOutsideIdentityAll'
export * from './resources/PersonOutsideIdentity'
export * from './resources/IdentityAuthorizationConnect'
export * from './resources/IdentityProviders'
export * from './resources/RobotAccount'
export * from './resources/RobotAccounts'
export * from './resources/SearchKnowledgeObjects'
export * from './resources/SearchPhraseRecent'
export * from './resources/RobotAccount'
export * from './resources/RobotAccounts'
export * from './resources/PeopleBrowse'
export * from './resources/CatalogPermission'
export * from './resources/PersonLogonName'
export * from './resources/TimeZone'
export * from './resources/Languages'
export * from './resources/TrainingSummary'
export * from './resources/CurriculumSummaryReport'
export * from './resources/CurriculumSubcomponentSummaryReport'
export * from './resources/TrainingCatalogLessonCompletionSummarySB2165'
export * from './resources/TrainingDetail'
export * from './resources/LessonViewHistoryPerson'
export * from './resources/MenuManage'
export * from './resources/DomainUI'
export * from './resources/CatalogNews'
export * from './resources/LibraryLegacy'
export * from './resources/LibraryTeamFeatured'
export * from './resources/DomainUIConfiguration'
export * from './resources/DomainUIConfigurationLibraryImageUpload'
export * from './resources/DomainUIConfigurations'
export * from './resources/DomainUIConfigurationCurrent'
export * from './resources/DomainUIImage'
export * from './resources/Library'
export * from './resources/LibraryCategory'
export * from './resources/LibraryCategoryCopy'
export * from './resources/LibraryItem'
export * from './resources/LibraryCategoryIcon'
export * from './resources/BlocksForEdit'
export * from './resources/BlocksForEnrollment'
