const DEPRECIATED_FUNCTIONS = [
  {
    functionName: 'Logon',
    functionID: 1,
    functionDesc: 'DEPRICATE',
    functionType: 'ocDATA',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Curriculum',
    functionID: 4,
    functionDesc:
      "DEPRECATE Manage a course's contents, also see Function: Blocks",
    functionType: 'ocDATA',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Content Mgmt',
    functionID: 6,
    functionDesc: 'DEPRICATE',
    functionType: 'ocDATA',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Curric Structure',
    functionID: 15,
    functionDesc:
      "DEPRICATE Can manage a course's contents (how is different from Curriculum)",
    functionType: 'ocDATA',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Root Teams',
    functionID: 16,
    functionDesc: "DEPRICATE Can manage a team's root assignment",
    functionType: 'ocDATA',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Root Curricula',
    functionID: 17,
    functionDesc: 'DEPRICATE',
    functionType: 'ocDATA',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Block Register',
    functionID: 19,
    functionDesc:
      "DEPRICATE Manage registrations in courses (depricated 2010-Feb Peter Bachman: redundant with 'Block Enroll' there is no distinction between enrollment and registration)",
    functionType: 'ocDATA',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Curriculum Status',
    functionID: 20,
    functionDesc:
      'DEPRICATE Can manage enrollment status (depricated 2010-Feb this is a poorly named function)',
    functionType: 'ocDATA',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Lesson Launch',
    functionID: 21,
    functionDesc:
      'DEPRICATE Allows Lesson Launching in a context other than registration',
    functionType: 'ocDATA',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Admin',
    functionID: 23,
    functionDesc:
      'DEPRICATE Admin best describes a role not a function only use is link to Administrator Site',
    functionType: 'ocDATA',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'GoalSharing Admin',
    functionID: 25,
    functionDesc:
      'DEPRICATE Can manage any goal sharing object implicitly. (depricated 2010-Feb Peter Bachman: Now that functions are specified with a scope it is redundant to have functions that are scope specific)',
    functionType: 'ocDATA',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Mentor Activity',
    functionID: 32,
    functionDesc:
      'DEPRICATE Can manage the assignment of mentor activities to members',
    functionType: 'ocDATA',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Assessments Implicit',
    functionID: 40,
    functionDesc:
      'DEPRICATE Can manage assesments with implicit permission. Overrides explicit sharing',
    functionType: 'ocDATA',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Beta',
    functionID: 43,
    functionDesc: 'Can view elements in the beta test wrapper',
    functionType: 'ocUI',
    menuDisplayName: 'Development',
    uiType: 'ocPAGE',
    param1Desc: 'URI',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Page Assessments',
    functionID: 52,
    functionDesc:
      'DEPRICATEInterface Descriptor for the Assessments tab. Does not grant any specific access to data. Just whether or not a tab is present.',
    functionType: 'ocUI',
    menuDisplayName: 'Page Assessments',
    uiType: 'ocPAGE',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Page Courses',
    functionID: 53,
    functionDesc:
      'Interface Descriptor for the Courses tab. Does not grant any specific access to data. Just whether or not a tab is present.',
    functionType: 'ocUI',
    menuDisplayName: 'Page Courses',
    uiType: 'ocPAGE',
    param1Desc: 'blockID',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Page Mentor',
    functionID: 56,
    functionDesc:
      'DEPRICATE Interface Descriptor for the Mentor Tab. Does not grant any specific access to data, just whether or not a tab is present.',
    functionType: 'ocUI',
    menuDisplayName: 'Page Mentor',
    uiType: 'ocPAGE',
    param1Desc: 'taskID',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Page Home Beta',
    functionID: 59,
    functionDesc: 'Beta view of latest changes to the Home page',
    functionType: 'ocUI',
    menuDisplayName: 'Page Home Beta',
    uiType: 'ocPAGE',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Page Library Beta',
    functionID: 70,
    functionDesc: 'A tab containing latest developments in library technology',
    functionType: 'ocUI',
    menuDisplayName: 'Page Library Beta',
    uiType: 'ocPAGE',
    param1Desc: 'memberID',
    param2Desc: 'categoryID',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Confidential Tasks',
    functionID: 120,
    functionDesc:
      'DEPRECATE Manage the confidential Tasks assigned. Extends the base task type when the task is marked confidential. Users lacking view permission are prevented from viewing certain details of the task.',
    functionType: 'ocDATA',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
]

export const ALL_SECURITY_FUNCTIONS = [
  {
    functionName: 'People',
    functionID: 2,
    functionDesc: 'Manage User records ',
    functionType: 'ocDATA',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Teams',
    functionID: 3,
    functionDesc:
      'Manage Team records used primarily on the right side of the teams and people editor',
    functionType: 'ocDATA',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Assessments',
    functionID: 5,
    functionDesc:
      'Manage the design of assesments including questions and categories. This is implicit for the selected scopes',
    functionType: 'ocDATA',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Goal Sharing',
    functionID: 7,
    functionDesc: 'Manage goalsharing objects',
    functionType: 'ocDATA',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Person Password',
    functionID: 8,
    functionDesc: "Manage user's password and loginname",
    functionType: 'ocDATA',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Person Address',
    functionID: 9,
    functionDesc: "Manage user's address information ",
    functionType: 'ocDATA',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Person Admin',
    functionID: 10,
    functionDesc:
      "Manage user's team root, security role, custom tab allocation, linking(unlinking) person accounts together, and single sign-on identity fields. Team root alteration requires change on both previous and new teams. Add/Delete allows increments/decrements to maxPersons at the team level and altering detailSummary.",
    functionType: 'ocDATA',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Person Demographics',
    functionID: 11,
    functionDesc: "Manage user's information other than address and password",
    functionType: 'ocDATA',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Team Membership',
    functionID: 12,
    functionDesc:
      'Manage the association between a team and persons. ViewScope drives the tree view in the left side of the team and people editor. Also exposes the R3 heatmap and aggregated Disc scores in the context of a team.',
    functionType: 'ocDATA',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Blocks',
    functionID: 13,
    functionDesc: 'Manage Courses, high level containers of knowlege objects',
    functionType: 'ocDATA',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Lessons',
    functionID: 14,
    functionDesc:
      'Manage Knowlege Objects (non-answerkey, non-enrollment required). Items in libraries, courses, notices all implicitly allow read access to those members with read access to those interfaces. View access grants users access to search for knowledge objects rooted in a team scope without requiring enrollment',
    functionType: 'ocDATA',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Block Enroll',
    functionID: 18,
    functionDesc:
      'Manage enrollments in courses. The scope defines which users or teams user may view. ',
    functionType: 'ocDATA',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Roles',
    functionID: 22,
    functionDesc:
      'Manage role definition and function collections. A scope less than Domain is meaningless.',
    functionType: 'ocDATA',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Reports',
    functionID: 24,
    functionDesc:
      'Domain Statistics Reports: billable activities, user adoption and utilization, etc.',
    functionType: 'ocDATA',
    menuDisplayName: 'Statistics',
    uiType: 'ocPAGE',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Bugs',
    functionID: 29,
    functionDesc: 'Can manage bugs notices',
    functionType: 'ocDATA',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Impersonate',
    functionID: 30,
    functionDesc: 'Can impersonate another user in the domain via bypasslogin',
    functionType: 'ocDATA',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'System',
    functionID: 31,
    functionDesc: 'The System tab is visible',
    functionType: 'ocDATA',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'News Team',
    functionID: 33,
    functionDesc: 'Can manage news articles ',
    functionType: 'ocDATA',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Notice Team',
    functionID: 34,
    functionDesc: 'Can manage the posts on team board',
    functionType: 'ocDATA',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'LibraryFront Team',
    functionID: 35,
    functionDesc:
      'Manage the library entries and category assginments belonging to the teams front room',
    functionType: 'ocDATA',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'LibraryBack Team',
    functionID: 36,
    functionDesc:
      "Manage the library entries in the team's back room (archives)",
    functionType: 'ocDATA',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Notices Person',
    functionID: 37,
    functionDesc:
      'Manage messages private messages. View scope determines whether a user has the private messaging module',
    functionType: 'ocDATA',
    menuDisplayName: 'Inbox',
    uiType: 'ocPAGE',
    param1Desc: 'noticeID',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Function',
    functionID: 38,
    functionDesc:
      'Can manage the description and name of functions. Not currently implemented as an interface option!',
    functionType: 'ocDATA',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'onCourseLegacy',
    functionID: 41,
    functionDesc: 'UI Descriptor for displaying the link to the old admin site',
    functionType: 'ocDATA',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Domain',
    functionID: 42,
    functionDesc: 'Manage a special type of team known as a Domain',
    functionType: 'ocDATA',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Exams',
    functionID: 44,
    functionDesc:
      'Manage the design of exams categories, questions, answers in the selected scope. Select users may be extended greater permissions in the exam editor interface that ignore this setting',
    functionType: 'ocDATA',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'System Log',
    functionID: 45,
    functionDesc:
      'Mangage system generated log entries caused by errors and debug tracking',
    functionType: 'ocDATA',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Lesson Answerkey',
    functionID: 46,
    functionDesc: 'Manage knowledge objects designated as an answerkey',
    functionType: 'ocDATA',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Debug',
    functionID: 47,
    functionDesc:
      'User is exposed to debug information in the interface exposing error details a variable values',
    functionType: 'ocDATA',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Page Library',
    functionID: 48,
    functionDesc:
      'Interface Descriptor for the Library tab. Does not grant any specific access to data. Just whether or not a tab is present.',
    functionType: 'ocUI',
    menuDisplayName: 'Library',
    uiType: 'ocPAGE',
    param1Desc: 'memberID',
    param2Desc: 'categoryID',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Page Team',
    functionID: 49,
    functionDesc:
      'Interface Descriptor for the Team tab. Does not grant any specific access to data. Just whether or not a tab is present.',
    functionType: 'ocUI',
    menuDisplayName: 'Team',
    uiType: 'ocPAGE',
    param1Desc: 'teamID',
    param2Desc: 'noticeID',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Page News',
    functionID: 50,
    functionDesc:
      'Interface Descriptor for the News tab. Does not grant any specific access to data. Just whether or not a tab is present.',
    functionType: 'ocUI',
    menuDisplayName: 'News',
    uiType: 'ocPAGE',
    param1Desc: 'newsID',
    param2Desc: 'noticeID',
    param3Desc: 'noticeCommentID',
    param4Desc: '',
  },
  {
    functionName: 'Page Search',
    functionID: 51,
    functionDesc:
      'Interface Descriptor for the Search tab. Does not grant any specific access to data. Just whether or not a tab is present.',
    functionType: 'ocUI',
    menuDisplayName: 'Search',
    uiType: 'ocPAGE',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Page Home',
    functionID: 54,
    functionDesc:
      'Interface Descriptor for the Home tab. Does not grant any specific access to data. Just whether or not a tab is present.',
    functionType: 'ocUI',
    menuDisplayName: 'Home',
    uiType: 'ocPAGE',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Page Manage',
    functionID: 55,
    functionDesc:
      'Interface Descriptor for the Manage/Control Panel tab. Does not grant any specific access to data. Just whether or not a tab is present.',
    functionType: 'ocUI',
    menuDisplayName: 'Manage',
    uiType: 'ocPAGE',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Surveys',
    functionID: 57,
    functionDesc: 'Manage the questions and options in a survey',
    functionType: 'ocDATA',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'DomainLoginURI',
    functionID: 58,
    functionDesc:
      'Manage the email domain names for user authentication via email challenge',
    functionType: 'ocDATA',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Page Portal',
    functionID: 60,
    functionDesc:
      'Grants access to a special UI Portal tab whose behavior is defined by varibles in the Domain',
    functionType: 'ocUI',
    menuDisplayName: 'Portal (Custom Tabs)',
    uiType: 'ocPAGE',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Replication Data',
    functionID: 61,
    functionDesc:
      'Manage certain outside id fields used for system integration and single sign on clients',
    functionType: 'ocDATA',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'LibraryFront Person',
    functionID: 63,
    functionDesc: 'Can manage the library entries of a given user',
    functionType: 'ocDATA',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Person Activity',
    functionID: 64,
    functionDesc:
      'Can manage the historical log of user interactions, searches, course launches, etc.',
    functionType: 'ocDATA',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'DevTasks',
    functionID: 65,
    functionDesc: 'Can manage the tasks assigned to members',
    functionType: 'ocDATA',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'DevPlans',
    functionID: 66,
    functionDesc:
      'Can manage the plan templates that will be assinged as tasks to members',
    functionType: 'ocDATA',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Page Training',
    functionID: 67,
    functionDesc: 'Can view the Training tab no other security restrictions',
    functionType: 'ocUI',
    menuDisplayName: 'Training (Mastery)',
    uiType: 'ocPAGE',
    param1Desc: 'taskID',
    param2Desc: 'blockID',
    param3Desc: 'devPlanID',
    param4Desc: 'enrollmentID',
  },
  {
    functionName: 'Page Reports',
    functionID: 68,
    functionDesc: 'grants access to the Reports Tab',
    functionType: 'ocUI',
    menuDisplayName: 'Reports',
    uiType: 'ocPAGE',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Teams Analytics',
    functionID: 69,
    functionDesc:
      'Drives the list of teams on the left side of the Interactive Analytics Dshboard',
    functionType: 'ocDATA',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Chat Private',
    functionID: 71,
    functionDesc:
      'Enables a user to send instant messages to another user in the system',
    functionType: 'ocDATA',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'TPA',
    functionID: 72,
    functionDesc: 'Manage the Team Performance Assessment (tm)',
    functionType: 'ocDATA',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Page ToDo',
    functionID: 73,
    functionDesc: 'View the ToDos tab',
    functionType: 'ocUI',
    menuDisplayName: "To Do's",
    uiType: 'ocPAGE',
    param1Desc: 'taskID',
    param2Desc: 'noticeID',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Lessons QuickDoc',
    functionID: 74,
    functionDesc: 'Manage ocQuickDoc ocLESSON subtype',
    functionType: 'ocDATA',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Blocks Published',
    functionID: 75,
    functionDesc:
      'Manage the blocks that are published or toggle a blocks publication',
    functionType: 'ocDATA',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Catalog CurriculumPub',
    functionID: 76,
    functionDesc: 'Manage the Curriculum Publication Catalog',
    functionType: 'ocDATA',
    param1Desc: 'catalogID',
    param2Desc: 'memberID',
    param3Desc: 'parentCatalogID',
    param4Desc: '',
  },
  {
    functionName: 'DevTasks Team',
    functionID: 77,
    functionDesc: 'Manage DevTasks assigned to a Team as the participant',
    functionType: 'ocDATA',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Page Reports Users',
    functionID: 78,
    functionDesc: 'Sub tab of the dashboard reports tab',
    functionType: 'ocUI',
    menuDisplayName: 'Users Reports',
    uiType: 'ocPAGE',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Page Reports Courses',
    functionID: 79,
    functionDesc: 'Sub tab of the dashboard reports tab',
    functionType: 'ocUI',
    menuDisplayName: 'Courses Reports',
    uiType: 'ocPAGE',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Page Reports Todos',
    functionID: 80,
    functionDesc: 'Sub tab of the dashboard reports tab',
    functionType: 'ocUI',
    menuDisplayName: 'Todos Reports',
    uiType: 'ocPAGE',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Page Reports Roles',
    functionID: 81,
    functionDesc: 'Sub tab of the dashboard reports tab',
    functionType: 'ocUI',
    menuDisplayName: 'Roles Reports',
    uiType: 'ocPAGE',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Page Reports Email',
    functionID: 82,
    functionDesc: 'Sub tab of the dashboard reports tab',
    functionType: 'ocUI',
    menuDisplayName: 'Email Reports',
    uiType: 'ocPAGE',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Page Reports Activity',
    functionID: 83,
    functionDesc: 'Sub tab of the dashboard reports tab',
    functionType: 'ocUI',
    menuDisplayName: 'Activity Reports',
    uiType: 'ocPAGE',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'SB MyAccount',
    functionID: 89,
    functionDesc: 'Springboard to MyAccount',
    functionType: 'ocUI',
    menuDisplayName: 'My Account',
    uiType: 'ocPAGE',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Curriculum Credit',
    functionID: 91,
    functionDesc:
      'can manage the list of Curriculum Credit available to a domain',
    functionType: 'ocDATA',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Events',
    functionID: 96,
    functionDesc: 'Manage Events by PrimaryElement',
    functionType: 'ocDATA',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'EventAttendees Team',
    functionID: 97,
    functionDesc:
      'Manage Team Event Attendance (ocEventAttendee.Add/Delete/Change also requires ocEvent.ChangeAccess)',
    functionType: 'ocDATA',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'EventAttendees Person',
    functionID: 98,
    functionDesc:
      'Manage Person Event Attendance (ocEventAttendee.Add/Delete/Change also requires ocEvent.ChangeAccess)',
    functionType: 'ocDATA',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Page Events',
    functionID: 99,
    functionDesc: 'Presents the Events tab to the user',
    functionType: 'ocUI',
    menuDisplayName: 'Calendar',
    uiType: 'ocPAGE',
    param1Desc: 'eventID',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Page Bugs',
    functionID: 101,
    functionDesc: 'interface descriptor for viewing a bug',
    functionType: 'ocUI',
    menuDisplayName: 'Bugs Reports',
    uiType: 'ocPAGEMANAGE',
    param1Desc: 'bugID',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Page Lesson',
    functionID: 102,
    functionDesc: 'Interface descriptor for viewing a lesson',
    functionType: 'ocUI',
    menuDisplayName: 'Lesson Viewer Page',
    uiType: 'ocPAGE',
    param1Desc: 'lessonID',
    param2Desc: 'assetID',
    param3Desc: 'noticeID',
    param4Desc: 'lessonItemType',
  },
  {
    functionName: 'Page Notice',
    functionID: 103,
    functionDesc:
      'interface descriptor for viewing a notice, its comments and attachments',
    functionType: 'ocUI',
    menuDisplayName: 'Notifications Viewer',
    uiType: 'ocPAGE',
    param1Desc: 'noticeID',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Page Catalog Curriculum',
    functionID: 104,
    functionDesc: 'interface descriptor for the curriculum catalog',
    functionType: 'ocUI',
    menuDisplayName: 'Training Catalog',
    uiType: 'ocPAGE',
    param1Desc: 'catalogID',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Catalog SharedService',
    functionID: 105,
    functionDesc:
      'Manage the Shared Service Catalog. A value of domain or greater grants the ability to set email-in address and set explicit permissions per catalog.',
    functionType: 'ocDATA',
    menuDisplayName: 'Services',
    uiType: 'ocPAGE',
    param1Desc: 'catalogID',
    param2Desc: 'memberID',
    param3Desc: 'parentCatalogID',
    param4Desc: '',
  },
  {
    functionName: 'Inbox Team',
    functionID: 106,
    functionDesc:
      'Controls the ability to add inbox messages to persons through teams search result. View, Change, Delete scopes are meaningless for now.',
    functionType: 'ocDATA',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Page TeamEditor',
    functionID: 107,
    functionDesc:
      'Controls the visibility of team editor. This function is implicitly included into the api/manage/menu  based on having a "Team Membership" and "Page Manage" operation view greater than NONE. Assigning a view scope on the role includes a main menu item.',
    functionType: 'ocUI',
    menuDisplayName: 'Team Editor',
    uiType: 'ocPAGEMANAGE',
    param1Desc: 'teamID',
    param2Desc: 'userID',
    param3Desc: 'eID',
    param4Desc: '',
  },
  {
    functionName: 'Notice Team Cascade',
    functionID: 109,
    functionDesc:
      'Allows use of the isCascade property on a notice to a team Only Add is used',
    functionType: 'ocDATA',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Page Verify',
    functionID: 110,
    functionDesc: 'Task or enrollment verification interface',
    functionType: 'ocUI',
    menuDisplayName: 'Verify',
    uiType: 'ocPAGE',
    param1Desc: 'noticeID',
    param2Desc: 'lessonID',
    param3Desc: 'reviewTaskID',
    param4Desc: 'enrollmentID',
  },
  {
    functionName: 'Checklist',
    functionID: 111,
    functionDesc: 'Manage Checklist Plan Templates',
    functionType: 'ocDATA',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Checklist Tasks',
    functionID: 112,
    functionDesc: 'Manage schedules assigned to teams and people',
    functionType: 'ocDATA',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Page Asset',
    functionID: 113,
    functionDesc:
      'UI descriptor for assets, most specifically notices to assets within photo albums. This is a very deep link to very specific legacy interface',
    functionType: 'ocUI',
    menuDisplayName: 'Asset',
    uiType: 'ocPAGE',
    param1Desc: 'assetID',
    param2Desc: 'courseItemID',
    param3Desc: 'noticeID',
    param4Desc: '',
  },
  {
    functionName: 'Person TraitR3',
    functionID: 114,
    functionDesc:
      'Manage the R3 suite of leadership tools. "Team Membership:View" controls the aggregate view of scores (heat-map). View scope is an interface descriptor for R3 menu item and the viewability of the PDF report version. Delete allows clearing an existing disc profile. Change enables an "Import" button, however, import from PeopleKeys is problematic because, the pkAccount is shared among multiple domains. All users in the Peoplekeys account are exposed. Search is only pk-web participants (taken with the iFRAME or direct from Peoplekeys). There is no ability to search participants who used the PK-api to take the exam.',
    functionType: 'ocDATA',
    menuDisplayName: 'R3',
    uiType: 'ocPAGE',
    param1Desc: 'itemTraitID',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Catalog EventTemplate',
    functionID: 115,
    functionDesc: 'Manage the Event Template Catalog',
    functionType: 'ocDATA',
    param1Desc: 'catalogID',
    param2Desc: 'memberID',
    param3Desc: 'parentCatalogID',
    param4Desc: '',
  },
  {
    functionName: 'EventTemplates',
    functionID: 116,
    functionDesc: 'Manage Event Templates',
    functionType: 'ocDATA',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'VCEPlan',
    functionID: 117,
    functionDesc:
      'Strategy domain customization. Manage Devplan extension Vision, Commitment, Execution Plan (VCEP)',
    functionType: 'ocUI',
    menuDisplayName: 'VCEP Editor',
    uiType: 'ocPAGE',
    param1Desc: 'devplanID',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Page GSPPF',
    functionID: 118,
    functionDesc:
      'Interface descriptor for Personal Professional Development Plan',
    functionType: 'ocUI',
    menuDisplayName: 'PPF',
    uiType: 'ocPAGE',
    param1Desc: 'planID',
    param2Desc: 'goalID',
    param3Desc: 'noticeID',
    param4Desc: '',
  },
  {
    functionName: 'TransGrowth Tasks Team',
    functionID: 119,
    functionDesc: 'Manage the Transformational Growth Tasks assigned to a team',
    functionType: 'ocDATA',
    menuDisplayName: 'Action Plan',
    uiType: 'ocPAGE',
    param1Desc: 'teamID',
    param2Desc: 'taskID',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Page Manage TrainingDashboard',
    functionID: 121,
    functionDesc: 'User Interface for editing Training Dashboard',
    functionType: 'ocUI',
    menuDisplayName: 'Training Dashboard',
    uiType: 'ocPAGE',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Page Manage News',
    functionID: 122,
    functionDesc: 'User Interface for managing News',
    functionType: 'ocUI',
    menuDisplayName: 'News',
    uiType: 'ocPAGEMANAGE',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Page Manage SecurityRoles',
    functionID: 123,
    functionDesc: 'User Interface for managing Security Roles',
    functionType: 'ocUI',
    menuDisplayName: 'Security Roles',
    uiType: 'ocPAGEMANAGE',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Page Manage AddMultiplePeople',
    functionID: 124,
    functionDesc: 'User Interface for managing Add Multiple People',
    functionType: 'ocUI',
    menuDisplayName: 'Add Multiple People',
    uiType: 'ocPAGEMANAGE',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Page Manage AbilityList',
    functionID: 125,
    functionDesc: 'User Interface for managing Ability List',
    functionType: 'ocUI',
    menuDisplayName: 'Ability List',
    uiType: 'ocPAGEMANAGE',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Page Manage EventTemplates',
    functionID: 126,
    functionDesc: 'User Interface for managing Event Templates',
    functionType: 'ocUI',
    menuDisplayName: 'Event Templates',
    uiType: 'ocPAGEMANAGE',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Page Manage Courses',
    functionID: 127,
    functionDesc: 'User Interface for managing Courses',
    functionType: 'ocUI',
    menuDisplayName: 'Courses',
    uiType: 'ocPAGEMANAGE',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Page Manage CreditTypes',
    functionID: 128,
    functionDesc: 'User Interface for managing Credit Types',
    functionType: 'ocUI',
    menuDisplayName: 'Credit Types',
    uiType: 'ocPAGEMANAGE',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Page Manage PlanTemplates',
    functionID: 129,
    functionDesc: 'User Interface for managing Plan Templates',
    functionType: 'ocUI',
    menuDisplayName: 'Plan Templates',
    uiType: 'ocPAGEMANAGE',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Page Manage ChecklistTemplates',
    functionID: 130,
    functionDesc: 'User Interface for managing Checklist Templates',
    functionType: 'ocUI',
    menuDisplayName: 'Checklist Templates',
    uiType: 'ocPAGEMANAGE',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Page Manage Catalog',
    functionID: 131,
    functionDesc: 'User Interface for managing Catalog',
    functionType: 'ocUI',
    menuDisplayName: 'Catalog',
    uiType: 'ocPAGEMANAGE',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Page Manage CategoryManager',
    functionID: 132,
    functionDesc: 'User Interface for managing Category Manager',
    functionType: 'ocUI',
    menuDisplayName: 'Category Manager',
    uiType: 'ocPAGEMANAGE',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Page Manage Exams',
    functionID: 133,
    functionDesc: 'User Interface for managing Exams',
    functionType: 'ocUI',
    menuDisplayName: 'Exam Editor',
    uiType: 'ocPAGEMANAGE',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Page Manage Surveys',
    functionID: 134,
    functionDesc: 'User Interface for managing Surveys',
    functionType: 'ocUI',
    menuDisplayName: 'Survey Editor',
    uiType: 'ocPAGEMANAGE',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Page Manage TPA',
    functionID: 135,
    functionDesc: 'User Interface for managing TPA',
    functionType: 'ocUI',
    menuDisplayName: 'TPA',
    uiType: 'ocPAGEMANAGE',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Page Manage ElementInfo',
    functionID: 136,
    functionDesc: 'User Interface for managing Element Info',
    functionType: 'ocUI',
    menuDisplayName: 'Element Info',
    uiType: 'ocPAGEMANAGE',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Page Manage FileSearch',
    functionID: 137,
    functionDesc: 'User Interface for managing File Search',
    functionType: 'ocUI',
    menuDisplayName: 'File Search',
    uiType: 'ocPAGEMANAGE',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Page Manage NoticeInfo',
    functionID: 138,
    functionDesc: 'User Interface for managing Notice Info',
    functionType: 'ocUI',
    menuDisplayName: 'Notice Info',
    uiType: 'ocPAGEMANAGE',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Page Manage ObjectInfo',
    functionID: 139,
    functionDesc: 'User Interface for managing Object Info',
    functionType: 'ocUI',
    menuDisplayName: 'Object Info',
    uiType: 'ocPAGEMANAGE',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Page Manage ServerVariables',
    functionID: 140,
    functionDesc: 'User Interface for managing Server Variables',
    functionType: 'ocUI',
    menuDisplayName: 'Server Variables',
    uiType: 'ocPAGEMANAGE',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Page Manage ChatRiver',
    functionID: 141,
    functionDesc: 'User Interface for managing Chat River',
    functionType: 'ocUI',
    menuDisplayName: 'Chat River',
    uiType: 'ocPAGEMANAGE',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Page Manage ChumbyPrime',
    functionID: 142,
    functionDesc: 'User Interface for reporting Chumby Prime',
    functionType: 'ocUI',
    menuDisplayName: 'Chumby Prime',
    uiType: 'ocPAGEMANAGE',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Page Manage MrRadar',
    functionID: 143,
    functionDesc: 'User Interface for managing Mr. Radar',
    functionType: 'ocUI',
    menuDisplayName: 'Mr. Radar',
    uiType: 'ocPAGEMANAGE',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Page Manage SystemDiagnostics',
    functionID: 144,
    functionDesc: 'User Interface for managing System Diagnostics',
    functionType: 'ocUI',
    menuDisplayName: 'System Diagnostics',
    uiType: 'ocPAGEMANAGE',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Page Manage SystemLog',
    functionID: 145,
    functionDesc: 'User Interface for managing System Log',
    functionType: 'ocUI',
    menuDisplayName: 'System Log',
    uiType: 'ocPAGEMANAGE',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Page Manage Billing',
    functionID: 146,
    functionDesc: 'User Interface for managing Billing',
    functionType: 'ocUI',
    menuDisplayName: 'Billing',
    uiType: 'ocPAGEMANAGE',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'PublicWall',
    functionID: 147,
    functionDesc: 'manage public wall posts',
    functionType: 'ocDATA',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Page PublicWallPost',
    functionID: 148,
    functionDesc: 'interface descriptor for a single wall post',
    functionType: 'ocUI',
    menuDisplayName: '',
    uiType: 'ocPAGE',
    param1Desc: 'publicWallID',
    param2Desc: 'publicWallCommentGUID',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Page PublicWall',
    functionID: 149,
    functionDesc: 'interface descriptor for a public profile activity stream',
    functionType: 'ocUI',
    menuDisplayName: '',
    uiType: 'ocPAGE',
    param1Desc: 'memberID',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'ProjectTeam',
    functionID: 150,
    functionDesc: 'Manage a special type of team known as a Project team',
    functionType: 'ocDATA',
    menuDisplayName: 'Projects',
    uiType: 'ocPAGE',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'ServiceBid',
    functionID: 155,
    functionDesc: '',
    functionType: 'ocUI',
    menuDisplayName: 'Service Request',
    uiType: 'ocPAGE',
    param1Desc: 'serviceBidID',
    param2Desc: 'serviceBidMethodID',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Catalog Playbook',
    functionID: 156,
    functionDesc: 'Manage content in the Playbook catalog',
    functionType: 'ocDATA',
    menuDisplayName: 'Playbook',
    uiType: 'ocPAGE',
    param1Desc: 'catalogID',
    param2Desc: 'memberID',
    param3Desc: 'parentCatalogID',
    param4Desc: '',
  },
  {
    functionName: 'Lesson Policy',
    functionID: 157,
    functionDesc: 'Manage the review process of designated Knowledge objects',
    functionType: 'ocUI',
    menuDisplayName: 'Review Articles',
    uiType: 'ocUI',
    param1Desc: 'policyID',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'User Function',
    functionID: 158,
    functionDesc:
      'Can view which users have an ability over a given function scope and operation',
    functionType: 'ocDATA',
    param1Desc: 'functionName',
    param2Desc: 'teamID',
    param3Desc: 'operation',
    param4Desc: '',
  },
  {
    functionName: 'ServiceBidMethod',
    functionID: 159,
    functionDesc: 'Service bid methods',
    functionType: 'ocUI',
    menuDisplayName: 'tblServiceBidMethod.name',
    uiType: 'ocUI',
    param1Desc: 'serviceBidMethodID',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Page Survey',
    functionID: 160,
    functionDesc: 'Take a survey and review results',
    functionType: 'ocUI',
    menuDisplayName: 'Surveys',
    uiType: 'ocPAGE',
    param1Desc: 'inviteID',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Page Manage RestorePerson',
    functionID: 161,
    functionDesc: 'Undelete People',
    functionType: 'ocUI',
    menuDisplayName: 'Restore People',
    uiType: 'ocPAGEMANAGE',
    param1Desc: 'personID',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'TeamTools',
    functionID: 162,
    functionDesc: 'Team tools app menu item',
    functionType: 'ocUI',
    menuDisplayName: 'Team Tools',
    uiType: 'ocPAGE',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Page GSPPF Dashboard',
    functionID: 163,
    functionDesc: 'PPF Statistics Page Permissions ',
    functionType: 'ocDATA',
    menuDisplayName: 'PPF Dashboard',
    uiType: 'ocUI',
    param1Desc: '',
    param2Desc: '',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'Team Platformreview',
    functionID: 164,
    functionDesc: 'Manage DevTasks derived from cvPLATREVIEW devplans. ',
    functionType: 'ocDATA',
    menuDisplayName: 'Platform Review',
    uiType: 'ocDATA',
    param1Desc: 'rootTaskID',
    param2Desc: 'teamID',
    param3Desc: 'taskID',
    param4Desc: '',
  },
  {
    functionName: 'ClientServiceNote Team',
    functionID: 165,
    functionDesc: 'Manage Client Service Notes in a team context',
    functionType: 'ocDATA',
    param1Desc: 'clientServiceNoteID',
    param2Desc: 'teamID',
    param3Desc: '',
    param4Desc: '',
  },
  {
    functionName: 'EnrollmentWatch',
    functionID: 166,
    functionDesc: 'interface descriptor for course recommendation lists',
    functionType: 'ocUI',
    menuDisplayName: 'Course Recommendations',
    uiType: 'ocPAGE',
    param1Desc: 'enrollmentWatchID',
    param2Desc: 'memberType',
    param3Desc: '',
    param4Desc: '',
  },
] as const
