import { renderHook, waitFor } from '@testing-library/react'
import {
  describe,
  expect,
  it,
  vi,
  afterAll,
  afterEach,
  beforeAll,
} from 'vitest'
import { setupServer } from 'msw/node'
import { rest } from 'msw'
import { PropsWithChildren } from 'react'
import { TYTO_ENDPOINT_PATHS } from '@tyto/client'
import {
  QueryClientProvider,
  TytoClientProvider,
} from '@spacedock/holoprojector'

import { usePersonQuery } from './usePersonQuery'

vi.mock('@spacedock/cargo-bay', () => ({
  SessionHandling: { getActiveSessionKey: () => 'key' },
}))

export const restHandlers = [
  rest.get(
    `http://localhost:4400/api${TYTO_ENDPOINT_PATHS.PERSON}`,
    (req, res, ctx) => {
      return res(
        ctx.status(200),
        ctx.json({
          person: {
            teamMemberships: [
              {
                preferredTeam: 0,
                TeamID: 1698652,
                teamName: 'Cardone Ventures',
                teamDesc: '',
                elementType: 'ocTEAM',
                activeStatus: 'ocENABLED',
                elementSubType: 'ocDOMAIN',
                lvl: 3,
                sn: 231,
                tPath: ',551,1825957,',
                parentID: 1825957,
                direct: true,
                leader: false,
                iscascade: false,
                ParentNamePath: '\tCherry\tCV\t',
                SubDomainParentNamePath: '\t',
                domainID: 1825957,
                createByID: 2048276,
                createdByName: 'Ariel Zilist',
                createdDate: '2023-07-27T23:03:33.083+00:00',
                memberTitle: '',
                teamOutsideID: '',
                teamBoardEMailPreference: 'ocINSTANT',
              },
              {
                preferredTeam: 0,
                TeamID: 1763598,
                teamName: '10X EMPLOYEE',
                teamDesc:
                  'This team is for all team members with the aspiration to become remarkable 10X Employees!',
                elementType: 'ocTEAM',
                activeStatus: 'ocENABLED',
                elementSubType: 'ocTEAM',
                lvl: 5,
                sn: 1747,
                tPath: ',551,1825957,1698652,1738904,',
                parentID: 1738904,
                direct: true,
                leader: false,
                iscascade: false,
                ParentNamePath:
                  '\tCherry\tCV\tCardone Ventures\tCardone Ventures Programs\t',
                SubDomainParentNamePath: '\tCardone Ventures Programs\t',
                domainID: 1698652,
                createByID: 1839518,
                createdByName: 'FIT Solutions',
                createdDate: '2022-03-11T09:45:36.483+00:00',
                memberTitle: '',
                teamOutsideID: '',
                teamBoardEMailPreference: 'ocDISABLED',
              },
              {
                preferredTeam: 0,
                TeamID: 1763597,
                teamName: '10X OWNER',
                teamDesc: '',
                elementType: 'ocTEAM',
                activeStatus: 'ocENABLED',
                elementSubType: 'ocTEAM',
                lvl: 5,
                sn: 1749,
                tPath: ',551,1825957,1698652,1738904,',
                parentID: 1738904,
                direct: true,
                leader: false,
                iscascade: false,
                ParentNamePath:
                  '\tCherry\tCV\tCardone Ventures\tCardone Ventures Programs\t',
                SubDomainParentNamePath: '\tCardone Ventures Programs\t',
                domainID: 1698652,
                createByID: 1839518,
                createdByName: 'FIT Solutions',
                createdDate: '2022-03-11T09:45:34.92+00:00',
                memberTitle: '',
                teamOutsideID: '',
                teamBoardEMailPreference: 'ocDISABLED',
              },
              {
                preferredTeam: 1,
                TeamID: 1763850,
                teamName: 'Cardone Ventures Team',
                teamDesc: '',
                elementType: 'ocTEAM',
                activeStatus: 'ocENABLED',
                elementSubType: 'ocTEAM',
                lvl: 4,
                sn: 1800,
                tPath: ',551,1825957,1698652,',
                parentID: 1698652,
                direct: true,
                leader: false,
                iscascade: false,
                ParentNamePath: '\tCherry\tCV\tCardone Ventures\t',
                SubDomainParentNamePath: '\t',
                domainID: 1698652,
                createByID: 1839518,
                createdByName: 'FIT Solutions',
                createdDate: '2022-03-11T09:43:06.937+00:00',
                memberTitle: '',
                teamOutsideID: '',
                teamBoardEMailPreference: 'ocDISABLED',
              },
            ],
            permissions: [
              {
                functionName: 'Person Demographics',
                businessCardPref: 'birthday',
                fieldName: 'birthdate',
                changeAccess: true,
                viewAccess: true,
                addAccess: true,
                deleteAccess: true,
              },
              {
                functionName: 'Person Demographics',
                businessCardPref: 'photo',
                fieldName: 'profileImageID',
                changeAccess: true,
                viewAccess: true,
                addAccess: true,
                deleteAccess: true,
              },
              {
                functionName: 'Person Demographics',
                businessCardPref: 'jobtitle',
                fieldName: 'jobTitle',
                changeAccess: true,
                viewAccess: true,
                addAccess: true,
                deleteAccess: true,
              },
              {
                functionName: 'Person Demographics',
                businessCardPref: 'website',
                fieldName: 'website',
                changeAccess: true,
                viewAccess: true,
                addAccess: true,
                deleteAccess: true,
              },
              {
                functionName: 'Person Demographics',
                businessCardPref: 'company',
                fieldName: 'company',
                changeAccess: true,
                viewAccess: true,
                addAccess: true,
                deleteAccess: true,
              },
              {
                functionName: 'Person Demographics',
                businessCardPref: '',
                fieldName: 'trainingClass',
                changeAccess: true,
                viewAccess: true,
                addAccess: true,
                deleteAccess: true,
              },
              {
                functionName: 'Person Demographics',
                businessCardPref: '',
                fieldName: 'experience',
                changeAccess: true,
                viewAccess: true,
                addAccess: true,
                deleteAccess: true,
              },
              {
                functionName: 'Person Demographics',
                businessCardPref: '',
                fieldName: 'yearsExperience',
                changeAccess: true,
                viewAccess: true,
                addAccess: true,
                deleteAccess: true,
              },
              {
                functionName: 'Person Demographics',
                businessCardPref: '',
                fieldName: 'jobTitle',
                changeAccess: true,
                viewAccess: true,
                addAccess: true,
                deleteAccess: true,
              },
              {
                functionName: 'Person Demographics',
                businessCardPref: '',
                fieldName: 'industry',
                changeAccess: true,
                viewAccess: true,
                addAccess: true,
                deleteAccess: true,
              },
              {
                functionName: 'Person Address',
                businessCardPref: 'email',
                fieldName: 'email',
                changeAccess: true,
                viewAccess: true,
                addAccess: true,
                deleteAccess: true,
              },
              {
                functionName: 'Person Address',
                businessCardPref: 'street',
                fieldName: 'address1',
                changeAccess: true,
                viewAccess: true,
                addAccess: true,
                deleteAccess: true,
              },
              {
                functionName: 'Person Address',
                businessCardPref: 'street',
                fieldName: 'address2',
                changeAccess: true,
                viewAccess: true,
                addAccess: true,
                deleteAccess: true,
              },
              {
                functionName: 'Person Address',
                businessCardPref: 'location',
                fieldName: 'city',
                changeAccess: true,
                viewAccess: true,
                addAccess: true,
                deleteAccess: true,
              },
              {
                functionName: 'Person Address',
                businessCardPref: 'location',
                fieldName: 'state',
                changeAccess: true,
                viewAccess: true,
                addAccess: true,
                deleteAccess: true,
              },
              {
                functionName: 'Person Address',
                businessCardPref: 'location',
                fieldName: 'country',
                changeAccess: true,
                viewAccess: true,
                addAccess: true,
                deleteAccess: true,
              },
              {
                functionName: 'Person Address',
                businessCardPref: 'location',
                fieldName: 'postalCode',
                changeAccess: true,
                viewAccess: true,
                addAccess: true,
                deleteAccess: true,
              },
              {
                functionName: 'Person Address',
                businessCardPref: 'phone1',
                fieldName: 'phone1',
                changeAccess: true,
                viewAccess: true,
                addAccess: true,
                deleteAccess: true,
              },
              {
                functionName: 'Person Address',
                businessCardPref: 'phone2',
                fieldName: 'phone2',
                changeAccess: true,
                viewAccess: true,
                addAccess: true,
                deleteAccess: true,
              },
              {
                functionName: 'Person Address',
                businessCardPref: '',
                fieldName: 'timeZoneNameGeneral',
                changeAccess: true,
                viewAccess: true,
                addAccess: true,
                deleteAccess: true,
              },
              {
                functionName: 'Person Admin',
                businessCardPref: '',
                fieldName: 'teamRoot',
                changeAccess: true,
                viewAccess: true,
                addAccess: true,
                deleteAccess: true,
              },
              {
                functionName: 'Person Admin',
                businessCardPref: '',
                fieldName: 'roleID',
                changeAccess: true,
                viewAccess: true,
                addAccess: true,
                deleteAccess: true,
              },
              {
                functionName: 'Person Admin',
                businessCardPref: '',
                fieldName: 'outsideType',
                changeAccess: true,
                viewAccess: true,
                addAccess: true,
                deleteAccess: true,
              },
              {
                functionName: 'Person Admin',
                businessCardPref: '',
                fieldName: 'outsideJoinDate',
                changeAccess: true,
                viewAccess: true,
                addAccess: true,
                deleteAccess: true,
              },
              {
                functionName: 'Person Admin',
                businessCardPref: '',
                fieldName: 'outsideTerminateDate',
                changeAccess: true,
                viewAccess: true,
                addAccess: true,
                deleteAccess: true,
              },
              {
                functionName: 'Person Admin',
                businessCardPref: '',
                fieldName: 'outsideModifiedDate',
                changeAccess: true,
                viewAccess: true,
                addAccess: true,
                deleteAccess: true,
              },
              {
                functionName: 'Person Admin',
                businessCardPref: '',
                fieldName: 'outsideActiveStatus',
                changeAccess: true,
                viewAccess: true,
                addAccess: true,
                deleteAccess: true,
              },
              {
                functionName: 'Person Admin',
                businessCardPref: '',
                fieldName: 'outsideRenewalDate',
                changeAccess: true,
                viewAccess: true,
                addAccess: true,
                deleteAccess: true,
              },
              {
                functionName: 'Person Admin',
                businessCardPref: '',
                fieldName: 'outsideID',
                changeAccess: true,
                viewAccess: true,
                addAccess: true,
                deleteAccess: true,
              },
              {
                functionName: 'Person Admin',
                businessCardPref: '',
                fieldName: 'ownerUserID',
                changeAccess: true,
                viewAccess: true,
                addAccess: true,
                deleteAccess: true,
              },
              {
                functionName: 'Person Admin',
                businessCardPref: '',
                fieldName: 'managerID',
                changeAccess: true,
                viewAccess: true,
                addAccess: true,
                deleteAccess: true,
              },
              {
                functionName: 'Person Password',
                businessCardPref: '',
                fieldName: 'changePassword',
                changeAccess: true,
                viewAccess: true,
                addAccess: true,
                deleteAccess: true,
              },
              {
                functionName: 'Person Password',
                businessCardPref: '',
                fieldName: 'passwordExpiresDate',
                changeAccess: true,
                viewAccess: true,
                addAccess: true,
                deleteAccess: true,
              },
              {
                functionName: 'Person Password',
                businessCardPref: '',
                fieldName: 'logonName',
                changeAccess: true,
                viewAccess: true,
                addAccess: true,
                deleteAccess: true,
              },
              {
                functionName: 'People',
                businessCardPref: '',
                fieldName: 'bio',
                changeAccess: true,
                viewAccess: true,
                addAccess: true,
                deleteAccess: true,
              },
              {
                functionName: 'People',
                businessCardPref: '',
                fieldName: 'personal1',
                changeAccess: true,
                viewAccess: true,
                addAccess: true,
                deleteAccess: true,
              },
              {
                functionName: 'People',
                businessCardPref: '',
                fieldName: 'personal2',
                changeAccess: true,
                viewAccess: true,
                addAccess: true,
                deleteAccess: true,
              },
              {
                functionName: 'People',
                businessCardPref: '',
                fieldName: 'personal3',
                changeAccess: true,
                viewAccess: true,
                addAccess: true,
                deleteAccess: true,
              },
              {
                functionName: 'People',
                businessCardPref: '',
                fieldName: 'personal4',
                changeAccess: true,
                viewAccess: true,
                addAccess: true,
                deleteAccess: true,
              },
              {
                functionName: 'People',
                businessCardPref: '',
                fieldName: 'givenName',
                changeAccess: true,
                viewAccess: true,
                addAccess: true,
                deleteAccess: true,
              },
              {
                functionName: 'People',
                businessCardPref: '',
                fieldName: 'familyName',
                changeAccess: true,
                viewAccess: true,
                addAccess: true,
                deleteAccess: true,
              },
              {
                functionName: 'People',
                businessCardPref: '',
                fieldName: 'familiarName',
                changeAccess: true,
                viewAccess: true,
                addAccess: true,
                deleteAccess: true,
              },
              {
                functionName: 'People',
                businessCardPref: '',
                fieldName: 'businessCardPreferences',
                changeAccess: true,
                viewAccess: true,
                addAccess: true,
                deleteAccess: true,
              },
              {
                functionName: 'People',
                businessCardPref: '',
                fieldName: 'emailPreference',
                changeAccess: true,
                viewAccess: true,
                addAccess: true,
                deleteAccess: true,
              },
              {
                functionName: 'People',
                businessCardPref: '',
                fieldName: 'onlinePreference',
                changeAccess: true,
                viewAccess: true,
                addAccess: true,
                deleteAccess: true,
              },
              {
                functionName: 'People',
                businessCardPref: '',
                fieldName: 'emailDigestHourGMTPreference',
                changeAccess: true,
                viewAccess: true,
                addAccess: true,
                deleteAccess: true,
              },
              {
                functionName: 'People',
                businessCardPref: '',
                fieldName: 'emailDigestNoticePreference',
                changeAccess: true,
                viewAccess: true,
                addAccess: true,
                deleteAccess: true,
              },
              {
                functionName: 'People',
                businessCardPref: '',
                fieldName: 'sessionTimeoutMinutesPreference',
                changeAccess: true,
                viewAccess: true,
                addAccess: true,
                deleteAccess: true,
              },
              {
                functionName: 'People',
                businessCardPref: '',
                fieldName: 'createdByID',
                changeAccess: true,
                viewAccess: true,
                addAccess: true,
                deleteAccess: true,
              },
              {
                functionName: 'People',
                businessCardPref: '',
                fieldName: 'modifiedByID',
                changeAccess: true,
                viewAccess: true,
                addAccess: true,
                deleteAccess: true,
              },
              {
                functionName: 'People',
                businessCardPref: '',
                fieldName: 'firstActivityDate',
                changeAccess: true,
                viewAccess: true,
                addAccess: true,
                deleteAccess: true,
              },
              {
                functionName: 'People',
                businessCardPref: '',
                fieldName: 'lastActivityDate',
                changeAccess: true,
                viewAccess: true,
                addAccess: true,
                deleteAccess: true,
              },
              {
                functionName: 'People',
                businessCardPref: '',
                fieldName: 'lastLoginDate',
                changeAccess: true,
                viewAccess: true,
                addAccess: true,
                deleteAccess: true,
              },
              {
                functionName: 'People',
                businessCardPref: '',
                fieldName: 'termsofServiceDate',
                changeAccess: true,
                viewAccess: true,
                addAccess: true,
                deleteAccess: true,
              },
              {
                functionName: 'People',
                businessCardPref: '',
                fieldName: 'department',
                changeAccess: true,
                viewAccess: true,
                addAccess: true,
                deleteAccess: true,
              },
              {
                functionName: 'People',
                businessCardPref: '',
                fieldName: 'domainTraits',
                changeAccess: true,
                viewAccess: true,
                addAccess: true,
                deleteAccess: true,
              },
              {
                functionName: 'People',
                businessCardPref: '',
                fieldName: 'activeStatus',
                changeAccess: true,
                viewAccess: true,
                addAccess: true,
                deleteAccess: true,
              },
              {
                functionName: 'Page Manage RestorePerson',
                businessCardPref: '',
                fieldName: '',
                changeAccess: false,
                viewAccess: false,
                addAccess: false,
                deleteAccess: false,
              },
              {
                functionName: 'Team Membership',
                businessCardPref: '',
                fieldName: '',
                changeAccess: true,
                viewAccess: true,
                addAccess: true,
                deleteAccess: true,
              },
              {
                functionName: 'LibraryFront Person',
                businessCardPref: '',
                fieldName: '',
                changeAccess: true,
                viewAccess: true,
                addAccess: true,
                deleteAccess: true,
              },
              {
                functionName: 'Block Enroll',
                businessCardPref: '',
                fieldName: '',
                changeAccess: true,
                viewAccess: true,
                addAccess: true,
                deleteAccess: true,
              },
              {
                functionName: 'Person Activity',
                businessCardPref: '',
                fieldName: '',
                changeAccess: false,
                viewAccess: true,
                addAccess: false,
                deleteAccess: false,
              },
              {
                functionName: 'DevTasks',
                businessCardPref: '',
                fieldName: '',
                changeAccess: true,
                viewAccess: true,
                addAccess: true,
                deleteAccess: true,
              },
              {
                functionName: 'Impersonate',
                businessCardPref: '',
                fieldName: '',
                changeAccess: true,
                viewAccess: true,
                addAccess: true,
                deleteAccess: true,
              },
              {
                functionName: 'Page Manage',
                businessCardPref: '',
                fieldName: '',
                changeAccess: false,
                viewAccess: true,
                addAccess: false,
                deleteAccess: false,
              },
              {
                functionName: 'Person TraitR3',
                businessCardPref: '',
                fieldName: '',
                changeAccess: true,
                viewAccess: true,
                addAccess: true,
                deleteAccess: true,
              },
              {
                functionName: 'Notices Person',
                businessCardPref: '',
                fieldName: '',
                changeAccess: true,
                viewAccess: true,
                addAccess: true,
                deleteAccess: true,
              },
            ],
            domain: {
              domainName: 'Cardone Ventures',
              domainLabelPersonal1: 'Favorite Activities',
              domainLabelPersonal2: 'Job Skills',
              domainLabelPersonal3: 'Favorite Quotes',
              domainLabelPersonal4: 'Favorite Books',
              domainLoginNameLabel: 'Email',
              domainIsSingleSignOn: false,
              outsideJoinDateLabel: 'Member Since',
            },
            personID: 2048276,
            elementType: 'ocPERSON',
            elementSubType: 'ocITEM',
            activeStatus: 'ocENABLED',
            modifiedDate: '2023-08-15T14:44:48.387+00:00',
            createdDate: '2022-03-11T09:43:06.913+00:00',
            primaryElementID: 1763850,
            domainID: 1698652,
            createdByID: 1839518,
            modifiedByID: 2043811,
            firstActivityDate: '2022-03-15T10:03:04.323+00:00',
            lastActivityDate: '2023-08-23T18:46:16.39+00:00',
            lastLoginDate: '2023-08-23T18:46:11.65+00:00',
            termsofServiceDate: '2022-03-15T10:03:04+00:00',
            givenName: 'Ariel',
            familyName: 'Zilist',
            familiarName: '',
            bio: 'UI/UX Designer focused on human-centered, accessible and delightful designs.',
            personal1: '',
            personal2: '',
            personal3:
              '"Enlightened trial and error succeeds over the planning of a lone genius"',
            personal4: '',
            businessCardPreferences:
              'birthday,company,email,jobtitle,photo,website,',
            emailPreference: 'ocDISABLED',
            onlinePreference: 'ocAVAILABLE',
            emailDigestHourGMTPreference: 2,
            emailDigestNoticePreference: 'ocDISABLED',
            sessionTimeoutMinutesPreference: 120,
            roleID: 432,
            teamRoot: 1763850,
            outsideType: '',
            outsideJoinDate: '1900-01-01T00:00:00+00:00',
            outsideTerminateDate: '1900-01-01T00:00:00+00:00',
            outsideModifiedDate: '1900-01-01T00:00:00+00:00',
            outsideActiveStatus: '',
            outsideRenewalDate: '1900-01-01T00:00:00+00:00',
            outsideID: '',
            ownerUserID: 2050817,
            changePassword: false,
            passwordExpiresDate: '1900-01-01T00:00:00+00:00',
            logonName: 'azilist@cardoneventures.com',
            logonNameBinding: 'email',
            email: 'azilist@cardoneventures.com',
            address1: '',
            address2: '',
            city: 'Chicago',
            state: 'IL',
            country: '',
            postalCode: '60622',
            phone1: '6303032533',
            phone2: '',
            timeZoneNameGeneral: 'US-Central',
            profileImageID: 2050229,
            birthDate: '1904-12-03T00:00:00+00:00',
            website: 'http://arielzilist.myportfolio.com',
            trainingClass: '',
            experience: '',
            yearsExperience: 0,
            jobTitle: 'Jr. UI/UX Designer',
            company: 'Cardone Ventures',
            industry: '',
            urlFacebook: '',
            urlTwitter: '',
            urlLinkedIn: '',
            urlSnapChat: '',
            urlInstagram: '',
            department: '',
            profileImageAssets: [
              {
                assetID: 2050228,
                assetName: 'aZilistProfilePic.png',
                assetDesc: '',
                assetType: 'ocPhoto',
                orientation: 'ocVOID',
                modifiedDate: '2022-03-16T10:12:59.527',
                modifiedByID: 2048276,
                createdDate: '2022-03-16T10:12:59.523',
                createdByID: 2048276,
                createdByName: 'Ariel Zilist',
                sequence: 1,
                softwareRequirements: '',
                originalMD5: '5IQ+rJsywIMAWk7576jT6A==',
                domainID: 1698652,
                encodings: [
                  {
                    encodingType: 'ocDEFAULT',
                    mimeType: 'image/jpeg',
                    modifiedDate: '2022-03-16T10:12:59.527',
                    height: 500,
                    width: 500,
                    length: 0,
                    sizeBytes: 0,
                    techNote: '',
                    activeStatus: 'ocENABLED',
                    pathURL:
                      '/tyto/api/person/profilephoto?assetID=2050228&encoding=ocDEFAULT',
                  },
                  {
                    encodingType: 'ocORIGINAL',
                    mimeType: 'image/png',
                    modifiedDate: '2022-03-16T10:12:59.527',
                    height: 500,
                    width: 500,
                    length: 0,
                    sizeBytes: 246130,
                    techNote: '',
                    activeStatus: 'ocENABLED',
                    pathURL:
                      '/tyto/api/person/profilephoto?assetID=2050228&encoding=ocORIGINAL',
                  },
                  {
                    encodingType: 'ocTHUMBNAIL',
                    mimeType: 'image/jpeg',
                    modifiedDate: '2022-03-16T10:12:59.527',
                    height: 500,
                    width: 500,
                    length: 0,
                    sizeBytes: 0,
                    techNote: '',
                    activeStatus: 'ocENABLED',
                    pathURL:
                      '/v2/domains/1698652/assets/2048276_4cjzhydmtqg_200px.jpg',
                  },
                ],
                courseItemID: 2048276,
              },
              {
                assetID: 2050229,
                assetName: 'Square Profile Pic.jpg',
                assetDesc: '',
                assetType: 'ocPhoto',
                orientation: 'ocVOID',
                modifiedDate: '2022-03-16T10:13:16.72',
                modifiedByID: 2048276,
                createdDate: '2022-03-16T10:13:16.72',
                createdByID: 2048276,
                createdByName: 'Ariel Zilist',
                sequence: 2,
                softwareRequirements: '',
                originalMD5: '8Eju0rX6OI8eAR4pd2PY5w==',
                domainID: 1698652,
                encodings: [
                  {
                    encodingType: 'ocDEFAULT',
                    mimeType: 'image/jpeg',
                    modifiedDate: '2022-03-16T10:13:16.72',
                    height: 500,
                    width: 500,
                    length: 0,
                    sizeBytes: 0,
                    techNote: '',
                    activeStatus: 'ocENABLED',
                    pathURL:
                      '/tyto/api/person/profilephoto?assetID=2050229&encoding=ocDEFAULT',
                  },
                  {
                    encodingType: 'ocORIGINAL',
                    mimeType: 'image/jpeg',
                    modifiedDate: '2022-03-16T10:13:16.72',
                    height: 500,
                    width: 500,
                    length: 0,
                    sizeBytes: 169784,
                    techNote: '',
                    activeStatus: 'ocENABLED',
                    pathURL:
                      '/tyto/api/person/profilephoto?assetID=2050229&encoding=ocORIGINAL',
                  },
                  {
                    encodingType: 'ocTHUMBNAIL',
                    mimeType: 'image/jpeg',
                    modifiedDate: '2022-03-16T10:13:16.72',
                    height: 500,
                    width: 500,
                    length: 0,
                    sizeBytes: 0,
                    techNote: '',
                    activeStatus: 'ocENABLED',
                    pathURL:
                      '/v2/domains/1698652/assets/2048276_nkjdniondpj_200px.jpg',
                  },
                ],
                courseItemID: 2048276,
              },
            ],
            urlYoutube: '',
            otherEmail: [],
            managerID: 0,
            telecom: [
              {
                telecomGUID: '758e3c18-3309-4a30-bfb4-c6a6112db3d0',
                label: 'Ariel Zilist Phone #',
                address: '6303032533',
                modifiedByID: 2048276,
                modifiedDateUTC: '2022-03-16T17:14:25.817+00:00',
                seq: 1,
                hasChange: true,
              },
            ],
          },
          traits: [],
          domainTraits: [],
          session: {
            userID: 2209853,
            userName: 'John Bailey',
            changePassword: false,
            termsOfServiceSignatureRequired: false,
            adminID: 0,
            teamListSyncDate: '1900-01-01T00:00:00+00:00',
            koPermissionSyncDate: '2023-08-23T15:59:42.447+00:00',
            domainID: 1698652,
            timeOutMnts: 2160,
            onCourseURL: 'https://cardoneventuresceo.com',
            profileThumbPath:
              '/v2/domains/1698652/assets/2209853_kvemjhrbf1w_200px.jpg',
            teamRootID: 1763850,
            roleID: 432,
            onlinePreference: 'ocAVAILABLE',
          },
          error: {
            sts: 0,
            msg: 'initialized',
          },
          links: [
            {
              encType: 'application/x-www-form-urlencoded',
              contentType: 'application/json',
              href: '/api/PersonAccount',
              media: '',
              method: 'get',
              targetPref: '',
              title: 'Get Accounts',
              parameters: [],
              rel: ['http://kvau.lt/api/person+accounts'],
            },
            {
              encType: 'application/json',
              contentType: 'application/json',
              href: '/api/Person',
              media: '',
              method: 'put',
              targetPref: '',
              title: 'Update',
              parameters: [
                {
                  paramName: 'sessionKey',
                  paramType: 'string',
                  functionParamMap: 'session.sessionKey',
                },
                {
                  paramName: 'person',
                  paramType: 'object',
                  functionParamMap: 'person',
                },
              ],
              rel: ['http://kvau.lt/api/person+change'],
            },
            {
              encType: '',
              contentType: 'text/html',
              href: 'http://localhost:4200/v25/team_e/team.asp?vdxc=2048276',
              media: '',
              method: 'get',
              targetPref: '',
              title: 'Edit',
              parameters: [],
              rel: ['http://kvau.lt/legacy/v2/ui'],
            },
          ],
        }),
      )
    },
  ),
]

const server = setupServer(...restHandlers)

describe('usePersonQuery', () => {
  // Start server before all tests
  beforeAll(() => server.listen({ onUnhandledRequest: 'error' }))

  //  Close server after all tests
  afterAll(() => server.close())

  // Reset handlers after each test `important for test isolation`
  afterEach(() => server.resetHandlers())
  it('returns data', async () => {
    const wrapper = ({ children }: PropsWithChildren) => (
      <TytoClientProvider>
        <QueryClientProvider>{children}</QueryClientProvider>
      </TytoClientProvider>
    )
    const { result } = renderHook(
      () => usePersonQuery({ params: { personID: 1 }, enabled: true }),
      {
        wrapper,
      },
    )

    //
    await waitFor(() => expect(result.current.isPending).toEqual(false))
    expect(result.current.data).toHaveProperty('person')
  })
})
