import React from 'react'
import type { Meta, StoryObj } from '@storybook/react'

import { BAAllEvents } from './BAAllEvents'

const meta: Meta<typeof BAAllEvents> = {
  title: 'Domain Ui/Organisms/BA All Events',
  component: BAAllEvents,
  tags: ['autodocs'],
}

export default meta
type Story = StoryObj<typeof BAAllEvents>

export const Default: Story = {
  parameters: {
    docs: {
      description: {
        story: '',
      },
    },
    design: {
      type: 'figma',
      url: 'REPLACE WITH FIGMA LINK or REMOVE',
    },
  },
  render: ({ ...props }) => (
    <BAAllEvents
      {...props}
      webcasts={{}}
      events={[
        {
          id: 'f40f98a1-1d3d-4a00-bff0-24bd26516b3e',
          title: "Austin's Test Event #1",
          code: '6LN3STDLWLY',
          virtual: true,
          description: '',
          format: 'Virtual',
          start: '2024-10-25T15:00:00.000Z',
          end: '2024-10-25T16:30:00.000Z',
          closeAfter: '2024-10-25T16:29:00.000Z',
          archiveAfter: '2025-01-23T17:30:00.000Z',
          launchAfter: '1900-01-01T05:00:00.000Z',
          timezone: 'America/New_York',
          defaultLocale: 'en-US',
          languages: ['en-US'],
          currency: 'USD',
          registrationSecurityLevel: 'Public',
          status: 'NoRegistrationRequired',
          eventStatus: 'Completed',
          testMode: false,
          planners: [
            {
              firstName: 'Austin',
              lastName: 'Blain',
              email: 'htelecsan@cardoneventures.com',
              deleted: true,
            },
          ],
          customFields: [
            {
              id: '2b7f6269-4d33-4b40-959a-a39c07d76697',
              name: 'Live Call Category',
              type: 'SingleSelect',
              value: ['Sales'],
              order: 1,
            },
            {
              id: '33c880f9-13af-4d4f-9795-fb27d9099185',
              name: 'Live Call Type',
              type: 'SingleSelect',
              value: ['Sales Coaching'],
              order: 2,
            },
          ],
          category: {
            name: 'Webinar',
          },
          type: 'Webinar',
          _links: {
            invitation: {
              href: 'https://www.cvent.com/d/p2qlqf/1Q',
            },
            agenda: {
              href: 'https://www.cvent.com/d/p2qlqf/6X',
            },
            summary: {
              href: 'https://www.cvent.com/d/p2qlqf',
            },
            registration: {
              href: 'https://www.cvent.com/d/p2qlqf/4W',
            },
          },
          created: '2024-10-24T19:37:56.957Z',
          lastModified: '2024-10-24T19:38:06.409Z',
          createdBy: 'Austin@tryyb.com',
          lastModifiedBy: 'Austin@tryyb.com',
          registration: null,
        },
        {
          id: '84ea50fc-0c2c-43ad-85f7-32d659b395b1',
          title: 'DEV Test',
          code: 'M7NVNZK8Z5Y',
          virtual: true,
          format: 'Virtual',
          description: '',
          start: '2024-11-08T23:00:00.000Z',
          end: '2024-11-09T00:00:00.000Z',
          closeAfter: '2024-11-08T23:59:00.000Z',
          archiveAfter: '2025-02-07T00:00:00.000Z',
          launchAfter: '1900-01-01T05:00:00.000Z',
          timezone: 'America/Phoenix',
          defaultLocale: 'en-US',
          languages: ['en-US'],
          currency: 'USD',
          registrationSecurityLevel: 'Public',
          status: 'Pending',
          eventStatus: 'Upcoming',
          testMode: true,
          planners: [
            {
              firstName: 'Max',
              lastName: 'Black',
              email: '10XBusinessAcademy@cardoneventures.com',
              deleted: true,
            },
          ],
          customFields: [
            {
              id: '2b7f6269-4d33-4b40-959a-a39c07d76697',
              name: 'Live Call Category',
              type: 'SingleSelect',
              value: ['Marketing'],
              order: 1,
            },
            {
              id: '33c880f9-13af-4d4f-9795-fb27d9099185',
              name: 'Live Call Type',
              type: 'SingleSelect',
              value: ['Training'],
              order: 2,
            },
          ],
          category: {
            name: 'Training Session',
          },
          type: 'TrainingSession',
          _links: {
            invitation: {
              href: 'https://www.cvent.com/d/k2q72l/1Q',
            },
            agenda: {
              href: 'https://www.cvent.com/d/k2q72l/6X',
            },
            summary: {
              href: 'https://www.cvent.com/d/k2q72l',
            },
            registration: {
              href: 'https://www.cvent.com/d/k2q72l/4W',
            },
          },
          created: '2024-10-02T21:43:46.320Z',
          lastModified: '2024-10-02T21:44:00.086Z',
          createdBy: 'Mblack@cardoneventures.com',
          lastModifiedBy: 'Mblack@cardoneventures.com',
          registration: null,
        },
        {
          id: 'bbee7f78-bb81-4964-abbd-1acf15c8a214',
          title: 'DEV Test #2',
          code: 'VCNVM2RQ7L6',
          virtual: true,
          format: 'Virtual',
          description: '',
          start: '2024-12-06T23:00:00.000Z',
          end: '2024-12-07T00:00:00.000Z',
          closeAfter: '2024-12-06T23:59:00.000Z',
          archiveAfter: '2025-03-07T00:00:00.000Z',
          launchAfter: '1900-01-01T05:00:00.000Z',
          timezone: 'America/Phoenix',
          defaultLocale: 'en-US',
          languages: ['en-US'],
          currency: 'USD',
          registrationSecurityLevel: 'Public',
          status: 'Pending',
          eventStatus: 'Upcoming',
          testMode: true,
          planners: [
            {
              firstName: 'Max',
              lastName: 'Black',
              email: '10XBusinessAcademy@cardoneventures.com',
              deleted: true,
            },
          ],
          customFields: [
            {
              id: '2b7f6269-4d33-4b40-959a-a39c07d76697',
              name: 'Live Call Category',
              type: 'SingleSelect',
              value: ['Marketing'],
              order: 1,
            },
            {
              id: '33c880f9-13af-4d4f-9795-fb27d9099185',
              name: 'Live Call Type',
              type: 'SingleSelect',
              value: ['Training'],
              order: 2,
            },
          ],
          category: {
            name: 'Training Session',
          },
          type: 'TrainingSession',
          _links: {
            invitation: {
              href: 'https://www.cvent.com/d/l2q720/1Q',
            },
            agenda: {
              href: 'https://www.cvent.com/d/l2q720/6X',
            },
            summary: {
              href: 'https://www.cvent.com/d/l2q720',
            },
            registration: {
              href: 'https://www.cvent.com/d/l2q720/4W',
            },
          },
          created: '2024-10-02T21:45:37.623Z',
          lastModified: '2024-10-02T21:45:46.653Z',
          createdBy: 'Mblack@cardoneventures.com',
          lastModifiedBy: 'Mblack@cardoneventures.com',
          registration: null,
        },
        {
          id: 'cc383ae5-deac-4862-83d7-a44ca8d004a7',
          title: 'Template - HR Live Call',
          code: 'TTNFQ75GY9L',
          virtual: true,
          description: '',
          format: 'Virtual',
          start: '2024-12-15T20:00:00.000Z',
          end: '2024-12-15T21:00:00.000Z',
          closeAfter: '2024-12-15T20:59:00.000Z',
          archiveAfter: '2025-03-15T21:00:00.000Z',
          launchAfter: '1900-01-01T05:00:00.000Z',
          timezone: 'America/Phoenix',
          defaultLocale: 'en-US',
          languages: ['en-US'],
          currency: 'USD',
          registrationSecurityLevel: 'Public',
          status: 'Pending',
          eventStatus: 'Upcoming',
          testMode: true,
          planners: [
            {
              firstName: '10X',
              lastName: 'Business Acadamey',
              email: '10XBusinessAcademy@cardoneventures.com',
              deleted: true,
            },
          ],
          customFields: [
            {
              id: '2b7f6269-4d33-4b40-959a-a39c07d76697',
              name: 'Live Call Category',
              type: 'SingleSelect',
              value: ['Marketing'],
              order: 1,
            },
            {
              id: '33c880f9-13af-4d4f-9795-fb27d9099185',
              name: 'Live Call Type',
              type: 'SingleSelect',
              value: ['Training'],
              order: 2,
            },
            {
              id: '87b2e6a5-4131-4f7e-894f-302b89f30ef0',
              name: 'Integrate with HubSpot',
              type: 'SingleSelect',
              value: ['Yes'],
              order: 3,
            },
            {
              id: '740422ff-6870-472c-aa39-696e0b111bbc',
              name: 'HubSpot Invited List ID',
              type: 'FreeText',
              value: ['12949'],
              order: 4,
            },
            {
              id: '6a9399e5-3ce9-4e99-8972-1e92045ff286',
              name: 'HubSpot Registered List ID',
              type: 'FreeText',
              value: ['12950'],
              order: 5,
            },
            {
              id: '39f8bb93-623f-4d62-ad6a-d7a33740e2ef',
              name: 'HubSpot Cancelled List ID',
              type: 'FreeText',
              value: ['12951'],
              order: 6,
            },
            {
              id: 'b5b14f29-b563-4bea-9382-b1222be3eedd',
              name: 'HubSpot Attended List ID',
              type: 'FreeText',
              value: ['12952'],
              order: 7,
            },
            {
              id: 'b4687398-a2e3-4ba7-9a7c-4d682a39ea16',
              name: 'Zoom Integration Type',
              type: 'SingleSelect',
              value: ['Meeting'],
              order: 9,
            },
            {
              id: 'b5df9ced-171e-4299-8ca3-c3891b4c9c2f',
              name: 'Participation Minimum Duration',
              type: 'FreeText',
              value: ['45'],
              order: 10,
            },
            {
              id: '717b5093-fb09-4da7-b8b9-899fbccaed66',
              name: 'Zoom Meeting/Webinar Alternate Host',
              type: 'FreeText',
              value: [
                'mblack@cardoneventures.com; jcunningham@cardoneventures.com',
              ],
              order: 11,
            },
            {
              id: '5f3e48de-3220-42ca-9706-84a43eae895e',
              name: 'Zoom Meeting/Webinar Host',
              type: 'FreeText',
              value: ['jlingo@cardoneventures.com'],
              order: 14,
            },
          ],
          category: {
            name: 'Webinar',
          },
          type: 'Webinar',
          _links: {
            invitation: {
              href: 'https://www.cvent.com/d/62qkct/1Q',
            },
            agenda: {
              href: 'https://www.cvent.com/d/62qkct/6X',
            },
            summary: {
              href: 'https://www.cvent.com/d/62qkct',
            },
            registration: {
              href: 'https://www.cvent.com/d/62qkct/4W',
            },
          },
          created: '2024-10-16T21:05:59.413Z',
          lastModified: '2024-10-16T21:06:16.722Z',
          createdBy: 'Mblack@cardoneventures.com',
          lastModifiedBy: 'Mblack@cardoneventures.com',
          registration: null,
        },
        {
          id: 'f30da217-043f-4cec-a3ee-5ed1073060a8',
          title: 'Alison Test',
          code: 'B2NBNZF35QJ',
          virtual: false,
          format: 'In-person',
          start: '2024-12-16T23:00:00.000Z',
          end: '2024-12-17T00:00:00.000Z',
          closeAfter: '2024-12-16T23:59:00.000Z',
          archiveAfter: '2025-03-17T00:00:00.000Z',
          launchAfter: '1900-01-01T05:00:00.000Z',
          timezone: 'America/Phoenix',
          defaultLocale: 'en-US',
          languages: ['en-US'],
          currency: 'USD',
          registrationSecurityLevel: 'Public',
          status: 'Pending',
          eventStatus: 'Upcoming',
          testMode: true,
          description: '',
          planners: [
            {
              firstName: 'Max',
              lastName: 'Black',
              email: '10XBusinessAcademy@cardoneventures.com',
              deleted: true,
            },
          ],
          customFields: [
            {
              id: '2b7f6269-4d33-4b40-959a-a39c07d76697',
              name: 'Live Call Category',
              type: 'SingleSelect',
              value: ['Marketing'],
              order: 1,
            },
            {
              id: '33c880f9-13af-4d4f-9795-fb27d9099185',
              name: 'Live Call Type',
              type: 'SingleSelect',
              value: ['Training'],
              order: 2,
            },
            {
              id: '87b2e6a5-4131-4f7e-894f-302b89f30ef0',
              name: 'Integrate with HubSpot',
              type: 'SingleSelect',
              value: ['Yes'],
              order: 3,
            },
            {
              id: '740422ff-6870-472c-aa39-696e0b111bbc',
              name: 'HubSpot Invited List ID',
              type: 'FreeText',
              value: ['12867'],
              order: 4,
            },
            {
              id: '6a9399e5-3ce9-4e99-8972-1e92045ff286',
              name: 'HubSpot Registered List ID',
              type: 'FreeText',
              value: ['12868'],
              order: 5,
            },
            {
              id: '39f8bb93-623f-4d62-ad6a-d7a33740e2ef',
              name: 'HubSpot Cancelled List ID',
              type: 'FreeText',
              value: ['12869'],
              order: 6,
            },
            {
              id: 'b5b14f29-b563-4bea-9382-b1222be3eedd',
              name: 'HubSpot Attended List ID',
              type: 'FreeText',
              value: ['12870'],
              order: 7,
            },
            {
              id: 'b4687398-a2e3-4ba7-9a7c-4d682a39ea16',
              name: 'Zoom Integration Type',
              type: 'SingleSelect',
              value: ['Meeting'],
              order: 9,
            },
            {
              id: 'b5df9ced-171e-4299-8ca3-c3891b4c9c2f',
              name: 'Participation Minimum Duration',
              type: 'FreeText',
              value: ['45'],
              order: 10,
            },
            {
              id: '717b5093-fb09-4da7-b8b9-899fbccaed66',
              name: 'Zoom Meeting/Webinar Alternate Host',
              type: 'FreeText',
              value: ['mblack@cardoneventures.com'],
              order: 11,
            },
            {
              id: '5f3e48de-3220-42ca-9706-84a43eae895e',
              name: 'Zoom Meeting/Webinar Host',
              type: 'FreeText',
              value: ['mblack@cardoneventures.com'],
              order: 14,
            },
          ],
          category: {
            name: 'Training Session',
          },
          type: 'TrainingSession',
          _links: {
            invitation: {
              href: 'https://www.cvent.com/d/62qk77/1Q',
            },
            agenda: {
              href: 'https://www.cvent.com/d/62qk77/6X',
            },
            summary: {
              href: 'https://www.cvent.com/d/62qk77',
            },
            registration: {
              href: 'https://www.cvent.com/d/62qk77/4W',
            },
          },
          created: '2024-10-17T21:57:15.727Z',
          lastModified: '2024-10-17T21:57:28.711Z',
          createdBy: '(Cvent - AMueller) Mblack@cardoneventures.com',
          lastModifiedBy: '(Cvent - AMueller) Mblack@cardoneventures.com',
          registration: null,
        },
        {
          id: 'fb9718a9-c1b6-4c3b-83f9-e86e5050e650',
          title: 'Alison Test 2 - create event wizard',
          code: '9XNYL4FM65W',
          virtual: false,
          description: '',
          format: 'In-person',
          start: '2024-12-16T23:00:00.000Z',
          end: '2024-12-17T00:00:00.000Z',
          closeAfter: '2024-12-16T23:59:00.000Z',
          archiveAfter: '2025-03-17T00:00:00.000Z',
          launchAfter: '1900-01-01T05:00:00.000Z',
          timezone: 'America/Phoenix',
          defaultLocale: 'en-US',
          languages: ['en-US'],
          currency: 'USD',
          registrationSecurityLevel: 'Public',
          status: 'Pending',
          eventStatus: 'Upcoming',
          testMode: true,
          planners: [
            {
              firstName: 'Max',
              lastName: 'Black',
              email: '10XBusinessAcademy@cardoneventures.com',
              deleted: true,
            },
          ],
          customFields: [
            {
              id: '2b7f6269-4d33-4b40-959a-a39c07d76697',
              name: 'Live Call Category',
              type: 'SingleSelect',
              value: ['Marketing'],
              order: 1,
            },
            {
              id: '33c880f9-13af-4d4f-9795-fb27d9099185',
              name: 'Live Call Type',
              type: 'SingleSelect',
              value: ['Training'],
              order: 2,
            },
            {
              id: '87b2e6a5-4131-4f7e-894f-302b89f30ef0',
              name: 'Integrate with HubSpot',
              type: 'SingleSelect',
              value: ['Yes'],
              order: 3,
            },
            {
              id: '740422ff-6870-472c-aa39-696e0b111bbc',
              name: 'HubSpot Invited List ID',
              type: 'FreeText',
              value: ['12867'],
              order: 4,
            },
            {
              id: '6a9399e5-3ce9-4e99-8972-1e92045ff286',
              name: 'HubSpot Registered List ID',
              type: 'FreeText',
              value: ['12868'],
              order: 5,
            },
            {
              id: '39f8bb93-623f-4d62-ad6a-d7a33740e2ef',
              name: 'HubSpot Cancelled List ID',
              type: 'FreeText',
              value: ['12869'],
              order: 6,
            },
            {
              id: 'b5b14f29-b563-4bea-9382-b1222be3eedd',
              name: 'HubSpot Attended List ID',
              type: 'FreeText',
              value: ['12870'],
              order: 7,
            },
            {
              id: 'b4687398-a2e3-4ba7-9a7c-4d682a39ea16',
              name: 'Zoom Integration Type',
              type: 'SingleSelect',
              value: ['Meeting'],
              order: 9,
            },
            {
              id: 'b5df9ced-171e-4299-8ca3-c3891b4c9c2f',
              name: 'Participation Minimum Duration',
              type: 'FreeText',
              value: ['45'],
              order: 10,
            },
            {
              id: '717b5093-fb09-4da7-b8b9-899fbccaed66',
              name: 'Zoom Meeting/Webinar Alternate Host',
              type: 'FreeText',
              value: ['mblack@cardoneventures.com'],
              order: 11,
            },
            {
              id: '5f3e48de-3220-42ca-9706-84a43eae895e',
              name: 'Zoom Meeting/Webinar Host',
              type: 'FreeText',
              value: ['mblack@cardoneventures.com'],
              order: 14,
            },
          ],
          category: {
            name: 'Training Session',
          },
          type: 'TrainingSession',
          _links: {
            invitation: {
              href: 'https://www.cvent.com/d/w2qk7j/1Q',
            },
            agenda: {
              href: 'https://www.cvent.com/d/w2qk7j/6X',
            },
            summary: {
              href: 'https://www.cvent.com/d/w2qk7j',
            },
            registration: {
              href: 'https://www.cvent.com/d/w2qk7j/4W',
            },
          },
          created: '2024-10-17T21:59:52.130Z',
          lastModified: '2024-10-17T22:00:07.398Z',
          createdBy: '(Cvent - AMueller) Mblack@cardoneventures.com',
          lastModifiedBy: '(Cvent - AMueller) Mblack@cardoneventures.com',
          registration: null,
        },
        {
          id: 'c556fec1-31d4-40e2-8ca0-757a51e62193',
          title: 'Template - Operations Live Call',
          code: 'KPN4RRX6LS9',
          description: '',
          virtual: true,
          format: 'Virtual',
          start: '2024-12-21T22:00:00.000Z',
          end: '2024-12-21T23:00:00.000Z',
          closeAfter: '2024-12-21T22:59:00.000Z',
          archiveAfter: '2025-03-21T23:00:00.000Z',
          launchAfter: '1900-01-01T05:00:00.000Z',
          timezone: 'America/Phoenix',
          defaultLocale: 'en-US',
          languages: ['en-US'],
          currency: 'USD',
          registrationSecurityLevel: 'Public',
          status: 'Pending',
          eventStatus: 'Upcoming',
          testMode: true,
          planners: [
            {
              firstName: '10X',
              lastName: 'Business Acadamey',
              email: '10XBusinessAcademy@cardoneventures.com',
              deleted: true,
            },
          ],
          customFields: [
            {
              id: '2b7f6269-4d33-4b40-959a-a39c07d76697',
              name: 'Live Call Category',
              type: 'SingleSelect',
              value: ['Finance'],
              order: 1,
            },
            {
              id: '33c880f9-13af-4d4f-9795-fb27d9099185',
              name: 'Live Call Type',
              type: 'SingleSelect',
              value: ['Training'],
              order: 2,
            },
            {
              id: '87b2e6a5-4131-4f7e-894f-302b89f30ef0',
              name: 'Integrate with HubSpot',
              type: 'SingleSelect',
              value: ['Yes'],
              order: 3,
            },
            {
              id: '740422ff-6870-472c-aa39-696e0b111bbc',
              name: 'HubSpot Invited List ID',
              type: 'FreeText',
              value: ['12949'],
              order: 4,
            },
            {
              id: '6a9399e5-3ce9-4e99-8972-1e92045ff286',
              name: 'HubSpot Registered List ID',
              type: 'FreeText',
              value: ['12950'],
              order: 5,
            },
            {
              id: '39f8bb93-623f-4d62-ad6a-d7a33740e2ef',
              name: 'HubSpot Cancelled List ID',
              type: 'FreeText',
              value: ['12951'],
              order: 6,
            },
            {
              id: 'b5b14f29-b563-4bea-9382-b1222be3eedd',
              name: 'HubSpot Attended List ID',
              type: 'FreeText',
              value: ['12952'],
              order: 7,
            },
            {
              id: 'b4687398-a2e3-4ba7-9a7c-4d682a39ea16',
              name: 'Zoom Integration Type',
              type: 'SingleSelect',
              value: ['Meeting'],
              order: 9,
            },
            {
              id: 'b5df9ced-171e-4299-8ca3-c3891b4c9c2f',
              name: 'Participation Minimum Duration',
              type: 'FreeText',
              value: ['45'],
              order: 10,
            },
            {
              id: '717b5093-fb09-4da7-b8b9-899fbccaed66',
              name: 'Zoom Meeting/Webinar Alternate Host',
              type: 'FreeText',
              value: ['jlingo@cardoneventures.com, mblack@cardoneventures.com'],
              order: 11,
            },
            {
              id: '5f3e48de-3220-42ca-9706-84a43eae895e',
              name: 'Zoom Meeting/Webinar Host',
              type: 'FreeText',
              value: ['10xbusinessacademy@cardoneventures.com'],
              order: 14,
            },
          ],
          category: {
            name: 'Webinar',
          },
          type: 'Webinar',
          _links: {
            invitation: {
              href: 'https://www.cvent.com/d/72ql4r/1Q',
            },
            agenda: {
              href: 'https://www.cvent.com/d/72ql4r/6X',
            },
            summary: {
              href: 'https://www.cvent.com/d/72ql4r',
            },
            registration: {
              href: 'https://www.cvent.com/d/72ql4r/4W',
            },
          },
          created: '2024-10-23T00:04:19.773Z',
          lastModified: '2024-10-23T00:04:34.225Z',
          createdBy: 'Mblack@cardoneventures.com',
          lastModifiedBy: 'Mblack@cardoneventures.com',
          registration: null,
        },
        {
          id: 'f15f6094-e00d-4dfa-a541-652b40b33b2e',
          title: 'Template - Live Call',
          code: 'JJNGQFXKZW6',
          virtual: true,
          format: 'Virtual',
          description: '',
          start: '2024-12-22T20:00:00.000Z',
          end: '2024-12-22T21:00:00.000Z',
          closeAfter: '2024-12-22T20:59:00.000Z',
          archiveAfter: '2025-03-22T21:00:00.000Z',
          launchAfter: '1900-01-01T05:00:00.000Z',
          timezone: 'America/Phoenix',
          defaultLocale: 'en-US',
          languages: ['en-US'],
          currency: 'USD',
          registrationSecurityLevel: 'Public',
          status: 'Pending',
          eventStatus: 'Upcoming',
          testMode: true,
          planners: [
            {
              firstName: '10X',
              lastName: 'Business Acadamey',
              email: 'htelecsan@cardoneventures.com',
              deleted: true,
            },
          ],
          customFields: [
            {
              id: '2b7f6269-4d33-4b40-959a-a39c07d76697',
              name: 'Live Call Category',
              type: 'SingleSelect',
              value: ['Sales'],
              order: 1,
            },
            {
              id: '33c880f9-13af-4d4f-9795-fb27d9099185',
              name: 'Live Call Type',
              type: 'SingleSelect',
              value: ['Training'],
              order: 2,
            },
            {
              id: '87b2e6a5-4131-4f7e-894f-302b89f30ef0',
              name: 'Integrate with HubSpot',
              type: 'SingleSelect',
              value: ['Yes'],
              order: 3,
            },
            {
              id: '740422ff-6870-472c-aa39-696e0b111bbc',
              name: 'HubSpot Invited List ID',
              type: 'FreeText',
              value: ['12949'],
              order: 4,
            },
            {
              id: '6a9399e5-3ce9-4e99-8972-1e92045ff286',
              name: 'HubSpot Registered List ID',
              type: 'FreeText',
              value: ['12950'],
              order: 5,
            },
            {
              id: '39f8bb93-623f-4d62-ad6a-d7a33740e2ef',
              name: 'HubSpot Cancelled List ID',
              type: 'FreeText',
              value: ['12951'],
              order: 6,
            },
            {
              id: 'b5b14f29-b563-4bea-9382-b1222be3eedd',
              name: 'HubSpot Attended List ID',
              type: 'FreeText',
              value: ['12952'],
              order: 7,
            },
            {
              id: 'b4687398-a2e3-4ba7-9a7c-4d682a39ea16',
              name: 'Zoom Integration Type',
              type: 'SingleSelect',
              value: ['Meeting'],
              order: 9,
            },
            {
              id: 'b5df9ced-171e-4299-8ca3-c3891b4c9c2f',
              name: 'Participation Minimum Duration',
              type: 'FreeText',
              value: ['45'],
              order: 10,
            },
            {
              id: '717b5093-fb09-4da7-b8b9-899fbccaed66',
              name: 'Zoom Meeting/Webinar Alternate Host',
              type: 'FreeText',
              value: ['jlingo@cardoneventures.com'],
              order: 11,
            },
            {
              id: '5f3e48de-3220-42ca-9706-84a43eae895e',
              name: 'Zoom Meeting/Webinar Host',
              type: 'FreeText',
              value: ['10xbusinessacademy@cardoneventures.com'],
              order: 14,
            },
          ],
          category: {
            name: 'Webinar',
          },
          type: 'Webinar',
          _links: {
            invitation: {
              href: 'https://www.cvent.com/d/42ql71/1Q',
            },
            agenda: {
              href: 'https://www.cvent.com/d/42ql71/6X',
            },
            summary: {
              href: 'https://www.cvent.com/d/42ql71',
            },
            registration: {
              href: 'https://www.cvent.com/d/42ql71/4W',
            },
          },
          created: '2024-10-23T22:44:48.223Z',
          lastModified: '2024-10-23T22:45:01.745Z',
          createdBy: 'jlingo@cardoneventures.com',
          lastModifiedBy: 'jlingo@cardoneventures.com',
          registration: null,
        },
        {
          id: '1cf2d5e6-a09b-4cf6-83f9-c34c10591afa',
          title: "Austin's Test Event #2",
          code: '6DNG5S33V55',
          virtual: true,
          format: 'Virtual',
          description: '',
          start: '2024-12-23T16:45:00.000Z',
          end: '2024-12-23T18:15:00.000Z',
          closeAfter: '2024-12-23T18:14:00.000Z',
          archiveAfter: '2025-03-23T17:15:00.000Z',
          launchAfter: '1900-01-01T05:00:00.000Z',
          timezone: 'America/New_York',
          defaultLocale: 'en-US',
          languages: ['en-US'],
          currency: 'USD',
          registrationSecurityLevel: 'Public',
          status: 'NoRegistrationRequired',
          eventStatus: 'Upcoming',
          testMode: false,
          planners: [
            {
              firstName: 'Austin',
              lastName: 'Blain',
              email: 'htelecsan@cardoneventures.com',
              deleted: true,
            },
          ],
          customFields: [
            {
              id: '2b7f6269-4d33-4b40-959a-a39c07d76697',
              name: 'Live Call Category',
              type: 'SingleSelect',
              value: ['Marketing'],
              order: 1,
            },
            {
              id: '33c880f9-13af-4d4f-9795-fb27d9099185',
              name: 'Live Call Type',
              type: 'SingleSelect',
              value: ['Training'],
              order: 2,
            },
          ],
          category: {
            name: 'Webinar',
          },
          type: 'Webinar',
          _links: {
            invitation: {
              href: 'https://www.cvent.com/d/t2qlqf/1Q',
            },
            agenda: {
              href: 'https://www.cvent.com/d/t2qlqf/6X',
            },
            summary: {
              href: 'https://www.cvent.com/d/t2qlqf',
            },
            registration: {
              href: 'https://www.cvent.com/d/t2qlqf/4W',
            },
          },
          created: '2024-10-24T19:39:07.803Z',
          lastModified: '2024-10-24T19:39:17.880Z',
          createdBy: 'Austin@tryyb.com',
          lastModifiedBy: 'Austin@tryyb.com',
          registration: null,
        },
        {
          id: '84007cf4-e68a-41d5-b908-b40e811f0b1c',
          title: "Johann's Test Event #1",
          code: '8VNRSH9Q3ZR',
          virtual: true,
          description: '',
          format: 'Virtual',
          start: '2024-12-24T00:00:00.000Z',
          end: '2024-12-24T01:00:00.000Z',
          closeAfter: '2024-12-24T00:59:00.000Z',
          archiveAfter: '2025-03-24T00:00:00.000Z',
          launchAfter: '1900-01-01T05:00:00.000Z',
          timezone: 'America/Los_Angeles',
          defaultLocale: 'en-US',
          languages: ['en-US'],
          currency: 'USD',
          registrationSecurityLevel: 'Public',
          status: 'NoRegistrationRequired',
          eventStatus: 'Upcoming',
          testMode: false,
          planners: [
            {
              firstName: 'Austin',
              lastName: 'Blain',
              email: 'htelecsan@cardoneventures.com',
              deleted: true,
            },
          ],
          customFields: [
            {
              id: '2b7f6269-4d33-4b40-959a-a39c07d76697',
              name: 'Live Call Category',
              type: 'SingleSelect',
              value: ['Operations'],
              order: 1,
            },
            {
              id: '33c880f9-13af-4d4f-9795-fb27d9099185',
              name: 'Live Call Type',
              type: 'SingleSelect',
              value: ['Training'],
              order: 2,
            },
          ],
          category: {
            name: 'Webinar',
          },
          type: 'Webinar',
          _links: {
            invitation: {
              href: 'https://www.cvent.com/d/q2qlqr/1Q',
            },
            agenda: {
              href: 'https://www.cvent.com/d/q2qlqr/6X',
            },
            summary: {
              href: 'https://www.cvent.com/d/q2qlqr',
            },
            registration: {
              href: 'https://www.cvent.com/d/q2qlqr/4W',
            },
          },
          created: '2024-10-24T19:34:46.237Z',
          lastModified: '2024-10-24T19:34:58.176Z',
          createdBy: 'Austin@tryyb.com',
          lastModifiedBy: 'Austin@tryyb.com',
          registration: null,
        },
        {
          id: 'bb57ffbe-6208-43fe-982b-071801ce1851',
          title: "Johann's Test Event #2",
          code: 'RWNBXKYTQBX',
          virtual: true,
          format: 'Virtual',
          description: '',
          start: '2024-12-24T01:00:00.000Z',
          end: '2024-12-24T01:30:00.000Z',
          closeAfter: '2024-12-24T01:29:00.000Z',
          archiveAfter: '2025-03-24T00:30:00.000Z',
          launchAfter: '1900-01-01T05:00:00.000Z',
          timezone: 'America/Los_Angeles',
          defaultLocale: 'en-US',
          languages: ['en-US'],
          currency: 'USD',
          registrationSecurityLevel: 'Public',
          status: 'NoRegistrationRequired',
          eventStatus: 'Upcoming',
          testMode: false,
          planners: [
            {
              firstName: 'Austin',
              lastName: 'Blain',
              email: 'htelecsan@cardoneventures.com',
              deleted: true,
            },
          ],
          customFields: [
            {
              id: '2b7f6269-4d33-4b40-959a-a39c07d76697',
              name: 'Live Call Category',
              type: 'SingleSelect',
              value: ['Operations'],
              order: 1,
            },
            {
              id: '33c880f9-13af-4d4f-9795-fb27d9099185',
              name: 'Live Call Type',
              type: 'SingleSelect',
              value: ['Training'],
              order: 2,
            },
          ],
          category: {
            name: 'Webinar',
          },
          type: 'Webinar',
          _links: {
            invitation: {
              href: 'https://www.cvent.com/d/g2qlqr/1Q',
            },
            agenda: {
              href: 'https://www.cvent.com/d/g2qlqr/6X',
            },
            summary: {
              href: 'https://www.cvent.com/d/g2qlqr',
            },
            registration: {
              href: 'https://www.cvent.com/d/g2qlqr/4W',
            },
          },
          created: '2024-10-24T19:36:17.327Z',
          lastModified: '2024-10-24T19:36:29.310Z',
          createdBy: 'Austin@tryyb.com',
          lastModifiedBy: 'Austin@tryyb.com',
          registration: null,
        },
      ]}
    />
  ),
}
