const BANNER_IMAGE_WIDTH = 1980
const BANNER_IMAGE_HEIGHT = 596

const TILE_IMAGE_WIDTH = 306
const TILE_IMAGE_HEIGHT = 144

// * ===============================
// * IMAGE CROP OPTIONS ============
// * ===============================
export const COURSE_TILE_IMAGE_DIMENSIONS = {
  width: TILE_IMAGE_WIDTH,
  height: TILE_IMAGE_HEIGHT,
  aspectRatio: TILE_IMAGE_WIDTH / TILE_IMAGE_HEIGHT,
} as const

export const COURSE_BANNER_IMAGE_DIMENSIONS = {
  width: BANNER_IMAGE_WIDTH,
  height: BANNER_IMAGE_HEIGHT,
  aspectRatio: BANNER_IMAGE_WIDTH / BANNER_IMAGE_HEIGHT,
} as const

export const TEAM_TILE_IMAGE_DIMENSIONS = COURSE_TILE_IMAGE_DIMENSIONS

export const TEAM_BANNER_IMAGE_DIMENSIONS = COURSE_BANNER_IMAGE_DIMENSIONS

export const CATEGORY_TILE_IMAGE_DIMENSIONS = COURSE_TILE_IMAGE_DIMENSIONS
