export const EventAttendeesDiscProfilesEndpointResponses = {
  invalidMissingEventId: () => {
    return {
      session: {
        userID: 2209853,
        userName: 'John Bailey',
        changePassword: false,
        termsOfServiceSignatureRequired: false,
        adminID: 0,
        teamListSyncDate: '1900-01-01T00:00:00+00:00',
        koPermissionSyncDate: '2023-11-13T18:23:33.36+00:00',
        domainID: 1698652,
        timeOutMnts: 90,
        onCourseURL: 'https://cardoneventuresceo.com',
        profileThumbPath:
          '/v2/domains/1698652/assets/2209853_kvemjhrbf1w_200px.jpg',
        teamRootID: 1763850,
        roleID: 432,
        onlinePreference: 'ocAVAILABLE',
      },
      error: {
        sts: -201,
        msg: "Server couldn't complete the request, try again",
        logID: 227258255,
        technical:
          "Procedure or function 'usp_getDiscProfilesForEvent' expects parameter '@eventID', which was not supplied.",
      },
      links: [],
    }
  },

  success: () => {
    return {
      discProfiles: {
        profiles: [
          {
            personName: 'Austin Blain',
            memberships: [
              {
                teamID: 2002987,
              },
            ],
            teamRoot: 551,
            nameStyleDisplay: 'Advocate',
            discID: 9657,
            d1: -7.12575675,
            i1: 0.72220286,
            s1: 7.02682745,
            c1: -1.36560146,
            d2: -5.77503503,
            i2: 0.76148558,
            s2: 6.62471315,
            c2: 5.08402172,
            d3: -5.88091582,
            i3: 0.36042681,
            s3: 6.8545898,
            c3: 2.83506944,
            nameStyle3: 'Advocate',
            testDate: '2017-10-10T11:41:00.147+00:00',
            resultID_clientSide: 5134,
            yearBorn: 1993,
            peopleKeysAccountID: 185,
            personID: 1503800,
            lessonID: 0,
            communicationTips:
              '[{"header":"When communicating with me, an Advocate, DO:","items":[{"value":"Build a favorable, friendly environment; allow for social  activities"},{"value":"Give opportunity for them to verbalize about ideas, people and their intuition"},{"value":"Give adequate information for informed decisions"},{"value":"Share testimonials from others relating to proposed ideas"},{"value":"Develop a team atmosphere and participative relationship"},{"value":"Create incentives for their quality workk"},{"value":"TESTING..."}]},{"header":"When communicating with me, an Advocate, DO NOT:","items":[{"value":"Be overly aggressive"},{"value":"Make them harshly discipline peers"},{"value":"Threaten their sense of security"},{"value":"Be overly critical"}]},{"header":"Value to a team:","items":[{"value":"Steady, hard worker, analytical"},{"value":"Motivates others to achieve by aiding and assisting"},{"value":"Good leader if parameters are clearly defined"},{"value":"Very relational and approachable"}]},{"header":"Personal growth areas:","items":[{"value":"Be open and participative"},{"value":"Believe in yourself and your leadership abilities"},{"value":"Delegate more"},{"value":"Do not take criticism personally"},{"value":"Stand up to those with more dominant personalities when necessary"},{"value":"May be overly protective of relationships"}]}]',
            discPersonActiveStatus: 'ocENABLED',
            useClientSideApi: true,
          },
          {
            personName: 'Joshua Rinard',
            memberships: [
              {
                teamID: 2002987,
              },
            ],
            teamRoot: 551,
            nameStyleDisplay: 'Technician',
            discID: 16429,
            d1: -5.59846282,
            i1: -2.74527552,
            s1: 7.9,
            c1: -5.19159872,
            d2: -2.55701813,
            i2: -3.07040038,
            s2: 7.9,
            c2: 2.47527578,
            d3: -3.6799144,
            i3: -3.63435574,
            s3: 7.4074864,
            c3: -0.60696496,
            nameStyle3: 'Technician',
            testDate: '2021-09-14T12:01:33.91+00:00',
            resultID_clientSide: 13815,
            yearBorn: 1985,
            peopleKeysAccountID: 185,
            personID: 1960713,
            lessonID: 0,
            communicationTips:
              '[{"header":"When communicating with me, a Peacemaker, DO:","items":[{"value":"Create a favorable environment that is personal and agreeable"},{"value":"Express a genuine interest in them as a person"},{"value":"Provide them with clarification for tasks and answers to \\"how\\" questions"},{"value":"Be patient and give them follow-up support"},{"value":"Present ideas or departures from current practices in a non-threatening manner; give them time to adjust"},{"value":"Clearly define goals, procedures and their role in the overall plan"}]},{"header":"When communicating with me, a Peacemaker, DO NOT:","items":[{"value":"Be pushy, overly aggressive, or demanding"},{"value":"Expect them to make decisions without all the information"},{"value":"Ask them to discipline others or put them in competitive environments"},{"value":"Be too confrontational or critical of their actions"}]},{"header":"Value to a team:","items":[{"value":"Reliable, steady and loyal team member"},{"value":"Compliant towards authority"},{"value":"Good listener, patient and empathetic"},{"value":"Will follow a task through from start to finish"}]},{"header":"Personal growth areas:","items":[{"value":"Be more open to change, develop more flexibility"},{"value":"Be more direct in your interactions"},{"value":"Focus on overall goals of the team rather than specific procedures"},{"value":"Deal with confrontation constructively"},{"value":"Increase pace to accomplish goals"},{"value":"Show more initiative"}]}]',
            discPersonActiveStatus: 'ocENABLED',
            useClientSideApi: true,
          },
          {
            personName: 'Johann Loch',
            memberships: [
              {
                teamID: 1763850,
              },
              {
                teamID: 1763598,
              },
              {
                teamID: 1763597,
              },
            ],
            teamRoot: 1763850,
            nameStyleDisplay: 'Contemplator',
            discID: 17902,
            d1: 1.25655717,
            i1: -4.64199016,
            s1: -1.8975181,
            c1: 1.80505764,
            d2: -0.36179063,
            i2: -3.07040038,
            s2: 3.92149287,
            c2: 2.47527578,
            d3: 0.6858437,
            i3: -4.38074487,
            s3: 0.76529318,
            c3: 2.83506944,
            nameStyle3: 'Contemplator',
            testDate: '2022-02-28T08:06:55.29+00:00',
            resultID_clientSide: 15408,
            yearBorn: 1998,
            peopleKeysAccountID: 652,
            personID: 2042763,
            lessonID: 2043263,
            communicationTips:
              '[{"header":"When communicating with me, a Contemplator, DO:","items":[{"value":"Provide information to back up statements"},{"value":"Offer sincere appreciation for their efforts"},{"value":"Focus on business; remember they desire results"},{"value":"Be loyal"},{"value":"Give them all the information they need"},{"value":"Give them ample time to respond"},{"value":"Recognize their high quality work"}]},{"header":"When communicating with me, a Contemplator, DO NOT:","items":[{"value":"Do all the talking"},{"value":"Focus on problems"},{"value":"Criticize or challenge them directly"},{"value":"Make generalizations or statements without support"}]},{"header":"Value to a team:","items":[{"value":"Values team working together to achieve results"},{"value":"Steady; not overly impulsive"},{"value":"Promotes high quality work and results"},{"value":"Good follow through and completion"}]},{"header":"Personal growth areas:","items":[{"value":"Strive to be an encourager to others"},{"value":"Be more expressive of feelings"},{"value":"Be less controlling and directive"},{"value":"Develop a greater appreciation for the opinions, feelings and desires of others"},{"value":"Let others feel more a part of the team"},{"value":"Share information with others"}]}]',
            discPersonActiveStatus: 'ocENABLED',
            useClientSideApi: true,
          },
          {
            personName: 'John Bailey',
            memberships: [
              {
                teamID: 1763850,
              },
              {
                teamID: 1763597,
              },
              {
                teamID: 1763598,
              },
            ],
            teamRoot: 1763850,
            nameStyleDisplay: 'Contemplator',
            discID: 21420,
            d1: 1.25655717,
            i1: -0.93017682,
            s1: 0.31201886,
            c1: -1.36560146,
            d2: 0.47272591,
            i2: -3.07040038,
            s2: 1.47622883,
            c2: 3.71135786,
            d3: 1.14111489,
            i3: -2.86574343,
            s3: 0.76529318,
            c3: 1.98514544,
            nameStyle3: 'Contemplator',
            testDate: '2023-04-11T02:09:47.977+00:00',
            resultID_clientSide: 19571,
            peopleKeysAccountID: 652,
            personID: 2209853,
            lessonID: 2210200,
            communicationTips: '',
            discPersonActiveStatus: 'ocENABLED',
            useClientSideApi: true,
          },
        ],
        teams: [
          {
            teamID: 1763598,
            teamName: '10X EMPLOYEE',
            domainID: 1698652,
            iPath: ',551,1825957,1698652,1738904,',
            subDomainParentNamePath: '\tCardone Ventures Programs\t',
            parentID: 1738904,
            lvl: 5,
            sn: 1791,
            memberCount: 3873,
            rootMemberCount: 2,
          },
          {
            teamID: 1763597,
            teamName: '10X OWNER',
            domainID: 1698652,
            iPath: ',551,1825957,1698652,1738904,',
            subDomainParentNamePath: '\tCardone Ventures Programs\t',
            parentID: 1738904,
            lvl: 5,
            sn: 1793,
            memberCount: 1073,
            rootMemberCount: 7,
          },
          {
            teamID: 1763850,
            teamName: 'Cardone Ventures Team',
            domainID: 1698652,
            iPath: ',551,1825957,1698652,',
            subDomainParentNamePath: '\t',
            parentID: 1698652,
            lvl: 4,
            sn: 1852,
            memberCount: 258,
            rootMemberCount: 245,
          },
          {
            teamID: 2002987,
            teamName: 'Mastery Training Feedback',
            domainID: 1698652,
            iPath: ',551,1825957,1698652,',
            subDomainParentNamePath: '\t',
            parentID: 1698652,
            lvl: 4,
            sn: 1982,
            memberCount: 3,
            rootMemberCount: 0,
          },
        ],
      },
      session: {
        userID: 2209853,
        userName: 'John Bailey',
        changePassword: false,
        termsOfServiceSignatureRequired: false,
        adminID: 0,
        teamListSyncDate: '1900-01-01T00:00:00+00:00',
        koPermissionSyncDate: '2023-11-13T18:23:33.36+00:00',
        domainID: 1698652,
        timeOutMnts: 90,
        onCourseURL: 'https://cardoneventuresceo.com',
        profileThumbPath:
          '/v2/domains/1698652/assets/2209853_kvemjhrbf1w_200px.jpg',
        teamRootID: 1763850,
        roleID: 432,
        onlinePreference: 'ocAVAILABLE',
      },
      error: {
        sts: 0,
        msg: 'initialized',
      },
      links: [],
    }
  },

  invalidFilter: () => {
    return {
      data: [],
      links: [],
      error: {
        logID: -1,
        msg: 'validation error for filterTimeUTC',
        sts: -1000,
        technical: 'should not contain :',
      },
    }
  },
  invalidMissingRequired: (propName: string) => {
    return {
      data: [],
      links: [],
      error: {
        logID: -1,
        sts: -1000,
        msg: `validation error: ${propName} required`,
        technical: `parameters must contain ${propName}`,
      },
    }
  },
}
