/**
 * To populate this please run
 * px g @tyto/scribe:postman
 */
export const PlatformReviewTeamsEndpointResponses = {
  get: {
    success: () => {
      return {
        platformReviewTeams: [
          {
            noticeID: 0,
            actionType: 'ocVACANT',
            taskID: 3467031,
            taskStatus: 'ocNOTSTARTED',
            taskCreatedDate: '2024-03-08T00:26:32.717+00:00',
            isTeamRoot: false,
            level: 5,
            iPath: ',551,1825957,1698652,1738895,',
            parentID: 1738895,
            isAbove: true,
            isBelow: true,
            isDirect: false,
            isLeader: false,
            isCascade: false,
            isCascadeInherited: false,
            parentNamePath:
              '\tCherry\tCV\tCardone Ventures\tCardone Ventures Clients\t',
            teamDesc: '',
            teamType: 'ocTEAM',
            teamID: 2470452,
            profileImageID: 0,
            name: 'Platform Review Clients',
            ocType: 'ocTEAM',
            domainID: 1698652,
            subDomainParentNamePath: '\tCardone Ventures Clients\t',
            activeStatus: 'ocENABLED',
          },
          {
            noticeID: 0,
            actionType: 'ocVACANT',
            taskID: 3467286,
            taskStatus: 'ocINCOMPLETE',
            taskCreatedDate: '2024-03-08T19:29:39.427+00:00',
            isTeamRoot: false,
            level: 7,
            iPath: ',551,1825957,1698652,1738895,2470452,2478017,',
            parentID: 2478017,
            isAbove: false,
            isBelow: true,
            isDirect: false,
            isLeader: false,
            isCascade: false,
            isCascadeInherited: false,
            parentNamePath:
              '\tCherry\tCV\tCardone Ventures\tCardone Ventures Clients\tPlatform Review Clients\tPR Test Teams\t',
            teamDesc:
              'Testum is Latin meaning small earthen pot \nhttp://www.punjabiuniversity.ac.in/pages/Images/elearn/TEST%20and%20Examination-converted.pdf',
            teamType: 'ocTEAM',
            teamID: 2478024,
            profileImageID: 0,
            name: 'Small Earthen Pot, LLC',
            ocType: 'ocTEAM',
            domainID: 1698652,
            subDomainParentNamePath:
              '\tCardone Ventures Clients\tPlatform Review Clients\tPR Test Teams\t',
            activeStatus: 'ocENABLED',
          },
          {
            noticeID: 0,
            actionType: 'ocVACANT',
            taskID: 3467124,
            taskStatus: 'ocNOTSTARTED',
            taskCreatedDate: '2024-03-08T01:16:04.823+00:00',
            isTeamRoot: false,
            level: 6,
            iPath: ',551,1825957,1698652,1738895,2470452,',
            parentID: 2470452,
            isAbove: false,
            isBelow: true,
            isDirect: false,
            isLeader: false,
            isCascade: false,
            isCascadeInherited: false,
            parentNamePath:
              '\tCherry\tCV\tCardone Ventures\tCardone Ventures Clients\tPlatform Review Clients\t',
            teamDesc: '',
            teamType: 'ocTEAM',
            teamID: 2477688,
            profileImageID: 0,
            name: 'Template 1',
            ocType: 'ocTEAM',
            domainID: 1698652,
            subDomainParentNamePath:
              '\tCardone Ventures Clients\tPlatform Review Clients\t',
            activeStatus: 'ocENABLED',
          },
          {
            noticeID: 0,
            actionType: 'ocVACANT',
            taskID: 3463786,
            taskStatus: 'ocNOTSTARTED',
            taskCreatedDate: '2024-02-29T20:30:12.41+00:00',
            isTeamRoot: false,
            level: 5,
            iPath: ',551,1825957,696300,2466938,',
            parentID: 2466938,
            isAbove: false,
            isBelow: false,
            isDirect: true,
            isLeader: false,
            isCascade: false,
            isCascadeInherited: false,
            parentNamePath:
              '\tCherry\tCV\tPeter Bachman\tPlatform Review Group\t',
            teamDesc: '',
            teamType: 'ocTEAM',
            teamID: 2466939,
            profileImageID: 0,
            name: "Bob's Burgers",
            ocType: 'ocTEAM',
            domainID: 696300,
            subDomainParentNamePath: '\tPlatform Review Group\t',
            activeStatus: 'ocENABLED',
          },
        ],
        hasAddTeamPlatformReview: true,
        session: {
          userID: 2209853,
          userName: 'John Bailey',
          changePassword: false,
          termsOfServiceSignatureRequired: false,
          adminID: 0,
          teamListSyncDate: '1900-01-01T00:00:00+00:00',
          koPermissionSyncDate: '2024-03-11T07:30:18.64+00:00',
          domainID: 1698652,
          timeOutMnts: 129600,
          onCourseURL: 'https://cardoneventuresceo.com',
          profileThumbPath:
            '/v2/domains/1698652/assets/2209853_kvemjhrbf1w_200px.jpg',
          teamRootID: 1763850,
          roleID: 432,
          onlinePreference: 'ocAVAILABLE',
        },
        error: {
          sts: 0,
          msg: 'initialized',
        },
        links: [
          {
            encType: 'application/x-www-form-urlencoded',
            contentType: 'application/json',
            href: 'api/PlatformReview/task',
            media: '',
            method: 'get',
            targetPref: '',
            title: 'Get Platform Review Tasks',
            parameters: [],
            rel: ['http://kvau.lt/PlatformReview/task'],
          },
        ],
      }
    },
  },
  invalidMissingRequired: (propName: string) => {
    return {
      data: [],
      links: [],
      error: {
        logID: -1,
        sts: -1000,
        msg: `validation error: ${propName} required`,
        technical: `parameters must contain ${propName}`,
      },
    }
  },
}
