/**
 * To populate this please run
 * px g @tyto/scribe:postman
 */
export const MenuManageEndpointResponses = {
  get: {
    success: () => {
      return {
        menuItems: [
          {
            functionID: 24,
            displayName: 'Statistics',
            functionName: 'Reports',
            iconPath: '/v25/images/icons/chart_128px.png',
            iconName: '',
            menuGroup: '/Statistics & Logs/',
            links: [
              {
                encType: 'application/x-www-form-urlencoded',
                contentType: 'text/html',
                href: '/v25/nl/#/stats/',
                media: 'screen',
                method: 'get',
                targetPref: '_top',
                title: 'Statistics',
                parameters: [
                  {
                    paramName: 'sessionKey',
                    paramType: 'string',
                  },
                ],
                rel: ['http://kvau.lt/legacy/v2/ui', 'http://kvau.lt/nl'],
              },
              {
                encType: 'application/x-www-form-urlencoded',
                contentType: 'text/html',
                href: '/v25/nl/?app=t#/stats/',
                media: 'screen',
                method: 'get',
                targetPref: '_top',
                title: 'Statistics',
                parameters: [],
                rel: ['http://kvau.lt/legacy/mobile/ui'],
              },
            ],
            param4Desc: '',
            param3Desc: '',
            param2Desc: '',
            param1Desc: '',
            param3: '',
            param2: '',
            param1: '',
            param4: '',
            iconPathLarge: '',
          },
          {
            functionID: 101,
            displayName: 'bugs',
            functionName: 'Page Bugs',
            iconPath: '/v25/images/icons/elementType/ocBUG/ocBug_50px.png',
            iconName: 'ocBug',
            menuGroup: '/System Utilities/',
            links: [
              {
                encType: 'application/x-www-form-urlencoded',
                contentType: 'text/html',
                href: '/x/bugs',
                media: '',
                method: 'get',
                targetPref: '_top',
                title: 'Bug Reports',
                parameters: [],
                rel: ['http://kvau.lt/default'],
              },
            ],
            param4Desc: '',
            param3Desc: '',
            param2Desc: '',
            param1Desc: 'bugID',
            param3: '',
            param2: '',
            param1: '',
            param4: '',
            iconPathLarge: '',
          },
          {
            functionID: 107,
            displayName: 'Manage Teams',
            functionName: 'Page TeamEditor',
            iconPath: '/v25/images/icons/elementType/ocTEAM/ocTeam_50px.png',
            iconName: 'ocTeam_50px.png',
            menuGroup: '/Teams and People/',
            links: [
              {
                encType: 'application/x-www-form-urlencoded',
                contentType: 'text/html',
                href: '/v25/team_e/team.asp',
                media: '',
                method: 'get',
                targetPref: '_top',
                title: 'Teams',
                parameters: [],
                rel: [
                  'http://kvau.lt/legacy/v2/ui',
                  'http://kvau.lt/nl/legacy?domainID=1698652',
                  'http://kvau.lt/nl/legacy?domainID=1825957',
                  'http://kvau.lt/nl/legacy?domainID=2823418',
                  'http://kvau.lt/nl/legacy?domainID=551',
                ],
              },
              {
                encType: 'application/x-www-form-urlencoded',
                contentType: 'text/html',
                href: '/v25/nl/#/team-editor',
                media: 'get',
                method: 'get',
                targetPref: '_top',
                title: 'Team Editor',
                parameters: [],
                rel: [
                  'http://kvau.lt/default',
                  'http://kvau.lt/nl',
                  'http://kvau.lt/nl/iframe?iframeOrigin=https://team-editor.azureedge.net/team-editor',
                ],
              },
            ],
            param4Desc: '',
            param3Desc: 'eID',
            param2Desc: 'userID',
            param1Desc: 'teamID',
            param3: '',
            param2: '',
            param1: '',
            param4: '',
            iconPathLarge: '',
          },
          {
            functionID: 117,
            displayName: 'VCEP Editor',
            functionName: 'VCEPlan',
            iconPath: '/v2/domains/551/traitIcons/trait268_hah04mos.png',
            iconName: '',
            menuGroup: '/Training Development/',
            links: [
              {
                encType: 'application/x-www-form-urlencoded',
                contentType: 'text/html',
                href: '/v25/nl/#/action-plan/vcep-editor',
                media: 'screen',
                method: 'get',
                targetPref: '_top',
                title: 'VCEP Editor',
                parameters: [],
                rel: [
                  'http://kvau.lt/default',
                  'http://kvau.lt/nl',
                  'http://kvau.lt/nl/iframe?iframeOrigin=https://action-plan.azureedge.net/action-plan',
                ],
              },
              {
                encType: 'application/x-www-form-urlencoded',
                contentType: 'text/html',
                href: '/v25/nl/#/vcep',
                media: 'all',
                method: 'get',
                targetPref: '_top',
                title: 'VCEP',
                parameters: [],
                rel: ['http://kvau.lt/legacy/v2/ui'],
              },
            ],
            param4Desc: '',
            param3Desc: '',
            param2Desc: '',
            param1Desc: 'devplanID',
            param3: '',
            param2: '',
            param1: '',
            param4: '',
            iconPathLarge: '',
          },
          {
            functionID: 121,
            displayName: 'Training Dashboard',
            functionName: 'Page Manage TrainingDashboard',
            iconPath: '/v25/images/icons/training_dash_64px.png',
            iconName: 'Training Dashboa',
            menuGroup: '/Training Development/',
            links: [
              {
                encType: 'application/x-www-form-urlencoded',
                contentType: 'text/html',
                href: '/v25/nl/#/training/dashboard',
                media: '',
                method: 'get',
                targetPref: '_top',
                title: 'Training Dashboard',
                parameters: [],
                rel: ['http://kvau.lt/default'],
              },
              {
                encType: 'application/x-www-form-urlencoded',
                contentType: 'text/html',
                href: '/v25/nl/#/analytics-dashboard',
                media: 'screen',
                method: 'get',
                targetPref: '_top',
                title: 'Analytics Dashboard',
                parameters: [],
                rel: [
                  'http://kvau.lt/nl',
                  'http://kvau.lt/nl/beta?domainID=1825957',
                  'http://kvau.lt/nl/beta?domainID=551',
                  'http://kvau.lt/nl/iframe?iframeOrigin=https://analytics-dashboard.azureedge.net/analytics-dashboard',
                ],
              },
            ],
            param4Desc: '',
            param3Desc: '',
            param2Desc: '',
            param1Desc: '',
            param3: '',
            param2: '',
            param1: '',
            param4: '',
            iconPathLarge: '',
          },
          {
            functionID: 122,
            displayName: 'News',
            functionName: 'Page Manage News',
            iconPath: '/v25/images/icons/news_50px.png',
            iconName: 'News icon',
            menuGroup: '/Teams and People/',
            links: [
              {
                encType: 'application/x-www-form-urlencoded',
                contentType: 'text/html',
                href: '/v25/nl/#/newseditor/',
                media: '',
                method: 'get',
                targetPref: '_top',
                title: 'News Editor',
                parameters: [],
                rel: ['http://kvau.lt/default'],
              },
            ],
            param4Desc: '',
            param3Desc: '',
            param2Desc: '',
            param1Desc: '',
            param3: '',
            param2: '',
            param1: '',
            param4: '',
            iconPathLarge: '',
          },
          {
            functionID: 123,
            displayName: 'Security Roles',
            functionName: 'Page Manage SecurityRoles',
            iconPath: '/v25/images/icons/secRole_50px.png',
            iconName: 'Security Ro icon',
            menuGroup: '/Teams and People/',
            links: [
              {
                encType: 'application/x-www-form-urlencoded',
                contentType: 'text/html',
                href: '/v25/roles/scope_listRoles.asp',
                media: '',
                method: 'get',
                targetPref: '_top',
                title: 'Security Roles',
                parameters: [],
                rel: [
                  'http://kvau.lt/legacy/v2/ui',
                  'http://kvau.lt/nl/legacy?domainID=551',
                ],
              },
              {
                encType: 'application/x-www-form-urlencoded',
                contentType: 'text/html',
                href: '/v25/nl/#/manage/roles',
                media: 'screen',
                method: 'get',
                targetPref: '_top',
                title: 'Security Roles',
                parameters: [],
                rel: ['http://kvau.lt/default'],
              },
            ],
            param4Desc: '',
            param3Desc: '',
            param2Desc: '',
            param1Desc: '',
            param3: '',
            param2: '',
            param1: '',
            param4: '',
            iconPathLarge: '',
          },
          {
            functionID: 124,
            displayName: 'Add Multiple People',
            functionName: 'Page Manage AddMultiplePeople',
            iconPath: '/v25/images/icons/bulkPeople_50px.png',
            iconName: 'Add Multipl icon',
            menuGroup: '/Teams and People/',
            links: [
              {
                encType: 'application/x-www-form-urlencoded',
                contentType: 'text/html',
                href: '/v25/nl/#/manage/addusers',
                media: '',
                method: 'get',
                targetPref: '_top',
                title: 'Add Multiple People',
                parameters: [],
                rel: ['http://kvau.lt/default'],
              },
            ],
            param4Desc: '',
            param3Desc: '',
            param2Desc: '',
            param1Desc: '',
            param3: '',
            param2: '',
            param1: '',
            param4: '',
            iconPathLarge: '',
          },
          {
            functionID: 125,
            displayName: 'Ability List',
            functionName: 'Page Manage AbilityList',
            iconPath: '/v25/images/icons/Ability_list_50px.png',
            iconName: 'Ability Lis icon',
            menuGroup: '/Teams and People/',
            links: [
              {
                encType: 'application/x-www-form-urlencoded',
                contentType: 'text/html',
                href: '/v25/roles/abilities_list.asp',
                media: '',
                method: 'get',
                targetPref: '_top',
                title: 'Ability List',
                parameters: [],
                rel: ['http://kvau.lt/default'],
              },
            ],
            param4Desc: '',
            param3Desc: '',
            param2Desc: '',
            param1Desc: '',
            param3: '',
            param2: '',
            param1: '',
            param4: '',
            iconPathLarge: '',
          },
          {
            functionID: 126,
            displayName: 'Event Templates',
            functionName: 'Page Manage EventTemplates',
            iconPath: '/v25/images/icons/elementType/ocEVENT/ocEvent_64px.png',
            iconName: 'Event Templ icon',
            menuGroup: '/Teams and People/',
            links: [
              {
                encType: 'application/x-www-form-urlencoded',
                contentType: 'text/html',
                href: '/v25/nl/#/eventtemplates',
                media: '',
                method: 'get',
                targetPref: '_top',
                title: 'Event Templates',
                parameters: [],
                rel: ['http://kvau.lt/default'],
              },
            ],
            param4Desc: '',
            param3Desc: '',
            param2Desc: '',
            param1Desc: '',
            param3: '',
            param2: '',
            param1: '',
            param4: '',
            iconPathLarge: '',
          },
          {
            functionID: 127,
            displayName: 'Courses',
            functionName: 'Page Manage Courses',
            iconPath: '/v25/images/icons/elementType/ocBLOCK/ocBlock_64px.png',
            iconName: 'Courses icon',
            menuGroup: '/Training Development/',
            links: [
              {
                encType: 'application/x-www-form-urlencoded',
                contentType: 'text/html',
                href: '/v25/course_e/courseBuilder.asp',
                media: '',
                method: 'get',
                targetPref: '_top',
                title: 'Courses',
                parameters: [],
                rel: ['http://kvau.lt/legacy/v2/ui'],
              },
              {
                encType: 'application/x-www-form-urlencoded',
                contentType: 'text/html',
                href: '/v25/nl/#/courseeditor',
                media: 'screen',
                method: 'get',
                targetPref: '_top',
                title: 'Course Editor',
                parameters: [],
                rel: ['http://kvau.lt/default', 'http://kvau.lt/nl'],
              },
            ],
            param4Desc: '',
            param3Desc: '',
            param2Desc: '',
            param1Desc: '',
            param3: '',
            param2: '',
            param1: '',
            param4: '',
            iconPathLarge: '',
          },
          {
            functionID: 128,
            displayName: 'Credit Types',
            functionName: 'Page Manage CreditTypes',
            iconPath: '/v25/images/icons/credits_50px.png',
            iconName: 'Credit Type icon',
            menuGroup: '/Training Development/',
            links: [
              {
                encType: 'application/x-www-form-urlencoded',
                contentType: 'text/html',
                href: '/v25/team_e/domainCreditTypes_edit.asp',
                media: '',
                method: 'get',
                targetPref: '_top',
                title: 'Credit Types',
                parameters: [],
                rel: ['http://kvau.lt/default'],
              },
            ],
            param4Desc: '',
            param3Desc: '',
            param2Desc: '',
            param1Desc: '',
            param3: '',
            param2: '',
            param1: '',
            param4: '',
            iconPathLarge: '',
          },
          {
            functionID: 129,
            displayName: 'Plan Templates',
            functionName: 'Page Manage PlanTemplates',
            iconPath:
              '/v25/images/icons/elementType/ocDEVPLAN/ocDevPlan_64px.png',
            iconName: 'Plan Templa icon',
            menuGroup: '/Training Development/',
            links: [
              {
                encType: 'application/x-www-form-urlencoded',
                contentType: 'text/html',
                href: '/v25/plan_e/planBuilder.asp',
                media: '',
                method: 'get',
                targetPref: '_top',
                title: 'Plan Templates',
                parameters: [],
                rel: ['http://kvau.lt/default'],
              },
            ],
            param4Desc: '',
            param3Desc: '',
            param2Desc: '',
            param1Desc: '',
            param3: '',
            param2: '',
            param1: '',
            param4: '',
            iconPathLarge: '',
          },
          {
            functionID: 130,
            displayName: 'Checklist Templates',
            functionName: 'Page Manage ChecklistTemplates',
            iconPath:
              '/v25/images/icons/elementType/ocDEVPLAN/ocChecklist_64px.png',
            iconName: 'Checklist T icon',
            menuGroup: '/Training Development/',
            links: [
              {
                encType: 'application/x-www-form-urlencoded',
                contentType: 'text/html',
                href: '/v25/tasks/checklist/edit/',
                media: '',
                method: 'get',
                targetPref: '_top',
                title: 'Checklist Templates',
                parameters: [],
                rel: ['http://kvau.lt/default'],
              },
            ],
            param4Desc: '',
            param3Desc: '',
            param2Desc: '',
            param1Desc: '',
            param3: '',
            param2: '',
            param1: '',
            param4: '',
            iconPathLarge: '',
          },
          {
            functionID: 131,
            displayName: 'Catalog',
            functionName: 'Page Manage Catalog',
            iconPath: '/v25/images/icons/ocCatalog_50px.png',
            iconName: 'Catalog icon',
            menuGroup: '/Training Development/',
            links: [
              {
                encType: 'application/x-www-form-urlencoded',
                contentType: 'text/html',
                href: '/v25/training/catalog/',
                media: '',
                method: 'get',
                targetPref: '_top',
                title: 'Catalog',
                parameters: [],
                rel: [
                  'http://kvau.lt/legacy/v2/ui',
                  'http://kvau.lt/nl/legacy?domainID=1698652',
                  'http://kvau.lt/nl/legacy?domainID=1825957',
                  'http://kvau.lt/nl/legacy?domainID=2179214',
                  'http://kvau.lt/nl/legacy?domainID=551',
                ],
              },
              {
                encType: 'application/x-www-form-urlencoded',
                contentType: 'text/html',
                href: '/v25/nl/#/course-catalog-editor',
                media: 'screen',
                method: 'get',
                targetPref: '_top',
                title: 'Course Catalog Editor',
                parameters: [],
                rel: [
                  'http://kvau.lt/default',
                  'http://kvau.lt/nl/default?domainID=1698652',
                  'http://kvau.lt/nl/default?domainID=1825957',
                  'http://kvau.lt/nl/default?domainID=2179214',
                  'http://kvau.lt/nl/default?domainID=551',
                ],
              },
            ],
            param4Desc: '',
            param3Desc: '',
            param2Desc: '',
            param1Desc: '',
            param3: '',
            param2: '',
            param1: '',
            param4: '',
            iconPathLarge: '',
          },
          {
            functionID: 132,
            displayName: 'Category Manager',
            functionName: 'Page Manage CategoryManager',
            iconPath: '/v25/images/icons/category_64px.png',
            iconName: 'Category Ma icon',
            menuGroup: '/Training Development/',
            links: [
              {
                encType: 'application/x-www-form-urlencoded',
                contentType: 'text/html',
                href: '/v25/nl/#/category/manager',
                media: '',
                method: 'get',
                targetPref: '_top',
                title: 'Category Manager',
                parameters: [],
                rel: ['http://kvau.lt/default'],
              },
            ],
            param4Desc: '',
            param3Desc: '',
            param2Desc: '',
            param1Desc: '',
            param3: '',
            param2: '',
            param1: '',
            param4: '',
            iconPathLarge: '',
          },
          {
            functionID: 133,
            displayName: 'Exams',
            functionName: 'Page Manage Exams',
            iconPath: '/v25/images/icons/elementType/ocEXAM/ocExam_64px.png',
            iconName: 'Exams icon',
            menuGroup: '/Assess/',
            links: [
              {
                encType: 'application/x-www-form-urlencoded',
                contentType: 'text/html',
                href: '/v25/exam/examBuilder.asp',
                media: '',
                method: 'get',
                targetPref: '_top',
                title: 'Exams',
                parameters: [],
                rel: ['http://kvau.lt/legacy/v2/ui'],
              },
              {
                encType: 'application/x-www-form-urlencoded',
                contentType: 'text/html',
                href: '/v25/nl/#/exam-editor',
                media: 'screen',
                method: 'get',
                targetPref: '_top',
                title: 'Exam Editor',
                parameters: [],
                rel: ['http://kvau.lt/default', 'http://kvau.lt/nl'],
              },
            ],
            param4Desc: '',
            param3Desc: '',
            param2Desc: '',
            param1Desc: '',
            param3: '',
            param2: '',
            param1: '',
            param4: '',
            iconPathLarge: '',
          },
          {
            functionID: 134,
            displayName: 'Surveys',
            functionName: 'Page Manage Surveys',
            iconPath: '/v25/images/icons/elementType/ocEXAM/ocSurvey_64px.png',
            iconName: 'Surveys icon',
            menuGroup: '/Assess/',
            links: [
              {
                encType: 'application/x-www-form-urlencoded',
                contentType: 'text/html',
                href: '/v25/nl/#/survey-editor',
                media: 'screen',
                method: 'get',
                targetPref: '_top',
                title: 'Survey Editor',
                parameters: [],
                rel: ['http://kvau.lt/default', 'http://kvau.lt/nl'],
              },
              {
                encType: 'application/x-www-form-urlencoded',
                contentType: 'text/html',
                href: '/v25/survey/asBuilder.asp?newType=survey',
                media: '',
                method: 'get',
                targetPref: '_top',
                title: 'Surveys',
                parameters: [],
                rel: ['http://kvau.lt/legacy/v2/ui'],
              },
            ],
            param4Desc: '',
            param3Desc: '',
            param2Desc: '',
            param1Desc: '',
            param3: '',
            param2: '',
            param1: '',
            param4: '',
            iconPathLarge: '',
          },
          {
            functionID: 135,
            displayName: 'TPA',
            functionName: 'Page Manage TPA',
            iconPath: '/v25/images/icons/elementType/ocEXAM/ocTPA_64px.png',
            iconName: 'TPA icon',
            menuGroup: '/Assess/',
            links: [
              {
                encType: 'application/x-www-form-urlencoded',
                contentType: 'text/html',
                href: '/v25/tpa/tpaBuilder.asp?newType=tpa',
                media: '',
                method: 'get',
                targetPref: '_top',
                title: 'TPA',
                parameters: [],
                rel: ['http://kvau.lt/default'],
              },
            ],
            param4Desc: '',
            param3Desc: '',
            param2Desc: '',
            param1Desc: '',
            param3: '',
            param2: '',
            param1: '',
            param4: '',
            iconPathLarge: '',
          },
          {
            functionID: 136,
            displayName: 'Element Info',
            functionName: 'Page Manage ElementInfo',
            iconPath: '/v25/images/icons/elementInfo_50px.png',
            iconName: 'Element Inf icon',
            menuGroup: '/System Utilities/',
            links: [
              {
                encType: 'application/x-www-form-urlencoded',
                contentType: 'text/html',
                href: '/v25/system/element_info.asp',
                media: '',
                method: 'get',
                targetPref: '_top',
                title: 'Element Info',
                parameters: [],
                rel: ['http://kvau.lt/default'],
              },
            ],
            param4Desc: '',
            param3Desc: '',
            param2Desc: '',
            param1Desc: '',
            param3: '',
            param2: '',
            param1: '',
            param4: '',
            iconPathLarge: '',
          },
          {
            functionID: 137,
            displayName: 'File Search',
            functionName: 'Page Manage FileSearch',
            iconPath: '/v25/images/icons/fileSearch_50px.png',
            iconName: 'File Search icon',
            menuGroup: '/System Utilities/',
            links: [
              {
                encType: 'application/x-www-form-urlencoded',
                contentType: 'text/html',
                href: '/v25/system/search.asp',
                media: '',
                method: 'get',
                targetPref: '_top',
                title: 'File Search',
                parameters: [],
                rel: ['http://kvau.lt/default'],
              },
            ],
            param4Desc: '',
            param3Desc: '',
            param2Desc: '',
            param1Desc: '',
            param3: '',
            param2: '',
            param1: '',
            param4: '',
            iconPathLarge: '',
          },
          {
            functionID: 138,
            displayName: 'Notice Info',
            functionName: 'Page Manage NoticeInfo',
            iconPath:
              '/v25/images/icons/elementType/ocNOTICE/ocMessage_50px.png',
            iconName: 'Notice Info icon',
            menuGroup: '/System Utilities/',
            links: [
              {
                encType: 'application/x-www-form-urlencoded',
                contentType: 'text/html',
                href: '/v25/test/notice/',
                media: '',
                method: 'get',
                targetPref: '_top',
                title: 'Notice Info',
                parameters: [],
                rel: ['http://kvau.lt/default'],
              },
            ],
            param4Desc: '',
            param3Desc: '',
            param2Desc: '',
            param1Desc: '',
            param3: '',
            param2: '',
            param1: '',
            param4: '',
            iconPathLarge: '',
          },
          {
            functionID: 139,
            displayName: 'Object Info',
            functionName: 'Page Manage ObjectInfo',
            iconPath: '/v25/images/icons/taskInfo_50px.png',
            iconName: 'Object Info icon',
            menuGroup: '/System Utilities/',
            links: [
              {
                encType: 'application/x-www-form-urlencoded',
                contentType: 'text/html',
                href: '/v25/system/object_info.asp',
                media: '',
                method: 'get',
                targetPref: '_top',
                title: 'Object Info',
                parameters: [],
                rel: ['http://kvau.lt/default'],
              },
            ],
            param4Desc: '',
            param3Desc: '',
            param2Desc: '',
            param1Desc: '',
            param3: '',
            param2: '',
            param1: '',
            param4: '',
            iconPathLarge: '',
          },
          {
            functionID: 140,
            displayName: 'Server Variables',
            functionName: 'Page Manage ServerVariables',
            iconPath: '/v25/images/icons/plugins_50px.png',
            iconName: 'Server Vari icon',
            menuGroup: '/System Utilities/',
            links: [
              {
                encType: 'application/x-www-form-urlencoded',
                contentType: 'text/html',
                href: '/v25/system/stats.asp',
                media: '',
                method: 'get',
                targetPref: '_top',
                title: 'Server Variables',
                parameters: [],
                rel: ['http://kvau.lt/default'],
              },
            ],
            param4Desc: '',
            param3Desc: '',
            param2Desc: '',
            param1Desc: '',
            param3: '',
            param2: '',
            param1: '',
            param4: '',
            iconPathLarge: '',
          },
          {
            functionID: 141,
            displayName: 'Chat River',
            functionName: 'Page Manage ChatRiver',
            iconPath: '/v25/images/icons/river_64px.png',
            iconName: 'Chat River icon',
            menuGroup: '/Statistics & Logs/',
            links: [
              {
                encType: 'application/x-www-form-urlencoded',
                contentType: 'text/html',
                href: '/v25/components/chat_River.asp',
                media: '',
                method: 'get',
                targetPref: '_top',
                title: 'Chat River',
                parameters: [],
                rel: ['http://kvau.lt/default'],
              },
            ],
            param4Desc: '',
            param3Desc: '',
            param2Desc: '',
            param1Desc: '',
            param3: '',
            param2: '',
            param1: '',
            param4: '',
            iconPathLarge: '',
          },
          {
            functionID: 142,
            displayName: 'Chumby Prime',
            functionName: 'Page Manage ChumbyPrime',
            iconPath: '/v25/images/icons/chumby_64px.png',
            iconName: 'Chumby Prim icon',
            menuGroup: '/Statistics & Logs/',
            links: [
              {
                encType: 'application/x-www-form-urlencoded',
                contentType: 'text/html',
                href: '/chumbyprime/',
                media: '',
                method: 'get',
                targetPref: '_top',
                title: 'Chumby Prime',
                parameters: [],
                rel: ['http://kvau.lt/default'],
              },
            ],
            param4Desc: '',
            param3Desc: '',
            param2Desc: '',
            param1Desc: '',
            param3: '',
            param2: '',
            param1: '',
            param4: '',
            iconPathLarge: '',
          },
          {
            functionID: 143,
            displayName: 'Mr. Radar',
            functionName: 'Page Manage MrRadar',
            iconPath: '/v25/images/icons/mrRadar_50px.png',
            iconName: 'Mr. Radar icon',
            menuGroup: '/Statistics & Logs/',
            links: [
              {
                encType: 'application/x-www-form-urlencoded',
                contentType: 'text/html',
                href: '/v25/mrradar/',
                media: '',
                method: 'get',
                targetPref: '_top',
                title: 'Mr. Radar',
                parameters: [],
                rel: ['http://kvau.lt/default'],
              },
            ],
            param4Desc: '',
            param3Desc: '',
            param2Desc: '',
            param1Desc: '',
            param3: '',
            param2: '',
            param1: '',
            param4: '',
            iconPathLarge: '',
          },
          {
            functionID: 144,
            displayName: 'System Diagnostics',
            functionName: 'Page Manage SystemDiagnostics',
            iconPath: '/v25/images/icons/pageInProgress_50px.png',
            iconName: 'System Diag icon',
            menuGroup: '/Statistics & Logs/',
            links: [
              {
                encType: 'application/x-www-form-urlencoded',
                contentType: 'text/html',
                href: '/v25/system/pages.asp?step=diag',
                media: '',
                method: 'get',
                targetPref: '_top',
                title: 'System Diagnostics',
                parameters: [],
                rel: ['http://kvau.lt/default'],
              },
            ],
            param4Desc: '',
            param3Desc: '',
            param2Desc: '',
            param1Desc: '',
            param3: '',
            param2: '',
            param1: '',
            param4: '',
            iconPathLarge: '',
          },
          {
            functionID: 145,
            displayName: 'System Log',
            functionName: 'Page Manage SystemLog',
            iconPath: '/v25/images/icons/systemLog_50px.png',
            iconName: 'System Log icon',
            menuGroup: '/Statistics & Logs/',
            links: [
              {
                encType: 'application/x-www-form-urlencoded',
                contentType: 'text/html',
                href: '/v25/system/errLog.asp?edt=7/28/2016',
                media: '',
                method: 'get',
                targetPref: '_top',
                title: 'System Log',
                parameters: [],
                rel: ['http://kvau.lt/default'],
              },
            ],
            param4Desc: '',
            param3Desc: '',
            param2Desc: '',
            param1Desc: '',
            param3: '',
            param2: '',
            param1: '',
            param4: '',
            iconPathLarge: '',
          },
          {
            functionID: 146,
            displayName: 'Billing',
            functionName: 'Page Manage Billing',
            iconPath: '/v25/images/icons/elementType/ocTEAM/ocDomain_64px.png',
            iconName: 'Billing icon',
            menuGroup: '/Statistics & Logs/',
            links: [
              {
                encType: 'application/x-www-form-urlencoded',
                contentType: 'text/html',
                href: '/v25/billing/list.asp',
                media: '',
                method: 'get',
                targetPref: '_top',
                title: 'Billing',
                parameters: [],
                rel: ['http://kvau.lt/default'],
              },
            ],
            param4Desc: '',
            param3Desc: '',
            param2Desc: '',
            param1Desc: '',
            param3: '',
            param2: '',
            param1: '',
            param4: '',
            iconPathLarge: '',
          },
          {
            functionID: 161,
            displayName: 'Restore People',
            functionName: 'Page Manage RestorePerson',
            iconPath: '/v25/images/icons/restorePeople_50px.png',
            iconName: 'Restore People',
            menuGroup: '/Teams and People/',
            links: [
              {
                encType: 'application/x-www-form-urlencoded',
                contentType: 'text/html',
                href: '/v25/nl/#/restorePerson',
                media: 'screen',
                method: 'get',
                targetPref: '_top',
                title: 'Restore People',
                parameters: [],
                rel: ['http://kvau.lt/default', 'http://kvau.lt/nl'],
              },
            ],
            param4Desc: '',
            param3Desc: '',
            param2Desc: '',
            param1Desc: 'personID',
            param3: '',
            param2: '',
            param1: '',
            param4: '',
            iconPathLarge: '/v25/images/icons/restorePeople_50px.png',
          },
        ],
        session: {
          adminID: 0,
          changePassword: false,
          domainID: 551,
          koPermissionSyncDate: '2023-09-29T15:25:54.27+00:00',
          onCourseURL: 'https://cherry.mocaworks.com',
          onlinePreference: 'ocHIDDEN',
          profileThumbPath:
            '/v2/domains/551/assets/1960713_tsc3eykcizn_200px.jpg',
          roleID: 1,
          teamRootID: 551,
          teamListSyncDate: '1900-01-01T00:00:00+00:00',
          termsOfServiceSignatureRequired: false,
          timeOutMnts: 129600,
          userID: 1960713,
          userName: 'Joshua Rinard',
        },
      }
    },
  },
  invalidMissingRequired: (propName: string) => {
    return {
      data: [],
      links: [],
      error: {
        logID: -1,
        sts: -1000,
        msg: `validation error: ${propName} required`,
        technical: `parameters must contain ${propName}`,
      },
    }
  },
}
