export const EventEndpointResponses = {
  delete: {
    success: () => {
      return {
        recordsAffected: -1,
        session: {
          userID: 2209853,
          userName: 'John Bailey',
          changePassword: false,
          termsOfServiceSignatureRequired: false,
          adminID: 0,
          teamListSyncDate: '1900-01-01T00:00:00+00:00',
          koPermissionSyncDate: '2024-01-24T17:03:03.62+00:00',
          domainID: 1698652,
          timeOutMnts: 129600,
          onCourseURL: 'https://cardoneventuresceo.com',
          profileThumbPath:
            '/v2/domains/1698652/assets/2209853_kvemjhrbf1w_200px.jpg',
          teamRootID: 1763850,
          roleID: 432,
          onlinePreference: 'ocAVAILABLE',
        },
        error: { sts: 0, msg: '' },
        links: [],
      }
    },
  },
  put: {
    success: () => {
      return {
        recordsAffected: -1,
        session: {
          userID: 2209853,
          userName: 'John Bailey',
          changePassword: false,
          termsOfServiceSignatureRequired: false,
          adminID: 0,
          teamListSyncDate: '1900-01-01T00:00:00+00:00',
          koPermissionSyncDate: '2024-02-14T18:08:43.01+00:00',
          domainID: 1698652,
          timeOutMnts: 129600,
          onCourseURL: 'https://cardoneventuresceo.com',
          profileThumbPath:
            '/v2/domains/1698652/assets/2209853_kvemjhrbf1w_200px.jpg',
          teamRootID: 1763850,
          roleID: 432,
          onlinePreference: 'ocAVAILABLE',
        },
        error: {
          sts: 0,
          msg: '',
        },
        links: [],
      }
    },
  },
  get: {
    errorNotFound: () => {
      return {
        session: {
          userID: 2209853,
          userName: 'John Bailey',
          changePassword: false,
          termsOfServiceSignatureRequired: false,
          adminID: 0,
          teamListSyncDate: '1900-01-01T00:00:00+00:00',
          koPermissionSyncDate: '2024-02-19T03:15:45.123+00:00',
          domainID: 1698652,
          timeOutMnts: 129600,
          onCourseURL: 'https://cardoneventuresceo.com',
          profileThumbPath:
            '/v2/domains/1698652/assets/2209853_kvemjhrbf1w_200px.jpg',
          teamRootID: 1763850,
          roleID: 432,
          onlinePreference: 'ocAVAILABLE',
        },
        error: {
          sts: 0,
          msg: 'cmdGetEvent',
        },
        links: [
          {
            encType: 'application/x-www-form-urlencoded',
            contentType: 'application/json',
            href: 'api/task',
            media: '',
            method: 'get',
            targetPref: '',
            title: 'Get Agenda Task Structure',
            parameters: [
              {
                paramName: 'taskID',
                paramType: 'int',
                functionParamMap: 'event.agendaTaskID',
              },
              {
                paramName: 'taskID',
                paramType: 'int',
                functionParamMap: 'event.actionTaskID',
              },
            ],
            rel: ['http://kvau.lt/api/event/agenda'],
          },
          {
            encType: 'application/x-www-form-urlencoded',
            contentType: 'application/json',
            href: 'api/task',
            media: '',
            method: 'get',
            targetPref: '',
            title: 'Get Action Task Structure',
            parameters: [],
            rel: ['http://kvau.lt/api/event/action'],
          },
          {
            encType: 'application/x-www-form-urlencoded',
            contentType: 'application/json',
            href: 'api/event',
            media: '',
            method: 'put',
            targetPref: '',
            title: 'Update Event',
            parameters: [],
            rel: ['http://kvau.lt/api/event'],
          },
          {
            encType: 'application/x-www-form-urlencoded',
            contentType: 'application/json',
            href: '/api/event/{eventID}/action',
            media: '',
            method: 'post',
            targetPref: '',
            title: 'Add Action Task',
            parameters: [
              {
                paramName: 'taskName',
                paramType: 'string',
              },
              {
                paramName: 'taskDesc',
                paramType: 'string',
              },
              {
                paramName: 'taskType',
                paramType: 'string',
              },
              {
                paramName: 'memberID',
                paramType: 'int',
              },
              {
                paramName: 'mentorID',
                paramType: 'int?',
              },
              {
                paramName: 'dueDate',
                paramType: 'dateTime?',
              },
              {
                paramName: 'aboutID',
                paramType: 'int?',
              },
              {
                paramName: 'aboutType',
                paramType: 'string',
              },
              {
                paramName: 'sendNotice',
                paramType: 'bool?',
              },
              {
                paramName: 'parentTaskID',
                paramType: 'int?',
                functionParamMap:
                  'event.actionTaskID || event.agendaTaskID || {get api/task?taskID=event.agendaTaskID}.task[].taskID || {get api/task?taskID=event.actionTaskID}.task[].taskID',
              },
              {
                paramName: 'isCompletionOptional',
                paramType: 'bool?',
              },
              {
                paramName: 'startDate',
                paramType: 'dateTime?',
              },
              {
                paramName: 'durationMinutes',
                paramType: 'int?',
              },
              {
                paramName: 'operation',
                paramType: 'object',
                functionParamMap: '/api/operation/meta',
              },
            ],
            rel: ['http://kvau.lt/api/event/action+add'],
          },
          {
            encType: 'application/x-www-form-urlencoded',
            contentType: 'application/json',
            href: '/api/event/{eventID}/agenda',
            media: '',
            method: 'post',
            targetPref: '',
            title: 'Add Action Task',
            parameters: [
              {
                paramName: 'taskName',
                paramType: 'string',
              },
              {
                paramName: 'taskDesc',
                paramType: 'string',
              },
              {
                paramName: 'taskType',
                paramType: 'string',
              },
              {
                paramName: 'memberID',
                paramType: 'int',
              },
              {
                paramName: 'mentorID',
                paramType: 'int?',
              },
              {
                paramName: 'dueDate',
                paramType: 'dateTime?',
              },
              {
                paramName: 'aboutID',
                paramType: 'int?',
              },
              {
                paramName: 'aboutType',
                paramType: 'string',
              },
              {
                paramName: 'sendNotice',
                paramType: 'bool?',
              },
              {
                paramName: 'parentTaskID',
                paramType: 'int?',
                functionParamMap:
                  'event.actionTaskID || event.agendaTaskID || {get api/task?taskID=event.agendaTaskID}.task[].taskID || {get api/task?taskID=event.actionTaskID}.task[].taskID',
              },
              {
                paramName: 'isCompletionOptional',
                paramType: 'bool?',
              },
              {
                paramName: 'startDate',
                paramType: 'dateTime?',
              },
              {
                paramName: 'durationMinutes',
                paramType: 'int?',
              },
              {
                paramName: 'operation',
                paramType: 'object',
                functionParamMap: '/api/operation/meta',
              },
            ],
            rel: ['http://kvau.lt/api/event/agenda+add'],
          },
          {
            encType: 'application/x-www-form-urlencoded',
            contentType: 'application/json',
            href: '/api/task/meta',
            media: '',
            method: 'get',
            targetPref: '',
            title: 'Task meta',
            parameters: [],
            rel: ['http://kvau.lt/api/task/meta'],
          },
          {
            encType: 'application/x-www-form-urlencoded',
            contentType: 'application/json',
            href: 'https://cardoneventuresceo.com/v25/nl/components/events/functions.asp?command=loadEventMinutes',
            media: '',
            method: 'get',
            targetPref: '',
            title: 'Get Meeting Minutes',
            parameters: [],
            rel: ['http://kvau.lt/api/event/minutes'],
          },
          {
            encType: 'application/x-www-form-urlencoded',
            contentType: 'application/json',
            href: 'api/event/{eventID:int}/minutes',
            media: '',
            method: 'post',
            targetPref: '',
            title: 'Add Meeting Minutes',
            parameters: [
              {
                paramName: 'actionType',
                paramType: 'string',
              },
              {
                paramName: 'noticeText',
                paramType: 'string',
              },
              {
                paramName: 'taskID',
                paramType: 'int?',
              },
            ],
            rel: ['http://kvau.lt/api/event/minutes+add'],
          },
          {
            encType: 'application/x-www-form-urlencoded',
            contentType: 'application/json',
            href: 'api/event/{eventID:int}/minutes/rating',
            media: '',
            method: 'get',
            targetPref: '',
            title: 'Get Meeting Minutes Approval Rating',
            parameters: [],
            rel: ['http://kvau.lt/api/event/minutes/rating'],
          },
          {
            encType: 'application/x-www-form-urlencoded',
            contentType: 'text/calendar',
            href: 'api/event/ical',
            media: '',
            method: 'get',
            targetPref: '',
            title: 'Get iCal Publication',
            parameters: [],
            rel: ['http://kvau.lt/api/event/ical'],
          },
        ],
      }
    },
    success: (scenario: 'no-agenda' | 'with-agenda' = 'no-agenda') => {
      if (scenario === 'with-agenda') {
        return {
          event: {
            eventID: 2451001,
            eventName: 'something else',
            eventDesc: 'sfgsfdgsdfg',
            elementType: 'ocEVENT',
            eventType: 'ocITEM',
            activeStatus: 'ocENABLED',
            domainID: 1698652,
            outsideID: '',
            createdBy: 2209853,
            createdDate: '2024-02-07T01:12:51.99+00:00',
            primaryElementID: 2209853,
            modifiedBy: 2209853,
            modifiedDate: '2024-02-07T01:12:51.99+00:00',
            startTime: '2024-02-06T14:15:27.733',
            endTime: '2024-02-06T20:15:27.733',
            startTimeAndOffset: '2024-02-06T14:15:27.733+00:00',
            endTimeAndOffset: '2024-02-06T20:15:27.733+00:00',
            isAllDay: false,
            location: 'https://cardoneventuresceo.com/dfgdfg',
            streetAddress: '',
            profileImageID: 0,
            invitationType: 'ocSELF',
            maxCapacity: 0,
            rsvpDeadlineDateUTC: '1900-01-01T00:00:00Z',
            defaultReminderMinutes: 0,
            examTaskID: 0,
            addExamTaskInviteDelayOffsetFromEndTime: 0,
            startTimeUTC: '2024-02-06T14:15:27.733Z',
            endTimeUTC: '2024-02-06T20:15:27.733Z',
            agendaTaskID: 3455469,
            actionTaskID: 0,
            timeZoneIDStart: 1,
            timeZoneStart: {
              nameGeneral: 'Default 00',
              iCalTZID: 'Factory',
              nameObserved: 'UTC',
              observanceType: 'ocCONSTANT',
              modifiedDateUTC: '2023-09-22T16:54:19.527Z',
              iCalTZURL: 'https://www.iana.org/time-zones',
              startDate: '2009-05-17T00:00:00',
              offSetToMinutes: 0,
              offSetFromMinutes: 0,
              iCalRRule: '',
            },
            timeZoneIDEnd: 1,
            timeZoneEnd: {
              nameGeneral: 'Default 00',
              iCalTZID: 'Factory',
              nameObserved: 'UTC',
              observanceType: 'ocCONSTANT',
              modifiedDateUTC: '2023-09-22T16:54:19.527Z',
              iCalTZURL: 'https://www.iana.org/time-zones',
              startDate: '2009-05-17T00:00:00',
              offSetToMinutes: 0,
              offSetFromMinutes: 0,
              iCalRRule: '',
            },
            localTimeZoneIDStart: 9,
            localTimeZoneStart: {
              nameGeneral: 'US-AlaskaAleutian',
              iCalTZID: 'America/Adak',
              nameObserved: 'HAST',
              observanceType: 'ocSTANDARD',
              modifiedDateUTC: '2023-09-22T16:54:19.527Z',
              iCalTZURL: 'https://www.iana.org/time-zones',
              startDate: '2007-11-04T02:00:00',
              offSetToMinutes: -600,
              offSetFromMinutes: -540,
              iCalRRule: 'FREQ=YEARLY;WKST=MO;INTERVAL=1;BYMONTH=11;BYDAY=1SU',
            },
            localTimeZoneIDEnd: 9,
            localTimeZoneEnd: {
              nameGeneral: 'US-AlaskaAleutian',
              iCalTZID: 'America/Adak',
              nameObserved: 'HAST',
              observanceType: 'ocSTANDARD',
              modifiedDateUTC: '2023-09-22T16:54:19.527Z',
              iCalTZURL: 'https://www.iana.org/time-zones',
              startDate: '2007-11-04T02:00:00',
              offSetToMinutes: -600,
              offSetFromMinutes: -540,
              iCalRRule: 'FREQ=YEARLY;WKST=MO;INTERVAL=1;BYMONTH=11;BYDAY=1SU',
            },
            addAccess: true,
            viewAccess: true,
            changeAccess: true,
            deleteAccess: true,
            groupElementID: 0,
            addPersonInvite: true,
            addTeamInvite: true,
            library: [],
            iCalUID: '43BF80DB-7C7C-4FBB-9405-A8DF0635D689',
            iCalSequence: 0,
            personalAttendance: {
              eventAttendeeID: 728400,
              eventID: 2451001,
              instanceEventID: 2451001,
              memberID: 2209853,
              isCascade: false,
              attendanceType: 'ocHOST',
              rsvpStatus: 'ocYES',
              rsvpStatusDateUTC: '2024-02-07T01:12:51.993Z',
              rsvpStatusByID: 2209853,
              attendanceStatus: 'ocVACANT',
              attendanceStatusByID: 2209853,
              attendanceStatusDateUTC: '2024-02-07T01:12:51.993Z',
              emailPreference: 'ocINSTANT',
              modifiedByID: 2209853,
              modifiedDateUTC: '2024-02-07T01:12:51.993Z',
              createdByID: 2209853,
              createdDateUTC: '2024-02-07T01:12:51.993Z',
              lastReminderDateUTC: '1900-01-01T00:00:00Z',
              outsideRegistrationID: '',
              paidDateUTC: '1900-01-01T00:00:00Z',
              reminderMinutes: 0,
            },
            organizer: {
              commonName: 'John Bailey',
              sentBy: 'mailto:event.2451001@CardoneVentures.knowledgevault.com',
              value: 'mailto:event.2451001@CardoneVentures.knowledgevault.com',
            },
            hasSubtabs: false,
            minutesLessonID: 0,
            curriculumID: 0,
            outsideRegMsg: '',
            outsideRegUrl: '',
          },
          session: {
            userID: 2209853,
            userName: 'John Bailey',
            changePassword: false,
            termsOfServiceSignatureRequired: false,
            adminID: 0,
            teamListSyncDate: '1900-01-01T00:00:00+00:00',
            koPermissionSyncDate: '2024-02-07T01:08:56.36+00:00',
            domainID: 1698652,
            timeOutMnts: 2160,
            onCourseURL: 'https://cardoneventuresceo.com',
            profileThumbPath:
              '/v2/domains/1698652/assets/2209853_kvemjhrbf1w_200px.jpg',
            teamRootID: 1763850,
            roleID: 432,
            onlinePreference: 'ocAVAILABLE',
          },
          error: {
            sts: 0,
            msg: '',
          },
          links: [
            {
              encType: 'application/x-www-form-urlencoded',
              contentType: 'application/json',
              href: 'api/task',
              media: '',
              method: 'get',
              targetPref: '',
              title: 'Get Agenda Task Structure',
              parameters: [
                {
                  paramName: 'taskID',
                  paramType: 'int',
                  functionParamMap: 'event.agendaTaskID',
                },
                {
                  paramName: 'taskID',
                  paramType: 'int',
                  functionParamMap: 'event.actionTaskID',
                },
              ],
              rel: ['http://kvau.lt/api/event/agenda'],
            },
            {
              encType: 'application/x-www-form-urlencoded',
              contentType: 'application/json',
              href: 'api/task',
              media: '',
              method: 'get',
              targetPref: '',
              title: 'Get Action Task Structure',
              parameters: [],
              rel: ['http://kvau.lt/api/event/action'],
            },
            {
              encType: 'application/x-www-form-urlencoded',
              contentType: 'application/json',
              href: 'api/event',
              media: '',
              method: 'put',
              targetPref: '',
              title: 'Update Event',
              parameters: [],
              rel: ['http://kvau.lt/api/event'],
            },
            {
              encType: 'application/x-www-form-urlencoded',
              contentType: 'application/json',
              href: '/api/event/{eventID}/action',
              media: '',
              method: 'post',
              targetPref: '',
              title: 'Add Action Task',
              parameters: [
                {
                  paramName: 'taskName',
                  paramType: 'string',
                },
                {
                  paramName: 'taskDesc',
                  paramType: 'string',
                },
                {
                  paramName: 'taskType',
                  paramType: 'string',
                },
                {
                  paramName: 'memberID',
                  paramType: 'int',
                },
                {
                  paramName: 'mentorID',
                  paramType: 'int?',
                },
                {
                  paramName: 'dueDate',
                  paramType: 'dateTime?',
                },
                {
                  paramName: 'aboutID',
                  paramType: 'int?',
                },
                {
                  paramName: 'aboutType',
                  paramType: 'string',
                },
                {
                  paramName: 'sendNotice',
                  paramType: 'bool?',
                },
                {
                  paramName: 'parentTaskID',
                  paramType: 'int?',
                  functionParamMap:
                    'event.actionTaskID || event.agendaTaskID || {get api/task?taskID=event.agendaTaskID}.task[].taskID || {get api/task?taskID=event.actionTaskID}.task[].taskID',
                },
                {
                  paramName: 'isCompletionOptional',
                  paramType: 'bool?',
                },
                {
                  paramName: 'startDate',
                  paramType: 'dateTime?',
                },
                {
                  paramName: 'durationMinutes',
                  paramType: 'int?',
                },
                {
                  paramName: 'operation',
                  paramType: 'object',
                  functionParamMap: '/api/operation/meta',
                },
              ],
              rel: ['http://kvau.lt/api/event/action+add'],
            },
            {
              encType: 'application/x-www-form-urlencoded',
              contentType: 'application/json',
              href: '/api/event/{eventID}/agenda',
              media: '',
              method: 'post',
              targetPref: '',
              title: 'Add Action Task',
              parameters: [
                {
                  paramName: 'taskName',
                  paramType: 'string',
                },
                {
                  paramName: 'taskDesc',
                  paramType: 'string',
                },
                {
                  paramName: 'taskType',
                  paramType: 'string',
                },
                {
                  paramName: 'memberID',
                  paramType: 'int',
                },
                {
                  paramName: 'mentorID',
                  paramType: 'int?',
                },
                {
                  paramName: 'dueDate',
                  paramType: 'dateTime?',
                },
                {
                  paramName: 'aboutID',
                  paramType: 'int?',
                },
                {
                  paramName: 'aboutType',
                  paramType: 'string',
                },
                {
                  paramName: 'sendNotice',
                  paramType: 'bool?',
                },
                {
                  paramName: 'parentTaskID',
                  paramType: 'int?',
                  functionParamMap:
                    'event.actionTaskID || event.agendaTaskID || {get api/task?taskID=event.agendaTaskID}.task[].taskID || {get api/task?taskID=event.actionTaskID}.task[].taskID',
                },
                {
                  paramName: 'isCompletionOptional',
                  paramType: 'bool?',
                },
                {
                  paramName: 'startDate',
                  paramType: 'dateTime?',
                },
                {
                  paramName: 'durationMinutes',
                  paramType: 'int?',
                },
                {
                  paramName: 'operation',
                  paramType: 'object',
                  functionParamMap: '/api/operation/meta',
                },
              ],
              rel: ['http://kvau.lt/api/event/agenda+add'],
            },
            {
              encType: 'application/x-www-form-urlencoded',
              contentType: 'application/json',
              href: '/api/task/meta',
              media: '',
              method: 'get',
              targetPref: '',
              title: 'Task meta',
              parameters: [],
              rel: ['http://kvau.lt/api/task/meta'],
            },
            {
              encType: 'application/x-www-form-urlencoded',
              contentType: 'application/json',
              href: 'http://localhost:4200/v25/nl/components/events/functions.asp?command=loadEventMinutes',
              media: '',
              method: 'get',
              targetPref: '',
              title: 'Get Meeting Minutes',
              parameters: [],
              rel: ['http://kvau.lt/api/event/minutes'],
            },
            {
              encType: 'application/x-www-form-urlencoded',
              contentType: 'application/json',
              href: 'api/event/{eventID:int}/minutes',
              media: '',
              method: 'post',
              targetPref: '',
              title: 'Add Meeting Minutes',
              parameters: [
                {
                  paramName: 'actionType',
                  paramType: 'string',
                },
                {
                  paramName: 'noticeText',
                  paramType: 'string',
                },
                {
                  paramName: 'taskID',
                  paramType: 'int?',
                },
              ],
              rel: ['http://kvau.lt/api/event/minutes+add'],
            },
            {
              encType: 'application/x-www-form-urlencoded',
              contentType: 'application/json',
              href: 'api/event/{eventID:int}/minutes/rating',
              media: '',
              method: 'get',
              targetPref: '',
              title: 'Get Meeting Minutes Approval Rating',
              parameters: [],
              rel: ['http://kvau.lt/api/event/minutes/rating'],
            },
            {
              encType: 'application/x-www-form-urlencoded',
              contentType: 'text/calendar',
              href: 'api/event/ical',
              media: '',
              method: 'get',
              targetPref: '',
              title: 'Get iCal Publication',
              parameters: [],
              rel: ['http://kvau.lt/api/event/ical'],
            },
          ],
        }
      }
      return {
        event: {
          eventID: 2310374,
          eventName: 'Developer "Lunch & Learn"',
          eventDesc:
            'A space for Devs to share things we have learned or created with each other. Feel free to be nerdy about it!',
          elementType: 'ocEVENT',
          eventType: 'ocITEM',
          activeStatus: 'ocENABLED',
          domainID: 551,
          outsideID: '',
          createdBy: 1503800,
          createdDate: '2023-11-01T17:21:30.397+00:00',
          primaryElementID: 1503800,
          modifiedBy: 2209853,
          modifiedDate: '2023-11-07T19:17:11.757+00:00',
          startTime: '2023-11-07T12:00:00',
          endTime: '2023-11-07T12:45:00',
          startTimeAndOffset: '2023-11-07T12:00:00-08:00',
          endTimeAndOffset: '2023-11-07T12:45:00-08:00',
          isAllDay: false,
          location:
            'https://www.google.com/url?q=https://us06web.zoom.us/j/82606261539?pwd%3DGmS5soYJNBkgrIQtywva5zRf70KaAj.1&sa=D&source=calendar&ust=1699816589414697&usg=AOvVaw3h-dvTPhkRYMHSCNL7jwve',
          streetAddress: '',
          profileImageID: 0,
          invitationType: 'ocSELF',
          maxCapacity: 0,
          rsvpDeadlineDateUTC: '1900-01-01T00:00:00Z',
          defaultReminderMinutes: 0,
          examTaskID: 0,
          addExamTaskInviteDelayOffsetFromEndTime: 0,
          startTimeUTC: '2023-11-07T20:00:00Z',
          endTimeUTC: '2023-11-07T20:45:00Z',
          agendaTaskID: 3409879,
          actionTaskID: 0,
          timeZoneIDStart: 5,
          timeZoneStart: {
            nameGeneral: 'US-Pacific',
            iCalTZID: 'America/Los_Angeles',
            nameObserved: 'PST',
            observanceType: 'ocSTANDARD',
            modifiedDateUTC: '2023-09-22T16:54:19.527Z',
            iCalTZURL: 'https://www.iana.org/time-zones',
            startDate: '2007-11-04T02:00:00',
            offSetToMinutes: -480,
            offSetFromMinutes: -420,
            iCalRRule: 'FREQ=YEARLY;WKST=MO;INTERVAL=1;BYMONTH=11;BYDAY=1SU',
          },
          timeZoneIDEnd: 5,
          timeZoneEnd: {
            nameGeneral: 'US-Pacific',
            iCalTZID: 'America/Los_Angeles',
            nameObserved: 'PST',
            observanceType: 'ocSTANDARD',
            modifiedDateUTC: '2023-09-22T16:54:19.527Z',
            iCalTZURL: 'https://www.iana.org/time-zones',
            startDate: '2007-11-04T02:00:00',
            offSetToMinutes: -480,
            offSetFromMinutes: -420,
            iCalRRule: 'FREQ=YEARLY;WKST=MO;INTERVAL=1;BYMONTH=11;BYDAY=1SU',
          },
          localTimeZoneIDStart: 9,
          localTimeZoneStart: {
            nameGeneral: 'US-AlaskaAleutian',
            iCalTZID: 'America/Adak',
            nameObserved: 'HAST',
            observanceType: 'ocSTANDARD',
            modifiedDateUTC: '2023-09-22T16:54:19.527Z',
            iCalTZURL: 'https://www.iana.org/time-zones',
            startDate: '2007-11-04T02:00:00',
            offSetToMinutes: -600,
            offSetFromMinutes: -540,
            iCalRRule: 'FREQ=YEARLY;WKST=MO;INTERVAL=1;BYMONTH=11;BYDAY=1SU',
          },
          localTimeZoneIDEnd: 9,
          localTimeZoneEnd: {
            nameGeneral: 'US-AlaskaAleutian',
            iCalTZID: 'America/Adak',
            nameObserved: 'HAST',
            observanceType: 'ocSTANDARD',
            modifiedDateUTC: '2023-09-22T16:54:19.527Z',
            iCalTZURL: 'https://www.iana.org/time-zones',
            startDate: '2007-11-04T02:00:00',
            offSetToMinutes: -600,
            offSetFromMinutes: -540,
            iCalRRule: 'FREQ=YEARLY;WKST=MO;INTERVAL=1;BYMONTH=11;BYDAY=1SU',
          },
          addAccess: true,
          viewAccess: true,
          changeAccess: true,
          deleteAccess: true,
          groupElementID: 2310373,
          addPersonInvite: true,
          addTeamInvite: true,
          library: [],
          iCalUID: '228E5E15-0EEB-447A-B3BE-CDE95061D8CB',
          iCalSequence: 2,
          iCalRecurIndexDate: '2023-11-07T12:00:00',
          iCalHost:
            'ORGANIZER;SENT-BY="mailto:event.2310373@cherry.knowledgevault.com";CN=Austin Blain:mailto:event.2310373@cherry.knowledgevault.com',
          personalAttendance: {
            eventAttendeeID: 0,
            eventID: 2310374,
            memberID: 2209853,
            isCascade: false,
            attendanceType: 'ocHOST',
            rsvpStatus: 'ocYES',
            rsvpStatusDateUTC: '2023-11-07T17:49:42.86Z',
            rsvpStatusByID: 2209853,
            attendanceStatus: 'ocVACANT',
            attendanceStatusByID: 0,
            attendanceStatusDateUTC: '1900-01-01T00:00:00Z',
            emailPreference: 'ocVACANT',
            modifiedByID: 2209853,
            modifiedDateUTC: '2023-11-07T21:05:17.853Z',
            createdByID: 1503800,
            createdDateUTC: '2023-11-01T17:21:47.383Z',
            lastReminderDateUTC: '1900-01-01T00:00:00Z',
            outsideRegistrationID: '',
            paidDateUTC: '1900-01-01T00:00:00Z',
            reminderMinutes: 0,
            seriesMasterEventAttendeeID: 700728,
            seriesMasterEventID: 2310373,
          },
          seriesMasterEvent: {
            recurrenceRules: [
              {
                iCalRule:
                  'FREQ=WEEKLY;INTERVAL=3;UNTIL=20240103T155900Z;BYDAY=TU',
                period: 'ocWEEKLY',
                interval: 3,
                isTuesday: true,
                untilDate: '2024-01-03T07:59:00',
                untilDateUTC: '2024-01-03T15:59:00Z',
                recurrenceICALID: 10547,
              },
            ],
            eventID: 2310373,
            startTime: '2023-11-07T12:00:00',
            startTimeAndOffset: '2023-11-07T12:00:00-08:00',
            timeZoneStart: {
              offSetToMinutes: -480,
            },
          },
          hasSubtabs: false,
          minutesLessonID: 0,
          curriculumID: 0,
          outsideRegMsg: '',
          outsideRegUrl: '',
        },
        session: {
          userID: 2209853,
          userName: 'John Bailey',
          changePassword: false,
          termsOfServiceSignatureRequired: false,
          adminID: 0,
          teamListSyncDate: '1900-01-01T00:00:00+00:00',
          koPermissionSyncDate: '1900-01-01T00:00:00+00:00',
          domainID: 1698652,
          timeOutMnts: 129600,
          onCourseURL: 'https://cardoneventuresceo.com',
          profileThumbPath:
            '/v2/domains/1698652/assets/2209853_kvemjhrbf1w_200px.jpg',
          teamRootID: 1763850,
          roleID: 432,
          onlinePreference: 'ocAVAILABLE',
        },
        error: {
          sts: 0,
          msg: '',
        },
        links: [
          {
            encType: 'application/x-www-form-urlencoded',
            contentType: 'application/json',
            href: 'api/task',
            media: '',
            method: 'get',
            targetPref: '',
            title: 'Get Agenda Task Structure',
            parameters: [
              {
                paramName: 'taskID',
                paramType: 'int',
                functionParamMap: 'event.agendaTaskID',
              },
              {
                paramName: 'taskID',
                paramType: 'int',
                functionParamMap: 'event.actionTaskID',
              },
            ],
            rel: ['http://kvau.lt/api/event/agenda'],
          },
          {
            encType: 'application/x-www-form-urlencoded',
            contentType: 'application/json',
            href: 'api/task',
            media: '',
            method: 'get',
            targetPref: '',
            title: 'Get Action Task Structure',
            parameters: [],
            rel: ['http://kvau.lt/api/event/action'],
          },
          {
            encType: 'application/x-www-form-urlencoded',
            contentType: 'application/json',
            href: 'api/event',
            media: '',
            method: 'put',
            targetPref: '',
            title: 'Update Event',
            parameters: [],
            rel: ['http://kvau.lt/api/event'],
          },
          {
            encType: 'application/x-www-form-urlencoded',
            contentType: 'application/json',
            href: '/api/event/{eventID}/action',
            media: '',
            method: 'post',
            targetPref: '',
            title: 'Add Action Task',
            parameters: [
              {
                paramName: 'taskName',
                paramType: 'string',
              },
              {
                paramName: 'taskDesc',
                paramType: 'string',
              },
              {
                paramName: 'taskType',
                paramType: 'string',
              },
              {
                paramName: 'memberID',
                paramType: 'int',
              },
              {
                paramName: 'mentorID',
                paramType: 'int?',
              },
              {
                paramName: 'dueDate',
                paramType: 'dateTime?',
              },
              {
                paramName: 'aboutID',
                paramType: 'int?',
              },
              {
                paramName: 'aboutType',
                paramType: 'string',
              },
              {
                paramName: 'sendNotice',
                paramType: 'bool?',
              },
              {
                paramName: 'parentTaskID',
                paramType: 'int?',
                functionParamMap:
                  'event.actionTaskID || event.agendaTaskID || {get api/task?taskID=event.agendaTaskID}.task[].taskID || {get api/task?taskID=event.actionTaskID}.task[].taskID',
              },
              {
                paramName: 'isCompletionOptional',
                paramType: 'bool?',
              },
              {
                paramName: 'startDate',
                paramType: 'dateTime?',
              },
              {
                paramName: 'durationMinutes',
                paramType: 'int?',
              },
              {
                paramName: 'operation',
                paramType: 'object',
                functionParamMap: '/api/operation/meta',
              },
            ],
            rel: ['http://kvau.lt/api/event/action+add'],
          },
          {
            encType: 'application/x-www-form-urlencoded',
            contentType: 'application/json',
            href: '/api/event/{eventID}/agenda',
            media: '',
            method: 'post',
            targetPref: '',
            title: 'Add Action Task',
            parameters: [
              {
                paramName: 'taskName',
                paramType: 'string',
              },
              {
                paramName: 'taskDesc',
                paramType: 'string',
              },
              {
                paramName: 'taskType',
                paramType: 'string',
              },
              {
                paramName: 'memberID',
                paramType: 'int',
              },
              {
                paramName: 'mentorID',
                paramType: 'int?',
              },
              {
                paramName: 'dueDate',
                paramType: 'dateTime?',
              },
              {
                paramName: 'aboutID',
                paramType: 'int?',
              },
              {
                paramName: 'aboutType',
                paramType: 'string',
              },
              {
                paramName: 'sendNotice',
                paramType: 'bool?',
              },
              {
                paramName: 'parentTaskID',
                paramType: 'int?',
                functionParamMap:
                  'event.actionTaskID || event.agendaTaskID || {get api/task?taskID=event.agendaTaskID}.task[].taskID || {get api/task?taskID=event.actionTaskID}.task[].taskID',
              },
              {
                paramName: 'isCompletionOptional',
                paramType: 'bool?',
              },
              {
                paramName: 'startDate',
                paramType: 'dateTime?',
              },
              {
                paramName: 'durationMinutes',
                paramType: 'int?',
              },
              {
                paramName: 'operation',
                paramType: 'object',
                functionParamMap: '/api/operation/meta',
              },
            ],
            rel: ['http://kvau.lt/api/event/agenda+add'],
          },
          {
            encType: 'application/x-www-form-urlencoded',
            contentType: 'application/json',
            href: '/api/task/meta',
            media: '',
            method: 'get',
            targetPref: '',
            title: 'Task meta',
            parameters: [],
            rel: ['http://kvau.lt/api/task/meta'],
          },
          {
            encType: 'application/x-www-form-urlencoded',
            contentType: 'application/json',
            href: 'https://cardoneventuresceo.com/v25/nl/components/events/functions.asp?command=loadEventMinutes',
            media: '',
            method: 'get',
            targetPref: '',
            title: 'Get Meeting Minutes',
            parameters: [],
            rel: ['http://kvau.lt/api/event/minutes'],
          },
          {
            encType: 'application/x-www-form-urlencoded',
            contentType: 'application/json',
            href: 'api/event/{eventID:int}/minutes',
            media: '',
            method: 'post',
            targetPref: '',
            title: 'Add Meeting Minutes',
            parameters: [
              {
                paramName: 'actionType',
                paramType: 'string',
              },
              {
                paramName: 'noticeText',
                paramType: 'string',
              },
              {
                paramName: 'taskID',
                paramType: 'int?',
              },
            ],
            rel: ['http://kvau.lt/api/event/minutes+add'],
          },
          {
            encType: 'application/x-www-form-urlencoded',
            contentType: 'application/json',
            href: 'api/event/{eventID:int}/minutes/rating',
            media: '',
            method: 'get',
            targetPref: '',
            title: 'Get Meeting Minutes Approval Rating',
            parameters: [],
            rel: ['http://kvau.lt/api/event/minutes/rating'],
          },
          {
            encType: 'application/x-www-form-urlencoded',
            contentType: 'text/calendar',
            href: 'api/event/ical',
            media: '',
            method: 'get',
            targetPref: '',
            title: 'Get iCal Publication',
            parameters: [],
            rel: ['http://kvau.lt/api/event/ical'],
          },
        ],
      }
    },
    invalidMissingRequired: (propName: string) => {
      return {
        data: [],
        links: [],
        error: {
          logID: -1,
          sts: -1000,
          msg: `validation error: ${propName} required`,
          technical: `parameters must contain ${propName}`,
        },
      }
    },
  },
  post: {
    success: () => {
      return {
        recordsAffected: -2,
        eventID: 2439678,
        addRecurrenceRuleResponses: [
          {
            icalRecurrenceRule: 'FREQ=WEEKLY;UNTIL=20240130T195900Z;BYDAY=MO',
            icalRecurrenceID: 11420,
            sts: 0,
            msg: '',
          },
        ],
        session: {
          userID: 2209853,
          userName: 'John Bailey',
          changePassword: false,
          termsOfServiceSignatureRequired: false,
          adminID: 0,
          teamListSyncDate: '1900-01-01T00:00:00+00:00',
          koPermissionSyncDate: '1900-01-01T00:00:00+00:00',
          domainID: 1698652,
          timeOutMnts: 129600,
          onCourseURL: 'https://cardoneventuresceo.com',
          profileThumbPath:
            '/v2/domains/1698652/assets/2209853_kvemjhrbf1w_200px.jpg',
          teamRootID: 1763850,
          roleID: 432,
          onlinePreference: 'ocAVAILABLE',
        },
        error: {
          sts: 0,
          msg: 'initialized',
        },
        links: [],
      }
    },
  },
  /**
   * @deprecated Use EventEndpointResponses.get.success()
   */
  success: () => EventEndpointResponses.get.success(),
  /**
   * @deprecated Use EventEndpointResponses.get.invalidMissingRequired()
   */
  invalidMissingRequired: (propName: string) =>
    EventEndpointResponses.get.invalidMissingRequired(propName),
}
