export const BlockPrerequisitesEndpointResponses = {
  success: () => {
    return {
      prerequisites: [
        {
          prerequisiteID: 2540067,
          prerequisiteName: 'Droid Technicals',
          prerequisiteType: 'ocASSIGNMENT',
          parentID: 2540063,
          sequence: 1,
          itemName: 'Droid Technicals',
          itemType: 'ocLESSON',
          itemSubtype: 'ocASSIGNMENT',
          aboutID: 2540066,
          activeStatus: 'ocENABLED',
          isCredit: false,
          creditUnits: 0,
          creditUnitDesc: '',
          isResource: false,
          masteryScore: 0,
          setCompletion: 0,
          createdBy: 1960713,
          createdDate: '2024-06-18T19:22:32.617+00:00',
          createdName: 'Rinard, Joshua',
          isDemo: false,
          isOptional: false,
          setStatus: 2,
          courseItemStatus: 'ocENABLED',
          itemDescription: '',
          isFeatured: false,
          images: [],
          expirationDate: '1900-01-01T00:00:00+00:00',
        },
        {
          prerequisiteID: 2848444,
          prerequisiteName: 'Droids 105',
          prerequisiteType: 'ocNOTYPE',
          parentID: 2540063,
          sequence: 2,
          itemName: 'Droids 105',
          itemType: 'ocBLOCK',
          itemSubtype: 'ocITEM',
          aboutID: 2848443,
          activeStatus: 'ocENABLED',
          isCredit: false,
          creditUnits: 0,
          creditUnitDesc: ' ',
          isResource: false,
          masteryScore: 0,
          setCompletion: 0,
          createdBy: 1960713,
          createdDate: '2024-10-25T03:21:01.1+00:00',
          createdName: 'Rinard, Joshua',
          isDemo: false,
          isOptional: false,
          setStatus: 2,
          courseItemStatus: 'ocENABLED',
          itemDescription: '',
          isFeatured: false,
          images: [],
          expirationDate: '1900-01-01T00:00:00+00:00',
        },
      ],
      recordsAffected: -1,
      registrationCount: 1,
      session: {
        userID: 1960713,
        userName: 'Joshua Rinard',
        changePassword: false,
        termsOfServiceSignatureRequired: false,
        adminID: 0,
        teamListSyncDate: '1900-01-01T00:00:00-08:00',
        koPermissionSyncDate: '2024-01-16T08:59:27.27-08:00',
        domainID: 551,
        timeOutMnts: 90,
        onCourseURL: 'https://oc.mocaworks.com',
        profileThumbPath:
          '/v2/domains/551/assets/1960713_lqzzjhduv2h_200px.jpg',
        teamRootID: 551,
        roleID: 1,
        onlinePreference: 'ocHIDDEN',
      },
      error: {
        sts: 0,
        msg: 'initialized',
      },
      links: [],
    }
  },

  invalidMissingRequired: (propName: string) => {
    return {
      data: [],
      links: [],
      error: {
        logID: -1,
        sts: -1000,
        msg: `validation error: ${propName} required`,
        technical: `parameters must contain ${propName}`,
      },
    }
  },
}
