export const SearchKnowledgeObjectsEndpointResponses = {
  success: () => {
    return {
      resultCountTotal: 5,
      searchID: 245247,
      results: [
        {
          relevanceRank: 1,
          scoreKeyWord: 0,
          scoreElementName: 1024,
          scoreElementDescription: 0,
          scoreContent: 0,
          scoreTotal: 1024,
          scorehit: 0,
          scoreContainsAll: 1,
          hasDelete: true,
          hasChange: true,
          permissionSources: {
            blocks: false,
            lessons: false,
            libraryBackTeam: false,
            libraryFrontTeam: false,
            libraryFrontPerson: false,
            survey: false,
            exam: false,
            examTpa: false,
            noticeTeam: false,
            noticesPerson: false,
            devPlans: false,
            devTask: false,
            newsTeam: false,
            enrollment: false,
            explicitPermission: true,
            catalogCurriculumPub: false,
          },
          assets: [
            {
              assetID: 2056700,
              assetName: 'Droid2.jpg',
              assetDesc: 'profileImageID',
              assetType: 'ocProfilePhoto',
              orientation: 'ocVOID',
              modifiedDate: '2022-04-05T16:55:30.14',
              modifiedByID: 1960713,
              createdDate: '2022-04-05T16:55:30.137',
              createdByID: 1960713,
              createdByName: 'Joshua Rinard',
              sequence: 1,
              softwareRequirements: '',
              originalMD5: 'zifQ0f4rwxjbZO5mGXCYcw==',
              domainID: 551,
              encodings: [
                {
                  encodingType: 'ocDEFAULT',
                  mimeType: 'image/jpeg',
                  modifiedDate: '2022-04-05T16:55:30.14',
                  height: 410,
                  width: 606,
                  length: 0,
                  sizeBytes: 0,
                  techNote: '',
                  activeStatus: 'ocENABLED',
                  pathURL:
                    '/v2/domains/551/assets/profilePhotos/2056640_gd1ins0wlyt_1024px.jpg',
                },
                {
                  encodingType: 'ocTHUMBNAIL',
                  mimeType: 'image/jpeg',
                  modifiedDate: '2022-04-05T16:55:30.14',
                  height: 410,
                  width: 606,
                  length: 0,
                  sizeBytes: 0,
                  techNote: '',
                  activeStatus: 'ocENABLED',
                  pathURL:
                    '/v2/domains/551/assets/profilePhotos/2056640_gd1ins0wlyt_200px.jpg',
                },
              ],
              courseItemID: 2056640,
            },
            {
              assetID: 2056701,
              assetName: 'Droids.png',
              assetDesc: 'profileImageFeaturedID',
              assetType: 'ocProfilePhoto',
              orientation: 'ocVOID',
              modifiedDate: '2022-04-05T16:55:30.503',
              modifiedByID: 1960713,
              createdDate: '2022-04-05T16:55:30.503',
              createdByID: 1960713,
              createdByName: 'Joshua Rinard',
              sequence: 2,
              softwareRequirements: '',
              originalMD5: 'foF6TlVb7Uu5/CcdNC9RTA==',
              domainID: 551,
              encodings: [
                {
                  encodingType: 'ocDEFAULT',
                  mimeType: 'image/jpeg',
                  modifiedDate: '2022-04-05T16:55:30.503',
                  height: 370,
                  width: 1111,
                  length: 0,
                  sizeBytes: 0,
                  techNote: '',
                  activeStatus: 'ocENABLED',
                  pathURL:
                    '/v2/domains/551/assets/profilePhotos/2056640_5wjxkijico2_1024px.jpg',
                },
                {
                  encodingType: 'ocTHUMBNAIL',
                  mimeType: 'image/jpeg',
                  modifiedDate: '2022-04-05T16:55:30.503',
                  height: 370,
                  width: 1111,
                  length: 0,
                  sizeBytes: 0,
                  techNote: '',
                  activeStatus: 'ocENABLED',
                  pathURL:
                    '/v2/domains/551/assets/profilePhotos/2056640_5wjxkijico2_200px.jpg',
                },
              ],
              courseItemID: 2056640,
            },
          ],
          starRating: {
            sessionUsersRating: 0,
            sumAllRatings: 0,
            countRatings: 0,
          },
          element: {
            name: 'Droids 101',
            locID: 2056640,
            ocType: 'ocBLOCK',
            elementID: 2056640,
            elementName: 'Droids 101',
            elementDesc: 'Test Course',
            elementType: 'ocBLOCK',
            elementSubType: 'ocITEM',
            domainID: 551,
            createdByID: 1960713,
            createdDate: '2022-04-05T16:06:57.7+00:00',
            primaryElementID: 551,
            modifiedDate: '2024-12-06T20:34:33.62+00:00',
            createdBy: {
              name: 'Joshua Rinard',
              ocType: 'ocELEMENT',
              elementName: 'Joshua Rinard',
            },
          },
        },
        {
          relevanceRank: 2,
          scoreKeyWord: 0,
          scoreElementName: 1024,
          scoreElementDescription: 0,
          scoreContent: 0,
          scoreTotal: 1024,
          scorehit: 0,
          scoreContainsAll: 1,
          hasDelete: true,
          hasChange: true,
          permissionSources: {
            blocks: false,
            lessons: false,
            libraryBackTeam: false,
            libraryFrontTeam: false,
            libraryFrontPerson: false,
            survey: false,
            exam: false,
            examTpa: false,
            noticeTeam: false,
            noticesPerson: false,
            devPlans: false,
            devTask: false,
            newsTeam: false,
            enrollment: false,
            explicitPermission: true,
            catalogCurriculumPub: false,
          },
          starRating: {
            sessionUsersRating: 0,
            sumAllRatings: 0,
            countRatings: 0,
          },
          element: {
            name: 'Droids 102',
            locID: 2468375,
            ocType: 'ocBLOCK',
            elementID: 2468375,
            elementName: 'Droids 102',
            elementDesc: '',
            elementType: 'ocBLOCK',
            elementSubType: 'ocITEM',
            domainID: 551,
            createdByID: 1960713,
            createdDate: '2024-02-27T22:04:15.027+00:00',
            primaryElementID: 551,
            modifiedDate: '2024-12-06T20:40:18.673+00:00',
            createdBy: {
              name: 'Joshua Rinard',
              ocType: 'ocELEMENT',
              elementName: 'Joshua Rinard',
            },
          },
        },
        {
          relevanceRank: 3,
          scoreKeyWord: 0,
          scoreElementName: 1024,
          scoreElementDescription: 0,
          scoreContent: 0,
          scoreTotal: 1024,
          scorehit: 0,
          scoreContainsAll: 1,
          hasDelete: true,
          hasChange: true,
          permissionSources: {
            blocks: false,
            lessons: false,
            libraryBackTeam: false,
            libraryFrontTeam: false,
            libraryFrontPerson: false,
            survey: false,
            exam: false,
            examTpa: false,
            noticeTeam: false,
            noticesPerson: false,
            devPlans: false,
            devTask: false,
            newsTeam: false,
            enrollment: false,
            explicitPermission: true,
            catalogCurriculumPub: false,
          },
          starRating: {
            sessionUsersRating: 0,
            sumAllRatings: 0,
            countRatings: 0,
          },
          element: {
            name: 'Droids 104',
            locID: 2540063,
            ocType: 'ocBLOCK',
            elementID: 2540063,
            elementName: 'Droids 104',
            elementDesc: '',
            elementType: 'ocBLOCK',
            elementSubType: 'ocITEM',
            domainID: 551,
            createdByID: 1960713,
            createdDate: '2024-06-18T19:20:39.327+00:00',
            primaryElementID: 551,
            modifiedDate: '2024-06-18T19:21:47.32+00:00',
            createdBy: {
              name: 'Joshua Rinard',
              ocType: 'ocELEMENT',
              elementName: 'Joshua Rinard',
            },
          },
        },
      ],
      session: {
        adminID: 0,
        changePassword: false,
        domainID: 551,
        koPermissionSyncDate: '2023-09-29T15:25:54.27+00:00',
        onCourseURL: 'https://cherry.mocaworks.com',
        onlinePreference: 'ocHIDDEN',
        profileThumbPath:
          '/v2/domains/551/assets/1960713_tsc3eykcizn_200px.jpg',
        roleID: 1,
        teamRootID: 551,
        teamListSyncDate: '1900-01-01T00:00:00+00:00',
        termsOfServiceSignatureRequired: false,
        timeOutMnts: 129600,
        userID: 1960713,
        userName: 'Joshua Rinard',
      },
      error: {
        sts: 0,
        msg: 'initialized',
      },
      links: [],
    }
  },

  invalidMissingRequired: (propName: string) => {
    return {
      data: [],
      links: [],
      error: {
        logID: -1,
        sts: -1000,
        msg: `validation error: ${propName} required`,
        technical: `parameters must contain ${propName}`,
      },
    }
  },
}
