import { faker } from '@faker-js/faker'

/**
 * To populate this please run
 * px g @tyto/scribe:postman
 */
export const CatalogCurriculumPublicationEndpointResponses = {
  success: (example: 'fixed' | 'dynamic' = 'fixed') => {
    if (example === 'dynamic') {
      return {
        catalogs: [
          {
            restrictedAdd: false,
            restrictedChange: false,
            restrictedDelete: false,
            restrictedShare: false,
            restrictedview: true,
            catalogID: faker.number.int(),
            catalogType: faker.lorem.word(),
            childContainers: [],
            childItems: [
              {
                createdByID: faker.number.int(),
                createdDate: faker.date.recent().toISOString(),
                description: faker.lorem.words(),
                domainID: faker.number.int({ min: 100, max: 999 }),
                hasAdd: true,
                hasChange: true,
                hasDelete: true,
                images: [],
                locID: faker.number.int(),
                modifiedByID: faker.number.int(),
                modifiedDate: faker.date.recent().toISOString(),
                name: faker.company.name(),
                ocType: faker.lorem.word(),
                outsideID: faker.lorem.word(),
                parentCatalogID: faker.number.int(),
                pathIDs: faker.lorem.word(),
                pathName: faker.lorem.word(),
                primaryElementID: faker.number.int(),
                primaryElementTreeSerialLeft: faker.number.int(),
                siblingSeq: faker.number.int(),
                thumbnailPath: faker.lorem.word(),
                about: {
                  catalogIDs: [],
                  curriculumPublicationID: faker.number.int(),
                  beginDate: faker.date.recent().toISOString(),
                  expiresDate: faker.date.future().toISOString(),
                  curriculumID: faker.number.int(),
                  curriculumType: faker.lorem.word(),
                  curriculum: {
                    catalogIDs: [faker.number.int()],
                    blockID: faker.number.int(),
                    courseIdentifier: faker.lorem.word(),
                    teamRoot: faker.number.int(),
                    expirationDate: faker.date.future(),
                    products: [],
                    author: {
                      name: faker.lorem.word(),
                      title: faker.lorem.word(),
                      authorID: faker.number.int(),
                      photoAsset: {
                        assetID: faker.number.int(),
                        assetName: faker.lorem.word(),
                        assetDesc: faker.lorem.sentence(),
                        assetType: 'ocPhoto',
                        orientation: 'ocVOID',
                        modifiedDate: faker.date.recent(),
                        modifiedByID: faker.number.int(),
                        createdDate: faker.date.past(),
                        createdByID: faker.number.int(),
                        createdByName: faker.lorem.word(),
                        sequence: faker.number.int(),
                        softwareRequirements: faker.lorem.sentence(),
                        originalMD5: faker.lorem.word(),
                        domainID: faker.number.int({ min: 100, max: 999 }),
                        encodings: [],
                        courseItemID: faker.number.int(),
                      },
                    },
                    audienceDesc: faker.lorem.sentence(),
                    difficultyDesc: faker.lorem.sentence(),
                    expectationDesc: faker.lorem.sentence(),
                    durationEstimate: faker.number.toString(),
                    isContainerUnit: true,
                    internalTitle: faker.lorem.word(),
                    name: faker.vehicle.model(),
                    locID: faker.number.int(),
                    ocType: faker.lorem.word(),
                    elementID: faker.number.int(),
                    elementName: faker.lorem.word(),
                    elementDesc: faker.lorem.sentence(),
                    elementType: faker.lorem.word(),
                    elementSubType: faker.lorem.word(),
                    domainID: faker.number.int({ min: 100, max: 999 }),
                    outsideID: faker.lorem.word(),
                    createdByID: faker.number.int(),
                    createdDate: faker.date.recent(),
                    primaryElementID: faker.number.int(),
                    modifiedByID: faker.number.int(),
                    modifiedDate: faker.date.recent(),
                    shareChangedDate: faker.date.recent(),
                    shareChangedByID: faker.number.int(),
                    activeStatus: 'ocENABLED',
                  },
                  name: faker.company.name(),
                  locID: faker.number.int(),
                  ocType: faker.lorem.word(),
                  elementID: faker.number.int(),
                  elementName: faker.lorem.word(),
                  elementDesc: faker.lorem.sentence(),
                  elementType: faker.lorem.word(),
                  elementSubType: faker.lorem.word(),
                  domainID: faker.number.int({ min: 100, max: 999 }),
                  outsideID: faker.lorem.word(),
                  createdByID: faker.number.int(),
                  createdDate: faker.lorem.word(),
                  primaryElementID: faker.number.int(),
                  modifiedByID: faker.number.int(),
                  modifiedDate: faker.lorem.word(),
                  shareChangedDate: faker.lorem.word(),
                  shareChangedByID: faker.number.int(),
                  activeStatus: 'ocENABLED',
                },
                activeStatus: 'ocENABLED',
                catalogID: 99334,
                catalogItemID: 99331,
                catalogItemSubType: 'ocCONTAINER',
                catalogItemType: 'ocCATALOG',
                catalogType: 'ocCURRICULUMPUB',
                childContainers: [],
                childItems: [],
              },
            ],
            hasAdd: true,
            hasChange: true,
            hasDelete: true,
            createdDate: faker.date.recent().toISOString(),
            description: faker.lorem.words(),
            domainID: faker.number.int({ min: 100, max: 99999 }),
            modifiedDate: faker.date.recent().toISOString(),
            name: faker.company.name(),
            siblingSeq: faker.number.int(),
            activeStatus: 'ocENABLED',
            ocType: faker.lorem.word(),
            elementID: faker.number.int(),
            elementName: faker.lorem.word(),
            elementDesc: faker.lorem.sentence(),
            elementType: faker.lorem.word(),
            catalogItemID: 2056612,
            catalogItemSubType: 'ocCONTAINER',
            catalogItemType: 'ocCATALOG',
            createdByID: 1960713,
            images: [
              {
                originalMimeType: 'image/png',
                height: 596,
                width: 1980,
                imageName: 'bannerOverride',
                pathURL: '/v2/domains/551/assets/profilePhotos/2056612_jj3b',
              },
            ],
            locID: 2056612,
            modifiedByID: 1960713,
            outsideID: '',
            parentCatalogID: 0,
            pathIDs: ',',
            pathName: '\t',
            primaryElementID: 551,
            primaryElementTreeSerialLeft: 1,
            thumbnailPath: '',
          },
        ],
        session: {
          adminID: 0,
          changePassword: false,
          domainID: 551,
          koPermissionSyncDate: '2023-09-29T15:25:54.27+00:00',
          onCourseURL: 'https://cherry.mocaworks.com',
          onlinePreference: 'ocHIDDEN',
          profileThumbPath:
            '/v2/domains/551/assets/1960713_tsc3eykcizn_200px.jpg',
          roleID: 1,
          teamRootID: 551,
          teamListSyncDate: '1900-01-01T00:00:00+00:00',
          termsOfServiceSignatureRequired: false,
          timeOutMnts: 129600,
          userID: 1960713,
          userName: 'Joshua Rinard',
        },
        error: {
          sts: 0,
          msg: 'initialized',
        },
        links: [],
      }
    }
    return {
      catalogs: [
        {
          childContainers: [
            {
              activeStatus: 'ocENABLED',
              catalogID: 99334,
              catalogItemID: 99331,
              catalogItemSubType: 'ocCONTAINER',
              catalogItemType: 'ocCATALOG',
              catalogType: 'ocCURRICULUMPUB',
              childContainers: [],
              childItems: [],
              createdByID: 4799,
              createdDate: '2011-05-25T17:26:05.293-07:00',
              description: '',
              domainID: 551,
              hasAdd: true,
              hasChange: true,
              hasDelete: true,
              images: [],
              locID: 99334,
              modifiedByID: 4799,
              modifiedDate: '2017-01-26T11:47:41.103-08:00',
              name: 'oc Child Catalog',
              ocType: 'ocELEMENT',
              outsideID: '',
              parentCatalogID: 99331,
              pathIDs: ',99331,',
              pathName: '\\toc Root Catalog\\',
              primaryElementID: 551,
              primaryElementTreeSerialLeft: 1,
              siblingSeq: 16,
              thumbnailPath: '',
            },
          ],
          activeStatus: 'ocENABLED',
          catalogID: 2056612,
          catalogItemID: 2056612,
          catalogItemSubType: 'ocCONTAINER',
          catalogItemType: 'ocCATALOG',
          catalogType: 'ocCURRICULUMPUB',
          childItems: [
            {
              about: {
                catalogIDs: [2056616, 2056616],
                curriculumPublicationID: 2056615,
                beginDate: '1900-01-01T00:00:00-08:00',
                expiresDate: '1900-01-01T00:00:00-08:00',
                curriculumID: 2045402,
                curriculumType: 'ocBLOCK',
                curriculum: {
                  catalogIDs: [],
                  blockID: 2045402,
                  courseIdentifier: '',
                  teamRoot: 551,
                  expirationDate: '1900-01-01T00:00:00-08:00',
                  profileImage: {
                    assetID: 2147187,
                    assetName: '2045402_nmv31brvode.jpg',
                    assetDesc: 'profileImageID',
                    assetType: 'ocProfilePhoto',
                    orientation: 'ocVOID',
                    modifiedDate: '2022-11-17T13:51:07.65',
                    modifiedByID: 1960713,
                    createdDate: '2022-11-17T13:51:07.65',
                    createdByID: 1960713,
                    createdByName: 'Joshua Rinard',
                    sequence: 4,
                    softwareRequirements: '',
                    originalMD5: 'N446rOST6RLZjrpqNzuDaw==',
                    domainID: 551,
                    encodings: [
                      {
                        encodingType: 'ocDEFAULT',
                        mimeType: 'image/jpeg',
                        modifiedDate: '2022-11-17T13:51:07.65',
                        height: 410,
                        width: 606,
                        length: 0,
                        sizeBytes: 0,
                        techNote: '',
                        activeStatus: 'ocENABLED',
                        pathURL:
                          '/v2/domains/551/assets/profilePhotos/2045402_1epipgadawj_1024px.jpg',
                      },
                      {
                        encodingType: 'ocORIGINAL',
                        mimeType: 'image/jpeg',
                        modifiedDate: '2022-11-17T13:51:07.65',
                        height: 410,
                        width: 606,
                        length: 0,
                        sizeBytes: 133082,
                        techNote: '',
                        activeStatus: 'ocENABLED',
                        pathURL:
                          '/v2/domains/551/assets/profilePhotos/2045402_1epipgadawj.jpg',
                      },
                      {
                        encodingType: 'ocTHUMBNAIL',
                        mimeType: 'image/jpeg',
                        modifiedDate: '2022-11-17T13:51:07.65',
                        height: 410,
                        width: 606,
                        length: 0,
                        sizeBytes: 0,
                        techNote: '',
                        activeStatus: 'ocENABLED',
                        pathURL:
                          '/v2/domains/551/assets/profilePhotos/2045402_1epipgadawj_200px.jpg',
                      },
                    ],
                    courseItemID: 2045402,
                  },
                  profileImageFeatured: {
                    assetID: 2045437,
                    assetName: 'lighting.jpg',
                    assetDesc: 'profileImageFeaturedID',
                    assetType: 'ocProfilePhoto',
                    orientation: 'ocVOID',
                    modifiedDate: '2022-03-04T11:51:19.39',
                    modifiedByID: 2043811,
                    createdDate: '2022-03-04T11:51:19.39',
                    createdByID: 2043811,
                    createdByName: 'Johann Loch',
                    sequence: 2,
                    softwareRequirements: '',
                    originalMD5: 'XpOlDTs/7v8e+zS4rFS/sw==',
                    domainID: 551,
                    encodings: [
                      {
                        encodingType: 'ocDEFAULT',
                        mimeType: 'image/jpeg',
                        modifiedDate: '2022-03-04T11:51:19.39',
                        height: 370,
                        width: 1111,
                        length: 0,
                        sizeBytes: 0,
                        techNote: '',
                        activeStatus: 'ocENABLED',
                        pathURL:
                          '/v2/domains/551/assets/profilePhotos/2045402_nmv31brvode_1024px.jpg',
                      },
                      {
                        encodingType: 'ocORIGINAL',
                        mimeType: 'image/jpeg',
                        modifiedDate: '2022-03-04T11:51:19.39',
                        height: 370,
                        width: 1111,
                        length: 0,
                        sizeBytes: 191646,
                        techNote: '',
                        activeStatus: 'ocENABLED',
                        pathURL:
                          '/v2/domains/551/assets/profilePhotos/2045402_nmv31brvode.jpg',
                      },
                      {
                        encodingType: 'ocTHUMBNAIL',
                        mimeType: 'image/jpeg',
                        modifiedDate: '2022-03-04T11:51:19.39',
                        height: 370,
                        width: 1111,
                        length: 0,
                        sizeBytes: 0,
                        techNote: '',
                        activeStatus: 'ocENABLED',
                        pathURL:
                          '/v2/domains/551/assets/profilePhotos/2045402_nmv31brvode_200px.jpg',
                      },
                    ],
                    courseItemID: 2045402,
                  },
                  products: [],
                  author: {
                    name: 'Johann Loch',
                    title: '',
                    authorID: 2043811,
                    photoAsset: {
                      assetID: 2153412,
                      assetName: 'IMG-1180.jpg',
                      assetDesc: '',
                      assetType: 'ocPhoto',
                      orientation: 'ocVOID',
                      modifiedDate: '2023-01-18T11:50:39.073',
                      modifiedByID: 2043811,
                      createdDate: '2023-01-18T11:50:39.073',
                      createdByID: 2043811,
                      createdByName: 'Johann Loch',
                      sequence: 5,
                      softwareRequirements: '',
                      originalMD5: 'y+lt+QEL+cJxT5Za/I40bw==',
                      domainID: 551,
                      encodings: [
                        {
                          encodingType: 'ocDEFAULT',
                          mimeType: 'image/jpeg',
                          modifiedDate: '2023-01-18T11:50:39.073',
                          height: 500,
                          width: 500,
                          length: 0,
                          sizeBytes: 0,
                          techNote: '',
                          activeStatus: 'ocENABLED',
                          pathURL:
                            '/tyto/api/person/profilephoto?assetID=2153412&encoding=ocDEFAULT',
                        },
                        {
                          encodingType: 'ocORIGINAL',
                          mimeType: 'image/jpeg',
                          modifiedDate: '2023-01-18T11:50:39.073',
                          height: 500,
                          width: 500,
                          length: 0,
                          sizeBytes: 221702,
                          techNote: '',
                          activeStatus: 'ocENABLED',
                          pathURL:
                            '/tyto/api/person/profilephoto?assetID=2153412&encoding=ocORIGINAL',
                        },
                        {
                          encodingType: 'ocTHUMBNAIL',
                          mimeType: 'image/jpeg',
                          modifiedDate: '2023-01-18T11:50:39.073',
                          height: 500,
                          width: 500,
                          length: 0,
                          sizeBytes: 0,
                          techNote: '',
                          activeStatus: 'ocENABLED',
                          pathURL:
                            '/v2/domains/551/assets/2043811_vytweeebxuc_200px.jpg',
                        },
                      ],
                      courseItemID: 2043811,
                    },
                  },
                  audienceDesc: '',
                  difficultyDesc: 'ocBEGINNER',
                  expectationDesc: '',
                  durationEstimate: '5 Minutes',
                  isContainerUnit: false,
                  internalTitle: 'sdas',
                  name: "Johann's Course",
                  locID: 2045402,
                  ocType: 'ocBLOCK',
                  elementID: 2045402,
                  elementName: "Johann's Course",
                  elementDesc:
                    'Test course by Johann that displays the variety of item types regardless if they are supported.',
                  elementType: 'ocBLOCK',
                  elementSubType: 'ocITEM',
                  domainID: 551,
                  outsideID: '',
                  createdByID: 2043811,
                  createdDate: '2022-03-04T11:34:03.28-08:00',
                  primaryElementID: 551,
                  modifiedByID: 2043811,
                  modifiedDate: '2023-08-11T07:17:55.063-07:00',
                  shareChangedDate: '2023-09-26T16:24:34.073-07:00',
                  shareChangedByID: 1960713,
                  activeStatus: 'ocENABLED',
                },
                name: 'Knowledge Vault',
                locID: 2056615,
                ocType: 'ocCURRICULUMPUB',
                elementID: 2056615,
                elementName: 'Knowledge Vault',
                elementDesc: '',
                elementType: 'ocCURRICULUMPUB',
                elementSubType: 'ocBLOCK',
                domainID: 551,
                outsideID: '',
                createdByID: 1960713,
                createdDate: '2022-04-05T15:55:31.34-07:00',
                primaryElementID: 551,
                modifiedByID: 1960713,
                modifiedDate: '2022-04-05T15:55:31.34-07:00',
                shareChangedDate: '2022-04-05T15:55:31.35-07:00',
                shareChangedByID: 1960713,
                activeStatus: 'ocENABLED',
              },
              catalogID: 2056616,
              description: '',
              catalogType: 'ocCURRICULUMPUB',
              parentCatalogID: 2056612,
              primaryElementTreeSerialLeft: 1,
              pathName: '\tMocaworks Dev Catalog\t',
              pathIDs: ',2056612,',
              thumbnailPath: '',
              catalogItemID: 2056615,
              catalogItemType: 'ocCURRICULUMPUB',
              catalogItemSubType: 'ocBLOCK',
              hasChange: true,
              hasAdd: true,
              hasDelete: true,
              siblingSeq: 4,
              name: '',
              locID: 2056616,
              ocType: 'ocELEMENT',
              domainID: 551,
              outsideID: '',
              createdByID: 1960713,
              createdDate: '2022-04-05T15:55:31.35-07:00',
              primaryElementID: 551,
              modifiedByID: 1960713,
              modifiedDate: '2023-02-15T12:43:34.71-08:00',
              activeStatus: 'ocENABLED',
            },
            {
              about: {
                catalogIDs: [2056709, 2147369, 2056709, 2147369],
                curriculumPublicationID: 2056708,
                beginDate: '1900-01-01T00:00:00-08:00',
                expiresDate: '1900-01-01T00:00:00-08:00',
                curriculumID: 2056640,
                curriculumType: 'ocBLOCK',
                curriculum: {
                  catalogIDs: [],
                  blockID: 2056640,
                  courseIdentifier: '',
                  teamRoot: 551,
                  expirationDate: '1900-01-01T00:00:00-08:00',
                  profileImage: {
                    assetID: 2056700,
                    assetName: 'Droid2.jpg',
                    assetDesc: 'profileImageID',
                    assetType: 'ocProfilePhoto',
                    orientation: 'ocVOID',
                    modifiedDate: '2022-04-05T16:55:30.14',
                    modifiedByID: 1960713,
                    createdDate: '2022-04-05T16:55:30.137',
                    createdByID: 1960713,
                    createdByName: 'Joshua Rinard',
                    sequence: 1,
                    softwareRequirements: '',
                    originalMD5: 'zifQ0f4rwxjbZO5mGXCYcw==',
                    domainID: 551,
                    encodings: [
                      {
                        encodingType: 'ocDEFAULT',
                        mimeType: 'image/jpeg',
                        modifiedDate: '2022-04-05T16:55:30.14',
                        height: 410,
                        width: 606,
                        length: 0,
                        sizeBytes: 0,
                        techNote: '',
                        activeStatus: 'ocENABLED',
                        pathURL:
                          '/v2/domains/551/assets/profilePhotos/2056640_gd1ins0wlyt_1024px.jpg',
                      },
                      {
                        encodingType: 'ocORIGINAL',
                        mimeType: 'image/jpeg',
                        modifiedDate: '2022-04-05T16:55:30.14',
                        height: 410,
                        width: 606,
                        length: 0,
                        sizeBytes: 106278,
                        techNote: '',
                        activeStatus: 'ocENABLED',
                        pathURL:
                          '/v2/domains/551/assets/profilePhotos/2056640_gd1ins0wlyt.jpg',
                      },
                      {
                        encodingType: 'ocTHUMBNAIL',
                        mimeType: 'image/jpeg',
                        modifiedDate: '2022-04-05T16:55:30.14',
                        height: 410,
                        width: 606,
                        length: 0,
                        sizeBytes: 0,
                        techNote: '',
                        activeStatus: 'ocENABLED',
                        pathURL:
                          '/v2/domains/551/assets/profilePhotos/2056640_gd1ins0wlyt_200px.jpg',
                      },
                    ],
                    courseItemID: 2056640,
                  },
                  profileImageFeatured: {
                    assetID: 2056701,
                    assetName: 'Droids.png',
                    assetDesc: 'profileImageFeaturedID',
                    assetType: 'ocProfilePhoto',
                    orientation: 'ocVOID',
                    modifiedDate: '2022-04-05T16:55:30.503',
                    modifiedByID: 1960713,
                    createdDate: '2022-04-05T16:55:30.503',
                    createdByID: 1960713,
                    createdByName: 'Joshua Rinard',
                    sequence: 2,
                    softwareRequirements: '',
                    originalMD5: 'foF6TlVb7Uu5/CcdNC9RTA==',
                    domainID: 551,
                    encodings: [
                      {
                        encodingType: 'ocDEFAULT',
                        mimeType: 'image/jpeg',
                        modifiedDate: '2022-04-05T16:55:30.503',
                        height: 370,
                        width: 1111,
                        length: 0,
                        sizeBytes: 0,
                        techNote: '',
                        activeStatus: 'ocENABLED',
                        pathURL:
                          '/v2/domains/551/assets/profilePhotos/2056640_5wjxkijico2_1024px.jpg',
                      },
                      {
                        encodingType: 'ocORIGINAL',
                        mimeType: 'image/png',
                        modifiedDate: '2022-04-05T16:55:30.503',
                        height: 370,
                        width: 1111,
                        length: 0,
                        sizeBytes: 224551,
                        techNote: '',
                        activeStatus: 'ocENABLED',
                        pathURL:
                          '/v2/domains/551/assets/profilePhotos/2056640_5wjxkijico2.png',
                      },
                      {
                        encodingType: 'ocTHUMBNAIL',
                        mimeType: 'image/jpeg',
                        modifiedDate: '2022-04-05T16:55:30.503',
                        height: 370,
                        width: 1111,
                        length: 0,
                        sizeBytes: 0,
                        techNote: '',
                        activeStatus: 'ocENABLED',
                        pathURL:
                          '/v2/domains/551/assets/profilePhotos/2056640_5wjxkijico2_200px.jpg',
                      },
                    ],
                    courseItemID: 2056640,
                  },
                  products: [],
                  author: {
                    name: 'Joshua Rinard',
                    title: 'React Developer',
                    authorID: 1960713,
                    photoAsset: {
                      assetID: 2158389,
                      assetName: 'IMG_6513.jpeg',
                      assetDesc: '',
                      assetType: 'ocPhoto',
                      orientation: 'ocVOID',
                      modifiedDate: '2023-02-22T11:32:59.283',
                      modifiedByID: 1960713,
                      createdDate: '2023-02-22T11:32:59.283',
                      createdByID: 1960713,
                      createdByName: 'Joshua Rinard',
                      sequence: 4,
                      softwareRequirements: '',
                      originalMD5: 'X0eoXVpnXzzBtZH+3lDdpA==',
                      domainID: 551,
                      encodings: [
                        {
                          encodingType: 'ocDEFAULT',
                          mimeType: 'image/jpeg',
                          modifiedDate: '2023-02-22T11:32:59.283',
                          height: 500,
                          width: 500,
                          length: 0,
                          sizeBytes: 0,
                          techNote: '',
                          activeStatus: 'ocENABLED',
                          pathURL:
                            '/tyto/api/person/profilephoto?assetID=2158389&encoding=ocDEFAULT',
                        },
                        {
                          encodingType: 'ocORIGINAL',
                          mimeType: 'image/jpeg',
                          modifiedDate: '2023-02-22T11:32:59.283',
                          height: 500,
                          width: 500,
                          length: 0,
                          sizeBytes: 42527,
                          techNote: '',
                          activeStatus: 'ocENABLED',
                          pathURL:
                            '/tyto/api/person/profilephoto?assetID=2158389&encoding=ocORIGINAL',
                        },
                        {
                          encodingType: 'ocTHUMBNAIL',
                          mimeType: 'image/jpeg',
                          modifiedDate: '2023-02-22T11:32:59.283',
                          height: 500,
                          width: 500,
                          length: 0,
                          sizeBytes: 0,
                          techNote: '',
                          activeStatus: 'ocENABLED',
                          pathURL:
                            '/v2/domains/551/assets/1960713_lqzzjhduv2h_200px.jpg',
                        },
                      ],
                      courseItemID: 1960713,
                    },
                  },
                  audienceDesc: '',
                  difficultyDesc: 'ocINTERMEDIATE',
                  expectationDesc: '',
                  durationEstimate: '1 Hour',
                  isContainerUnit: false,
                  internalTitle: '',
                  name: 'Droids 101',
                  locID: 2056640,
                  ocType: 'ocBLOCK',
                  elementID: 2056640,
                  elementName: 'Droids 101',
                  elementDesc:
                    "Joshua's Test Course he uses for Testim Testing",
                  elementType: 'ocBLOCK',
                  elementSubType: 'ocITEM',
                  domainID: 551,
                  outsideID: '',
                  createdByID: 1960713,
                  createdDate: '2022-04-05T16:06:57.7-07:00',
                  primaryElementID: 551,
                  modifiedByID: 1960713,
                  modifiedDate: '2022-11-22T15:13:13.343-08:00',
                  shareChangedDate: '2022-04-05T16:06:57.7-07:00',
                  shareChangedByID: 0,
                  activeStatus: 'ocENABLED',
                },
                name: 'Unlimited',
                locID: 2056708,
                ocType: 'ocCURRICULUMPUB',
                elementID: 2056708,
                elementName: 'Unlimited',
                elementDesc: '',
                elementType: 'ocCURRICULUMPUB',
                elementSubType: 'ocBLOCK',
                domainID: 551,
                outsideID: '',
                createdByID: 1960713,
                createdDate: '2022-04-05T16:58:53.79-07:00',
                primaryElementID: 551,
                modifiedByID: 1960713,
                modifiedDate: '2022-04-05T16:58:53.79-07:00',
                shareChangedDate: '2022-11-21T16:26:01.547-08:00',
                shareChangedByID: 1960713,
                activeStatus: 'ocENABLED',
              },
              catalogID: 2147369,
              description: '',
              catalogType: 'ocCURRICULUMPUB',
              parentCatalogID: 99422,
              primaryElementTreeSerialLeft: 13232,
              pathName: '\tSelenium Catalog\t',
              pathIDs: ',99422,',
              thumbnailPath: '',
              catalogItemID: 2056708,
              catalogItemType: 'ocCURRICULUMPUB',
              catalogItemSubType: 'ocBLOCK',
              hasChange: true,
              hasAdd: true,
              hasDelete: true,
              siblingSeq: 2,
              name: '',
              locID: 2147369,
              ocType: 'ocELEMENT',
              domainID: 4798,
              outsideID: '',
              createdByID: 1960713,
              createdDate: '2022-11-21T16:26:01.5-08:00',
              primaryElementID: 4798,
              modifiedByID: 1960713,
              modifiedDate: '2023-01-27T13:22:47.637-08:00',
              activeStatus: 'ocENABLED',
            },
          ],
          createdByID: 1960713,
          createdDate: '2022-04-05T15:54:58.507-07:00',
          description: '',
          domainID: 551,
          hasAdd: true,
          hasChange: true,
          hasDelete: true,
          images: [
            {
              originalMimeType: 'image/png',
              height: 596,
              width: 1980,
              imageName: 'bannerOverride',
              pathURL: '/v2/domains/551/assets/profilePhotos/2056612_jj3b',
            },
          ],
          locID: 2056612,
          modifiedByID: 1960713,
          modifiedDate: '2022-04-05T17:00:42.86-07:00',
          name: 'Mocaworks Dev Catalog',
          ocType: 'ocELEMENT',
          outsideID: '',
          parentCatalogID: 0,
          pathIDs: ',',
          pathName: '\t',
          primaryElementID: 551,
          primaryElementTreeSerialLeft: 1,
          siblingSeq: 1,
          thumbnailPath: '',
        },
      ],
      session: {
        adminID: 0,
        changePassword: false,
        domainID: 551,
        koPermissionSyncDate: '2023-09-29T15:25:54.27+00:00',
        onCourseURL: 'https://cherry.mocaworks.com',
        onlinePreference: 'ocHIDDEN',
        profileThumbPath:
          '/v2/domains/551/assets/1960713_tsc3eykcizn_200px.jpg',
        roleID: 1,
        teamRootID: 551,
        teamListSyncDate: '1900-01-01T00:00:00+00:00',
        termsOfServiceSignatureRequired: false,
        timeOutMnts: 129600,
        userID: 1960713,
        userName: 'Joshua Rinard',
      },
      error: {
        sts: 0,
        msg: 'initialized',
      },
      links: [],
    }
  },

  invalidMissingRequired: (propName: string) => {
    return {
      data: [],
      links: [],
      error: {
        logID: -1,
        sts: -1000,
        msg: `validation error: ${propName} required`,
        technical: `parameters must contain ${propName}`,
      },
    }
  },
}
