export const BadgeEndpointResponses = {
  success: () => {
    return {
      badges: [
        {
          badgeID: 2538896,
          badgeName: 'Black',
          badgeDesc: 'Black\n',
          badgeType: 'ocITEM',
          activeStatus: 'ocENABLED',
          domainID: 2365525,
          outsideID: '',
          primaryElementID: 2365525,
          ModifiedBy: 1960713,
          ModifiedDate: '6/17/2024 9:46:38 PM',
          createdBy: 1960713,
          createdDate: '6/13/2024 7:31:52 PM',
          hasChange: true,
          hasDelete: true,
          hasAddShare: true,
          shareViewWithDomain: 1,
        },
        {
          badgeID: 2538965,
          badgeName: 'Orange',
          badgeDesc: 'Orange',
          badgeType: 'ocITEM',
          activeStatus: 'ocENABLED',
          domainID: 2365525,
          outsideID: '',
          primaryElementID: 2365525,
          ModifiedBy: 1960713,
          ModifiedDate: '6/17/2024 8:54:24 PM',
          createdBy: 1960713,
          createdDate: '6/13/2024 10:49:17 PM',
          hasChange: true,
          hasDelete: true,
          hasAddShare: true,
          shareViewWithDomain: 0,
        },
        {
          badgeID: 2539783,
          badgeName: 'Red',
          badgeDesc: 'Red',
          badgeType: 'ocITEM',
          activeStatus: 'ocENABLED',
          domainID: 2365525,
          outsideID: '',
          primaryElementID: 2365525,
          ModifiedBy: 1960713,
          ModifiedDate: '6/17/2024 9:43:05 PM',
          createdBy: 1960713,
          createdDate: '6/17/2024 9:33:34 PM',
          hasChange: true,
          hasDelete: true,
          hasAddShare: true,
          shareViewWithDomain: 0,
        },
      ],
      session: {
        userID: 1960713,
        userName: 'Joshua Rinard',
        changePassword: false,
        termsOfServiceSignatureRequired: false,
        adminID: 0,
        teamListSyncDate: '1900-01-01T00:00:00-08:00',
        koPermissionSyncDate: '2024-01-16T08:59:27.27-08:00',
        domainID: 551,
        timeOutMnts: 90,
        onCourseURL: 'https://oc.mocaworks.com',
        profileThumbPath:
          '/v2/domains/551/assets/1960713_lqzzjhduv2h_200px.jpg',
        teamRootID: 551,
        roleID: 1,
        onlinePreference: 'ocHIDDEN',
      },
      error: {
        sts: 0,
        msg: 'ocBadge.ListBadges',
        serverTime: '6/17/2024 11:47:37 PM',
      },
    }
  },

  invalidMissingRequired: (propName: string) => {
    return {
      data: [],
      links: [],
      error: {
        logID: -1,
        sts: -1000,
        msg: `validation error: ${propName} required`,
        technical: `parameters must contain ${propName}`,
      },
    }
  },
}
