import React from 'react'
import type { Meta, StoryObj } from '@storybook/react'

import { BACourseCarousel } from './BACourseCarousel'
import { withRouter } from '@holodeck/router'

const meta: Meta<typeof BACourseCarousel> = {
  title: 'Domain Ui/Organisms/BA Course Carousel',
  component: BACourseCarousel,
  tags: ['autodocs'],
  decorators: [withRouter()],
}

export default meta
type Story = StoryObj<typeof BACourseCarousel>

export const Default: Story = {
  parameters: {
    docs: {
      description: {
        story: 'Default',
      },
    },
    design: {
      type: 'figma',
      url: 'REPLACE WITH FIGMA LINK or REMOVE',
    },
  },
  render: ({ ...props }) => (
    <BACourseCarousel
      startedCourses={[
        {
          enrollmentID: 33172722,
          registeredDate: '2024-11-25T15:21:04.86+00:00',
          registeredByID: 2847041,
          startedDate: '1900-01-01T00:00:00+00:00',
          dueDate: '1900-01-01T00:00:00+00:00',
          completeStatus: 'ocINCOMPLETE',
          statusDate: '1900-01-01T00:00:00+00:00',
          modifiedDate: '2024-11-25T16:33:35.62+00:00',
          recertDate: '1900-01-01T00:00:00+00:00',
          curriculumID: 2846357,
          curriculumType: 'ocBLOCK',
          curriculumSubType: 'ocITEM',
          curriculumName: 'What is Revenue Operations?',
          expirationDate: '1900-01-01T00:00:00+00:00',
          courseIdentifier: '',
          onDueDateAction: 'ocVACANT',
          recursiveRequiredCompleteCount: 0,
          parentTasks: [],
          coursesBelowCount: 0,
          completedCoursesBelowCount: 0,
          profileImage: {
            assetID: 2854805,
            assetName: '10.png',
            assetDesc: 'profileImageID',
            assetType: 'ocProfilePhoto',
            orientation: 'ocVOID',
            modifiedDate: '2024-11-18T22:54:33.34',
            modifiedByID: 2800269,
            createdDate: '2024-11-18T22:54:33.34',
            createdByID: 2800269,
            createdByName: 'Tatum  Starr',
            sequence: 10,
            softwareRequirements: '',
            originalMD5: 'dho6WgK5PYo+pUKQqLNurw==',
            domainID: 1825957,
            encodings: [
              {
                encodingType: 'ocDEFAULT',
                mimeType: 'image/jpeg',
                modifiedDate: '2024-11-18T22:54:33.34',
                height: 280,
                width: 600,
                length: 0,
                sizeBytes: 0,
                techNote: '',
                activeStatus: 'ocENABLED',
                pathURL:
                  '/v2/domains/1825957/assets/profilePhotos/2846357_hbmbazt5iqq_1024px.jpg',
              },
              {
                encodingType: 'ocORIGINAL',
                mimeType: 'image/png',
                modifiedDate: '2024-11-18T22:54:33.34',
                height: 280,
                width: 600,
                length: 0,
                sizeBytes: 85546,
                techNote: '',
                activeStatus: 'ocENABLED',
                pathURL:
                  '/v2/domains/1825957/assets/profilePhotos/2846357_hbmbazt5iqq.png',
              },
              {
                encodingType: 'ocTHUMBNAIL',
                mimeType: 'image/jpeg',
                modifiedDate: '2024-11-18T22:54:33.34',
                height: 280,
                width: 600,
                length: 0,
                sizeBytes: 0,
                techNote: '',
                activeStatus: 'ocENABLED',
                pathURL:
                  '/v2/domains/1825957/assets/profilePhotos/2846357_hbmbazt5iqq_200px.jpg',
              },
            ],
            courseItemID: 2846357,
          },
          subTaskCompleteCount: 1,
          subTaskCount: 2,
          completePercent: 50,
          durationEstimate: '15 mins',
          expectationDesc: '',
          audienceDesc: 'All Team Members, Me Roles, We Leadership ',
          difficultyDesc: 'ocBEGINNER',
          authorID: 2845202,
          curriculumDescription:
            "Whether you're new to Revenue Operations (RevOps) or refining your existing strategies, this course provides the knowledge and best practices to align your revenue teams for scalable growth. You'll explore the function of RevOps and how to maximize revenue potential through Promotion, Profit, Process, and People.",
          parentBlocks: [
            {
              enrollmentID: 33172721,
              blockID: 2829119,
            },
          ],
          subTaskRequiredCount: 2,
          subTaskRequiredCompleteCount: 1,
          requiredCompletePercent: 50,
          internalTitle: '10XBA - Course 1 - 11/19/2024 ',
        },
        {
          enrollmentID: 33172725,
          registeredDate: '2024-11-25T15:21:04.86+00:00',
          registeredByID: 2847041,
          startedDate: '1900-01-01T00:00:00+00:00',
          dueDate: '1900-01-01T00:00:00+00:00',
          completeStatus: 'ocNOTATTEMPTED',
          statusDate: '1900-01-01T00:00:00+00:00',
          modifiedDate: '2024-11-25T15:21:04.86+00:00',
          recertDate: '1900-01-01T00:00:00+00:00',
          curriculumID: 2847683,
          curriculumType: 'ocBLOCK',
          curriculumSubType: 'ocITEM',
          curriculumName: 'Reverse Engineering Targets',
          expirationDate: '1900-01-01T00:00:00+00:00',
          courseIdentifier: '',
          onDueDateAction: 'ocVACANT',
          recursiveRequiredCompleteCount: 0,
          parentTasks: [],
          coursesBelowCount: 0,
          completedCoursesBelowCount: 0,
          profileImage: {
            assetID: 2854809,
            assetName: '13.png',
            assetDesc: 'profileImageID',
            assetType: 'ocProfilePhoto',
            orientation: 'ocVOID',
            modifiedDate: '2024-11-18T22:55:19.057',
            modifiedByID: 2800269,
            createdDate: '2024-11-18T22:55:19.057',
            createdByID: 2800269,
            createdByName: 'Tatum  Starr',
            sequence: 2,
            softwareRequirements: '',
            originalMD5: 'Jm7yQc1yePxOEIG/RGsMMw==',
            domainID: 2823418,
            encodings: [
              {
                encodingType: 'ocDEFAULT',
                mimeType: 'image/jpeg',
                modifiedDate: '2024-11-18T22:55:19.057',
                height: 280,
                width: 600,
                length: 0,
                sizeBytes: 0,
                techNote: '',
                activeStatus: 'ocENABLED',
                pathURL:
                  '/v2/domains/2823418/assets/profilePhotos/2847683_bzwjwmzlcqg_1024px.jpg',
              },
              {
                encodingType: 'ocORIGINAL',
                mimeType: 'image/png',
                modifiedDate: '2024-11-18T22:55:19.057',
                height: 280,
                width: 600,
                length: 0,
                sizeBytes: 67407,
                techNote: '',
                activeStatus: 'ocENABLED',
                pathURL:
                  '/v2/domains/2823418/assets/profilePhotos/2847683_bzwjwmzlcqg.png',
              },
              {
                encodingType: 'ocTHUMBNAIL',
                mimeType: 'image/jpeg',
                modifiedDate: '2024-11-18T22:55:19.057',
                height: 280,
                width: 600,
                length: 0,
                sizeBytes: 0,
                techNote: '',
                activeStatus: 'ocENABLED',
                pathURL:
                  '/v2/domains/2823418/assets/profilePhotos/2847683_bzwjwmzlcqg_200px.jpg',
              },
            ],
            courseItemID: 2847683,
          },
          subTaskCompleteCount: 0,
          subTaskCount: 6,
          completePercent: 0,
          durationEstimate: '20 mins',
          expectationDesc: '',
          audienceDesc: 'All Team Members, Me Roles, We Leadership ',
          difficultyDesc: 'ocBEGINNER',
          authorID: 2845202,
          curriculumDescription:
            "Get ready to master a proven framework that aligns your sales, marketing, and customer success teams for maximum impact. In this course, you'll learn the importance of KPI and metrics tracking and how to reverse engineering targets that boost team performance and drive revenue growth. Let’s dive in and transform your operations for success!",
          parentBlocks: [
            {
              enrollmentID: 33172721,
              blockID: 2829119,
            },
          ],
          subTaskRequiredCount: 6,
          subTaskRequiredCompleteCount: 0,
          requiredCompletePercent: 0,
          internalTitle: '10XBA - Course 2 - 11/19/2024',
        },
        {
          enrollmentID: 33172723,
          registeredDate: '2024-11-25T15:21:04.86+00:00',
          registeredByID: 2847041,
          startedDate: '1900-01-01T00:00:00+00:00',
          dueDate: '1900-01-01T00:00:00+00:00',
          completeStatus: 'ocNOTATTEMPTED',
          statusDate: '1900-01-01T00:00:00+00:00',
          modifiedDate: '2024-11-25T15:21:04.86+00:00',
          recertDate: '1900-01-01T00:00:00+00:00',
          curriculumID: 2846389,
          curriculumType: 'ocBLOCK',
          curriculumSubType: 'ocITEM',
          curriculumName: 'Aligning Promotion Through The 7 Promotes',
          expirationDate: '1900-01-01T00:00:00+00:00',
          courseIdentifier: '',
          onDueDateAction: 'ocVACANT',
          recursiveRequiredCompleteCount: 0,
          parentTasks: [],
          coursesBelowCount: 0,
          completedCoursesBelowCount: 0,
          profileImage: {
            assetID: 2854815,
            assetName: '16.png',
            assetDesc: 'profileImageID',
            assetType: 'ocProfilePhoto',
            orientation: 'ocVOID',
            modifiedDate: '2024-11-18T22:56:38.843',
            modifiedByID: 2800269,
            createdDate: '2024-11-18T22:56:38.84',
            createdByID: 2800269,
            createdByName: 'Tatum  Starr',
            sequence: 5,
            softwareRequirements: '',
            originalMD5: '/f+Vm+2KU5Ev4nvR3foyDg==',
            domainID: 2823418,
            encodings: [
              {
                encodingType: 'ocDEFAULT',
                mimeType: 'image/jpeg',
                modifiedDate: '2024-11-18T22:56:38.843',
                height: 280,
                width: 600,
                length: 0,
                sizeBytes: 0,
                techNote: '',
                activeStatus: 'ocENABLED',
                pathURL:
                  '/v2/domains/2823418/assets/profilePhotos/2846389_eduqeacaaha_1024px.jpg',
              },
              {
                encodingType: 'ocORIGINAL',
                mimeType: 'image/png',
                modifiedDate: '2024-11-18T22:56:38.843',
                height: 280,
                width: 600,
                length: 0,
                sizeBytes: 100415,
                techNote: '',
                activeStatus: 'ocENABLED',
                pathURL:
                  '/v2/domains/2823418/assets/profilePhotos/2846389_eduqeacaaha.png',
              },
              {
                encodingType: 'ocTHUMBNAIL',
                mimeType: 'image/jpeg',
                modifiedDate: '2024-11-18T22:56:38.843',
                height: 280,
                width: 600,
                length: 0,
                sizeBytes: 0,
                techNote: '',
                activeStatus: 'ocENABLED',
                pathURL:
                  '/v2/domains/2823418/assets/profilePhotos/2846389_eduqeacaaha_200px.jpg',
              },
            ],
            courseItemID: 2846389,
          },
          subTaskCompleteCount: 0,
          subTaskCount: 3,
          completePercent: 0,
          durationEstimate: '15 mins',
          expectationDesc: '',
          audienceDesc: 'All Team Members, Me Roles, We Leadership ',
          difficultyDesc: 'ocBEGINNER',
          authorID: 2845202,
          curriculumDescription:
            "In this course, you’ll master the art of creating clear, consistent messaging that aligns your entire organization—from sales to marketing and beyond. We’ll dive into The 7 Promotes framework to help you craft impactful promotions, drive better results, and ensure everyone is on the same page. Get ready to sharpen your promotional strategies and elevate your brand's communication. Let’s get started!",
          parentBlocks: [
            {
              enrollmentID: 33172721,
              blockID: 2829119,
            },
          ],
          subTaskRequiredCount: 3,
          subTaskRequiredCompleteCount: 0,
          requiredCompletePercent: 0,
          internalTitle: '10XBA - Course 4 - 11/19/2024',
        },
        {
          enrollmentID: 33172724,
          registeredDate: '2024-11-25T15:21:04.86+00:00',
          registeredByID: 2847041,
          startedDate: '1900-01-01T00:00:00+00:00',
          dueDate: '1900-01-01T00:00:00+00:00',
          completeStatus: 'ocNOTATTEMPTED',
          statusDate: '1900-01-01T00:00:00+00:00',
          modifiedDate: '2024-11-25T15:21:04.86+00:00',
          recertDate: '1900-01-01T00:00:00+00:00',
          curriculumID: 2846415,
          curriculumType: 'ocBLOCK',
          curriculumSubType: 'ocITEM',
          curriculumName: 'Solutions To Common RevOps Alignment Challenges',
          expirationDate: '1900-01-01T00:00:00+00:00',
          courseIdentifier: '',
          onDueDateAction: 'ocVACANT',
          recursiveRequiredCompleteCount: 0,
          parentTasks: [],
          coursesBelowCount: 0,
          completedCoursesBelowCount: 0,
          profileImage: {
            assetID: 2854814,
            assetName: '14.png',
            assetDesc: 'profileImageID',
            assetType: 'ocProfilePhoto',
            orientation: 'ocVOID',
            modifiedDate: '2024-11-18T22:55:52.94',
            modifiedByID: 2800269,
            createdDate: '2024-11-18T22:55:52.937',
            createdByID: 2800269,
            createdByName: 'Tatum  Starr',
            sequence: 5,
            softwareRequirements: '',
            originalMD5: 'SBiyV7GCfEIHBWmB4lR4rA==',
            domainID: 2823418,
            encodings: [
              {
                encodingType: 'ocDEFAULT',
                mimeType: 'image/jpeg',
                modifiedDate: '2024-11-18T22:55:52.94',
                height: 280,
                width: 600,
                length: 0,
                sizeBytes: 0,
                techNote: '',
                activeStatus: 'ocENABLED',
                pathURL:
                  '/v2/domains/2823418/assets/profilePhotos/2846415_0naldn22vn4_1024px.jpg',
              },
              {
                encodingType: 'ocORIGINAL',
                mimeType: 'image/png',
                modifiedDate: '2024-11-18T22:55:52.94',
                height: 280,
                width: 600,
                length: 0,
                sizeBytes: 153272,
                techNote: '',
                activeStatus: 'ocENABLED',
                pathURL:
                  '/v2/domains/2823418/assets/profilePhotos/2846415_0naldn22vn4.png',
              },
              {
                encodingType: 'ocTHUMBNAIL',
                mimeType: 'image/jpeg',
                modifiedDate: '2024-11-18T22:55:52.94',
                height: 280,
                width: 600,
                length: 0,
                sizeBytes: 0,
                techNote: '',
                activeStatus: 'ocENABLED',
                pathURL:
                  '/v2/domains/2823418/assets/profilePhotos/2846415_0naldn22vn4_200px.jpg',
              },
            ],
            courseItemID: 2846415,
          },
          subTaskCompleteCount: 0,
          subTaskCount: 4,
          completePercent: 0,
          durationEstimate: '15 mins',
          expectationDesc: '',
          audienceDesc: 'All Team Members, Me Roles, We Leadership ',
          difficultyDesc: 'ocBEGINNER',
          authorID: 2845202,
          curriculumDescription:
            "Get ready to tackle the biggest roadblocks in aligning your sales and marketing teams. This course will give you practical strategies to improve communication, streamline processes, and boost your team's effectiveness—so you can drive serious revenue growth. Let's jump in and start turning alignment issues into success stories!",
          parentBlocks: [
            {
              enrollmentID: 33172721,
              blockID: 2829119,
            },
          ],
          subTaskRequiredCount: 4,
          subTaskRequiredCompleteCount: 0,
          requiredCompletePercent: 0,
          internalTitle: '10XBA - Course 3 - 11/19/2024 ',
        },
      ]}
    />
  ),
}
