export const RolesEndpointResponses = {
  get: {
    success: () => {
      return {
        roles: [
          {
            roleID: 1,
            teamRoot: 551,
            roleName: 'Sys Admin',
            roleDesc: 'System Administrator, no restrictions or provisions.',
            teamName: 'Cherry',
            iPath: ',',
            parentNamePath: '\t',
            domainID: 551,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 2,
            teamRoot: 551,
            roleName: 'Company Admin',
            roleDesc: 'This is the template for Company Admins',
            teamName: 'Cherry',
            iPath: ',',
            parentNamePath: '\t',
            domainID: 551,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 3,
            teamRoot: 551,
            roleName: 'Manager Default Template',
            roleDesc: 'Manager',
            teamName: 'Cherry',
            iPath: ',',
            parentNamePath: '\t',
            domainID: 551,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 4,
            teamRoot: 551,
            roleName: 'Team Leader',
            roleDesc:
              'A user with this role generally has permissions to manage members of their team, add enrollments, and view reports',
            teamName: 'Cherry',
            iPath: ',',
            parentNamePath: '\t',
            domainID: 551,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 5,
            teamRoot: 551,
            roleName: 'Project Team Member',
            roleDesc:
              'This is the template Student role for new domains. It describes a general class of users with limited permissions',
            teamName: 'Cherry',
            iPath: ',',
            parentNamePath: '\t',
            domainID: 551,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 17,
            teamRoot: 551,
            roleName: 'Oca Test Role',
            roleDesc: 'Testing role building interface',
            teamName: 'Cherry',
            iPath: ',',
            parentNamePath: '\t',
            domainID: 551,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 59,
            teamRoot: 551,
            roleName: 'Moca Test Role',
            roleDesc: 'A Security Function Sand Box',
            teamName: 'Cherry',
            iPath: ',',
            parentNamePath: '\t',
            domainID: 551,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 72,
            teamRoot: 551,
            roleName: 'Training Developer',
            roleDesc:
              'Training Developers would have access to course building activities and not much person editing',
            teamName: 'Cherry',
            iPath: ',',
            parentNamePath: '\t',
            domainID: 551,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 117,
            teamRoot: 551,
            roleName: 'Sys Admin TESToca',
            roleDesc:
              'System Administrator, no restrictions or provisions.\r\n(this role was copied from Sys Admin COPY)',
            teamName: 'Cherry',
            iPath: ',',
            parentNamePath: '\t',
            domainID: 551,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 152,
            teamRoot: 551,
            roleName: 'Stratus Managers',
            roleDesc:
              'Corporate Administrators of Audigy domain adds and edits persons in the entire organization\r\n(this role was copied from Audigy G',
            teamName: 'Cherry',
            iPath: ',',
            parentNamePath: '\t',
            domainID: 551,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 155,
            teamRoot: 551,
            roleName: 'Enhanced Stratus Manager',
            roleDesc:
              'Corporate Administrators of Audigy domain adds and edits persons in the entire organization\r\n(this role was copied from Audigy G',
            teamName: 'Cherry',
            iPath: ',',
            parentNamePath: '\t',
            domainID: 551,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 156,
            teamRoot: 551,
            roleName: 'supervisor',
            roleDesc: '',
            teamName: 'Cherry',
            iPath: ',',
            parentNamePath: '\t',
            domainID: 551,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 173,
            teamRoot: 551,
            roleName: 'BMSFADL',
            roleDesc: 'Former BMS Therapy Partners Admin',
            teamName: 'Cherry',
            iPath: ',',
            parentNamePath: '\t',
            domainID: 551,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 193,
            teamRoot: 551,
            roleName: 'Member Managers (test)',
            roleDesc:
              'This role was designed to be for Audigy Corporate Team Leaders and Audigy Member Team Leaders. To include Audigy Member Owners.\r',
            teamName: 'Cherry',
            iPath: ',',
            parentNamePath: '\t',
            domainID: 551,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 264,
            teamRoot: 551,
            roleName: 'Frenchisee COPY',
            roleDesc:
              'Localized Admin\r\n(this role was copied from Frenchisee COPY)',
            teamName: 'Cherry',
            iPath: ',',
            parentNamePath: '\t',
            domainID: 551,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 290,
            teamRoot: 551,
            roleName: 'brcb',
            roleDesc: '',
            teamName: 'Cherry',
            iPath: ',',
            parentNamePath: '\t',
            domainID: 551,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 294,
            teamRoot: 551,
            roleName: 'AudigyMedical (disable)',
            roleDesc: '',
            teamName: 'Cherry',
            iPath: ',',
            parentNamePath: '\t',
            domainID: 551,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 303,
            teamRoot: 551,
            roleName: 'enhanced audigy',
            roleDesc: '',
            teamName: 'Cherry',
            iPath: ',',
            parentNamePath: '\t',
            domainID: 551,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 312,
            teamRoot: 551,
            roleName: 'Member Managers Disabled',
            roleDesc:
              'This role was designed to be for Audigy Corporate Team Leaders and Audigy Member Team Leaders. To include Audigy Member Owners.\r',
            teamName: 'Cherry',
            iPath: ',',
            parentNamePath: '\t',
            domainID: 551,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 314,
            teamRoot: 551,
            roleName: 'KnowledgeVaultDe Admin',
            roleDesc: '',
            teamName: 'Cherry',
            iPath: ',',
            parentNamePath: '\t',
            domainID: 551,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 328,
            teamRoot: 551,
            roleName: 'Tryyb Admins',
            roleDesc:
              'Role for Maggie, Mark and Natalie\r\n(this role was copied from Audigy Group Admin COPY)\r\n',
            teamName: 'Cherry',
            iPath: ',',
            parentNamePath: '\t',
            domainID: 551,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 329,
            teamRoot: 551,
            roleName: 'Unit Test Role',
            roleDesc: 'Security for Unit Test Accounts',
            teamName: 'Cherry',
            iPath: ',',
            parentNamePath: '\t',
            domainID: 551,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 341,
            teamRoot: 551,
            roleName: 'Audigy Medical SSMT (Disabled)',
            roleDesc:
              "Copied from Enhanced audigy medical managers but given the ability to see PPF's for people below Audigy Medical members team.\r\n",
            teamName: 'Cherry',
            iPath: ',',
            parentNamePath: '\t',
            domainID: 551,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 355,
            teamRoot: 551,
            roleName: 'beltone',
            roleDesc: '',
            teamName: 'Cherry',
            iPath: ',',
            parentNamePath: '\t',
            domainID: 551,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 360,
            teamRoot: 551,
            roleName: 'disabledRole',
            roleDesc: '',
            teamName: 'Cherry',
            iPath: ',',
            parentNamePath: '\t',
            domainID: 551,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 367,
            teamRoot: 551,
            roleName: 'Disabled',
            roleDesc:
              'this role was copied from( Audigy Enhanced Manager)\r\n(this role was copied from Beltone Manager COPY)',
            teamName: 'Cherry',
            iPath: ',',
            parentNamePath: '\t',
            domainID: 551,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 381,
            teamRoot: 551,
            roleName: 'manager not used',
            roleDesc: '',
            teamName: 'Cherry',
            iPath: ',',
            parentNamePath: '\t',
            domainID: 551,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 397,
            teamRoot: 551,
            roleName: 'Moca Test Role COPY',
            roleDesc:
              'A Security Function Sand Box\r\n(this role was copied from Moca Test Role COPY)',
            teamName: 'Cherry',
            iPath: ',',
            parentNamePath: '\t',
            domainID: 551,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 400,
            teamRoot: 551,
            roleName: 'Company Admin COPY',
            roleDesc:
              'This is the template for Company Admins\r\n(this role was copied from Company Admin COPY)',
            teamName: 'Cherry',
            iPath: ',',
            parentNamePath: '\t',
            domainID: 551,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 428,
            teamRoot: 551,
            roleName: 'beltone',
            roleDesc: '',
            teamName: 'Cherry',
            iPath: ',',
            parentNamePath: '\t',
            domainID: 551,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 439,
            teamRoot: 551,
            roleName: 'Member +Marketing Tickets +Playbook',
            roleDesc:
              'RECYCLED: Copied from Beltone Staff and will add Marketing Ticketing Request for testing and Playbook',
            teamName: 'Cherry',
            iPath: ',',
            parentNamePath: '\t',
            domainID: 551,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 508,
            teamRoot: 551,
            roleName: 'RECYCLED: Manager Default Template',
            roleDesc: 'RECYCLED: Manager for testing',
            teamName: 'Cherry',
            iPath: ',',
            parentNamePath: '\t',
            domainID: 551,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 511,
            teamRoot: 551,
            roleName: 'Manager Role Update Test',
            roleDesc: 'RECYCLED: Manager',
            teamName: 'Cherry',
            iPath: ',',
            parentNamePath: '\t',
            domainID: 551,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 686,
            teamRoot: 551,
            roleName: 'mocaworks testuser',
            roleDesc: '',
            teamName: 'Cherry',
            iPath: ',',
            parentNamePath: '\t',
            domainID: 551,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 701,
            teamRoot: 551,
            roleName: 'Test Staff + Content Creation',
            roleDesc:
              'RECYCLED: Add the ability to create/manage course content on teams with team leader',
            teamName: 'Cherry',
            iPath: ',',
            parentNamePath: '\t',
            domainID: 551,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 702,
            teamRoot: 551,
            roleName: 'Team Membership',
            roleDesc: '',
            teamName: 'Cherry',
            iPath: ',',
            parentNamePath: '\t',
            domainID: 551,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 708,
            teamRoot: 551,
            roleName: 'cv sbu',
            roleDesc: '',
            teamName: 'Cherry',
            iPath: ',',
            parentNamePath: '\t',
            domainID: 551,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 715,
            teamRoot: 551,
            roleName: 'ariel',
            roleDesc: '',
            teamName: 'Cherry',
            iPath: ',',
            parentNamePath: '\t',
            domainID: 551,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 719,
            teamRoot: 551,
            roleName: 'client owner',
            roleDesc: '',
            teamName: 'Cherry',
            iPath: ',',
            parentNamePath: '\t',
            domainID: 551,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 729,
            teamRoot: 551,
            roleName: '657',
            roleDesc: '',
            teamName: 'Cherry',
            iPath: ',',
            parentNamePath: '\t',
            domainID: 551,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 520,
            teamRoot: 1825957,
            roleName: 'CV Student',
            roleDesc: 'Default student role for CV',
            teamName: 'CV',
            iPath: ',551,',
            parentNamePath: '\tCherry\t',
            domainID: 1825957,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 521,
            teamRoot: 1825957,
            roleName: 'CV Admin',
            roleDesc: 'Default admin role for CV',
            teamName: 'CV',
            iPath: ',551,',
            parentNamePath: '\tCherry\t',
            domainID: 1825957,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 714,
            teamRoot: 1825957,
            roleName: 'CTTI Admin',
            roleDesc: 'RECYCLED: Default admin role for CV',
            teamName: 'CV',
            iPath: ',551,',
            parentNamePath: '\tCherry\t',
            domainID: 1825957,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 718,
            teamRoot: 1825957,
            roleName: 'Content Creators',
            roleDesc: 'For Cardone Ventures Content Uploaders',
            teamName: 'CV',
            iPath: ',551,',
            parentNamePath: '\tCherry\t',
            domainID: 1825957,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 712,
            teamRoot: 2104562,
            roleName: 'Business Advisors',
            roleDesc: 'Default student role for 10X Business Advisors',
            teamName: '10X Business Advisor',
            iPath: ',551,1825957,',
            parentNamePath: '\tCherry\tCV\t',
            domainID: 2104562,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 713,
            teamRoot: 2104562,
            roleName: '10XBA Admin',
            roleDesc: 'Default admin role for 10X Business Advisors',
            teamName: '10X Business Advisor',
            iPath: ',551,1825957,',
            parentNamePath: '\tCherry\tCV\t',
            domainID: 2104562,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 727,
            teamRoot: 2104562,
            roleName: '10X BA Client Manager',
            roleDesc:
              'Managers role Plus VCEP reading\r\nThis is a manager role similar to SBU Managers that HB mentioned in bug https://cherry.mocawork',
            teamName: '10X Business Advisor',
            iPath: ',551,1825957,',
            parentNamePath: '\tCherry\tCV\t',
            domainID: 2104562,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 728,
            teamRoot: 2104562,
            roleName: '10XBA Content Creator',
            roleDesc:
              'Started as Cardone Student role added content creation domain wide courses and plans',
            teamName: '10X Business Advisor',
            iPath: ',551,1825957,',
            parentNamePath: '\tCherry\tCV\t',
            domainID: 2104562,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 733,
            teamRoot: 2104562,
            roleName: '10X BA Onboarding',
            roleDesc:
              'Automatic course enrollment for: \r\n10X Business Advisor CEO 101\r\nCertification Program',
            teamName: '10X Business Advisor',
            iPath: ',551,1825957,',
            parentNamePath: '\tCherry\tCV\t',
            domainID: 2104562,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 734,
            teamRoot: 2104562,
            roleName: '10X BA Active',
            roleDesc:
              'Automatic course enrollment for: \r\nCardone University\r\n10X Owner\r\n10X Employee\r\nResponse Mentor Program',
            teamName: '10X Business Advisor',
            iPath: ',551,1825957,',
            parentNamePath: '\tCherry\tCV\t',
            domainID: 2104562,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 735,
            teamRoot: 2104562,
            roleName: 'Business Advisor - Active w/Training',
            roleDesc:
              'Automatic course enrollment for: \r\nCardone University\r\n10X Owner\r\n10X Employee\r\nResponse Mentor Program\r\n',
            teamName: '10X Business Advisor',
            iPath: ',551,1825957,',
            parentNamePath: '\tCherry\tCV\t',
            domainID: 2104562,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 764,
            teamRoot: 2104562,
            roleName: 'BA Clients - Individual',
            roleDesc: 'RECYCLED: CV Member Team',
            teamName: '10X Business Advisor',
            iPath: ',551,1825957,',
            parentNamePath: '\tCherry\tCV\t',
            domainID: 2104562,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 765,
            teamRoot: 2104562,
            roleName: '10X BA Active Test',
            roleDesc:
              'Automatic course enrollment for: \r\nCardone University\r\n10X Owner\r\n10X Employee\r\nResponse Mentor Program\r\n(this role was copied f',
            teamName: '10X Business Advisor',
            iPath: ',551,1825957,',
            parentNamePath: '\tCherry\tCV\t',
            domainID: 2104562,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 766,
            teamRoot: 2104562,
            roleName: '10X BA Active - JUST FOR TEST',
            roleDesc:
              'RECYCLED: Automatic course enrollment for: \r\nCardone University\r\n10X Owner\r\n10X Employee\r\nResponse Mentor Program',
            teamName: '10X Business Advisor',
            iPath: ',551,1825957,',
            parentNamePath: '\tCherry\tCV\t',
            domainID: 2104562,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 758,
            teamRoot: 2249497,
            roleName: 'BuySell Buyers',
            roleDesc: 'Default student role for 10X Buy Sell',
            teamName: '10X Buy Sell',
            iPath: ',551,1825957,',
            parentNamePath: '\tCherry\tCV\t',
            domainID: 2249497,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 759,
            teamRoot: 2249497,
            roleName: 'BuySell Admins',
            roleDesc: 'Default admin role for 10X Buy Sell',
            teamName: '10X Buy Sell',
            iPath: ',551,1825957,',
            parentNamePath: '\tCherry\tCV\t',
            domainID: 2249497,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 689,
            teamRoot: 2001650,
            roleName: '10XHealthSystem Staff',
            roleDesc: 'Default student role for 10X Health System',
            teamName: '10X Health System',
            iPath: ',551,1825957,',
            parentNamePath: '\tCherry\tCV\t',
            domainID: 2001650,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 690,
            teamRoot: 2001650,
            roleName: '10XHealthSystem Admin',
            roleDesc: 'Default admin role for 10X Health System',
            teamName: '10X Health System',
            iPath: ',551,1825957,',
            parentNamePath: '\tCherry\tCV\t',
            domainID: 2001650,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 705,
            teamRoot: 2001650,
            roleName: '10X Health SBU Manager',
            roleDesc:
              'RECYCLED: Managers role Plus VCEP reading\r\n(this role was copied from SBU Managers COPY)',
            teamName: '10X Health System',
            iPath: ',551,1825957,',
            parentNamePath: '\tCherry\tCV\t',
            domainID: 2001650,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 706,
            teamRoot: 2001650,
            roleName: 'Client Supervisor',
            roleDesc:
              'RECYCLED: Client Owners minus PPF default view of team members.',
            teamName: '10X Health System',
            iPath: ',551,1825957,',
            parentNamePath: '\tCherry\tCV\t',
            domainID: 2001650,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 707,
            teamRoot: 2001650,
            roleName: 'Client Owners',
            roleDesc: 'RECYCLED: Increased access to training records\n',
            teamName: '10X Health System',
            iPath: ',551,1825957,',
            parentNamePath: '\tCherry\tCV\t',
            domainID: 2001650,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 757,
            teamRoot: 2001650,
            roleName: 'RECYCLED: CU Only',
            roleDesc:
              'RECYCLED: For team members of PR clients who should ONLY have access to Cardone University.',
            teamName: '10X Health System',
            iPath: ',551,1825957,',
            parentNamePath: '\tCherry\tCV\t',
            domainID: 2001650,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 767,
            teamRoot: 2329987,
            roleName: '10XHealthFS Student',
            roleDesc: 'Default student role for 10X Health Franchise & License',
            teamName: '10X Health Franchise & License',
            iPath: ',551,1825957,2001650,',
            parentNamePath: '\tCherry\tCV\t10X Health System\t',
            domainID: 2329987,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 768,
            teamRoot: 2329987,
            roleName: '10XHealthFS Admin',
            roleDesc: 'Default admin role for 10X Health Franchise & License',
            teamName: '10X Health Franchise & License',
            iPath: ',551,1825957,2001650,',
            parentNamePath: '\tCherry\tCV\t10X Health System\t',
            domainID: 2329987,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 769,
            teamRoot: 2329987,
            roleName: '10X HealthFS - Franchisee Owner',
            roleDesc:
              'Copy of "CV Client Owners"\nIncreased access to training records\n',
            teamName: '10X Health Franchise & License',
            iPath: ',551,1825957,2001650,',
            parentNamePath: '\tCherry\tCV\t10X Health System\t',
            domainID: 2329987,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 770,
            teamRoot: 2329987,
            roleName: '10X HealthFS - Franchisee Team',
            roleDesc: 'Copy from CV Client Team',
            teamName: '10X Health Franchise & License',
            iPath: ',551,1825957,2001650,',
            parentNamePath: '\tCherry\tCV\t10X Health System\t',
            domainID: 2329987,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 771,
            teamRoot: 2329987,
            roleName: '10X HealthFS - Licensee Account',
            roleDesc: 'Copy of "Client Team"',
            teamName: '10X Health Franchise & License',
            iPath: ',551,1825957,2001650,',
            parentNamePath: '\tCherry\tCV\t10X Health System\t',
            domainID: 2329987,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 440,
            teamRoot: 1752244,
            roleName: 'AMI Staff',
            roleDesc: 'Default student role for Advanced Medical Integration',
            teamName: 'Advanced Medical Integration',
            iPath: ',551,1825957,',
            parentNamePath: '\tCherry\tCV\t',
            domainID: 1752244,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 441,
            teamRoot: 1752244,
            roleName: 'AMI Admin',
            roleDesc: 'Default admin role for Advanced Medical Integration',
            teamName: 'Advanced Medical Integration',
            iPath: ',551,1825957,',
            parentNamePath: '\tCherry\tCV\t',
            domainID: 1752244,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 444,
            teamRoot: 1752244,
            roleName: 'AMI Supervisor',
            roleDesc:
              'RECYCLED: This role was designed to be for Audigy Corporate Team Leaders and Audigy Member Team Leaders. To include Audigy Membe',
            teamName: 'Advanced Medical Integration',
            iPath: ',551,1825957,',
            parentNamePath: '\tCherry\tCV\t',
            domainID: 1752244,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 450,
            teamRoot: 1752244,
            roleName: 'Client Owners',
            roleDesc: 'Increased access to training records\n',
            teamName: 'Advanced Medical Integration',
            iPath: ',551,1825957,',
            parentNamePath: '\tCherry\tCV\t',
            domainID: 1752244,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 470,
            teamRoot: 1752244,
            roleName: 'SBU Managers',
            roleDesc: 'AMI Managers role Plus VCEP reading',
            teamName: 'Advanced Medical Integration',
            iPath: ',551,1825957,',
            parentNamePath: '\tCherry\tCV\t',
            domainID: 1752244,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 504,
            teamRoot: 1752244,
            roleName: 'Client Team',
            roleDesc: 'RECYCLED: Client Team (Cardone Ventures)',
            teamName: 'Advanced Medical Integration',
            iPath: ',551,1825957,',
            parentNamePath: '\tCherry\tCV\t',
            domainID: 1752244,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 626,
            teamRoot: 1752244,
            roleName: 'AMI Admin - No PPF',
            roleDesc:
              'This role was duplicated from the admin role and designed not to have global PPF access',
            teamName: 'Advanced Medical Integration',
            iPath: ',551,1825957,',
            parentNamePath: '\tCherry\tCV\t',
            domainID: 1752244,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 674,
            teamRoot: 1752244,
            roleName: 'Client Supervisor',
            roleDesc:
              'RECYCLED: Client Owners minus PPF default view of team members.',
            teamName: 'Advanced Medical Integration',
            iPath: ',551,1825957,',
            parentNamePath: '\tCherry\tCV\t',
            domainID: 1752244,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 684,
            teamRoot: 1964196,
            roleName: 'BuildanEmpire Student',
            roleDesc: 'Default student role for Build an Empire',
            teamName: 'Build an Empire',
            iPath: ',551,1825957,',
            parentNamePath: '\tCherry\tCV\t',
            domainID: 1964196,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 685,
            teamRoot: 1964196,
            roleName: 'BuildanEmpire Admin',
            roleDesc: 'Default admin role for Build an Empire',
            teamName: 'Build an Empire',
            iPath: ',551,1825957,',
            parentNamePath: '\tCherry\tCV\t',
            domainID: 1964196,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 763,
            teamRoot: 1964196,
            roleName: 'Vendor Limited',
            roleDesc:
              'This is a very limited role intended to get a user in the system and not see much other than start page.',
            teamName: 'Build an Empire',
            iPath: ',551,1825957,',
            parentNamePath: '\tCherry\tCV\t',
            domainID: 1964196,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 306,
            teamRoot: 1698652,
            roleName: 'Vendor Test',
            roleDesc:
              'Audigy Students role restricted to memberships only and very few menu items',
            teamName: 'Cardone Ventures',
            iPath: ',551,1825957,',
            parentNamePath: '\tCherry\tCV\t',
            domainID: 1698652,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 431,
            teamRoot: 1698652,
            roleName: 'CV Employees',
            roleDesc: 'Default student role for Cardone Ventures',
            teamName: 'Cardone Ventures',
            iPath: ',551,1825957,',
            parentNamePath: '\tCherry\tCV\t',
            domainID: 1698652,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 432,
            teamRoot: 1698652,
            roleName: 'CV Admin',
            roleDesc: 'Default admin role for Cardone Ventures',
            teamName: 'Cardone Ventures',
            iPath: ',551,1825957,',
            parentNamePath: '\tCherry\tCV\t',
            domainID: 1698652,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 445,
            teamRoot: 1698652,
            roleName: 'CV Account Manager',
            roleDesc:
              'RECYCLED: RECYCLED: This role was designed to be for Audigy Corporate Team Leaders and Audigy Member Team Leaders. To include Au',
            teamName: 'Cardone Ventures',
            iPath: ',551,1825957,',
            parentNamePath: '\tCherry\tCV\t',
            domainID: 1698652,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 449,
            teamRoot: 1698652,
            roleName: 'Client Owners',
            roleDesc: 'Increased access to training records\n',
            teamName: 'Cardone Ventures',
            iPath: ',551,1825957,',
            parentNamePath: '\tCherry\tCV\t',
            domainID: 1698652,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 503,
            teamRoot: 1698652,
            roleName: 'Client Team',
            roleDesc: 'RECYCLED: Member Team (Stratus)',
            teamName: 'Cardone Ventures',
            iPath: ',551,1825957,',
            parentNamePath: '\tCherry\tCV\t',
            domainID: 1698652,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 507,
            teamRoot: 1698652,
            roleName: 'Client Owners (w/Training)',
            roleDesc: 'RECYCLED: Increased access to training records\n',
            teamName: 'Cardone Ventures',
            iPath: ',551,1825957,',
            parentNamePath: '\tCherry\tCV\t',
            domainID: 1698652,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 557,
            teamRoot: 1698652,
            roleName: 'CV External Facing',
            roleDesc:
              'Managers role Plus VCEP reading\r\n(this role was copied from SBU Managers COPY)',
            teamName: 'Cardone Ventures',
            iPath: ',551,1825957,',
            parentNamePath: '\tCherry\tCV\t',
            domainID: 1698652,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 657,
            teamRoot: 1698652,
            roleName: 'Client Supervisor',
            roleDesc: 'Client Owners minus PPF default view of team members.',
            teamName: 'Cardone Ventures',
            iPath: ',551,1825957,',
            parentNamePath: '\tCherry\tCV\t',
            domainID: 1698652,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 699,
            teamRoot: 1698652,
            roleName: 'CV Trainual Contributor',
            roleDesc:
              'Started as Cardone Student role added content creation domain wide courses and plans',
            teamName: 'Cardone Ventures',
            iPath: ',551,1825957,',
            parentNamePath: '\tCherry\tCV\t',
            domainID: 1698652,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 704,
            teamRoot: 1698652,
            roleName: 'Client Team (with bug reporting)',
            roleDesc:
              'Same as Client Team except can report bugs. Use role in special cases only.',
            teamName: 'Cardone Ventures',
            iPath: ',551,1825957,',
            parentNamePath: '\tCherry\tCV\t',
            domainID: 1698652,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 709,
            teamRoot: 1698652,
            roleName: 'CV HR Admin',
            roleDesc: 'Super Admin role with access to all PPFs',
            teamName: 'Cardone Ventures',
            iPath: ',551,1825957,',
            parentNamePath: '\tCherry\tCV\t',
            domainID: 1698652,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 720,
            teamRoot: 1698652,
            roleName: 'Client Owners w/ Financial Reporting',
            roleDesc:
              'Increased access to Power BI Financial Reporting for Owners\n',
            teamName: 'Cardone Ventures',
            iPath: ',551,1825957,',
            parentNamePath: '\tCherry\tCV\t',
            domainID: 1698652,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 746,
            teamRoot: 1698652,
            roleName: 'UAT CV Admin',
            roleDesc: 'RECYCLED: Default admin role for Cardone Ventures',
            teamName: 'Cardone Ventures',
            iPath: ',551,1825957,',
            parentNamePath: '\tCherry\tCV\t',
            domainID: 1698652,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 752,
            teamRoot: 1698652,
            roleName: 'CU Only',
            roleDesc:
              'For team members of PR clients who should ONLY have access to Cardone University.',
            teamName: 'Cardone Ventures',
            iPath: ',551,1825957,',
            parentNamePath: '\tCherry\tCV\t',
            domainID: 1698652,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 754,
            teamRoot: 1698652,
            roleName: 'BMLP Withdrawal',
            roleDesc:
              'Only Access to Mastery\n\nRECYCLED: For team members of PR clients who should ONLY have access to Cardone University.',
            teamName: 'Cardone Ventures',
            iPath: ',551,1825957,',
            parentNamePath: '\tCherry\tCV\t',
            domainID: 1698652,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 756,
            teamRoot: 1698652,
            roleName: 'Client Supervisor - w/Training',
            roleDesc:
              'Client Owners\n- Removed PPF default view of team members.\n- Access to Course Editor/Training - Role Block',
            teamName: 'Cardone Ventures',
            iPath: ',551,1825957,',
            parentNamePath: '\tCherry\tCV\t',
            domainID: 1698652,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 760,
            teamRoot: 1698652,
            roleName: 'Client Team (w/Training)',
            roleDesc: 'Client Team (w/Training)',
            teamName: 'Cardone Ventures',
            iPath: ',551,1825957,',
            parentNamePath: '\tCherry\tCV\t',
            domainID: 1698652,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 723,
            teamRoot: 2179214,
            roleName: 'CTTI Student',
            roleDesc: 'Default student role for CTTI',
            teamName: 'CTTI',
            iPath: ',551,1825957,',
            parentNamePath: '\tCherry\tCV\t',
            domainID: 2179214,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 724,
            teamRoot: 2179214,
            roleName: 'CTTI Admin',
            roleDesc: 'Default admin role for CTTI',
            teamName: 'CTTI',
            iPath: ',551,1825957,',
            parentNamePath: '\tCherry\tCV\t',
            domainID: 2179214,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 736,
            teamRoot: 2193182,
            roleName: '10XCertifiedCoac Student',
            roleDesc: 'Default student role for 10X Certified Coaches',
            teamName: '10X Certified Coaches',
            iPath: ',551,1825957,2179214,',
            parentNamePath: '\tCherry\tCV\tCTTI\t',
            domainID: 2193182,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 737,
            teamRoot: 2193182,
            roleName: '10XCertifiedCoac Admin',
            roleDesc: 'Default admin role for 10X Certified Coaches',
            teamName: '10X Certified Coaches',
            iPath: ',551,1825957,2179214,',
            parentNamePath: '\tCherry\tCV\tCTTI\t',
            domainID: 2193182,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 740,
            teamRoot: 2202699,
            roleName: 'CardoneUni Student',
            roleDesc: 'Default student role for Cardone University',
            teamName: 'CTTI Internal Team',
            iPath: ',551,1825957,2179214,',
            parentNamePath: '\tCherry\tCV\tCTTI\t',
            domainID: 2202699,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 741,
            teamRoot: 2202699,
            roleName: 'CardoneUni Admin',
            roleDesc: 'Default admin role for Cardone University',
            teamName: 'CTTI Internal Team',
            iPath: ',551,1825957,2179214,',
            parentNamePath: '\tCherry\tCV\tCTTI\t',
            domainID: 2202699,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 725,
            teamRoot: 2179789,
            roleName: 'Vendasta Student',
            roleDesc: 'Default student role for Vendasta',
            teamName: 'Vendasta',
            iPath: ',551,1825957,2179214,',
            parentNamePath: '\tCherry\tCV\tCTTI\t',
            domainID: 2179789,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 726,
            teamRoot: 2179789,
            roleName: 'Vendasta Admin',
            roleDesc: 'Default admin role for Vendasta',
            teamName: 'Vendasta',
            iPath: ',551,1825957,2179214,',
            parentNamePath: '\tCherry\tCV\tCTTI\t',
            domainID: 2179789,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 687,
            teamRoot: 1979415,
            roleName: 'ElenaCardoneEXP Student',
            roleDesc: 'Default student role for Elena Cardone EXP',
            teamName: 'Elena Cardone eXp',
            iPath: ',551,1825957,',
            parentNamePath: '\tCherry\tCV\t',
            domainID: 1979415,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 688,
            teamRoot: 1979415,
            roleName: 'ElenaCardoneEXP Admin',
            roleDesc: 'Default admin role for Elena Cardone EXP',
            teamName: 'Elena Cardone eXp',
            iPath: ',551,1825957,',
            parentNamePath: '\tCherry\tCV\t',
            domainID: 1979415,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 716,
            teamRoot: 1979415,
            roleName: 'External eXp User',
            roleDesc: 'RECYCLED: Default student role for Elena Cardone EXP',
            teamName: 'Elena Cardone eXp',
            iPath: ',551,1825957,',
            parentNamePath: '\tCherry\tCV\t',
            domainID: 1979415,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 717,
            teamRoot: 1979415,
            roleName: 'Bot User',
            roleDesc: 'RECYCLED: Default admin role for Elena Cardone EXP',
            teamName: 'Elena Cardone eXp',
            iPath: ',551,1825957,',
            parentNamePath: '\tCherry\tCV\t',
            domainID: 1979415,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 730,
            teamRoot: 2187726,
            roleName: 'Revified Student',
            roleDesc: 'Default student role for Revified',
            teamName: 'Revified',
            iPath: ',551,1825957,',
            parentNamePath: '\tCherry\tCV\t',
            domainID: 2187726,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 731,
            teamRoot: 2187726,
            roleName: 'Revified Admin',
            roleDesc: 'Default admin role for Revified',
            teamName: 'Revified',
            iPath: ',551,1825957,',
            parentNamePath: '\tCherry\tCV\t',
            domainID: 2187726,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 742,
            teamRoot: 2187726,
            roleName: 'Cardone University Managers',
            roleDesc: 'Increased access to training records\n',
            teamName: 'Revified',
            iPath: ',551,1825957,',
            parentNamePath: '\tCherry\tCV\t',
            domainID: 2187726,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 743,
            teamRoot: 2187726,
            roleName: 'Cardone University Team',
            roleDesc: 'For team members of Cardone University ONLY clients',
            teamName: 'Revified',
            iPath: ',551,1825957,',
            parentNamePath: '\tCherry\tCV\t',
            domainID: 2187726,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 744,
            teamRoot: 2187726,
            roleName: 'DEMO: CU Managers',
            roleDesc:
              'Cardone University Manager roles, but for DEMO purposes ONLY. Allows Sales team to demo CU without sequentiality enforced.',
            teamName: 'Revified',
            iPath: ',551,1825957,',
            parentNamePath: '\tCherry\tCV\t',
            domainID: 2187726,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 745,
            teamRoot: 2187726,
            roleName: 'DEMO: CU Team',
            roleDesc:
              'Cardone University Team role, but for DEMO purposes ONLY. Allows Sales team to demo CU without sequentiality enforced.',
            teamName: 'Revified',
            iPath: ',551,1825957,',
            parentNamePath: '\tCherry\tCV\t',
            domainID: 2187726,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 747,
            teamRoot: 2187726,
            roleName: 'Platform Review Manager',
            roleDesc:
              'Managers role Plus VCEP reading\n(this role was copied from CV SBU Managers)',
            teamName: 'Revified',
            iPath: ',551,1825957,',
            parentNamePath: '\tCherry\tCV\t',
            domainID: 2187726,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 748,
            teamRoot: 2187726,
            roleName: 'Revified Client Owners',
            roleDesc:
              'Revified base package. Does NOT include Cardone University\n',
            teamName: 'Revified',
            iPath: ',551,1825957,',
            parentNamePath: '\tCherry\tCV\t',
            domainID: 2187726,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 749,
            teamRoot: 2187726,
            roleName: 'Revified  + CU Client Owners',
            roleDesc:
              'RECYCLED: Revified base package. DOES include Cardone University\n',
            teamName: 'Revified',
            iPath: ',551,1825957,',
            parentNamePath: '\tCherry\tCV\t',
            domainID: 2187726,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 750,
            teamRoot: 2187726,
            roleName: 'Revified Client Team',
            roleDesc: 'Revified base product. Does NOT Include CU',
            teamName: 'Revified',
            iPath: ',551,1825957,',
            parentNamePath: '\tCherry\tCV\t',
            domainID: 2187726,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 751,
            teamRoot: 2187726,
            roleName: 'Revified + CU Client Team',
            roleDesc: 'Revified + CU. DOES Include CU',
            teamName: 'Revified',
            iPath: ',551,1825957,',
            parentNamePath: '\tCherry\tCV\t',
            domainID: 2187726,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 721,
            teamRoot: 2173946,
            roleName: 'Wave Student',
            roleDesc: 'Default student role for Wave',
            teamName: 'Wave',
            iPath: ',551,1825957,',
            parentNamePath: '\tCherry\tCV\t',
            domainID: 2173946,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 722,
            teamRoot: 2173946,
            roleName: 'Wave Admin',
            roleDesc: 'Default admin role for Wave',
            teamName: 'Wave',
            iPath: ',551,1825957,',
            parentNamePath: '\tCherry\tCV\t',
            domainID: 2173946,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 429,
            teamRoot: 4798,
            roleName: 'Selenium Test Role',
            roleDesc: 'A role for testing',
            teamName: 'Selenium Domain',
            iPath: ',551,',
            parentNamePath: '\tCherry\t',
            domainID: 4798,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 739,
            teamRoot: 4798,
            roleName: 'Selenium Admin',
            roleDesc: 'RECYCLED: Default admin role for Cardone Ventures',
            teamName: 'Selenium Domain',
            iPath: ',551,',
            parentNamePath: '\tCherry\t',
            domainID: 4798,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 291,
            teamRoot: 696300,
            roleName: 'PeterBachman',
            roleDesc: '',
            teamName: 'Peter Bachman',
            iPath: ',551,4798,',
            parentNamePath: '\tCherry\tSelenium Domain\t',
            domainID: 696300,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 761,
            teamRoot: 2250833,
            roleName: 'TestDomain Student',
            roleDesc: 'Default student role for Test Domain',
            teamName: 'Test Domain',
            iPath: ',551,4798,',
            parentNamePath: '\tCherry\tSelenium Domain\t',
            domainID: 2250833,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 762,
            teamRoot: 2250833,
            roleName: 'TestDomain Admin',
            roleDesc: 'Default admin role for Test Domain',
            teamName: 'Test Domain',
            iPath: ',551,4798,',
            parentNamePath: '\tCherry\tSelenium Domain\t',
            domainID: 2250833,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 215,
            teamRoot: 279857,
            roleName: 'New Skin Domain Admin',
            roleDesc: 'auto generated admin role at domain creation',
            teamName: 'New Skin Domain',
            iPath: ',551,4798,42038,',
            parentNamePath: '\tCherry\tSelenium Domain\tUnder Scott Domain\t',
            domainID: 279857,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 216,
            teamRoot: 279857,
            roleName: 'New Skin Domain Student',
            roleDesc: 'auto generated student role at domain creation',
            teamName: 'New Skin Domain',
            iPath: ',551,4798,42038,',
            parentNamePath: '\tCherry\tSelenium Domain\tUnder Scott Domain\t',
            domainID: 279857,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 772,
            teamRoot: 2365525,
            roleName: 'testDomain1 Student',
            roleDesc: 'Default student role for testDomain',
            teamName: 'testDomain',
            iPath: ',551,',
            parentNamePath: '\tCherry\t',
            domainID: 2365525,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 773,
            teamRoot: 2365525,
            roleName: 'testDomain1 Admin',
            roleDesc: 'Default admin role for testDomain',
            teamName: 'testDomain',
            iPath: ',551,',
            parentNamePath: '\tCherry\t',
            domainID: 2365525,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 774,
            teamRoot: 2365530,
            roleName: 'testDomain2 Student',
            roleDesc: 'Default student role for testDomain2',
            teamName: 'testDomain2',
            iPath: ',551,2365525,',
            parentNamePath: '\tCherry\ttestDomain\t',
            domainID: 2365530,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
          {
            roleID: 775,
            teamRoot: 2365530,
            roleName: 'testDomain2 Admin',
            roleDesc: 'Default admin role for testDomain2',
            teamName: 'testDomain2',
            iPath: ',551,2365525,',
            parentNamePath: '\tCherry\ttestDomain\t',
            domainID: 2365530,
            hasView: true,
            hasChange: true,
            hasDelete: true,
          },
        ],
        session: {
          userID: 2043811,
          userName: 'Johann Loch',
          changePassword: false,
          termsOfServiceSignatureRequired: false,
          adminID: 0,
          teamListSyncDate: '1900-01-01T00:00:00+00:00',
          koPermissionSyncDate: '2023-12-26T15:01:04.137+00:00',
          domainID: 551,
          timeOutMnts: 90,
          onCourseURL: 'https://cherry.mocaworks.com',
          profileThumbPath:
            '/v2/domains/551/assets/2043811_sxuwdy5uwwo_200px.jpg',
          teamRootID: 551,
          roleID: 1,
          onlinePreference: 'ocHIDDEN',
        },
        error: {
          sts: 0,
          msg: 'initialized',
        },
        links: [],
      }
    },
  },
  invalidMissingRequired: (propName: string) => {
    return {
      data: [],
      links: [],
      error: {
        logID: -1,
        sts: -1000,
        msg: `validation error: ${propName} required`,
        technical: `parameters must contain ${propName}`,
      },
    }
  },
}
