export const PersonEndpointResponses = {
  get: {
    success: () => {
      return {
        person: {
          teamMemberships: [
            {
              preferredTeam: 1,
              TeamID: 551,
              teamName: 'Cherry',
              teamDesc: 'Social Knowledge sharing with purpose!',
              elementType: 'ocTEAM',
              activeStatus: 'ocENABLED',
              elementSubType: 'ocDOMAIN',
              lvl: 1,
              sn: 1,
              tPath: ',',
              parentID: 0,
              direct: true,
              leader: false,
              iscascade: false,
              ParentNamePath: '\t',
              SubDomainParentNamePath: '\t',
              domainID: 551,
              createByID: 1625045,
              createdByName: 'Ryann Michaud',
              createdDate: '2023-02-03T21:21:06.893+00:00',
              memberTitle: '',
              teamOutsideID: '',
              teamBoardEMailPreference: 'ocINSTANT',
            },
          ],
          permissions: [
            {
              functionName: 'Person Demographics',
              businessCardPref: 'birthday',
              fieldName: 'birthdate',
              changeAccess: true,
              viewAccess: true,
              addAccess: true,
              deleteAccess: true,
            },
            {
              functionName: 'Person Demographics',
              businessCardPref: 'photo',
              fieldName: 'profileImageID',
              changeAccess: true,
              viewAccess: true,
              addAccess: true,
              deleteAccess: true,
            },
            {
              functionName: 'Person Demographics',
              businessCardPref: 'jobtitle',
              fieldName: 'jobTitle',
              changeAccess: true,
              viewAccess: true,
              addAccess: true,
              deleteAccess: true,
            },
            {
              functionName: 'Person Demographics',
              businessCardPref: 'website',
              fieldName: 'website',
              changeAccess: true,
              viewAccess: true,
              addAccess: true,
              deleteAccess: true,
            },
            {
              functionName: 'Person Admin',
              businessCardPref: '',
              fieldName: 'teamRoot',
              changeAccess: true,
              viewAccess: true,
              addAccess: true,
              deleteAccess: true,
            },
            {
              functionName: 'Person Admin',
              businessCardPref: '',
              fieldName: 'roleID',
              changeAccess: true,
              viewAccess: true,
              addAccess: true,
              deleteAccess: true,
            },
          ],
          domain: {
            domainName: 'Cherry',
            domainLabelPersonal1: 'Favorite Activities...',
            domainLabelPersonal2: 'Job Skills',
            domainLabelPersonal3: 'Favorite Quotes',
            domainLabelPersonal4: 'Favorite Books',
            domainLoginNameLabel: 'Login Name',
            domainIsSingleSignOn: false,
            outsideJoinDateLabel: 'Member Since',
          },
          personID: 2184472,
          elementType: 'ocPERSON',
          elementSubType: 'ocITEM',
          activeStatus: 'ocENABLED',
          modifiedDate: '2023-02-24T21:08:56.207+00:00',
          createdDate: '2023-02-03T21:21:06.843+00:00',
          primaryElementID: 551,
          domainID: 551,
          createdByID: 1625045,
          modifiedByID: 1625045,
          firstActivityDate: '2023-02-24T21:10:04.587+00:00',
          lastActivityDate: '2023-08-23T22:29:27.213+00:00',
          lastLoginDate: '2023-08-23T21:42:57.253+00:00',
          termsofServiceDate: '2023-02-24T21:10:04.587+00:00',
          givenName: 'Ashley',
          familyName: 'Galindo',
          familiarName: '',
          bio: '',
          personal1: '',
          personal2: '',
          personal3: '',
          personal4: '',
          businessCardPreferences: '',
          emailPreference: 'ocHTML',
          onlinePreference: 'ocAVAILABLE',
          emailDigestHourGMTPreference: 2,
          emailDigestNoticePreference: 'ocINSTANT',
          sessionTimeoutMinutesPreference: 120,
          roleID: 1,
          teamRoot: 551,
          outsideType: '',
          outsideJoinDate: '1900-01-01T00:00:00+00:00',
          outsideTerminateDate: '1900-01-01T00:00:00+00:00',
          outsideModifiedDate: '1900-01-01T00:00:00+00:00',
          outsideActiveStatus: '',
          outsideRenewalDate: '1900-01-01T00:00:00+00:00',
          outsideID: '',
          ownerUserID: 2216450,
          changePassword: false,
          passwordExpiresDate: '1900-01-01T00:00:00+00:00',
          languagePreference: 'en',
          logonName: 'agalindo@cardoneventures.com',
          logonNameBinding: 'email',
          email: 'agalindo@cardoneventures.com',
          address1: '',
          address2: '',
          city: '',
          state: '',
          country: '',
          postalCode: '',
          phone1: '',
          phone2: '',
          timeZoneNameGeneral: '',
          profileImageID: 0,
          birthDate: '1904-01-01T00:00:00+00:00',
          website: '',
          trainingClass: '',
          experience: '',
          yearsExperience: 0,
          jobTitle: '',
          company: '',
          industry: '',
          urlFacebook: '',
          urlTwitter: '',
          urlLinkedIn: '',
          urlSnapChat: '',
          urlInstagram: '',
          department: '',
          urlYoutube: '',
          otherEmail: [],
          managerID: 0,
          telecom: [],
        },
        traits: [],
        session: {
          adminID: 0,
          changePassword: false,
          domainID: 551,
          koPermissionSyncDate: '2023-09-29T15:25:54.27+00:00',
          onCourseURL: 'https://cherry.mocaworks.com',
          onlinePreference: 'ocHIDDEN',
          profileThumbPath:
            '/v2/domains/551/assets/1960713_tsc3eykcizn_200px.jpg',
          roleID: 1,
          teamRootID: 551,
          teamListSyncDate: '1900-01-01T00:00:00+00:00',
          termsOfServiceSignatureRequired: false,
          timeOutMnts: 129600,
          userID: 1960713,
          userName: 'Joshua Rinard',
        },
        error: {
          sts: 0,
          msg: 'initialized',
        },
        links: [],
        profileImages: [],
      }
    },
  },
  post: {
    success: () => {
      return {
        personID: 2184472,
        session: {
          adminID: 0,
          changePassword: false,
          domainID: 551,
          koPermissionSyncDate: '2023-09-29T15:25:54.27+00:00',
          onCourseURL: 'https://cherry.mocaworks.com',
          onlinePreference: 'ocHIDDEN',
          profileThumbPath:
            '/v2/domains/551/assets/1960713_tsc3eykcizn_200px.jpg',
          roleID: 1,
          teamRootID: 551,
          teamListSyncDate: '1900-01-01T00:00:00+00:00',
          termsOfServiceSignatureRequired: false,
          timeOutMnts: 129600,
          userID: 1960713,
          userName: 'Joshua Rinard',
        },
        error: {
          sts: 0,
          msg: 'initialized',
        },
        links: [],
      }
    },
  },
  put: {
    success: () => {
      return {
        personID: 2184472,
        session: {
          adminID: 0,
          changePassword: false,
          domainID: 551,
          koPermissionSyncDate: '2023-09-29T15:25:54.27+00:00',
          onCourseURL: 'https://cherry.mocaworks.com',
          onlinePreference: 'ocHIDDEN',
          profileThumbPath:
            '/v2/domains/551/assets/1960713_tsc3eykcizn_200px.jpg',
          roleID: 1,
          teamRootID: 551,
          teamListSyncDate: '1900-01-01T00:00:00+00:00',
          termsOfServiceSignatureRequired: false,
          timeOutMnts: 129600,
          userID: 1960713,
          userName: 'Joshua Rinard',
        },
        error: {
          sts: 0,
          msg: 'initialized',
        },
        links: [],
      }
    },
  },
  delete: {
    success: () => {
      return {
        recordsAffected: 2,
        session: {
          adminID: 0,
          changePassword: false,
          domainID: 551,
          koPermissionSyncDate: '2023-09-29T15:25:54.27+00:00',
          onCourseURL: 'https://cherry.mocaworks.com',
          onlinePreference: 'ocHIDDEN',
          profileThumbPath:
            '/v2/domains/551/assets/1960713_tsc3eykcizn_200px.jpg',
          roleID: 1,
          teamRootID: 551,
          teamListSyncDate: '1900-01-01T00:00:00+00:00',
          termsOfServiceSignatureRequired: false,
          timeOutMnts: 129600,
          userID: 1960713,
          userName: 'Joshua Rinard',
        },
        error: {
          sts: 0,
          msg: 'initialized',
        },
        links: [],
      }
    },
  },
  invalidFilter: () => {
    return {
      data: [],
      links: [],
      error: {
        logID: -1,
        msg: 'validation error',
        sts: -1000,
        technical: 'should not contain :',
      },
    }
  },
  invalidMissingRequired: (propName: string) => {
    return {
      data: [],
      links: [],
      error: {
        logID: -1,
        sts: -1000,
        msg: `validation error: ${propName} required`,
        technical: `parameters must contain ${propName}`,
      },
    }
  },
}
