/**
 * *****
 * 'Security Role' meaning the `Security Role` every ocPerson has
 * Namely, constants around the `Security Function`s that make a `Security Role`
 * *****
 * *
 * *
 * *
 * *****
 * Each `Security Function` as 4 `Function Scopes` of `ocVIEW`, `ocADD`, `ocCHANGE`, `ocDELETE`
 * each of those 4 Scopes will have one of the numberic Scope values
 * listed in `SCOPE_CONSTANTS`, below.
 * *****
 */

export const FUNCTION_SCOPE_NAMES = {
  ocVIEW: 'ocVIEW',
  ocADD: 'ocADD',
  ocCHANGE: 'ocCHANGE',
  ocDELETE: 'ocDELETE',
} as const

export const SCOPE_CONSTANTS = {
  DOMAIN: 6,
  DOMAINSTOROOT: 800,
  MEMBERSHIPS: 2,
  MEMBERSHIPSDOWN: 3,
  MEMBERSHIPSUP: 4,
  MEMBERSHIPSUPDOWN: 5,
  NONE: 0,
  ROOT: 7,
  SELF: 1,
  TEAMLEAD: 1,
} as const

export const FUNCTION_IDS_BY_FRIENDLY_NAME = {
  SECURITY_ROLE: -1,
  PROFILE: 2,
  GOALSHARING: 7,
  STATISTICS: 24,
  INBOX: 37,
  LIBRARY: 48,
  TEAMS: 49,
  NEWS: 50,
  HOME: 54,
  MANAGE: 55,
  CUSTOM_TABS_MENU_ITEM: 60,
  TRAINING: 67,
  TODO: 73,
  SBNN_EXAM_LIST: 94, // * DEPRECATED
  SBNN_STATS: 95, // * DEPRECATED
  CALENDAR: 99, // * ALIAS FOR EVENTS
  EVENTS: 99,
  SBNN_EVENTS: 100, // * DEPRECATED
  BUGS: 101,
  LESSON_VIEWER: 102,
  NOTICE: 103,
  TEAM_EDITOR: 107,
  R3: 114,
  PPF: 118,
  ACTION_PLAN: 119,
  TGP: 119,
  TRAINING_DASHBOARD: 121,
  SECURITY_ROLES: 123,
  ADD_MULTIPLE_USERS: 124,
  COURSE_EDITOR: 127,
  COURSE_CATALOG_EDITOR: 131,
  EXAM_EDITOR: 133,
  SURVEY_EDITOR: 134,
  TPA_EDITOR: 135,
  ELEMENT_INFO: 136,
  FILE_SEARCH: 137,
  NOTICE_INFO: 138,
  OBJECT_INFO: 139,
  SERVER_VARIABLES: 140,
  CHAT_RIVER: 141,
  CHUMBY: 142,
  MR_RADAR: 143,
  SYSTEM_DIAGNOSTICS: 144,
  SYSTEM_LOG: 145,
  BILLING: 146,
  SERVICE_BIDS: 155,
  PLAYBOOK: 156,
  PLAYBOOK_REVIEWER_NOTICE: 157,
  PROJECTS: 150,
  SURVEYS: 160,
  TEAMTOOLS: 162,
  ENROLLMENT_WATCH: 166,
} as const

export const FUNCTIONS_NAMES_BY_ID = {
  2: 'People',
  3: 'Teams',
  5: 'Assessments',
  7: 'Goal Sharing',
  8: 'Person Password',
  9: 'Person Address',
  10: 'Person Admin',
  11: 'Person Demographics',
  12: 'Team Membership',
  13: 'Blocks',
  14: 'Lessons',
  18: 'Block Enroll',
  22: 'Roles',
  24: 'Reports',
  29: 'Bugs',
  30: 'Impersonate',
  31: 'System',
  33: 'News Team',
  34: 'Notice Team',
  35: 'LibraryFront Team',
  36: 'LibraryBack Team',
  37: 'Notices Person',
  38: 'Function',
  41: 'onCourseLegacy',
  42: 'Domain',
  43: 'Beta',
  44: 'Exams',
  45: 'System Log',
  46: 'Lesson Answerkey',
  47: 'Debug',
  48: 'Page Library',
  49: 'Page Team',
  50: 'Page News',
  51: 'Page Search',
  54: 'Page Home',
  55: 'Page Manage',
  57: 'Surveys',
  58: 'DomainLoginURI',
  59: 'Page Home Beta',
  60: 'Page Portal',
  61: 'Replication Data',
  63: 'LibraryFront Person',
  64: 'Person Activity',
  65: 'DevTasks',
  66: 'DevPlans',
  67: 'Page Training',
  68: 'Page Reports',
  69: 'Teams Analytics',
  70: 'Page Library Beta',
  71: 'Chat Private',
  72: 'TPA',
  73: 'Page ToDo',
  74: 'Lessons QuickDoc',
  75: 'Blocks Published',
  76: 'Catalog CurriculumPub',
  77: 'DevTasks Team',
  78: 'Page Reports Users',
  79: 'Page Reports Courses',
  80: 'Page Reports Todos',
  81: 'Page Reports Roles',
  82: 'Page Reports Email',
  83: 'Page Reports Activity',
  91: 'Curriculum Credit',
  96: 'Events',
  97: 'EventAttendees Team',
  98: 'EventAttendees Person',
  99: 'Page Events',
  101: 'Page Bugs',
  103: 'Page Notice',
  104: 'Page Catalog Curriculum',
  105: 'Catalog SharedService',
  106: 'Inbox Team',
  107: 'Page TeamEditor',
  109: 'Notice Team Cascade',
  110: 'Page Verify',
  111: 'Checklist',
  112: 'Checklist Tasks',
  113: 'Page Asset',
  114: 'Person TraitR3',
  115: 'Catalog EventTemplate',
  116: 'EventTemplates',
  117: 'VCEPlan',
  118: 'Page GSPPF',
  119: 'TransGrowth Tasks Team',
  121: 'Page Manage TrainingDashboard',
  147: 'PublicWall',
  148: 'Page PublicWallPost',
  149: 'Page PublicWall',
  150: 'ProjectTeam',
  155: 'ServiceBid',
  156: 'Catalog Playbook',
  157: 'Lesson Policy',
  158: 'User Function',
  159: 'ServiceBidMethod',
  160: 'Page Survey',
  161: 'Page Manage RestorePerson',
  162: 'TeamTools',
  163: 'Page GSPPF Dashboard',
  164: 'Team Platformreview',
} as const
const FUNCTION_NAMES_ARRAY = Object.values(FUNCTIONS_NAMES_BY_ID)

export type FunctionID = keyof typeof FUNCTIONS_NAMES_BY_ID
export type FunctionName = (typeof FUNCTION_NAMES_ARRAY)[number]
export type FunctionScopeName = keyof typeof FUNCTION_SCOPE_NAMES
export type OperationName = FunctionScopeName
