/**
 * To populate this please run
 * px g @tyto/scribe:postman
 */
export const TeamAdminEndpointResponses = {
  success: () => {
    return {
      team: {
        teamID: 4798,
        teamName: 'Selenium Domain',
        elementType: 'ocTEAM',
        teamDesc: 'This is a domain for testing purposes DO NOT DELETE',
        teamType: 'ocDOMAIN',
        domainID: 551,
        activeStatus: 'ocENABLED',
        address1: '12345 NE Twelve Rd',
        address2: '',
        city: 'Virginia Beach',
        state: 'Virginia',
        country: '',
        postalCode: '23451',
        phone1: '',
        phone2: '',
        email: 'scott@mocaworks.com',
        fax: '',
        teamLeaderID: 0,
        teamLeaderOutsideID: '0',
        teamLeaderName: '',
        profileImageID: 0,
        dateFounded: '1987-08-10T00:00:00+00:00',
        outsideType: 'The Best Ever',
        website: 'http://www.google.com',
        outsideExpirationDate: '1900-01-01T00:00:00+00:00',
        outsideID: '',
        lastRefreshWithOutside: '1900-01-01T00:00:00+00:00',
        achievementIconID: 0,
        rosterView: true,
        geographyPostalCode: '23451',
        createdByID: 2,
        modifiedByID: 1960713,
        createdDate: '2009-02-20T22:39:05.62+00:00',
        modifiedDate: '2023-10-31T18:51:40.633+00:00',
        primaryElementID: 0,
        teamToolsConfig: {
          modifiedByID: 4792,
          modifiedDate: '2023-11-27T22:23:52.1+00:00',
          teamName: 'Selenium Domain',
          teamRoot: 4798,
          onInitialize: {
            mayTakeDisc: true,
            mayImportDisc: true,
            mayTakeBasicTrain: false,
            mayTakeAdvTrain: false,
            hasBasicViewDisc: true,
            hasAdvViewDisc: true,
            hasPermitChange: false,
            hasGrantPermitChange: false,
          },
          onDiscComplete: {
            mayTakeDisc: true,
            mayImportDisc: true,
            mayTakeBasicTrain: false,
            mayTakeAdvTrain: false,
            hasBasicViewDisc: true,
            hasAdvViewDisc: true,
            hasPermitChange: false,
            hasGrantPermitChange: false,
          },
          onBasicTrainingComplete: {
            mayTakeDisc: true,
            mayImportDisc: true,
            mayTakeBasicTrain: false,
            mayTakeAdvTrain: false,
            hasBasicViewDisc: true,
            hasAdvViewDisc: true,
            hasPermitChange: false,
            hasGrantPermitChange: false,
          },
          onAdvTrainingComplete: {
            mayTakeDisc: true,
            mayImportDisc: true,
            mayTakeBasicTrain: false,
            mayTakeAdvTrain: false,
            hasBasicViewDisc: true,
            hasAdvViewDisc: true,
            hasPermitChange: false,
            hasGrantPermitChange: false,
          },
          basicTrainingID: 0,
          advTrainingID: 0,
        },
      },
      profileImages: [],
      admin: {
        adminDetail: {
          detailSummary: '',
          maxPersons: -1,
        },
        permissions: [
          {
            functionName: 'Person Admin',
            fieldName: 'detailSummary',
            changeAccess: true,
            viewAccess: true,
            addAccess: true,
            deleteAccess: true,
          },
          {
            functionName: 'Person Admin',
            fieldName: 'maxPersons',
            changeAccess: true,
            viewAccess: true,
            addAccess: true,
            deleteAccess: true,
          },
          {
            functionName: 'Teams',
            fieldName: '',
            changeAccess: true,
            viewAccess: true,
            addAccess: true,
            deleteAccess: true,
          },
          {
            functionName: 'Team Membership',
            fieldName: '',
            changeAccess: true,
            viewAccess: true,
            addAccess: true,
            deleteAccess: true,
          },
          {
            functionName: 'People',
            fieldName: '',
            changeAccess: true,
            viewAccess: true,
            addAccess: true,
            deleteAccess: true,
          },
          {
            functionName: 'Block Enroll',
            fieldName: '',
            changeAccess: true,
            viewAccess: true,
            addAccess: true,
            deleteAccess: true,
          },
          {
            functionName: 'Domain',
            fieldName: '',
            changeAccess: true,
            viewAccess: true,
            addAccess: true,
            deleteAccess: true,
          },
          {
            functionName: 'Person Password',
            fieldName: '',
            changeAccess: true,
            viewAccess: true,
            addAccess: true,
            deleteAccess: true,
          },
        ],
      },
      session: {
        userID: 1960713,
        userName: 'Joshua Rinard',
        changePassword: false,
        termsOfServiceSignatureRequired: false,
        adminID: 0,
        teamListSyncDate: '1900-01-01T00:00:00+00:00',
        koPermissionSyncDate: '2024-04-02T11:09:50.963+00:00',
        domainID: 551,
        timeOutMnts: 129600,
        onCourseURL: 'https://cherry.mocaworks.com',
        profileThumbPath:
          '/v2/domains/551/assets/1960713_tsc3eykcizn_200px.jpg',
        teamRootID: 551,
        roleID: 1,
        onlinePreference: 'ocHIDDEN',
      },
      error: {
        sts: 0,
        msg: 'initialized',
      },
      links: [],
    }
  },

  put: {
    success: () => {
      return {
        recordsAffected: -1,
        session: {
          userID: 2043811,
          userName: 'Johann Loch',
          changePassword: false,
          termsOfServiceSignatureRequired: false,
          adminID: 0,
          teamListSyncDate: '1900-01-01T00:00:00+00:00',
          koPermissionSyncDate: '1900-01-01T00:00:00+00:00',
          domainID: 551,
          timeOutMnts: 90,
          onCourseURL: 'https://cherry.mocaworks.com',
          profileThumbPath:
            '/v2/domains/551/assets/2043811_sxuwdy5uwwo_200px.jpg',
          teamRootID: 551,
          roleID: 1,
          onlinePreference: 'ocHIDDEN',
        },
        error: {
          sts: 0,
          msg: 'initialized',
        },
        links: [],
      }
    },
  },

  invalidMissingRequired: (propName: string) => {
    return {
      data: [],
      links: [],
      error: {
        logID: -1,
        sts: -1000,
        msg: `validation error: ${propName} required`,
        technical: `parameters must contain ${propName}`,
      },
    }
  },
}
